package router

import "cephtower/backend/internal/api/v1/handler"

func cephfsRoutes(h *handler.Handler) []Route {
	return []Route{
		{"GET", "/filesystems", h.ListFilesystems},
		{"POST", "/filesystem", h.CreateFilesystem},
		{"GET", "/filesystem", h.GetFilesystem},
		{"GET", "/filesystem/performance", h.GetCephFSPerformance},
		{"GET", "/filesystem/pools", h.GetCephFSPools},
		{"GET", "/filesystem/mds", h.GetCephFSMDS},
		{"PATCH", "/filesystem", h.UpdateFilesystem},
		{"PUT", "/filesystem", h.RenameFilesystem},
		{"DELETE", "/filesystem", h.DeleteFilesystem},
		{"GET", "/filesystem/clients", h.ListFilesystemClients},
		{"DELETE", "/filesystem/client", h.EvictFilesystemClient},
		{"GET", "/filesystem/subvolume/groups", h.ListSubvolumeGroups},
		{"POST", "/filesystem/subvolume/group", h.CreateSubvolumeGroup},
		{"GET", "/filesystem/subvolume/group", h.GetSubvolumeGroup},
		{"PATCH", "/filesystem/subvolume/group", h.UpdateSubvolumeGroup},
		{"DELETE", "/filesystem/subvolume/group", h.DeleteSubvolumeGroup},
		{"GET", "/filesystem/subvolumes", h.ListSubvolumes},
		{"POST", "/filesystem/subvolume", h.CreateSubvolume},
		{"GET", "/filesystem/subvolume", h.GetSubvolume},
		{"PATCH", "/filesystem/subvolume", h.UpdateSubvolume},
		{"DELETE", "/filesystem/subvolume", h.DeleteSubvolume},
		{"POST", "/filesystem/subvolume/clone/cancel", h.CancelSubvolumeClone},
		{"GET", "/filesystem/subvolume/snapshots", h.ListCephFSSnapshots},
		{"POST", "/filesystem/subvolume/snapshot", h.CreateCephFSSnapshot},
		{"DELETE", "/filesystem/subvolume/snapshot", h.DeleteCephFSSnapshot},
		{"POST", "/filesystem/subvolume/snapshot/clone", h.CloneCephFSSnapshot},
		{"GET", "/filesystem/snapshot/schedules", h.ListSnapshotSchedules},
		{"GET", "/filesystem/snapshot/schedule/status", h.GetSnapshotScheduleStatus},
		{"POST", "/filesystem/snapshot/schedule", h.CreateSnapshotSchedule},
		{"POST", "/filesystem/snapshot/schedule/action", h.RunSnapshotScheduleAction},
		{"POST", "/filesystem/snapshot/schedule/retention", h.UpdateSnapshotRetention},
		{"GET", "/filesystem/authorizations", h.ListCephFSAuthorizations},
		{"POST", "/filesystem/authorization", h.CreateCephFSAuthorization},
		{"GET", "/filesystem/entries", h.ListCephFSEntries},
		{"POST", "/filesystem/entry", h.CreateCephFSEntry},
		{"PATCH", "/filesystem/entry", h.RenameCephFSEntry},
		{"DELETE", "/filesystem/entry", h.DeleteCephFSEntry},
		{"PATCH", "/filesystem/entry/quota", h.UpdateCephFSEntryQuota},
		{"GET", "/filesystem/entry/snapshots", h.ListCephFSEntrySnapshots},
		{"POST", "/filesystem/entry/snapshot", h.CreateCephFSEntrySnapshot},
		{"DELETE", "/filesystem/entry/snapshot", h.DeleteCephFSEntrySnapshot},
	}
}
