package router

import "cephtower/backend/internal/api/v1/handler"

func proxyRoutes(h *handler.Handler) []Route {
	return []Route{
		{"GET", "/monitor", h.ProxyPath},
		{"GET", "/mgr/module", h.ProxyPath},
		{"POST", "/mgr/module/{name}/enable", h.ProxyPath},
		{"POST", "/mgr/module/{name}/disable", h.ProxyPath},
		{"GET", "/service", h.ProxyPath},
		{"POST", "/service", h.ProxyPath},
		{"GET", "/service/known-type", h.ProxyPath},
		{"GET", "/service/{name}", h.ProxyPath},
		{"PUT", "/service/{name}", h.ProxyPath},
		{"DELETE", "/service/{name}", h.ProxyPath},
		{"GET", "/service/{name}/daemon", h.ProxyPath},
		{"GET", "/pool", h.ProxyPath},
		{"POST", "/pool", h.ProxyPath},
		{"GET", "/pool/{name}", h.ProxyPath},
		{"PUT", "/pool/{name}", h.ProxyPath},
		{"DELETE", "/pool/{name}", h.ProxyPath},
		{"GET", "/pool/{name}/configuration", h.ProxyPath},
		{"GET", "/block/image", h.ProxyPath},
		{"POST", "/block/image", h.ProxyPath},
		{"GET", "/block/image/default-feature", h.ProxyPath},
		{"GET", "/block/image/clone-format-version", h.ProxyPath},
		{"GET", "/block/image/trash", h.ProxyPath},
		{"POST", "/block/image/trash/purge", h.ProxyPath},
		{"DELETE", "/block/image/trash/{image}", h.ProxyPath},
		{"POST", "/block/image/trash/{image}/restore", h.ProxyPath},
		{"GET", "/block/image/{image}", h.ProxyPath},
		{"PUT", "/block/image/{image}", h.ProxyPath},
		{"DELETE", "/block/image/{image}", h.ProxyPath},
		{"POST", "/block/image/{image}/copy", h.ProxyPath},
		{"POST", "/block/image/{image}/flatten", h.ProxyPath},
		{"POST", "/block/image/{image}/snapshot", h.ProxyPath},
		{"DELETE", "/block/image/{image}/snapshot/{snapshot}", h.ProxyPath},
		{"PUT", "/block/image/{image}/snapshot/{snapshot}", h.ProxyPath},
		{"POST", "/block/image/{image}/snapshot/{snapshot}/clone", h.ProxyPath},
		{"POST", "/block/image/{image}/snapshot/{snapshot}/rollback", h.ProxyPath},
		{"GET", "/block/mirroring/summary", h.ProxyPath},
		{"GET", "/filesystem", h.ProxyPath},
		{"POST", "/filesystem", h.ProxyPath},
		{"GET", "/filesystem/{id}", h.ProxyPath},
		{"GET", "/filesystem/{id}/client", h.ProxyPath},
		{"GET", "/filesystem/{id}/root", h.ProxyPath},
		{"GET", "/filesystem/{id}/directory", h.ProxyPath},
		{"GET", "/filesystem/{id}/quota", h.ProxyPath},
		{"PUT", "/filesystem/{id}/quota", h.ProxyPath},
		{"GET", "/filesystem/{id}/statfs", h.ProxyPath},
		{"GET", "/object/gateway", h.ProxyPath},
		{"GET", "/object/gateway/{id}", h.ProxyPath},
		{"GET", "/object/user", h.ProxyPath},
		{"POST", "/object/user", h.ProxyPath},
		{"GET", "/object/user/{uid}", h.ProxyPath},
		{"PUT", "/object/user/{uid}", h.ProxyPath},
		{"DELETE", "/object/user/{uid}", h.ProxyPath},
		{"GET", "/object/bucket", h.ProxyPath},
		{"POST", "/object/bucket", h.ProxyPath},
		{"GET", "/object/bucket/{bucket}", h.ProxyPath},
		{"PUT", "/object/bucket/{bucket}", h.ProxyPath},
		{"DELETE", "/object/bucket/{bucket}", h.ProxyPath},
		{"GET", "/object/account", h.ProxyPath},
		{"POST", "/object/account", h.ProxyPath},
		{"GET", "/object/account/{id}", h.ProxyPath},
		{"PUT", "/object/account/{id}", h.ProxyPath},
		{"DELETE", "/object/account/{id}", h.ProxyPath},
		{"GET", "/configuration/filter", h.ProxyPath},
		{"GET", "/configuration", h.ProxyPath},
		{"POST", "/configuration", h.ProxyPath},
		{"PUT", "/configuration", h.ProxyPath},
		{"GET", "/configuration/{name}", h.ProxyPath},
		{"DELETE", "/configuration/{name}", h.ProxyPath},
		{"GET", "/log", h.ProxyPath},
	}
}
