package s3

import (
	"bytes"
	"context"
	"encoding/json"
	"encoding/xml"
	"fmt"
	"net/http"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"unicode/utf8"
)

var notificationARN = regexp.MustCompile(`^arn:aws:sns:[A-Za-z0-9_.-]+:[A-Za-z0-9_.-]*:[A-Za-z0-9_-]{1,256}$`)

// NotificationTopicName also validates the ARN before deriving the native
// notification ID + "_" + topic-name storage key (which omits the ARN scope).
func NotificationTopicName(arn string) (string, error) {
	if !notificationARN.MatchString(arn) {
		return "", fmt.Errorf("a complete native SNS topic ARN is required")
	}
	return strings.Split(arn, ":")[5], nil
}

// Native from_string and to_string are not symmetrical for AbortMultipartUpload.
func notificationEvent(value string) (string, bool) {
	if value == "s3:ObjectLifecycle:Expiration:AbortMultipartUpload" {
		return "s3:ObjectLifecycle:Expiration:AbortMPU", true
	}
	if value == "s3:ObjectLifecycle:Expiration:Noncurrent" || value == "s3:ObjectLifecycle:Transition:Noncurrent" {
		value = strings.TrimSuffix(value, "Noncurrent") + "NonCurrent"
	}
	for _, known := range []string{
		"s3:ObjectCreated:*", "s3:ObjectCreated:Put", "s3:ObjectCreated:Post", "s3:ObjectCreated:Copy", "s3:ObjectCreated:CompleteMultipartUpload",
		"s3:ObjectRemoved:*", "s3:ObjectRemoved:Delete", "s3:ObjectRemoved:DeleteMarkerCreated",
		"s3:ObjectLifecycle:*", "s3:ObjectLifecycle:Expiration:*", "s3:ObjectLifecycle:Expiration:Current", "s3:ObjectLifecycle:Expiration:NonCurrent", "s3:ObjectLifecycle:Expiration:DeleteMarker",
		"s3:ObjectLifecycle:Transition:*", "s3:ObjectLifecycle:Transition:Current", "s3:ObjectLifecycle:Transition:NonCurrent",
		"s3:ObjectSynced:*", "s3:ObjectSynced:Create", "s3:ObjectSynced:Delete", "s3:ObjectSynced:DeletionMarkerCreated",
		"s3:LifecycleExpiration:*", "s3:LifecycleExpiration:Delete", "s3:LifecycleExpiration:DeleteMarkerCreated", "s3:LifecycleTransition",
		"s3:Replication:*", "s3:Replication:Create", "s3:Replication:Delete", "s3:Replication:DeletionMarkerCreated",
	} {
		if value == known {
			return value, true
		}
	}
	return "", false
}

func notificationText(value string) bool {
	if !utf8.ValidString(value) {
		return false
	}
	for _, r := range value {
		if !(r == 9 || r == 10 || r == 13 || r >= 32 && r <= 0xd7ff || r >= 0xe000 && r <= 0xfffd || r >= 0x10000 && r <= 0x10ffff) {
			return false
		}
	}
	return true
}

// Build exactly one nonempty rule; an empty NotificationConfiguration is a
// destructive delete-all request and must never be generated by this writer.
func BucketNotificationDocument(rule BucketNotification) ([]byte, BucketNotification, error) {
	invalid := fmt.Errorf("invalid notification ID, event or filter; duplicate filter names are not allowed")
	if ValidateNotificationDeletion("single", rule.ID) != nil || !notificationText(rule.ID) || rule.Events == nil || rule.Filters == nil {
		return nil, rule, invalid
	}
	if _, err := NotificationTopicName(rule.Topic); err != nil {
		return nil, rule, err
	}
	want := BucketNotification{ID: rule.ID, Topic: rule.Topic, Events: []string{}, Filters: []BucketNotificationFilter{}}
	var b bytes.Buffer
	text := func(name, value string) {
		b.WriteString("<" + name + ">")
		_ = xml.EscapeText(&b, []byte(value))
		b.WriteString("</" + name + ">")
	}
	b.WriteString(`<NotificationConfiguration><TopicConfiguration>`)
	text("Id", rule.ID)
	text("Topic", rule.Topic)
	for _, event := range rule.Events {
		normal, ok := notificationEvent(event)
		if !ok {
			return nil, rule, invalid
		}
		want.Events = append(want.Events, normal)
		text("Event", event)
	}
	if len(rule.Events) == 0 {
		want.Events = []string{"s3:ObjectCreated:*", "s3:ObjectRemoved:*"}
	}
	seen := map[string]bool{}
	for _, filter := range rule.Filters {
		if !notificationText(filter.Name) || !notificationText(filter.Value) || seen[filter.Kind+"\x00"+filter.Name] {
			return nil, rule, invalid
		}
		seen[filter.Kind+"\x00"+filter.Name] = true
		switch filter.Kind {
		case "S3Key":
			if filter.Name != "prefix" && filter.Name != "suffix" && filter.Name != "regex" {
				return nil, rule, invalid
			}
		case "S3Metadata", "S3Tags":
		default:
			return nil, rule, invalid
		}
		if filter.Kind != "S3Key" || filter.Value != "" {
			want.Filters = append(want.Filters, filter)
		}
	}
	b.WriteString("<Filter>")
	for _, kind := range []string{"S3Key", "S3Metadata", "S3Tags"} {
		b.WriteString("<" + kind + ">")
		for _, filter := range rule.Filters {
			if filter.Kind != kind {
				continue
			}
			b.WriteString("<FilterRule>")
			text("Name", filter.Name)
			text("Value", filter.Value)
			b.WriteString("</FilterRule>")
		}
		b.WriteString("</" + kind + ">")
	}
	b.WriteString("</Filter></TopicConfiguration></NotificationConfiguration>")
	if b.Len() > 4<<20 {
		return nil, rule, fmt.Errorf("notification exceeds request limit")
	}
	return b.Bytes(), want, nil
}

func (c *Client) PutBucketNotification(ctx context.Context, bucket string, rule BucketNotification) error {
	body, _, err := BucketNotificationDocument(rule)
	if err != nil {
		return err
	}
	_, _, err = c.request(ctx, http.MethodPut, bucket, url.Values{"notification": {""}}, body)
	return err
}

// Native storage and filter maps reorder entries. Compare complete multisets,
// preserving event order and duplicate rules/filters rather than dropping them.
func SameBucketNotifications(a, b []BucketNotification) bool {
	canonical := func(rules []BucketNotification) string {
		encoded := make([]string, 0, len(rules))
		for _, rule := range rules {
			rule.Filters = append([]BucketNotificationFilter{}, rule.Filters...)
			sort.Slice(rule.Filters, func(i, j int) bool {
				a, _ := json.Marshal(rule.Filters[i])
				b, _ := json.Marshal(rule.Filters[j])
				return string(a) < string(b)
			})
			data, _ := json.Marshal(rule)
			encoded = append(encoded, string(data))
		}
		sort.Strings(encoded)
		data, _ := json.Marshal(encoded)
		return string(data)
	}
	return canonical(a) == canonical(b)
}
