// Code generated by tools/generate_ceph_dashboard_client.rb; DO NOT EDIT.

package endpoints

import (
	"context"
	"encoding/json"
	"net/http"
)

// block endpoints from docs/references/ceph/src/pybind/mgr/dashboard/openapi.yaml.

// GetBlockImage calls GET /api/block/image.
// Display Rbd Images
func (c *Client) GetBlockImage(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodGet, "/api/block/image", request, true)
}

// PostBlockImage calls POST /api/block/image.
// POST /api/block/image
func (c *Client) PostBlockImage(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodPost, "/api/block/image", request, true)
}

// GetBlockImageCloneFormatVersion calls GET /api/block/image/clone_format_version.
// GET /api/block/image/clone_format_version
func (c *Client) GetBlockImageCloneFormatVersion(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodGet, "/api/block/image/clone_format_version", request, true)
}

// GetBlockImageDefaultFeatures calls GET /api/block/image/default_features.
// GET /api/block/image/default_features
func (c *Client) GetBlockImageDefaultFeatures(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodGet, "/api/block/image/default_features", request, true)
}

// GetBlockImageTrash calls GET /api/block/image/trash.
// Get RBD Trash Details by pool name
func (c *Client) GetBlockImageTrash(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodGet, "/api/block/image/trash", request, true)
}

// PostBlockImageTrashPurge calls POST /api/block/image/trash/purge.
// POST /api/block/image/trash/purge
func (c *Client) PostBlockImageTrashPurge(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodPost, "/api/block/image/trash/purge", request, true)
}

// DeleteBlockImageTrashByImageIdSpec calls DELETE /api/block/image/trash/{image_id_spec}.
// DELETE /api/block/image/trash/{image_id_spec}
func (c *Client) DeleteBlockImageTrashByImageIdSpec(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodDelete, "/api/block/image/trash/{image_id_spec}", request, true)
}

// PostBlockImageTrashByImageIdSpecRestore calls POST /api/block/image/trash/{image_id_spec}/restore.
// POST /api/block/image/trash/{image_id_spec}/restore
func (c *Client) PostBlockImageTrashByImageIdSpecRestore(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodPost, "/api/block/image/trash/{image_id_spec}/restore", request, true)
}

// DeleteBlockImageByImageSpec calls DELETE /api/block/image/{image_spec}.
// DELETE /api/block/image/{image_spec}
func (c *Client) DeleteBlockImageByImageSpec(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodDelete, "/api/block/image/{image_spec}", request, true)
}

// GetBlockImageByImageSpec calls GET /api/block/image/{image_spec}.
// Get Rbd Image Info
func (c *Client) GetBlockImageByImageSpec(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodGet, "/api/block/image/{image_spec}", request, true)
}

// PutBlockImageByImageSpec calls PUT /api/block/image/{image_spec}.
// PUT /api/block/image/{image_spec}
func (c *Client) PutBlockImageByImageSpec(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodPut, "/api/block/image/{image_spec}", request, true)
}

// PostBlockImageByImageSpecCopy calls POST /api/block/image/{image_spec}/copy.
// POST /api/block/image/{image_spec}/copy
func (c *Client) PostBlockImageByImageSpecCopy(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodPost, "/api/block/image/{image_spec}/copy", request, true)
}

// PostBlockImageByImageSpecFlatten calls POST /api/block/image/{image_spec}/flatten.
// POST /api/block/image/{image_spec}/flatten
func (c *Client) PostBlockImageByImageSpecFlatten(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodPost, "/api/block/image/{image_spec}/flatten", request, true)
}

// PostBlockImageByImageSpecMoveTrash calls POST /api/block/image/{image_spec}/move_trash.
// POST /api/block/image/{image_spec}/move_trash
func (c *Client) PostBlockImageByImageSpecMoveTrash(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodPost, "/api/block/image/{image_spec}/move_trash", request, true)
}

// PostBlockImageByImageSpecSnap calls POST /api/block/image/{image_spec}/snap.
// POST /api/block/image/{image_spec}/snap
func (c *Client) PostBlockImageByImageSpecSnap(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodPost, "/api/block/image/{image_spec}/snap", request, true)
}

// DeleteBlockImageByImageSpecSnapBySnapshotName calls DELETE /api/block/image/{image_spec}/snap/{snapshot_name}.
// DELETE /api/block/image/{image_spec}/snap/{snapshot_name}
func (c *Client) DeleteBlockImageByImageSpecSnapBySnapshotName(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodDelete, "/api/block/image/{image_spec}/snap/{snapshot_name}", request, true)
}

// PutBlockImageByImageSpecSnapBySnapshotName calls PUT /api/block/image/{image_spec}/snap/{snapshot_name}.
// PUT /api/block/image/{image_spec}/snap/{snapshot_name}
func (c *Client) PutBlockImageByImageSpecSnapBySnapshotName(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodPut, "/api/block/image/{image_spec}/snap/{snapshot_name}", request, true)
}

// PostBlockImageByImageSpecSnapBySnapshotNameClone calls POST /api/block/image/{image_spec}/snap/{snapshot_name}/clone.
// POST /api/block/image/{image_spec}/snap/{snapshot_name}/clone
func (c *Client) PostBlockImageByImageSpecSnapBySnapshotNameClone(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodPost, "/api/block/image/{image_spec}/snap/{snapshot_name}/clone", request, true)
}

// PostBlockImageByImageSpecSnapBySnapshotNameRollback calls POST /api/block/image/{image_spec}/snap/{snapshot_name}/rollback.
// POST /api/block/image/{image_spec}/snap/{snapshot_name}/rollback
func (c *Client) PostBlockImageByImageSpecSnapBySnapshotNameRollback(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodPost, "/api/block/image/{image_spec}/snap/{snapshot_name}/rollback", request, true)
}

// GetBlockMirroringPoolByPoolName calls GET /api/block/mirroring/pool/{pool_name}.
// Display Rbd Mirroring Summary
func (c *Client) GetBlockMirroringPoolByPoolName(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodGet, "/api/block/mirroring/pool/{pool_name}", request, true)
}

// PutBlockMirroringPoolByPoolName calls PUT /api/block/mirroring/pool/{pool_name}.
// PUT /api/block/mirroring/pool/{pool_name}
func (c *Client) PutBlockMirroringPoolByPoolName(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodPut, "/api/block/mirroring/pool/{pool_name}", request, true)
}

// PostBlockMirroringPoolByPoolNameBootstrapPeer calls POST /api/block/mirroring/pool/{pool_name}/bootstrap/peer.
// POST /api/block/mirroring/pool/{pool_name}/bootstrap/peer
func (c *Client) PostBlockMirroringPoolByPoolNameBootstrapPeer(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodPost, "/api/block/mirroring/pool/{pool_name}/bootstrap/peer", request, true)
}

// PostBlockMirroringPoolByPoolNameBootstrapToken calls POST /api/block/mirroring/pool/{pool_name}/bootstrap/token.
// POST /api/block/mirroring/pool/{pool_name}/bootstrap/token
func (c *Client) PostBlockMirroringPoolByPoolNameBootstrapToken(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodPost, "/api/block/mirroring/pool/{pool_name}/bootstrap/token", request, true)
}

// GetBlockMirroringPoolByPoolNamePeer calls GET /api/block/mirroring/pool/{pool_name}/peer.
// GET /api/block/mirroring/pool/{pool_name}/peer
func (c *Client) GetBlockMirroringPoolByPoolNamePeer(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodGet, "/api/block/mirroring/pool/{pool_name}/peer", request, true)
}

// PostBlockMirroringPoolByPoolNamePeer calls POST /api/block/mirroring/pool/{pool_name}/peer.
// POST /api/block/mirroring/pool/{pool_name}/peer
func (c *Client) PostBlockMirroringPoolByPoolNamePeer(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodPost, "/api/block/mirroring/pool/{pool_name}/peer", request, true)
}

// DeleteBlockMirroringPoolByPoolNamePeerByPeerUuid calls DELETE /api/block/mirroring/pool/{pool_name}/peer/{peer_uuid}.
// DELETE /api/block/mirroring/pool/{pool_name}/peer/{peer_uuid}
func (c *Client) DeleteBlockMirroringPoolByPoolNamePeerByPeerUuid(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodDelete, "/api/block/mirroring/pool/{pool_name}/peer/{peer_uuid}", request, true)
}

// GetBlockMirroringPoolByPoolNamePeerByPeerUuid calls GET /api/block/mirroring/pool/{pool_name}/peer/{peer_uuid}.
// GET /api/block/mirroring/pool/{pool_name}/peer/{peer_uuid}
func (c *Client) GetBlockMirroringPoolByPoolNamePeerByPeerUuid(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodGet, "/api/block/mirroring/pool/{pool_name}/peer/{peer_uuid}", request, true)
}

// PutBlockMirroringPoolByPoolNamePeerByPeerUuid calls PUT /api/block/mirroring/pool/{pool_name}/peer/{peer_uuid}.
// PUT /api/block/mirroring/pool/{pool_name}/peer/{peer_uuid}
func (c *Client) PutBlockMirroringPoolByPoolNamePeerByPeerUuid(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodPut, "/api/block/mirroring/pool/{pool_name}/peer/{peer_uuid}", request, true)
}

// GetBlockMirroringSiteName calls GET /api/block/mirroring/site_name.
// Display Rbd Mirroring sitename
func (c *Client) GetBlockMirroringSiteName(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodGet, "/api/block/mirroring/site_name", request, true)
}

// PutBlockMirroringSiteName calls PUT /api/block/mirroring/site_name.
// PUT /api/block/mirroring/site_name
func (c *Client) PutBlockMirroringSiteName(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodPut, "/api/block/mirroring/site_name", request, true)
}

// GetBlockMirroringSummary calls GET /api/block/mirroring/summary.
// Display Rbd Mirroring Summary
func (c *Client) GetBlockMirroringSummary(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodGet, "/api/block/mirroring/summary", request, true)
}

// GetBlockMirroringByPoolNameByImageNameSummary calls GET /api/block/mirroring/{pool_name}/{image_name}/summary.
// GET /api/block/mirroring/{pool_name}/{image_name}/summary
func (c *Client) GetBlockMirroringByPoolNameByImageNameSummary(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodGet, "/api/block/mirroring/{pool_name}/{image_name}/summary", request, true)
}

// GetBlockPoolByPoolNameGroup calls GET /api/block/pool/{pool_name}/group.
// List groups by pool name
func (c *Client) GetBlockPoolByPoolNameGroup(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodGet, "/api/block/pool/{pool_name}/group", request, true)
}

// PostBlockPoolByPoolNameGroup calls POST /api/block/pool/{pool_name}/group.
// Create a group
func (c *Client) PostBlockPoolByPoolNameGroup(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodPost, "/api/block/pool/{pool_name}/group", request, true)
}

// DeleteBlockPoolByPoolNameGroupByGroupName calls DELETE /api/block/pool/{pool_name}/group/{group_name}.
// Delete a group
func (c *Client) DeleteBlockPoolByPoolNameGroupByGroupName(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodDelete, "/api/block/pool/{pool_name}/group/{group_name}", request, true)
}

// GetBlockPoolByPoolNameGroupByGroupName calls GET /api/block/pool/{pool_name}/group/{group_name}.
// Get the list of images in a group
func (c *Client) GetBlockPoolByPoolNameGroupByGroupName(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodGet, "/api/block/pool/{pool_name}/group/{group_name}", request, true)
}

// PutBlockPoolByPoolNameGroupByGroupName calls PUT /api/block/pool/{pool_name}/group/{group_name}.
// Update a group (rename)
func (c *Client) PutBlockPoolByPoolNameGroupByGroupName(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodPut, "/api/block/pool/{pool_name}/group/{group_name}", request, true)
}

// DeleteBlockPoolByPoolNameGroupByGroupNameImage calls DELETE /api/block/pool/{pool_name}/group/{group_name}/image.
// Remove image from a group
func (c *Client) DeleteBlockPoolByPoolNameGroupByGroupNameImage(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodDelete, "/api/block/pool/{pool_name}/group/{group_name}/image", request, true)
}

// PostBlockPoolByPoolNameGroupByGroupNameImage calls POST /api/block/pool/{pool_name}/group/{group_name}/image.
// Add image to a group
func (c *Client) PostBlockPoolByPoolNameGroupByGroupNameImage(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodPost, "/api/block/pool/{pool_name}/group/{group_name}/image", request, true)
}

// GetBlockPoolByPoolNameGroupByGroupNameSnap calls GET /api/block/pool/{pool_name}/group/{group_name}/snap.
// List group snapshots
func (c *Client) GetBlockPoolByPoolNameGroupByGroupNameSnap(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodGet, "/api/block/pool/{pool_name}/group/{group_name}/snap", request, true)
}

// PostBlockPoolByPoolNameGroupByGroupNameSnap calls POST /api/block/pool/{pool_name}/group/{group_name}/snap.
// Create a group snapshot
func (c *Client) PostBlockPoolByPoolNameGroupByGroupNameSnap(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodPost, "/api/block/pool/{pool_name}/group/{group_name}/snap", request, true)
}

// DeleteBlockPoolByPoolNameGroupByGroupNameSnapBySnapshotName calls DELETE /api/block/pool/{pool_name}/group/{group_name}/snap/{snapshot_name}.
// Delete a group snapshot
func (c *Client) DeleteBlockPoolByPoolNameGroupByGroupNameSnapBySnapshotName(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodDelete, "/api/block/pool/{pool_name}/group/{group_name}/snap/{snapshot_name}", request, true)
}

// GetBlockPoolByPoolNameGroupByGroupNameSnapBySnapshotName calls GET /api/block/pool/{pool_name}/group/{group_name}/snap/{snapshot_name}.
// Get group snapshot information
func (c *Client) GetBlockPoolByPoolNameGroupByGroupNameSnapBySnapshotName(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodGet, "/api/block/pool/{pool_name}/group/{group_name}/snap/{snapshot_name}", request, true)
}

// PutBlockPoolByPoolNameGroupByGroupNameSnapBySnapshotName calls PUT /api/block/pool/{pool_name}/group/{group_name}/snap/{snapshot_name}.
// Update a group snapshot
func (c *Client) PutBlockPoolByPoolNameGroupByGroupNameSnapBySnapshotName(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodPut, "/api/block/pool/{pool_name}/group/{group_name}/snap/{snapshot_name}", request, true)
}

// PostBlockPoolByPoolNameGroupByGroupNameSnapBySnapshotNameRollback calls POST /api/block/pool/{pool_name}/group/{group_name}/snap/{snapshot_name}/rollback.
// Rollback group to snapshot
func (c *Client) PostBlockPoolByPoolNameGroupByGroupNameSnapBySnapshotNameRollback(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodPost, "/api/block/pool/{pool_name}/group/{group_name}/snap/{snapshot_name}/rollback", request, true)
}

// GetBlockPoolByPoolNameNamespace calls GET /api/block/pool/{pool_name}/namespace.
// GET /api/block/pool/{pool_name}/namespace
func (c *Client) GetBlockPoolByPoolNameNamespace(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodGet, "/api/block/pool/{pool_name}/namespace", request, true)
}

// PostBlockPoolByPoolNameNamespace calls POST /api/block/pool/{pool_name}/namespace.
// POST /api/block/pool/{pool_name}/namespace
func (c *Client) PostBlockPoolByPoolNameNamespace(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodPost, "/api/block/pool/{pool_name}/namespace", request, true)
}

// DeleteBlockPoolByPoolNameNamespaceByNamespace calls DELETE /api/block/pool/{pool_name}/namespace/{namespace}.
// DELETE /api/block/pool/{pool_name}/namespace/{namespace}
func (c *Client) DeleteBlockPoolByPoolNameNamespaceByNamespace(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodDelete, "/api/block/pool/{pool_name}/namespace/{namespace}", request, true)
}
