// Code generated by tools/generate_ceph_dashboard_client.rb; DO NOT EDIT.

package endpoints

import (
	"context"
	"encoding/json"
	"net/http"
)

// cluster endpoints from docs/references/ceph/src/pybind/mgr/dashboard/openapi.yaml.

// GetCluster calls GET /api/cluster.
// Get the cluster status
func (c *Client) GetCluster(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodGet, "/api/cluster", request, true)
}

// PutCluster calls PUT /api/cluster.
// Update the cluster status
func (c *Client) PutCluster(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodPut, "/api/cluster", request, true)
}

// GetClusterUpgrade calls GET /api/cluster/upgrade.
// Get the available versions to upgrade
func (c *Client) GetClusterUpgrade(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodGet, "/api/cluster/upgrade", request, true)
}

// PutClusterUpgradePause calls PUT /api/cluster/upgrade/pause.
// Pause the cluster upgrade
func (c *Client) PutClusterUpgradePause(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodPut, "/api/cluster/upgrade/pause", request, true)
}

// PutClusterUpgradeResume calls PUT /api/cluster/upgrade/resume.
// Resume the cluster upgrade
func (c *Client) PutClusterUpgradeResume(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodPut, "/api/cluster/upgrade/resume", request, true)
}

// PostClusterUpgradeStart calls POST /api/cluster/upgrade/start.
// Start the cluster upgrade
func (c *Client) PostClusterUpgradeStart(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodPost, "/api/cluster/upgrade/start", request, true)
}

// GetClusterUpgradeStatus calls GET /api/cluster/upgrade/status.
// Get the cluster upgrade status
func (c *Client) GetClusterUpgradeStatus(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodGet, "/api/cluster/upgrade/status", request, true)
}

// PutClusterUpgradeStop calls PUT /api/cluster/upgrade/stop.
// Stop the cluster upgrade
func (c *Client) PutClusterUpgradeStop(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodPut, "/api/cluster/upgrade/stop", request, true)
}

// GetClusterUser calls GET /api/cluster/user.
// Get list of ceph users
func (c *Client) GetClusterUser(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodGet, "/api/cluster/user", request, true)
}

// PostClusterUser calls POST /api/cluster/user.
// Create Ceph User
func (c *Client) PostClusterUser(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodPost, "/api/cluster/user", request, true)
}

// PutClusterUser calls PUT /api/cluster/user.
// Edit Ceph User Capabilities
func (c *Client) PutClusterUser(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodPut, "/api/cluster/user", request, true)
}

// PostClusterUserExport calls POST /api/cluster/user/export.
// Export Ceph Users
func (c *Client) PostClusterUserExport(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodPost, "/api/cluster/user/export", request, true)
}

// DeleteClusterUserByUserEntities calls DELETE /api/cluster/user/{user_entities}.
// Delete one or more Ceph Users
func (c *Client) DeleteClusterUserByUserEntities(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodDelete, "/api/cluster/user/{user_entities}", request, true)
}
