// Code generated by tools/generate_ceph_dashboard_client.rb; DO NOT EDIT.

package endpoints

import (
	"context"
	"encoding/json"
	"net/http"
)

// cluster_conf endpoints from docs/references/ceph/src/pybind/mgr/dashboard/openapi.yaml.

// GetClusterConf calls GET /api/cluster_conf.
// GET /api/cluster_conf
func (c *Client) GetClusterConf(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodGet, "/api/cluster_conf", request, true)
}

// PostClusterConf calls POST /api/cluster_conf.
// Create/Update Cluster Configuration
func (c *Client) PostClusterConf(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodPost, "/api/cluster_conf", request, true)
}

// PutClusterConf calls PUT /api/cluster_conf.
// PUT /api/cluster_conf
func (c *Client) PutClusterConf(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodPut, "/api/cluster_conf", request, true)
}

// GetClusterConfFilter calls GET /api/cluster_conf/filter.
// Get Cluster Configuration by name
func (c *Client) GetClusterConfFilter(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodGet, "/api/cluster_conf/filter", request, true)
}

// DeleteClusterConfByName calls DELETE /api/cluster_conf/{name}.
// DELETE /api/cluster_conf/{name}
func (c *Client) DeleteClusterConfByName(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodDelete, "/api/cluster_conf/{name}", request, true)
}

// GetClusterConfByName calls GET /api/cluster_conf/{name}.
// GET /api/cluster_conf/{name}
func (c *Client) GetClusterConfByName(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodGet, "/api/cluster_conf/{name}", request, true)
}
