// Code generated by tools/generate_ceph_dashboard_client.rb; DO NOT EDIT.

package endpoints

import (
	"context"
	"encoding/json"
	"net/http"
)

// crush_rule endpoints from docs/references/ceph/src/pybind/mgr/dashboard/openapi.yaml.

// GetCrushRule calls GET /api/crush_rule.
// List Crush Rule Configuration
func (c *Client) GetCrushRule(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodGet, "/api/crush_rule", request, true)
}

// PostCrushRule calls POST /api/crush_rule.
// POST /api/crush_rule
func (c *Client) PostCrushRule(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodPost, "/api/crush_rule", request, true)
}

// DeleteCrushRuleByName calls DELETE /api/crush_rule/{name}.
// DELETE /api/crush_rule/{name}
func (c *Client) DeleteCrushRuleByName(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodDelete, "/api/crush_rule/{name}", request, true)
}

// GetCrushRuleByName calls GET /api/crush_rule/{name}.
// GET /api/crush_rule/{name}
func (c *Client) GetCrushRuleByName(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodGet, "/api/crush_rule/{name}", request, true)
}
