// Code generated by tools/generate_ceph_dashboard_client.rb; DO NOT EDIT.

package endpoints

import (
	"context"
	"encoding/json"
	"net/http"
)

// iscsi endpoints from docs/references/ceph/src/pybind/mgr/dashboard/openapi.yaml.

// GetIscsiDiscoveryauth calls GET /api/iscsi/discoveryauth.
// Get Iscsi discoveryauth Details
func (c *Client) GetIscsiDiscoveryauth(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodGet, "/api/iscsi/discoveryauth", request, true)
}

// PutIscsiDiscoveryauth calls PUT /api/iscsi/discoveryauth.
// Set Iscsi discoveryauth
func (c *Client) PutIscsiDiscoveryauth(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodPut, "/api/iscsi/discoveryauth", request, true)
}

// GetIscsiTarget calls GET /api/iscsi/target.
// GET /api/iscsi/target
func (c *Client) GetIscsiTarget(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodGet, "/api/iscsi/target", request, true)
}

// PostIscsiTarget calls POST /api/iscsi/target.
// POST /api/iscsi/target
func (c *Client) PostIscsiTarget(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodPost, "/api/iscsi/target", request, true)
}

// DeleteIscsiTargetByTargetIqn calls DELETE /api/iscsi/target/{target_iqn}.
// DELETE /api/iscsi/target/{target_iqn}
func (c *Client) DeleteIscsiTargetByTargetIqn(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodDelete, "/api/iscsi/target/{target_iqn}", request, true)
}

// GetIscsiTargetByTargetIqn calls GET /api/iscsi/target/{target_iqn}.
// GET /api/iscsi/target/{target_iqn}
func (c *Client) GetIscsiTargetByTargetIqn(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodGet, "/api/iscsi/target/{target_iqn}", request, true)
}

// PutIscsiTargetByTargetIqn calls PUT /api/iscsi/target/{target_iqn}.
// PUT /api/iscsi/target/{target_iqn}
func (c *Client) PutIscsiTargetByTargetIqn(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodPut, "/api/iscsi/target/{target_iqn}", request, true)
}
