// Code generated by tools/generate_ceph_dashboard_client.rb; DO NOT EDIT.

package endpoints

import (
	"context"
	"encoding/json"
	"net/http"
)

// logs endpoints from docs/references/ceph/src/pybind/mgr/dashboard/openapi.yaml.

// GetLogsAll calls GET /api/logs/all.
// Display Logs Configuration
func (c *Client) GetLogsAll(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodGet, "/api/logs/all", request, true)
}
