// Code generated by tools/generate_ceph_dashboard_client.rb; DO NOT EDIT.

package endpoints

import (
	"context"
	"encoding/json"
	"net/http"
)

// nvmeof endpoints from docs/references/ceph/src/pybind/mgr/dashboard/openapi.yaml.

// GetNvmeofGateway calls GET /api/nvmeof/gateway.
// Get information about the NVMeoF gateway
func (c *Client) GetNvmeofGateway(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodGet, "/api/nvmeof/gateway", request, true)
}

// GetNvmeofGatewayGroup calls GET /api/nvmeof/gateway/group.
// GET /api/nvmeof/gateway/group
func (c *Client) GetNvmeofGatewayGroup(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodGet, "/api/nvmeof/gateway/group", request, true)
}

// GetNvmeofGatewayListenerInfoByNqn calls GET /api/nvmeof/gateway/listener_info/{nqn}.
// Get NVMeoF gateway's listeners info
func (c *Client) GetNvmeofGatewayListenerInfoByNqn(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodGet, "/api/nvmeof/gateway/listener_info/{nqn}", request, true)
}

// GetNvmeofGatewayLogLevel calls GET /api/nvmeof/gateway/log_level.
// Get NVMeoF gateway log level information
func (c *Client) GetNvmeofGatewayLogLevel(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodGet, "/api/nvmeof/gateway/log_level", request, true)
}

// PutNvmeofGatewayLogLevel calls PUT /api/nvmeof/gateway/log_level.
// Set NVMeoF gateway log levels
func (c *Client) PutNvmeofGatewayLogLevel(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodPut, "/api/nvmeof/gateway/log_level", request, true)
}

// GetNvmeofGatewayStats calls GET /api/nvmeof/gateway/stats.
// Get NVMeoF statistics for the gateway
func (c *Client) GetNvmeofGatewayStats(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodGet, "/api/nvmeof/gateway/stats", request, true)
}

// GetNvmeofGatewayVersion calls GET /api/nvmeof/gateway/version.
// Get the version of the NVMeoF gateway
func (c *Client) GetNvmeofGatewayVersion(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodGet, "/api/nvmeof/gateway/version", request, true)
}

// GetNvmeofSpdkLogLevel calls GET /api/nvmeof/spdk/log_level.
// Get NVMeoF gateway spdk log levels
func (c *Client) GetNvmeofSpdkLogLevel(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodGet, "/api/nvmeof/spdk/log_level", request, true)
}

// PutNvmeofSpdkLogLevel calls PUT /api/nvmeof/spdk/log_level.
// Set NVMeoF gateway spdk log levels
func (c *Client) PutNvmeofSpdkLogLevel(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodPut, "/api/nvmeof/spdk/log_level", request, true)
}

// PutNvmeofSpdkLogLevelDisable calls PUT /api/nvmeof/spdk/log_level/disable.
// Disable NVMeoF gateway spdk log
func (c *Client) PutNvmeofSpdkLogLevelDisable(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodPut, "/api/nvmeof/spdk/log_level/disable", request, true)
}

// GetNvmeofSubsystem calls GET /api/nvmeof/subsystem.
// List all NVMeoF subsystems
func (c *Client) GetNvmeofSubsystem(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodGet, "/api/nvmeof/subsystem", request, true)
}

// PostNvmeofSubsystem calls POST /api/nvmeof/subsystem.
// Create a new NVMeoF subsystem
func (c *Client) PostNvmeofSubsystem(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodPost, "/api/nvmeof/subsystem", request, true)
}

// DeleteNvmeofSubsystemByNqn calls DELETE /api/nvmeof/subsystem/{nqn}.
// Delete an existing NVMeoF subsystem
func (c *Client) DeleteNvmeofSubsystemByNqn(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodDelete, "/api/nvmeof/subsystem/{nqn}", request, true)
}

// GetNvmeofSubsystemByNqn calls GET /api/nvmeof/subsystem/{nqn}.
// Get information from a specific NVMeoF subsystem
func (c *Client) GetNvmeofSubsystemByNqn(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodGet, "/api/nvmeof/subsystem/{nqn}", request, true)
}

// GetNvmeofSubsystemByNqnConnection calls GET /api/nvmeof/subsystem/{nqn}/connection.
// List all NVMeoF Subsystem Connections
func (c *Client) GetNvmeofSubsystemByNqnConnection(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodGet, "/api/nvmeof/subsystem/{nqn}/connection", request, true)
}

// GetNvmeofSubsystemByNqnHost calls GET /api/nvmeof/subsystem/{nqn}/host.
// List all allowed hosts for an NVMeoF subsystem
func (c *Client) GetNvmeofSubsystemByNqnHost(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodGet, "/api/nvmeof/subsystem/{nqn}/host", request, true)
}

// PostNvmeofSubsystemByNqnHost calls POST /api/nvmeof/subsystem/{nqn}/host.
// Allow hosts to access an NVMeoF subsystem
func (c *Client) PostNvmeofSubsystemByNqnHost(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodPost, "/api/nvmeof/subsystem/{nqn}/host", request, true)
}

// DeleteNvmeofSubsystemByNqnHostByHostNqn calls DELETE /api/nvmeof/subsystem/{nqn}/host/{host_nqn}.
// Disallow hosts from accessing an NVMeoF subsystem
func (c *Client) DeleteNvmeofSubsystemByNqnHostByHostNqn(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodDelete, "/api/nvmeof/subsystem/{nqn}/host/{host_nqn}", request, true)
}

// PutNvmeofSubsystemByNqnHostByHostNqnChangeControllerKey calls PUT /api/nvmeof/subsystem/{nqn}/host/{host_nqn}/change_controller_key.
// Change host DH-HMAC-CHAP controller key
func (c *Client) PutNvmeofSubsystemByNqnHostByHostNqnChangeControllerKey(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodPut, "/api/nvmeof/subsystem/{nqn}/host/{host_nqn}/change_controller_key", request, true)
}

// PutNvmeofSubsystemByNqnHostByHostNqnChangeKey calls PUT /api/nvmeof/subsystem/{nqn}/host/{host_nqn}/change_key.
// Change host DH-HMAC-CHAP key
func (c *Client) PutNvmeofSubsystemByNqnHostByHostNqnChangeKey(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodPut, "/api/nvmeof/subsystem/{nqn}/host/{host_nqn}/change_key", request, true)
}

// PutNvmeofSubsystemByNqnHostByHostNqnDelControllerKey calls PUT /api/nvmeof/subsystem/{nqn}/host/{host_nqn}/del_controller_key.
// Delete host DH-HMAC-CHAP controller key
func (c *Client) PutNvmeofSubsystemByNqnHostByHostNqnDelControllerKey(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodPut, "/api/nvmeof/subsystem/{nqn}/host/{host_nqn}/del_controller_key", request, true)
}

// PutNvmeofSubsystemByNqnHostByHostNqnDelKey calls PUT /api/nvmeof/subsystem/{nqn}/host/{host_nqn}/del_key.
// Delete host DH-HMAC-CHAP key
func (c *Client) PutNvmeofSubsystemByNqnHostByHostNqnDelKey(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodPut, "/api/nvmeof/subsystem/{nqn}/host/{host_nqn}/del_key", request, true)
}

// GetNvmeofSubsystemByNqnListener calls GET /api/nvmeof/subsystem/{nqn}/listener.
// List all NVMeoF listeners
func (c *Client) GetNvmeofSubsystemByNqnListener(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodGet, "/api/nvmeof/subsystem/{nqn}/listener", request, true)
}

// PostNvmeofSubsystemByNqnListener calls POST /api/nvmeof/subsystem/{nqn}/listener.
// Create a new NVMeoF listener
func (c *Client) PostNvmeofSubsystemByNqnListener(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodPost, "/api/nvmeof/subsystem/{nqn}/listener", request, true)
}

// DeleteNvmeofSubsystemByNqnListenerByHostNameByTraddrByTrsvcid calls DELETE /api/nvmeof/subsystem/{nqn}/listener/{host_name}/{traddr}/{trsvcid}.
// Delete an existing NVMeoF listener
func (c *Client) DeleteNvmeofSubsystemByNqnListenerByHostNameByTraddrByTrsvcid(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodDelete, "/api/nvmeof/subsystem/{nqn}/listener/{host_name}/{traddr}/{trsvcid}", request, true)
}

// GetNvmeofSubsystemByNqnNamespace calls GET /api/nvmeof/subsystem/{nqn}/namespace.
// List all NVMeoF namespaces in a subsystem
func (c *Client) GetNvmeofSubsystemByNqnNamespace(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodGet, "/api/nvmeof/subsystem/{nqn}/namespace", request, true)
}

// PostNvmeofSubsystemByNqnNamespace calls POST /api/nvmeof/subsystem/{nqn}/namespace.
// Create a new NVMeoF namespace.
func (c *Client) PostNvmeofSubsystemByNqnNamespace(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodPost, "/api/nvmeof/subsystem/{nqn}/namespace", request, true)
}

// DeleteNvmeofSubsystemByNqnNamespaceByNsid calls DELETE /api/nvmeof/subsystem/{nqn}/namespace/{nsid}.
// Delete an existing NVMeoF namespace
func (c *Client) DeleteNvmeofSubsystemByNqnNamespaceByNsid(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodDelete, "/api/nvmeof/subsystem/{nqn}/namespace/{nsid}", request, true)
}

// GetNvmeofSubsystemByNqnNamespaceByNsid calls GET /api/nvmeof/subsystem/{nqn}/namespace/{nsid}.
// Get info from specified NVMeoF namespace
func (c *Client) GetNvmeofSubsystemByNqnNamespaceByNsid(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodGet, "/api/nvmeof/subsystem/{nqn}/namespace/{nsid}", request, true)
}

// PatchNvmeofSubsystemByNqnNamespaceByNsid calls PATCH /api/nvmeof/subsystem/{nqn}/namespace/{nsid}.
// Update an existing NVMeoF namespace
func (c *Client) PatchNvmeofSubsystemByNqnNamespaceByNsid(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodPatch, "/api/nvmeof/subsystem/{nqn}/namespace/{nsid}", request, true)
}

// PutNvmeofSubsystemByNqnNamespaceByNsidAddHost calls PUT /api/nvmeof/subsystem/{nqn}/namespace/{nsid}/add_host.
// Adds a host to the specified NVMeoF namespace
func (c *Client) PutNvmeofSubsystemByNqnNamespaceByNsidAddHost(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodPut, "/api/nvmeof/subsystem/{nqn}/namespace/{nsid}/add_host", request, true)
}

// PutNvmeofSubsystemByNqnNamespaceByNsidChangeLoadBalancingGroup calls PUT /api/nvmeof/subsystem/{nqn}/namespace/{nsid}/change_load_balancing_group.
// set the load balancing group for specified NVMeoF namespace
func (c *Client) PutNvmeofSubsystemByNqnNamespaceByNsidChangeLoadBalancingGroup(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodPut, "/api/nvmeof/subsystem/{nqn}/namespace/{nsid}/change_load_balancing_group", request, true)
}

// PutNvmeofSubsystemByNqnNamespaceByNsidChangeVisibility calls PUT /api/nvmeof/subsystem/{nqn}/namespace/{nsid}/change_visibility.
// changes the visibility of the specified NVMeoF namespace to all or selected hosts
func (c *Client) PutNvmeofSubsystemByNqnNamespaceByNsidChangeVisibility(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodPut, "/api/nvmeof/subsystem/{nqn}/namespace/{nsid}/change_visibility", request, true)
}

// PutNvmeofSubsystemByNqnNamespaceByNsidDelHost calls PUT /api/nvmeof/subsystem/{nqn}/namespace/{nsid}/del_host.
// Removes a host from the specified NVMeoF namespace
func (c *Client) PutNvmeofSubsystemByNqnNamespaceByNsidDelHost(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodPut, "/api/nvmeof/subsystem/{nqn}/namespace/{nsid}/del_host", request, true)
}

// GetNvmeofSubsystemByNqnNamespaceByNsidIoStats calls GET /api/nvmeof/subsystem/{nqn}/namespace/{nsid}/io_stats.
// Get IO stats from specified NVMeoF namespace
func (c *Client) GetNvmeofSubsystemByNqnNamespaceByNsidIoStats(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodGet, "/api/nvmeof/subsystem/{nqn}/namespace/{nsid}/io_stats", request, true)
}

// PutNvmeofSubsystemByNqnNamespaceByNsidRefreshSize calls PUT /api/nvmeof/subsystem/{nqn}/namespace/{nsid}/refresh_size.
// refresh the specified NVMeoF namespace to current RBD image size
func (c *Client) PutNvmeofSubsystemByNqnNamespaceByNsidRefreshSize(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodPut, "/api/nvmeof/subsystem/{nqn}/namespace/{nsid}/refresh_size", request, true)
}

// PutNvmeofSubsystemByNqnNamespaceByNsidResize calls PUT /api/nvmeof/subsystem/{nqn}/namespace/{nsid}/resize.
// resize the specified NVMeoF namespace
func (c *Client) PutNvmeofSubsystemByNqnNamespaceByNsidResize(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodPut, "/api/nvmeof/subsystem/{nqn}/namespace/{nsid}/resize", request, true)
}

// PutNvmeofSubsystemByNqnNamespaceByNsidSetAutoResize calls PUT /api/nvmeof/subsystem/{nqn}/namespace/{nsid}/set_auto_resize.
// Enable or disable namespace auto resize when RBD image is resized
func (c *Client) PutNvmeofSubsystemByNqnNamespaceByNsidSetAutoResize(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodPut, "/api/nvmeof/subsystem/{nqn}/namespace/{nsid}/set_auto_resize", request, true)
}

// PutNvmeofSubsystemByNqnNamespaceByNsidSetQos calls PUT /api/nvmeof/subsystem/{nqn}/namespace/{nsid}/set_qos.
// set QOS for specified NVMeoF namespace
func (c *Client) PutNvmeofSubsystemByNqnNamespaceByNsidSetQos(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodPut, "/api/nvmeof/subsystem/{nqn}/namespace/{nsid}/set_qos", request, true)
}

// PutNvmeofSubsystemByNqnNamespaceByNsidSetRbdTrashImage calls PUT /api/nvmeof/subsystem/{nqn}/namespace/{nsid}/set_rbd_trash_image.
// changes the trash image on delete of the specified NVMeoF namespace to all or selected hosts
func (c *Client) PutNvmeofSubsystemByNqnNamespaceByNsidSetRbdTrashImage(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodPut, "/api/nvmeof/subsystem/{nqn}/namespace/{nsid}/set_rbd_trash_image", request, true)
}
