// Code generated by tools/generate_ceph_dashboard_client.rb; DO NOT EDIT.

package endpoints

import (
	"context"
	"encoding/json"
	"net/http"
)

// osd endpoints from docs/references/ceph/src/pybind/mgr/dashboard/openapi.yaml.

// GetOsd calls GET /api/osd.
// GET /api/osd
func (c *Client) GetOsd(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodGet, "/api/osd", request, true)
}

// PostOsd calls POST /api/osd.
// POST /api/osd
func (c *Client) PostOsd(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodPost, "/api/osd", request, true)
}

// GetOsdFlags calls GET /api/osd/flags.
// Display OSD Flags
func (c *Client) GetOsdFlags(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodGet, "/api/osd/flags", request, true)
}

// PutOsdFlags calls PUT /api/osd/flags.
// Sets OSD flags for the entire cluster.
func (c *Client) PutOsdFlags(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodPut, "/api/osd/flags", request, true)
}

// GetOsdFlagsIndividual calls GET /api/osd/flags/individual.
// Displays individual OSD flags
func (c *Client) GetOsdFlagsIndividual(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodGet, "/api/osd/flags/individual", request, true)
}

// PutOsdFlagsIndividual calls PUT /api/osd/flags/individual.
// Sets OSD flags for a subset of individual OSDs.
func (c *Client) PutOsdFlagsIndividual(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodPut, "/api/osd/flags/individual", request, true)
}

// GetOsdSafeToDelete calls GET /api/osd/safe_to_delete.
// GET /api/osd/safe_to_delete
func (c *Client) GetOsdSafeToDelete(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodGet, "/api/osd/safe_to_delete", request, true)
}

// GetOsdSafeToDestroy calls GET /api/osd/safe_to_destroy.
// Check If OSD is Safe to Destroy
func (c *Client) GetOsdSafeToDestroy(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodGet, "/api/osd/safe_to_destroy", request, true)
}

// GetOsdSettings calls GET /api/osd/settings.
// GET /api/osd/settings
func (c *Client) GetOsdSettings(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodGet, "/api/osd/settings", request, true)
}

// DeleteOsdBySvcId calls DELETE /api/osd/{svc_id}.
// DELETE /api/osd/{svc_id}
func (c *Client) DeleteOsdBySvcId(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodDelete, "/api/osd/{svc_id}", request, true)
}

// GetOsdBySvcId calls GET /api/osd/{svc_id}.
// GET /api/osd/{svc_id}
func (c *Client) GetOsdBySvcId(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodGet, "/api/osd/{svc_id}", request, true)
}

// PutOsdBySvcId calls PUT /api/osd/{svc_id}.
// PUT /api/osd/{svc_id}
func (c *Client) PutOsdBySvcId(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodPut, "/api/osd/{svc_id}", request, true)
}

// PostOsdBySvcIdDestroy calls POST /api/osd/{svc_id}/destroy.
// POST /api/osd/{svc_id}/destroy
func (c *Client) PostOsdBySvcIdDestroy(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodPost, "/api/osd/{svc_id}/destroy", request, true)
}

// GetOsdBySvcIdDevices calls GET /api/osd/{svc_id}/devices.
// GET /api/osd/{svc_id}/devices
func (c *Client) GetOsdBySvcIdDevices(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodGet, "/api/osd/{svc_id}/devices", request, true)
}

// GetOsdBySvcIdHistogram calls GET /api/osd/{svc_id}/histogram.
// GET /api/osd/{svc_id}/histogram
func (c *Client) GetOsdBySvcIdHistogram(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodGet, "/api/osd/{svc_id}/histogram", request, true)
}

// PutOsdBySvcIdMark calls PUT /api/osd/{svc_id}/mark.
// Mark OSD flags (out, in, down, lost, ...)
func (c *Client) PutOsdBySvcIdMark(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodPut, "/api/osd/{svc_id}/mark", request, true)
}

// PostOsdBySvcIdPurge calls POST /api/osd/{svc_id}/purge.
// POST /api/osd/{svc_id}/purge
func (c *Client) PostOsdBySvcIdPurge(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodPost, "/api/osd/{svc_id}/purge", request, true)
}

// PostOsdBySvcIdReweight calls POST /api/osd/{svc_id}/reweight.
// POST /api/osd/{svc_id}/reweight
func (c *Client) PostOsdBySvcIdReweight(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodPost, "/api/osd/{svc_id}/reweight", request, true)
}

// PostOsdBySvcIdScrub calls POST /api/osd/{svc_id}/scrub.
// POST /api/osd/{svc_id}/scrub
func (c *Client) PostOsdBySvcIdScrub(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodPost, "/api/osd/{svc_id}/scrub", request, true)
}

// GetOsdBySvcIdSmart calls GET /api/osd/{svc_id}/smart.
// GET /api/osd/{svc_id}/smart
func (c *Client) GetOsdBySvcIdSmart(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodGet, "/api/osd/{svc_id}/smart", request, true)
}
