// Code generated by tools/generate_ceph_dashboard_client.rb; DO NOT EDIT.

package endpoints

import (
	"context"
	"encoding/json"
	"net/http"
)

// prometheus endpoints from docs/references/ceph/src/pybind/mgr/dashboard/openapi.yaml.

// GetPrometheus calls GET /api/prometheus.
// GET /api/prometheus
func (c *Client) GetPrometheus(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodGet, "/api/prometheus", request, true)
}

// GetPrometheusAlertgroup calls GET /api/prometheus/alertgroup.
// GET /api/prometheus/alertgroup
func (c *Client) GetPrometheusAlertgroup(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodGet, "/api/prometheus/alertgroup", request, true)
}

// GetPrometheusData calls GET /api/prometheus/data.
// GET /api/prometheus/data
func (c *Client) GetPrometheusData(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodGet, "/api/prometheus/data", request, true)
}

// GetPrometheusNotifications calls GET /api/prometheus/notifications.
// GET /api/prometheus/notifications
func (c *Client) GetPrometheusNotifications(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodGet, "/api/prometheus/notifications", request, true)
}

// GetPrometheusPrometheusQueryData calls GET /api/prometheus/prometheus_query_data.
// GET /api/prometheus/prometheus_query_data
func (c *Client) GetPrometheusPrometheusQueryData(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodGet, "/api/prometheus/prometheus_query_data", request, true)
}

// GetPrometheusRules calls GET /api/prometheus/rules.
// GET /api/prometheus/rules
func (c *Client) GetPrometheusRules(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodGet, "/api/prometheus/rules", request, true)
}

// PostPrometheusSilence calls POST /api/prometheus/silence.
// POST /api/prometheus/silence
func (c *Client) PostPrometheusSilence(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodPost, "/api/prometheus/silence", request, true)
}

// DeletePrometheusSilenceBySId calls DELETE /api/prometheus/silence/{s_id}.
// DELETE /api/prometheus/silence/{s_id}
func (c *Client) DeletePrometheusSilenceBySId(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodDelete, "/api/prometheus/silence/{s_id}", request, true)
}

// GetPrometheusSilences calls GET /api/prometheus/silences.
// GET /api/prometheus/silences
func (c *Client) GetPrometheusSilences(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodGet, "/api/prometheus/silences", request, true)
}
