// Code generated by tools/generate_ceph_dashboard_client.rb; DO NOT EDIT.

package endpoints

import (
	"context"
	"encoding/json"
	"net/http"
)

// role endpoints from docs/references/ceph/src/pybind/mgr/dashboard/openapi.yaml.

// GetRole calls GET /api/role.
// Display Role list
func (c *Client) GetRole(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodGet, "/api/role", request, true)
}

// PostRole calls POST /api/role.
// POST /api/role
func (c *Client) PostRole(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodPost, "/api/role", request, true)
}

// DeleteRoleByName calls DELETE /api/role/{name}.
// DELETE /api/role/{name}
func (c *Client) DeleteRoleByName(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodDelete, "/api/role/{name}", request, true)
}

// GetRoleByName calls GET /api/role/{name}.
// GET /api/role/{name}
func (c *Client) GetRoleByName(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodGet, "/api/role/{name}", request, true)
}

// PutRoleByName calls PUT /api/role/{name}.
// PUT /api/role/{name}
func (c *Client) PutRoleByName(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodPut, "/api/role/{name}", request, true)
}

// PostRoleByNameClone calls POST /api/role/{name}/clone.
// POST /api/role/{name}/clone
func (c *Client) PostRoleByNameClone(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodPost, "/api/role/{name}/clone", request, true)
}
