// Code generated by tools/generate_ceph_dashboard_client.rb; DO NOT EDIT.

package typed

import (
	"context"
	"encoding/json"
	"net/http"
	"net/url"
)

// feedback typed endpoints from docs/references/ceph/src/pybind/mgr/dashboard/openapi.yaml.

type GetFeedbackResponse map[string]json.RawMessage

type GetFeedbackRequest struct{}

type PostFeedbackBody struct {
	ApiKey      string `json:"api_key,omitempty"`
	Description string `json:"description"`
	Project     string `json:"project"`
	Subject     string `json:"subject"`
	Tracker     string `json:"tracker"`
}

type PostFeedbackResponse map[string]json.RawMessage

type PostFeedbackRequest struct {
	Body PostFeedbackBody `json:"-"`
}

type DeleteFeedbackApiKeyResponse map[string]json.RawMessage

type DeleteFeedbackApiKeyRequest struct{}

type GetFeedbackApiKeyResponse map[string]json.RawMessage

type GetFeedbackApiKeyRequest struct{}

type PostFeedbackApiKeyBody struct {
	ApiKey string `json:"api_key"`
}

type PostFeedbackApiKeyResponse map[string]json.RawMessage

type PostFeedbackApiKeyRequest struct {
	Body PostFeedbackApiKeyBody `json:"-"`
}

// GetFeedback calls GET /api/feedback with typed request and response values.
func (c *Client) GetFeedback(ctx context.Context, request GetFeedbackRequest) (GetFeedbackResponse, error) {
	path := map[string]string{}
	query := url.Values{}
	var body any
	body = nil
	var response GetFeedbackResponse
	err := c.doJSON(ctx, http.MethodGet, "/api/feedback", path, query, body, true, &response)
	return response, err
}

// PostFeedback calls POST /api/feedback with typed request and response values.
func (c *Client) PostFeedback(ctx context.Context, request PostFeedbackRequest) (PostFeedbackResponse, error) {
	path := map[string]string{}
	query := url.Values{}
	var body any
	body = nil
	body = request.Body
	var response PostFeedbackResponse
	err := c.doJSON(ctx, http.MethodPost, "/api/feedback", path, query, body, true, &response)
	return response, err
}

// DeleteFeedbackApiKey calls DELETE /api/feedback/api_key with typed request and response values.
func (c *Client) DeleteFeedbackApiKey(ctx context.Context, request DeleteFeedbackApiKeyRequest) (DeleteFeedbackApiKeyResponse, error) {
	path := map[string]string{}
	query := url.Values{}
	var body any
	body = nil
	var response DeleteFeedbackApiKeyResponse
	err := c.doJSON(ctx, http.MethodDelete, "/api/feedback/api_key", path, query, body, true, &response)
	return response, err
}

// GetFeedbackApiKey calls GET /api/feedback/api_key with typed request and response values.
func (c *Client) GetFeedbackApiKey(ctx context.Context, request GetFeedbackApiKeyRequest) (GetFeedbackApiKeyResponse, error) {
	path := map[string]string{}
	query := url.Values{}
	var body any
	body = nil
	var response GetFeedbackApiKeyResponse
	err := c.doJSON(ctx, http.MethodGet, "/api/feedback/api_key", path, query, body, true, &response)
	return response, err
}

// PostFeedbackApiKey calls POST /api/feedback/api_key with typed request and response values.
func (c *Client) PostFeedbackApiKey(ctx context.Context, request PostFeedbackApiKeyRequest) (PostFeedbackApiKeyResponse, error) {
	path := map[string]string{}
	query := url.Values{}
	var body any
	body = nil
	body = request.Body
	var response PostFeedbackApiKeyResponse
	err := c.doJSON(ctx, http.MethodPost, "/api/feedback/api_key", path, query, body, true, &response)
	return response, err
}
