// Code generated by tools/generate_ceph_dashboard_client.rb; DO NOT EDIT.

package typed

import (
	"context"
	"encoding/json"
	"net/http"
	"net/url"
)

// hardware typed endpoints from docs/references/ceph/src/pybind/mgr/dashboard/openapi.yaml.

type GetHardwareSummaryResponse map[string]json.RawMessage

type GetHardwareSummaryRequest struct {
	Categories *string `query:"categories"`
	Hostname   *string `query:"hostname"`
}

// GetHardwareSummary calls GET /api/hardware/summary with typed request and response values.
func (c *Client) GetHardwareSummary(ctx context.Context, request GetHardwareSummaryRequest) (GetHardwareSummaryResponse, error) {
	path := map[string]string{}
	query := url.Values{}
	if request.Categories != nil {
		query.Set("categories", *request.Categories)
	}
	if request.Hostname != nil {
		query.Set("hostname", *request.Hostname)
	}
	var body any
	body = nil
	var response GetHardwareSummaryResponse
	err := c.doJSON(ctx, http.MethodGet, "/api/hardware/summary", path, query, body, true, &response)
	return response, err
}
