// Code generated by tools/generate_ceph_dashboard_client.rb; DO NOT EDIT.

package typed

import (
	"context"
	"net/http"
	"net/url"
)

// monitor typed endpoints from docs/references/ceph/src/pybind/mgr/dashboard/openapi.yaml.

type GetMonitorResponseInQuorumItemPublicAddrsAddrvecItem struct {
	Addr      string `json:"addr"`
	Nonce     int    `json:"nonce"`
	TypeValue string `json:"type"`
}

type GetMonitorResponseInQuorumItemPublicAddrs struct {
	Addrvec []GetMonitorResponseInQuorumItemPublicAddrsAddrvecItem `json:"addrvec"`
}

type GetMonitorResponseInQuorumItemStats struct {
	NumSessions []int `json:"num_sessions"`
}

type GetMonitorResponseInQuorumItem struct {
	Addr        string                                    `json:"addr"`
	Name        string                                    `json:"name"`
	Priority    int                                       `json:"priority"`
	PublicAddr  string                                    `json:"public_addr"`
	PublicAddrs GetMonitorResponseInQuorumItemPublicAddrs `json:"public_addrs"`
	Rank        int                                       `json:"rank"`
	Stats       GetMonitorResponseInQuorumItemStats       `json:"stats"`
	Weight      int                                       `json:"weight"`
}

type GetMonitorResponseMonStatusFeatureMapClientItem struct {
	Features string `json:"features"`
	Num      int    `json:"num"`
	Release  string `json:"release"`
}

type GetMonitorResponseMonStatusFeatureMapMdsItem struct {
	Features string `json:"features"`
	Num      int    `json:"num"`
	Release  string `json:"release"`
}

type GetMonitorResponseMonStatusFeatureMapMgrItem struct {
	Features string `json:"features"`
	Num      int    `json:"num"`
	Release  string `json:"release"`
}

type GetMonitorResponseMonStatusFeatureMapMonItem struct {
	Features string `json:"features"`
	Num      int    `json:"num"`
	Release  string `json:"release"`
}

type GetMonitorResponseMonStatusFeatureMap struct {
	Client []GetMonitorResponseMonStatusFeatureMapClientItem `json:"client"`
	Mds    []GetMonitorResponseMonStatusFeatureMapMdsItem    `json:"mds"`
	Mgr    []GetMonitorResponseMonStatusFeatureMapMgrItem    `json:"mgr"`
	Mon    []GetMonitorResponseMonStatusFeatureMapMonItem    `json:"mon"`
}

type GetMonitorResponseMonStatusFeatures struct {
	QuorumCon   string   `json:"quorum_con"`
	QuorumMon   []string `json:"quorum_mon"`
	RequiredCon string   `json:"required_con"`
	RequiredMon []int    `json:"required_mon"`
}

type GetMonitorResponseMonStatusMonmapFeatures struct {
	Optional   []string `json:"optional"`
	Persistent []string `json:"persistent"`
}

type GetMonitorResponseMonStatusMonmapMonsItemPublicAddrsAddrvecItem struct {
	Addr      string `json:"addr"`
	Nonce     int    `json:"nonce"`
	TypeValue string `json:"type"`
}

type GetMonitorResponseMonStatusMonmapMonsItemPublicAddrs struct {
	Addrvec []GetMonitorResponseMonStatusMonmapMonsItemPublicAddrsAddrvecItem `json:"addrvec"`
}

type GetMonitorResponseMonStatusMonmapMonsItemStats struct {
	NumSessions []int `json:"num_sessions"`
}

type GetMonitorResponseMonStatusMonmapMonsItem struct {
	Addr        string                                               `json:"addr"`
	Name        string                                               `json:"name"`
	Priority    int                                                  `json:"priority"`
	PublicAddr  string                                               `json:"public_addr"`
	PublicAddrs GetMonitorResponseMonStatusMonmapMonsItemPublicAddrs `json:"public_addrs"`
	Rank        int                                                  `json:"rank"`
	Stats       GetMonitorResponseMonStatusMonmapMonsItemStats       `json:"stats"`
	Weight      int                                                  `json:"weight"`
}

type GetMonitorResponseMonStatusMonmap struct {
	Created           string                                      `json:"created"`
	Epoch             int                                         `json:"epoch"`
	Features          GetMonitorResponseMonStatusMonmapFeatures   `json:"features"`
	Fsid              string                                      `json:"fsid"`
	MinMonRelease     int                                         `json:"min_mon_release"`
	MinMonReleaseName string                                      `json:"min_mon_release_name"`
	Modified          string                                      `json:"modified"`
	Mons              []GetMonitorResponseMonStatusMonmapMonsItem `json:"mons"`
}

type GetMonitorResponseMonStatus struct {
	ElectionEpoch   int                                   `json:"election_epoch"`
	ExtraProbePeers []string                              `json:"extra_probe_peers"`
	FeatureMap      GetMonitorResponseMonStatusFeatureMap `json:"feature_map"`
	Features        GetMonitorResponseMonStatusFeatures   `json:"features"`
	Monmap          GetMonitorResponseMonStatusMonmap     `json:"monmap"`
	Name            string                                `json:"name"`
	OutsideQuorum   []string                              `json:"outside_quorum"`
	Quorum          []int                                 `json:"quorum"`
	QuorumAge       int                                   `json:"quorum_age"`
	Rank            int                                   `json:"rank"`
	State           string                                `json:"state"`
	SyncProvider    []string                              `json:"sync_provider"`
}

type GetMonitorResponse struct {
	InQuorum  []GetMonitorResponseInQuorumItem `json:"in_quorum"`
	MonStatus GetMonitorResponseMonStatus      `json:"mon_status"`
	OutQuorum []int                            `json:"out_quorum"`
}

type GetMonitorRequest struct{}

// GetMonitor calls GET /api/monitor with typed request and response values.
func (c *Client) GetMonitor(ctx context.Context, request GetMonitorRequest) (GetMonitorResponse, error) {
	path := map[string]string{}
	query := url.Values{}
	var body any
	body = nil
	var response GetMonitorResponse
	err := c.doJSON(ctx, http.MethodGet, "/api/monitor", path, query, body, true, &response)
	return response, err
}
