// Code generated by tools/generate_ceph_dashboard_client.rb; DO NOT EDIT.

package typed

import (
	"context"
	"encoding/json"
	"net/http"
	"net/url"
	"strconv"
)

// nvmeof typed endpoints from docs/references/ceph/src/pybind/mgr/dashboard/openapi.yaml.

type GetNvmeofGatewayResponse map[string]json.RawMessage

type GetNvmeofGatewayRequest struct {
	GwGroup *string `query:"gw_group"`
	Traddr  *string `query:"traddr"`
}

type GetNvmeofGatewayGroupResponse map[string]json.RawMessage

type GetNvmeofGatewayGroupRequest struct{}

type GetNvmeofGatewayListenerInfoByNqnResponse map[string]json.RawMessage

type GetNvmeofGatewayListenerInfoByNqnRequest struct {
	Nqn     string  `path:"nqn"`
	GwGroup *string `query:"gw_group"`
	Traddr  *string `query:"traddr"`
}

type GetNvmeofGatewayLogLevelResponse map[string]json.RawMessage

type GetNvmeofGatewayLogLevelRequest struct {
	GwGroup *string `query:"gw_group"`
	Traddr  *string `query:"traddr"`
}

type PutNvmeofGatewayLogLevelBody struct {
	GwGroup  string `json:"gw_group,omitempty"`
	LogLevel string `json:"log_level"`
	Traddr   string `json:"traddr,omitempty"`
}

type PutNvmeofGatewayLogLevelResponse map[string]json.RawMessage

type PutNvmeofGatewayLogLevelRequest struct {
	Body PutNvmeofGatewayLogLevelBody `json:"-"`
}

type GetNvmeofGatewayStatsResponse map[string]json.RawMessage

type GetNvmeofGatewayStatsRequest struct {
	GwGroup *string `query:"gw_group"`
	Traddr  *string `query:"traddr"`
}

type GetNvmeofGatewayVersionResponse map[string]json.RawMessage

type GetNvmeofGatewayVersionRequest struct {
	GwGroup *string `query:"gw_group"`
	Traddr  *string `query:"traddr"`
}

type GetNvmeofSpdkLogLevelResponse map[string]json.RawMessage

type GetNvmeofSpdkLogLevelRequest struct {
	AllLogFlags *string `query:"all_log_flags"`
	GwGroup     *string `query:"gw_group"`
	Traddr      *string `query:"traddr"`
}

type PutNvmeofSpdkLogLevelBody struct {
	ExtraLogFlags string `json:"extra_log_flags,omitempty"`
	GwGroup       string `json:"gw_group,omitempty"`
	LogLevel      string `json:"log_level,omitempty"`
	PrintLevel    string `json:"print_level,omitempty"`
	Traddr        string `json:"traddr,omitempty"`
}

type PutNvmeofSpdkLogLevelResponse map[string]json.RawMessage

type PutNvmeofSpdkLogLevelRequest struct {
	Body PutNvmeofSpdkLogLevelBody `json:"-"`
}

type PutNvmeofSpdkLogLevelDisableBody struct {
	ExtraLogFlags string `json:"extra_log_flags,omitempty"`
	GwGroup       string `json:"gw_group,omitempty"`
	Traddr        string `json:"traddr,omitempty"`
}

type PutNvmeofSpdkLogLevelDisableResponse map[string]json.RawMessage

type PutNvmeofSpdkLogLevelDisableRequest struct {
	Body PutNvmeofSpdkLogLevelDisableBody `json:"-"`
}

type GetNvmeofSubsystemResponse map[string]json.RawMessage

type GetNvmeofSubsystemRequest struct {
	GwGroup *string `query:"gw_group"`
	Traddr  *string `query:"traddr"`
}

type PostNvmeofSubsystemBody struct {
	DhchapKey       string   `json:"dhchap_key,omitempty"`
	EnableHa        bool     `json:"enable_ha,omitempty"`
	GwGroup         string   `json:"gw_group,omitempty"`
	MaxNamespaces   int      `json:"max_namespaces,omitempty"`
	NetworkMask     []string `json:"network_mask,omitempty"`
	NoGroupAppend   int      `json:"no_group_append,omitempty"`
	Nqn             string   `json:"nqn"`
	Port            int      `json:"port,omitempty"`
	SecureListeners bool     `json:"secure_listeners,omitempty"`
	SerialNumber    string   `json:"serial_number,omitempty"`
	Traddr          string   `json:"traddr,omitempty"`
}

type PostNvmeofSubsystemResponse map[string]json.RawMessage

type PostNvmeofSubsystemRequest struct {
	Body PostNvmeofSubsystemBody `json:"-"`
}

type DeleteNvmeofSubsystemByNqnResponse map[string]json.RawMessage

type DeleteNvmeofSubsystemByNqnRequest struct {
	Nqn     string  `path:"nqn"`
	Force   *bool   `query:"force"`
	GwGroup *string `query:"gw_group"`
	Traddr  *string `query:"traddr"`
}

type GetNvmeofSubsystemByNqnResponse map[string]json.RawMessage

type GetNvmeofSubsystemByNqnRequest struct {
	Nqn     string  `path:"nqn"`
	GwGroup *string `query:"gw_group"`
	Traddr  *string `query:"traddr"`
}

type GetNvmeofSubsystemByNqnConnectionResponse map[string]json.RawMessage

type GetNvmeofSubsystemByNqnConnectionRequest struct {
	Nqn     string  `path:"nqn"`
	GwGroup *string `query:"gw_group"`
	Traddr  *string `query:"traddr"`
}

type GetNvmeofSubsystemByNqnHostResponse map[string]json.RawMessage

type GetNvmeofSubsystemByNqnHostRequest struct {
	Nqn         string  `path:"nqn"`
	ClearAlerts *bool   `query:"clear_alerts"`
	GwGroup     *string `query:"gw_group"`
	Traddr      *string `query:"traddr"`
}

type PostNvmeofSubsystemByNqnHostBody struct {
	DhchapControllerKey string `json:"dhchap_controller_key,omitempty"`
	DhchapKey           string `json:"dhchap_key,omitempty"`
	GwGroup             string `json:"gw_group,omitempty"`
	HostNqn             string `json:"host_nqn"`
	Psk                 string `json:"psk,omitempty"`
	Traddr              string `json:"traddr,omitempty"`
}

type PostNvmeofSubsystemByNqnHostResponse map[string]json.RawMessage

type PostNvmeofSubsystemByNqnHostRequest struct {
	Nqn  string                           `path:"nqn"`
	Body PostNvmeofSubsystemByNqnHostBody `json:"-"`
}

type DeleteNvmeofSubsystemByNqnHostByHostNqnResponse map[string]json.RawMessage

type DeleteNvmeofSubsystemByNqnHostByHostNqnRequest struct {
	Nqn     string  `path:"nqn"`
	HostNqn string  `path:"host_nqn"`
	GwGroup *string `query:"gw_group"`
	Traddr  *string `query:"traddr"`
}

type PutNvmeofSubsystemByNqnHostByHostNqnChangeControllerKeyBody struct {
	DhchapControllerKey string `json:"dhchap_controller_key"`
	GwGroup             string `json:"gw_group,omitempty"`
	Traddr              string `json:"traddr,omitempty"`
}

type PutNvmeofSubsystemByNqnHostByHostNqnChangeControllerKeyResponse map[string]json.RawMessage

type PutNvmeofSubsystemByNqnHostByHostNqnChangeControllerKeyRequest struct {
	Nqn     string                                                      `path:"nqn"`
	HostNqn string                                                      `path:"host_nqn"`
	Body    PutNvmeofSubsystemByNqnHostByHostNqnChangeControllerKeyBody `json:"-"`
}

type PutNvmeofSubsystemByNqnHostByHostNqnChangeKeyBody struct {
	DhchapKey string `json:"dhchap_key"`
	GwGroup   string `json:"gw_group,omitempty"`
	Traddr    string `json:"traddr,omitempty"`
}

type PutNvmeofSubsystemByNqnHostByHostNqnChangeKeyResponse map[string]json.RawMessage

type PutNvmeofSubsystemByNqnHostByHostNqnChangeKeyRequest struct {
	Nqn     string                                            `path:"nqn"`
	HostNqn string                                            `path:"host_nqn"`
	Body    PutNvmeofSubsystemByNqnHostByHostNqnChangeKeyBody `json:"-"`
}

type PutNvmeofSubsystemByNqnHostByHostNqnDelControllerKeyBody struct {
	GwGroup string `json:"gw_group,omitempty"`
	Traddr  string `json:"traddr,omitempty"`
}

type PutNvmeofSubsystemByNqnHostByHostNqnDelControllerKeyResponse map[string]json.RawMessage

type PutNvmeofSubsystemByNqnHostByHostNqnDelControllerKeyRequest struct {
	Nqn     string                                                   `path:"nqn"`
	HostNqn string                                                   `path:"host_nqn"`
	Body    PutNvmeofSubsystemByNqnHostByHostNqnDelControllerKeyBody `json:"-"`
}

type PutNvmeofSubsystemByNqnHostByHostNqnDelKeyBody struct {
	GwGroup string `json:"gw_group,omitempty"`
	Traddr  string `json:"traddr,omitempty"`
}

type PutNvmeofSubsystemByNqnHostByHostNqnDelKeyResponse map[string]json.RawMessage

type PutNvmeofSubsystemByNqnHostByHostNqnDelKeyRequest struct {
	Nqn     string                                         `path:"nqn"`
	HostNqn string                                         `path:"host_nqn"`
	Body    PutNvmeofSubsystemByNqnHostByHostNqnDelKeyBody `json:"-"`
}

type GetNvmeofSubsystemByNqnListenerResponse map[string]json.RawMessage

type GetNvmeofSubsystemByNqnListenerRequest struct {
	Nqn     string  `path:"nqn"`
	GwGroup *string `query:"gw_group"`
	Traddr  *string `query:"traddr"`
}

type PostNvmeofSubsystemByNqnListenerBody struct {
	Adrfam         int    `json:"adrfam,omitempty"`
	GwGroup        string `json:"gw_group,omitempty"`
	HostName       string `json:"host_name"`
	Secure         bool   `json:"secure,omitempty"`
	Traddr         string `json:"traddr"`
	Trsvcid        int    `json:"trsvcid,omitempty"`
	VerifyHostName bool   `json:"verify_host_name,omitempty"`
}

type PostNvmeofSubsystemByNqnListenerResponse map[string]json.RawMessage

type PostNvmeofSubsystemByNqnListenerRequest struct {
	Nqn  string                               `path:"nqn"`
	Body PostNvmeofSubsystemByNqnListenerBody `json:"-"`
}

type DeleteNvmeofSubsystemByNqnListenerByHostNameByTraddrByTrsvcidResponse map[string]json.RawMessage

type DeleteNvmeofSubsystemByNqnListenerByHostNameByTraddrByTrsvcidRequest struct {
	Nqn      string  `path:"nqn"`
	HostName string  `path:"host_name"`
	Traddr   string  `path:"traddr"`
	Trsvcid  string  `path:"trsvcid"`
	Adrfam   *int    `query:"adrfam"`
	Force    *bool   `query:"force"`
	GwGroup  *string `query:"gw_group"`
}

type GetNvmeofSubsystemByNqnNamespaceResponse map[string]json.RawMessage

type GetNvmeofSubsystemByNqnNamespaceRequest struct {
	Nqn     string  `path:"nqn"`
	Nsid    *string `query:"nsid"`
	GwGroup *string `query:"gw_group"`
	Traddr  *string `query:"traddr"`
}

type PostNvmeofSubsystemByNqnNamespaceBody struct {
	BlockSize           int      `json:"block_size,omitempty"`
	CreateImage         bool     `json:"create_image,omitempty"`
	DisableAutoResize   string   `json:"disable_auto_resize,omitempty"`
	EncryptionAlgorithm string   `json:"encryption_algorithm,omitempty"`
	EncryptionFormat    []string `json:"encryption_format,omitempty"`
	Force               bool     `json:"force,omitempty"`
	GwGroup             string   `json:"gw_group,omitempty"`
	KeyId               []string `json:"key_id,omitempty"`
	LoadBalancingGroup  int      `json:"load_balancing_group,omitempty"`
	NoAutoVisible       bool     `json:"no_auto_visible,omitempty"`
	Nsid                string   `json:"nsid,omitempty"`
	RadosNamespace      string   `json:"rados_namespace,omitempty"`
	RbdImageName        string   `json:"rbd_image_name"`
	RbdImageSize        int      `json:"rbd_image_size,omitempty"`
	RbdPool             string   `json:"rbd_pool,omitempty"`
	ReadOnly            string   `json:"read_only,omitempty"`
	Size                int      `json:"size,omitempty"`
	Traddr              string   `json:"traddr,omitempty"`
	TrashImage          bool     `json:"trash_image,omitempty"`
}

type PostNvmeofSubsystemByNqnNamespaceResponse map[string]json.RawMessage

type PostNvmeofSubsystemByNqnNamespaceRequest struct {
	Nqn  string                                `path:"nqn"`
	Body PostNvmeofSubsystemByNqnNamespaceBody `json:"-"`
}

type DeleteNvmeofSubsystemByNqnNamespaceByNsidResponse map[string]json.RawMessage

type DeleteNvmeofSubsystemByNqnNamespaceByNsidRequest struct {
	Nqn     string  `path:"nqn"`
	Nsid    string  `path:"nsid"`
	GwGroup *string `query:"gw_group"`
	Traddr  *string `query:"traddr"`
	Force   *string `query:"force"`
}

type GetNvmeofSubsystemByNqnNamespaceByNsidResponse map[string]json.RawMessage

type GetNvmeofSubsystemByNqnNamespaceByNsidRequest struct {
	Nqn     string  `path:"nqn"`
	Nsid    string  `path:"nsid"`
	GwGroup *string `query:"gw_group"`
	Traddr  *string `query:"traddr"`
}

type PatchNvmeofSubsystemByNqnNamespaceByNsidBody struct {
	GwGroup            string `json:"gw_group,omitempty"`
	LoadBalancingGroup int    `json:"load_balancing_group,omitempty"`
	RMbytesPerSecond   int    `json:"r_mbytes_per_second,omitempty"`
	RbdImageSize       int    `json:"rbd_image_size,omitempty"`
	RwIosPerSecond     int    `json:"rw_ios_per_second,omitempty"`
	RwMbytesPerSecond  int    `json:"rw_mbytes_per_second,omitempty"`
	Traddr             string `json:"traddr,omitempty"`
	TrashImage         bool   `json:"trash_image,omitempty"`
	WMbytesPerSecond   int    `json:"w_mbytes_per_second,omitempty"`
}

type PatchNvmeofSubsystemByNqnNamespaceByNsidResponse map[string]json.RawMessage

type PatchNvmeofSubsystemByNqnNamespaceByNsidRequest struct {
	Nqn  string                                       `path:"nqn"`
	Nsid string                                       `path:"nsid"`
	Body PatchNvmeofSubsystemByNqnNamespaceByNsidBody `json:"-"`
}

type PutNvmeofSubsystemByNqnNamespaceByNsidAddHostBody struct {
	Force   bool   `json:"force,omitempty"`
	GwGroup string `json:"gw_group,omitempty"`
	HostNqn string `json:"host_nqn"`
	Traddr  string `json:"traddr,omitempty"`
}

type PutNvmeofSubsystemByNqnNamespaceByNsidAddHostResponse map[string]json.RawMessage

type PutNvmeofSubsystemByNqnNamespaceByNsidAddHostRequest struct {
	Nqn  string                                            `path:"nqn"`
	Nsid string                                            `path:"nsid"`
	Body PutNvmeofSubsystemByNqnNamespaceByNsidAddHostBody `json:"-"`
}

type PutNvmeofSubsystemByNqnNamespaceByNsidChangeLoadBalancingGroupBody struct {
	GwGroup            string `json:"gw_group,omitempty"`
	LoadBalancingGroup int    `json:"load_balancing_group,omitempty"`
	Traddr             string `json:"traddr,omitempty"`
}

type PutNvmeofSubsystemByNqnNamespaceByNsidChangeLoadBalancingGroupResponse map[string]json.RawMessage

type PutNvmeofSubsystemByNqnNamespaceByNsidChangeLoadBalancingGroupRequest struct {
	Nqn  string                                                             `path:"nqn"`
	Nsid string                                                             `path:"nsid"`
	Body PutNvmeofSubsystemByNqnNamespaceByNsidChangeLoadBalancingGroupBody `json:"-"`
}

type PutNvmeofSubsystemByNqnNamespaceByNsidChangeVisibilityBody struct {
	AutoVisible bool   `json:"auto_visible"`
	Force       bool   `json:"force,omitempty"`
	GwGroup     string `json:"gw_group,omitempty"`
	Traddr      string `json:"traddr,omitempty"`
}

type PutNvmeofSubsystemByNqnNamespaceByNsidChangeVisibilityResponse map[string]json.RawMessage

type PutNvmeofSubsystemByNqnNamespaceByNsidChangeVisibilityRequest struct {
	Nqn  string                                                     `path:"nqn"`
	Nsid string                                                     `path:"nsid"`
	Body PutNvmeofSubsystemByNqnNamespaceByNsidChangeVisibilityBody `json:"-"`
}

type PutNvmeofSubsystemByNqnNamespaceByNsidDelHostBody struct {
	GwGroup string `json:"gw_group,omitempty"`
	HostNqn string `json:"host_nqn"`
	Traddr  string `json:"traddr,omitempty"`
}

type PutNvmeofSubsystemByNqnNamespaceByNsidDelHostResponse map[string]json.RawMessage

type PutNvmeofSubsystemByNqnNamespaceByNsidDelHostRequest struct {
	Nqn  string                                            `path:"nqn"`
	Nsid string                                            `path:"nsid"`
	Body PutNvmeofSubsystemByNqnNamespaceByNsidDelHostBody `json:"-"`
}

type GetNvmeofSubsystemByNqnNamespaceByNsidIoStatsResponse map[string]json.RawMessage

type GetNvmeofSubsystemByNqnNamespaceByNsidIoStatsRequest struct {
	Nqn     string  `path:"nqn"`
	Nsid    string  `path:"nsid"`
	GwGroup *string `query:"gw_group"`
	Traddr  *string `query:"traddr"`
}

type PutNvmeofSubsystemByNqnNamespaceByNsidRefreshSizeBody struct {
	GwGroup string `json:"gw_group,omitempty"`
	Traddr  string `json:"traddr,omitempty"`
}

type PutNvmeofSubsystemByNqnNamespaceByNsidRefreshSizeResponse map[string]json.RawMessage

type PutNvmeofSubsystemByNqnNamespaceByNsidRefreshSizeRequest struct {
	Nqn  string                                                `path:"nqn"`
	Nsid string                                                `path:"nsid"`
	Body PutNvmeofSubsystemByNqnNamespaceByNsidRefreshSizeBody `json:"-"`
}

type PutNvmeofSubsystemByNqnNamespaceByNsidResizeBody struct {
	GwGroup      string `json:"gw_group,omitempty"`
	RbdImageSize int    `json:"rbd_image_size"`
	Traddr       string `json:"traddr,omitempty"`
}

type PutNvmeofSubsystemByNqnNamespaceByNsidResizeResponse map[string]json.RawMessage

type PutNvmeofSubsystemByNqnNamespaceByNsidResizeRequest struct {
	Nqn  string                                           `path:"nqn"`
	Nsid string                                           `path:"nsid"`
	Body PutNvmeofSubsystemByNqnNamespaceByNsidResizeBody `json:"-"`
}

type PutNvmeofSubsystemByNqnNamespaceByNsidSetAutoResizeBody struct {
	AutoResizeEnabled bool   `json:"auto_resize_enabled"`
	GwGroup           string `json:"gw_group,omitempty"`
	Traddr            string `json:"traddr,omitempty"`
}

type PutNvmeofSubsystemByNqnNamespaceByNsidSetAutoResizeResponse map[string]json.RawMessage

type PutNvmeofSubsystemByNqnNamespaceByNsidSetAutoResizeRequest struct {
	Nqn  string                                                  `path:"nqn"`
	Nsid string                                                  `path:"nsid"`
	Body PutNvmeofSubsystemByNqnNamespaceByNsidSetAutoResizeBody `json:"-"`
}

type PutNvmeofSubsystemByNqnNamespaceByNsidSetQosBody struct {
	Force             bool   `json:"force,omitempty"`
	GwGroup           string `json:"gw_group,omitempty"`
	RMbytesPerSecond  int    `json:"r_mbytes_per_second,omitempty"`
	RwIosPerSecond    int    `json:"rw_ios_per_second,omitempty"`
	RwMbytesPerSecond int    `json:"rw_mbytes_per_second,omitempty"`
	Traddr            string `json:"traddr,omitempty"`
	WMbytesPerSecond  int    `json:"w_mbytes_per_second,omitempty"`
}

type PutNvmeofSubsystemByNqnNamespaceByNsidSetQosResponse map[string]json.RawMessage

type PutNvmeofSubsystemByNqnNamespaceByNsidSetQosRequest struct {
	Nqn  string                                           `path:"nqn"`
	Nsid string                                           `path:"nsid"`
	Body PutNvmeofSubsystemByNqnNamespaceByNsidSetQosBody `json:"-"`
}

type PutNvmeofSubsystemByNqnNamespaceByNsidSetRbdTrashImageBody struct {
	GwGroup               string `json:"gw_group,omitempty"`
	RbdTrashImageOnDelete bool   `json:"rbd_trash_image_on_delete"`
	Traddr                string `json:"traddr,omitempty"`
}

type PutNvmeofSubsystemByNqnNamespaceByNsidSetRbdTrashImageResponse map[string]json.RawMessage

type PutNvmeofSubsystemByNqnNamespaceByNsidSetRbdTrashImageRequest struct {
	Nqn  string                                                     `path:"nqn"`
	Nsid string                                                     `path:"nsid"`
	Body PutNvmeofSubsystemByNqnNamespaceByNsidSetRbdTrashImageBody `json:"-"`
}

// GetNvmeofGateway calls GET /api/nvmeof/gateway with typed request and response values.
func (c *Client) GetNvmeofGateway(ctx context.Context, request GetNvmeofGatewayRequest) (GetNvmeofGatewayResponse, error) {
	path := map[string]string{}
	query := url.Values{}
	if request.GwGroup != nil {
		query.Set("gw_group", *request.GwGroup)
	}
	if request.Traddr != nil {
		query.Set("traddr", *request.Traddr)
	}
	var body any
	body = nil
	var response GetNvmeofGatewayResponse
	err := c.doJSON(ctx, http.MethodGet, "/api/nvmeof/gateway", path, query, body, true, &response)
	return response, err
}

// GetNvmeofGatewayGroup calls GET /api/nvmeof/gateway/group with typed request and response values.
func (c *Client) GetNvmeofGatewayGroup(ctx context.Context, request GetNvmeofGatewayGroupRequest) (GetNvmeofGatewayGroupResponse, error) {
	path := map[string]string{}
	query := url.Values{}
	var body any
	body = nil
	var response GetNvmeofGatewayGroupResponse
	err := c.doJSON(ctx, http.MethodGet, "/api/nvmeof/gateway/group", path, query, body, true, &response)
	return response, err
}

// GetNvmeofGatewayListenerInfoByNqn calls GET /api/nvmeof/gateway/listener_info/{nqn} with typed request and response values.
func (c *Client) GetNvmeofGatewayListenerInfoByNqn(ctx context.Context, request GetNvmeofGatewayListenerInfoByNqnRequest) (GetNvmeofGatewayListenerInfoByNqnResponse, error) {
	path := map[string]string{
		"nqn": request.Nqn,
	}
	query := url.Values{}
	if request.GwGroup != nil {
		query.Set("gw_group", *request.GwGroup)
	}
	if request.Traddr != nil {
		query.Set("traddr", *request.Traddr)
	}
	var body any
	body = nil
	var response GetNvmeofGatewayListenerInfoByNqnResponse
	err := c.doJSON(ctx, http.MethodGet, "/api/nvmeof/gateway/listener_info/{nqn}", path, query, body, true, &response)
	return response, err
}

// GetNvmeofGatewayLogLevel calls GET /api/nvmeof/gateway/log_level with typed request and response values.
func (c *Client) GetNvmeofGatewayLogLevel(ctx context.Context, request GetNvmeofGatewayLogLevelRequest) (GetNvmeofGatewayLogLevelResponse, error) {
	path := map[string]string{}
	query := url.Values{}
	if request.GwGroup != nil {
		query.Set("gw_group", *request.GwGroup)
	}
	if request.Traddr != nil {
		query.Set("traddr", *request.Traddr)
	}
	var body any
	body = nil
	var response GetNvmeofGatewayLogLevelResponse
	err := c.doJSON(ctx, http.MethodGet, "/api/nvmeof/gateway/log_level", path, query, body, true, &response)
	return response, err
}

// PutNvmeofGatewayLogLevel calls PUT /api/nvmeof/gateway/log_level with typed request and response values.
func (c *Client) PutNvmeofGatewayLogLevel(ctx context.Context, request PutNvmeofGatewayLogLevelRequest) (PutNvmeofGatewayLogLevelResponse, error) {
	path := map[string]string{}
	query := url.Values{}
	var body any
	body = nil
	body = request.Body
	var response PutNvmeofGatewayLogLevelResponse
	err := c.doJSON(ctx, http.MethodPut, "/api/nvmeof/gateway/log_level", path, query, body, true, &response)
	return response, err
}

// GetNvmeofGatewayStats calls GET /api/nvmeof/gateway/stats with typed request and response values.
func (c *Client) GetNvmeofGatewayStats(ctx context.Context, request GetNvmeofGatewayStatsRequest) (GetNvmeofGatewayStatsResponse, error) {
	path := map[string]string{}
	query := url.Values{}
	if request.GwGroup != nil {
		query.Set("gw_group", *request.GwGroup)
	}
	if request.Traddr != nil {
		query.Set("traddr", *request.Traddr)
	}
	var body any
	body = nil
	var response GetNvmeofGatewayStatsResponse
	err := c.doJSON(ctx, http.MethodGet, "/api/nvmeof/gateway/stats", path, query, body, true, &response)
	return response, err
}

// GetNvmeofGatewayVersion calls GET /api/nvmeof/gateway/version with typed request and response values.
func (c *Client) GetNvmeofGatewayVersion(ctx context.Context, request GetNvmeofGatewayVersionRequest) (GetNvmeofGatewayVersionResponse, error) {
	path := map[string]string{}
	query := url.Values{}
	if request.GwGroup != nil {
		query.Set("gw_group", *request.GwGroup)
	}
	if request.Traddr != nil {
		query.Set("traddr", *request.Traddr)
	}
	var body any
	body = nil
	var response GetNvmeofGatewayVersionResponse
	err := c.doJSON(ctx, http.MethodGet, "/api/nvmeof/gateway/version", path, query, body, true, &response)
	return response, err
}

// GetNvmeofSpdkLogLevel calls GET /api/nvmeof/spdk/log_level with typed request and response values.
func (c *Client) GetNvmeofSpdkLogLevel(ctx context.Context, request GetNvmeofSpdkLogLevelRequest) (GetNvmeofSpdkLogLevelResponse, error) {
	path := map[string]string{}
	query := url.Values{}
	if request.AllLogFlags != nil {
		query.Set("all_log_flags", *request.AllLogFlags)
	}
	if request.GwGroup != nil {
		query.Set("gw_group", *request.GwGroup)
	}
	if request.Traddr != nil {
		query.Set("traddr", *request.Traddr)
	}
	var body any
	body = nil
	var response GetNvmeofSpdkLogLevelResponse
	err := c.doJSON(ctx, http.MethodGet, "/api/nvmeof/spdk/log_level", path, query, body, true, &response)
	return response, err
}

// PutNvmeofSpdkLogLevel calls PUT /api/nvmeof/spdk/log_level with typed request and response values.
func (c *Client) PutNvmeofSpdkLogLevel(ctx context.Context, request PutNvmeofSpdkLogLevelRequest) (PutNvmeofSpdkLogLevelResponse, error) {
	path := map[string]string{}
	query := url.Values{}
	var body any
	body = nil
	body = request.Body
	var response PutNvmeofSpdkLogLevelResponse
	err := c.doJSON(ctx, http.MethodPut, "/api/nvmeof/spdk/log_level", path, query, body, true, &response)
	return response, err
}

// PutNvmeofSpdkLogLevelDisable calls PUT /api/nvmeof/spdk/log_level/disable with typed request and response values.
func (c *Client) PutNvmeofSpdkLogLevelDisable(ctx context.Context, request PutNvmeofSpdkLogLevelDisableRequest) (PutNvmeofSpdkLogLevelDisableResponse, error) {
	path := map[string]string{}
	query := url.Values{}
	var body any
	body = nil
	body = request.Body
	var response PutNvmeofSpdkLogLevelDisableResponse
	err := c.doJSON(ctx, http.MethodPut, "/api/nvmeof/spdk/log_level/disable", path, query, body, true, &response)
	return response, err
}

// GetNvmeofSubsystem calls GET /api/nvmeof/subsystem with typed request and response values.
func (c *Client) GetNvmeofSubsystem(ctx context.Context, request GetNvmeofSubsystemRequest) (GetNvmeofSubsystemResponse, error) {
	path := map[string]string{}
	query := url.Values{}
	if request.GwGroup != nil {
		query.Set("gw_group", *request.GwGroup)
	}
	if request.Traddr != nil {
		query.Set("traddr", *request.Traddr)
	}
	var body any
	body = nil
	var response GetNvmeofSubsystemResponse
	err := c.doJSON(ctx, http.MethodGet, "/api/nvmeof/subsystem", path, query, body, true, &response)
	return response, err
}

// PostNvmeofSubsystem calls POST /api/nvmeof/subsystem with typed request and response values.
func (c *Client) PostNvmeofSubsystem(ctx context.Context, request PostNvmeofSubsystemRequest) (PostNvmeofSubsystemResponse, error) {
	path := map[string]string{}
	query := url.Values{}
	var body any
	body = nil
	body = request.Body
	var response PostNvmeofSubsystemResponse
	err := c.doJSON(ctx, http.MethodPost, "/api/nvmeof/subsystem", path, query, body, true, &response)
	return response, err
}

// DeleteNvmeofSubsystemByNqn calls DELETE /api/nvmeof/subsystem/{nqn} with typed request and response values.
func (c *Client) DeleteNvmeofSubsystemByNqn(ctx context.Context, request DeleteNvmeofSubsystemByNqnRequest) (DeleteNvmeofSubsystemByNqnResponse, error) {
	path := map[string]string{
		"nqn": request.Nqn,
	}
	query := url.Values{}
	if request.Force != nil {
		query.Set("force", strconv.FormatBool(*request.Force))
	}
	if request.GwGroup != nil {
		query.Set("gw_group", *request.GwGroup)
	}
	if request.Traddr != nil {
		query.Set("traddr", *request.Traddr)
	}
	var body any
	body = nil
	var response DeleteNvmeofSubsystemByNqnResponse
	err := c.doJSON(ctx, http.MethodDelete, "/api/nvmeof/subsystem/{nqn}", path, query, body, true, &response)
	return response, err
}

// GetNvmeofSubsystemByNqn calls GET /api/nvmeof/subsystem/{nqn} with typed request and response values.
func (c *Client) GetNvmeofSubsystemByNqn(ctx context.Context, request GetNvmeofSubsystemByNqnRequest) (GetNvmeofSubsystemByNqnResponse, error) {
	path := map[string]string{
		"nqn": request.Nqn,
	}
	query := url.Values{}
	if request.GwGroup != nil {
		query.Set("gw_group", *request.GwGroup)
	}
	if request.Traddr != nil {
		query.Set("traddr", *request.Traddr)
	}
	var body any
	body = nil
	var response GetNvmeofSubsystemByNqnResponse
	err := c.doJSON(ctx, http.MethodGet, "/api/nvmeof/subsystem/{nqn}", path, query, body, true, &response)
	return response, err
}

// GetNvmeofSubsystemByNqnConnection calls GET /api/nvmeof/subsystem/{nqn}/connection with typed request and response values.
func (c *Client) GetNvmeofSubsystemByNqnConnection(ctx context.Context, request GetNvmeofSubsystemByNqnConnectionRequest) (GetNvmeofSubsystemByNqnConnectionResponse, error) {
	path := map[string]string{
		"nqn": request.Nqn,
	}
	query := url.Values{}
	if request.GwGroup != nil {
		query.Set("gw_group", *request.GwGroup)
	}
	if request.Traddr != nil {
		query.Set("traddr", *request.Traddr)
	}
	var body any
	body = nil
	var response GetNvmeofSubsystemByNqnConnectionResponse
	err := c.doJSON(ctx, http.MethodGet, "/api/nvmeof/subsystem/{nqn}/connection", path, query, body, true, &response)
	return response, err
}

// GetNvmeofSubsystemByNqnHost calls GET /api/nvmeof/subsystem/{nqn}/host with typed request and response values.
func (c *Client) GetNvmeofSubsystemByNqnHost(ctx context.Context, request GetNvmeofSubsystemByNqnHostRequest) (GetNvmeofSubsystemByNqnHostResponse, error) {
	path := map[string]string{
		"nqn": request.Nqn,
	}
	query := url.Values{}
	if request.ClearAlerts != nil {
		query.Set("clear_alerts", strconv.FormatBool(*request.ClearAlerts))
	}
	if request.GwGroup != nil {
		query.Set("gw_group", *request.GwGroup)
	}
	if request.Traddr != nil {
		query.Set("traddr", *request.Traddr)
	}
	var body any
	body = nil
	var response GetNvmeofSubsystemByNqnHostResponse
	err := c.doJSON(ctx, http.MethodGet, "/api/nvmeof/subsystem/{nqn}/host", path, query, body, true, &response)
	return response, err
}

// PostNvmeofSubsystemByNqnHost calls POST /api/nvmeof/subsystem/{nqn}/host with typed request and response values.
func (c *Client) PostNvmeofSubsystemByNqnHost(ctx context.Context, request PostNvmeofSubsystemByNqnHostRequest) (PostNvmeofSubsystemByNqnHostResponse, error) {
	path := map[string]string{
		"nqn": request.Nqn,
	}
	query := url.Values{}
	var body any
	body = nil
	body = request.Body
	var response PostNvmeofSubsystemByNqnHostResponse
	err := c.doJSON(ctx, http.MethodPost, "/api/nvmeof/subsystem/{nqn}/host", path, query, body, true, &response)
	return response, err
}

// DeleteNvmeofSubsystemByNqnHostByHostNqn calls DELETE /api/nvmeof/subsystem/{nqn}/host/{host_nqn} with typed request and response values.
func (c *Client) DeleteNvmeofSubsystemByNqnHostByHostNqn(ctx context.Context, request DeleteNvmeofSubsystemByNqnHostByHostNqnRequest) (DeleteNvmeofSubsystemByNqnHostByHostNqnResponse, error) {
	path := map[string]string{
		"nqn":      request.Nqn,
		"host_nqn": request.HostNqn,
	}
	query := url.Values{}
	if request.GwGroup != nil {
		query.Set("gw_group", *request.GwGroup)
	}
	if request.Traddr != nil {
		query.Set("traddr", *request.Traddr)
	}
	var body any
	body = nil
	var response DeleteNvmeofSubsystemByNqnHostByHostNqnResponse
	err := c.doJSON(ctx, http.MethodDelete, "/api/nvmeof/subsystem/{nqn}/host/{host_nqn}", path, query, body, true, &response)
	return response, err
}

// PutNvmeofSubsystemByNqnHostByHostNqnChangeControllerKey calls PUT /api/nvmeof/subsystem/{nqn}/host/{host_nqn}/change_controller_key with typed request and response values.
func (c *Client) PutNvmeofSubsystemByNqnHostByHostNqnChangeControllerKey(ctx context.Context, request PutNvmeofSubsystemByNqnHostByHostNqnChangeControllerKeyRequest) (PutNvmeofSubsystemByNqnHostByHostNqnChangeControllerKeyResponse, error) {
	path := map[string]string{
		"nqn":      request.Nqn,
		"host_nqn": request.HostNqn,
	}
	query := url.Values{}
	var body any
	body = nil
	body = request.Body
	var response PutNvmeofSubsystemByNqnHostByHostNqnChangeControllerKeyResponse
	err := c.doJSON(ctx, http.MethodPut, "/api/nvmeof/subsystem/{nqn}/host/{host_nqn}/change_controller_key", path, query, body, true, &response)
	return response, err
}

// PutNvmeofSubsystemByNqnHostByHostNqnChangeKey calls PUT /api/nvmeof/subsystem/{nqn}/host/{host_nqn}/change_key with typed request and response values.
func (c *Client) PutNvmeofSubsystemByNqnHostByHostNqnChangeKey(ctx context.Context, request PutNvmeofSubsystemByNqnHostByHostNqnChangeKeyRequest) (PutNvmeofSubsystemByNqnHostByHostNqnChangeKeyResponse, error) {
	path := map[string]string{
		"nqn":      request.Nqn,
		"host_nqn": request.HostNqn,
	}
	query := url.Values{}
	var body any
	body = nil
	body = request.Body
	var response PutNvmeofSubsystemByNqnHostByHostNqnChangeKeyResponse
	err := c.doJSON(ctx, http.MethodPut, "/api/nvmeof/subsystem/{nqn}/host/{host_nqn}/change_key", path, query, body, true, &response)
	return response, err
}

// PutNvmeofSubsystemByNqnHostByHostNqnDelControllerKey calls PUT /api/nvmeof/subsystem/{nqn}/host/{host_nqn}/del_controller_key with typed request and response values.
func (c *Client) PutNvmeofSubsystemByNqnHostByHostNqnDelControllerKey(ctx context.Context, request PutNvmeofSubsystemByNqnHostByHostNqnDelControllerKeyRequest) (PutNvmeofSubsystemByNqnHostByHostNqnDelControllerKeyResponse, error) {
	path := map[string]string{
		"nqn":      request.Nqn,
		"host_nqn": request.HostNqn,
	}
	query := url.Values{}
	var body any
	body = nil
	body = request.Body
	var response PutNvmeofSubsystemByNqnHostByHostNqnDelControllerKeyResponse
	err := c.doJSON(ctx, http.MethodPut, "/api/nvmeof/subsystem/{nqn}/host/{host_nqn}/del_controller_key", path, query, body, true, &response)
	return response, err
}

// PutNvmeofSubsystemByNqnHostByHostNqnDelKey calls PUT /api/nvmeof/subsystem/{nqn}/host/{host_nqn}/del_key with typed request and response values.
func (c *Client) PutNvmeofSubsystemByNqnHostByHostNqnDelKey(ctx context.Context, request PutNvmeofSubsystemByNqnHostByHostNqnDelKeyRequest) (PutNvmeofSubsystemByNqnHostByHostNqnDelKeyResponse, error) {
	path := map[string]string{
		"nqn":      request.Nqn,
		"host_nqn": request.HostNqn,
	}
	query := url.Values{}
	var body any
	body = nil
	body = request.Body
	var response PutNvmeofSubsystemByNqnHostByHostNqnDelKeyResponse
	err := c.doJSON(ctx, http.MethodPut, "/api/nvmeof/subsystem/{nqn}/host/{host_nqn}/del_key", path, query, body, true, &response)
	return response, err
}

// GetNvmeofSubsystemByNqnListener calls GET /api/nvmeof/subsystem/{nqn}/listener with typed request and response values.
func (c *Client) GetNvmeofSubsystemByNqnListener(ctx context.Context, request GetNvmeofSubsystemByNqnListenerRequest) (GetNvmeofSubsystemByNqnListenerResponse, error) {
	path := map[string]string{
		"nqn": request.Nqn,
	}
	query := url.Values{}
	if request.GwGroup != nil {
		query.Set("gw_group", *request.GwGroup)
	}
	if request.Traddr != nil {
		query.Set("traddr", *request.Traddr)
	}
	var body any
	body = nil
	var response GetNvmeofSubsystemByNqnListenerResponse
	err := c.doJSON(ctx, http.MethodGet, "/api/nvmeof/subsystem/{nqn}/listener", path, query, body, true, &response)
	return response, err
}

// PostNvmeofSubsystemByNqnListener calls POST /api/nvmeof/subsystem/{nqn}/listener with typed request and response values.
func (c *Client) PostNvmeofSubsystemByNqnListener(ctx context.Context, request PostNvmeofSubsystemByNqnListenerRequest) (PostNvmeofSubsystemByNqnListenerResponse, error) {
	path := map[string]string{
		"nqn": request.Nqn,
	}
	query := url.Values{}
	var body any
	body = nil
	body = request.Body
	var response PostNvmeofSubsystemByNqnListenerResponse
	err := c.doJSON(ctx, http.MethodPost, "/api/nvmeof/subsystem/{nqn}/listener", path, query, body, true, &response)
	return response, err
}

// DeleteNvmeofSubsystemByNqnListenerByHostNameByTraddrByTrsvcid calls DELETE /api/nvmeof/subsystem/{nqn}/listener/{host_name}/{traddr}/{trsvcid} with typed request and response values.
func (c *Client) DeleteNvmeofSubsystemByNqnListenerByHostNameByTraddrByTrsvcid(ctx context.Context, request DeleteNvmeofSubsystemByNqnListenerByHostNameByTraddrByTrsvcidRequest) (DeleteNvmeofSubsystemByNqnListenerByHostNameByTraddrByTrsvcidResponse, error) {
	path := map[string]string{
		"nqn":       request.Nqn,
		"host_name": request.HostName,
		"traddr":    request.Traddr,
		"trsvcid":   request.Trsvcid,
	}
	query := url.Values{}
	if request.Adrfam != nil {
		query.Set("adrfam", strconv.Itoa(*request.Adrfam))
	}
	if request.Force != nil {
		query.Set("force", strconv.FormatBool(*request.Force))
	}
	if request.GwGroup != nil {
		query.Set("gw_group", *request.GwGroup)
	}
	var body any
	body = nil
	var response DeleteNvmeofSubsystemByNqnListenerByHostNameByTraddrByTrsvcidResponse
	err := c.doJSON(ctx, http.MethodDelete, "/api/nvmeof/subsystem/{nqn}/listener/{host_name}/{traddr}/{trsvcid}", path, query, body, true, &response)
	return response, err
}

// GetNvmeofSubsystemByNqnNamespace calls GET /api/nvmeof/subsystem/{nqn}/namespace with typed request and response values.
func (c *Client) GetNvmeofSubsystemByNqnNamespace(ctx context.Context, request GetNvmeofSubsystemByNqnNamespaceRequest) (GetNvmeofSubsystemByNqnNamespaceResponse, error) {
	path := map[string]string{
		"nqn": request.Nqn,
	}
	query := url.Values{}
	if request.Nsid != nil {
		query.Set("nsid", *request.Nsid)
	}
	if request.GwGroup != nil {
		query.Set("gw_group", *request.GwGroup)
	}
	if request.Traddr != nil {
		query.Set("traddr", *request.Traddr)
	}
	var body any
	body = nil
	var response GetNvmeofSubsystemByNqnNamespaceResponse
	err := c.doJSON(ctx, http.MethodGet, "/api/nvmeof/subsystem/{nqn}/namespace", path, query, body, true, &response)
	return response, err
}

// PostNvmeofSubsystemByNqnNamespace calls POST /api/nvmeof/subsystem/{nqn}/namespace with typed request and response values.
func (c *Client) PostNvmeofSubsystemByNqnNamespace(ctx context.Context, request PostNvmeofSubsystemByNqnNamespaceRequest) (PostNvmeofSubsystemByNqnNamespaceResponse, error) {
	path := map[string]string{
		"nqn": request.Nqn,
	}
	query := url.Values{}
	var body any
	body = nil
	body = request.Body
	var response PostNvmeofSubsystemByNqnNamespaceResponse
	err := c.doJSON(ctx, http.MethodPost, "/api/nvmeof/subsystem/{nqn}/namespace", path, query, body, true, &response)
	return response, err
}

// DeleteNvmeofSubsystemByNqnNamespaceByNsid calls DELETE /api/nvmeof/subsystem/{nqn}/namespace/{nsid} with typed request and response values.
func (c *Client) DeleteNvmeofSubsystemByNqnNamespaceByNsid(ctx context.Context, request DeleteNvmeofSubsystemByNqnNamespaceByNsidRequest) (DeleteNvmeofSubsystemByNqnNamespaceByNsidResponse, error) {
	path := map[string]string{
		"nqn":  request.Nqn,
		"nsid": request.Nsid,
	}
	query := url.Values{}
	if request.GwGroup != nil {
		query.Set("gw_group", *request.GwGroup)
	}
	if request.Traddr != nil {
		query.Set("traddr", *request.Traddr)
	}
	if request.Force != nil {
		query.Set("force", *request.Force)
	}
	var body any
	body = nil
	var response DeleteNvmeofSubsystemByNqnNamespaceByNsidResponse
	err := c.doJSON(ctx, http.MethodDelete, "/api/nvmeof/subsystem/{nqn}/namespace/{nsid}", path, query, body, true, &response)
	return response, err
}

// GetNvmeofSubsystemByNqnNamespaceByNsid calls GET /api/nvmeof/subsystem/{nqn}/namespace/{nsid} with typed request and response values.
func (c *Client) GetNvmeofSubsystemByNqnNamespaceByNsid(ctx context.Context, request GetNvmeofSubsystemByNqnNamespaceByNsidRequest) (GetNvmeofSubsystemByNqnNamespaceByNsidResponse, error) {
	path := map[string]string{
		"nqn":  request.Nqn,
		"nsid": request.Nsid,
	}
	query := url.Values{}
	if request.GwGroup != nil {
		query.Set("gw_group", *request.GwGroup)
	}
	if request.Traddr != nil {
		query.Set("traddr", *request.Traddr)
	}
	var body any
	body = nil
	var response GetNvmeofSubsystemByNqnNamespaceByNsidResponse
	err := c.doJSON(ctx, http.MethodGet, "/api/nvmeof/subsystem/{nqn}/namespace/{nsid}", path, query, body, true, &response)
	return response, err
}

// PatchNvmeofSubsystemByNqnNamespaceByNsid calls PATCH /api/nvmeof/subsystem/{nqn}/namespace/{nsid} with typed request and response values.
func (c *Client) PatchNvmeofSubsystemByNqnNamespaceByNsid(ctx context.Context, request PatchNvmeofSubsystemByNqnNamespaceByNsidRequest) (PatchNvmeofSubsystemByNqnNamespaceByNsidResponse, error) {
	path := map[string]string{
		"nqn":  request.Nqn,
		"nsid": request.Nsid,
	}
	query := url.Values{}
	var body any
	body = nil
	body = request.Body
	var response PatchNvmeofSubsystemByNqnNamespaceByNsidResponse
	err := c.doJSON(ctx, http.MethodPatch, "/api/nvmeof/subsystem/{nqn}/namespace/{nsid}", path, query, body, true, &response)
	return response, err
}

// PutNvmeofSubsystemByNqnNamespaceByNsidAddHost calls PUT /api/nvmeof/subsystem/{nqn}/namespace/{nsid}/add_host with typed request and response values.
func (c *Client) PutNvmeofSubsystemByNqnNamespaceByNsidAddHost(ctx context.Context, request PutNvmeofSubsystemByNqnNamespaceByNsidAddHostRequest) (PutNvmeofSubsystemByNqnNamespaceByNsidAddHostResponse, error) {
	path := map[string]string{
		"nqn":  request.Nqn,
		"nsid": request.Nsid,
	}
	query := url.Values{}
	var body any
	body = nil
	body = request.Body
	var response PutNvmeofSubsystemByNqnNamespaceByNsidAddHostResponse
	err := c.doJSON(ctx, http.MethodPut, "/api/nvmeof/subsystem/{nqn}/namespace/{nsid}/add_host", path, query, body, true, &response)
	return response, err
}

// PutNvmeofSubsystemByNqnNamespaceByNsidChangeLoadBalancingGroup calls PUT /api/nvmeof/subsystem/{nqn}/namespace/{nsid}/change_load_balancing_group with typed request and response values.
func (c *Client) PutNvmeofSubsystemByNqnNamespaceByNsidChangeLoadBalancingGroup(ctx context.Context, request PutNvmeofSubsystemByNqnNamespaceByNsidChangeLoadBalancingGroupRequest) (PutNvmeofSubsystemByNqnNamespaceByNsidChangeLoadBalancingGroupResponse, error) {
	path := map[string]string{
		"nqn":  request.Nqn,
		"nsid": request.Nsid,
	}
	query := url.Values{}
	var body any
	body = nil
	body = request.Body
	var response PutNvmeofSubsystemByNqnNamespaceByNsidChangeLoadBalancingGroupResponse
	err := c.doJSON(ctx, http.MethodPut, "/api/nvmeof/subsystem/{nqn}/namespace/{nsid}/change_load_balancing_group", path, query, body, true, &response)
	return response, err
}

// PutNvmeofSubsystemByNqnNamespaceByNsidChangeVisibility calls PUT /api/nvmeof/subsystem/{nqn}/namespace/{nsid}/change_visibility with typed request and response values.
func (c *Client) PutNvmeofSubsystemByNqnNamespaceByNsidChangeVisibility(ctx context.Context, request PutNvmeofSubsystemByNqnNamespaceByNsidChangeVisibilityRequest) (PutNvmeofSubsystemByNqnNamespaceByNsidChangeVisibilityResponse, error) {
	path := map[string]string{
		"nqn":  request.Nqn,
		"nsid": request.Nsid,
	}
	query := url.Values{}
	var body any
	body = nil
	body = request.Body
	var response PutNvmeofSubsystemByNqnNamespaceByNsidChangeVisibilityResponse
	err := c.doJSON(ctx, http.MethodPut, "/api/nvmeof/subsystem/{nqn}/namespace/{nsid}/change_visibility", path, query, body, true, &response)
	return response, err
}

// PutNvmeofSubsystemByNqnNamespaceByNsidDelHost calls PUT /api/nvmeof/subsystem/{nqn}/namespace/{nsid}/del_host with typed request and response values.
func (c *Client) PutNvmeofSubsystemByNqnNamespaceByNsidDelHost(ctx context.Context, request PutNvmeofSubsystemByNqnNamespaceByNsidDelHostRequest) (PutNvmeofSubsystemByNqnNamespaceByNsidDelHostResponse, error) {
	path := map[string]string{
		"nqn":  request.Nqn,
		"nsid": request.Nsid,
	}
	query := url.Values{}
	var body any
	body = nil
	body = request.Body
	var response PutNvmeofSubsystemByNqnNamespaceByNsidDelHostResponse
	err := c.doJSON(ctx, http.MethodPut, "/api/nvmeof/subsystem/{nqn}/namespace/{nsid}/del_host", path, query, body, true, &response)
	return response, err
}

// GetNvmeofSubsystemByNqnNamespaceByNsidIoStats calls GET /api/nvmeof/subsystem/{nqn}/namespace/{nsid}/io_stats with typed request and response values.
func (c *Client) GetNvmeofSubsystemByNqnNamespaceByNsidIoStats(ctx context.Context, request GetNvmeofSubsystemByNqnNamespaceByNsidIoStatsRequest) (GetNvmeofSubsystemByNqnNamespaceByNsidIoStatsResponse, error) {
	path := map[string]string{
		"nqn":  request.Nqn,
		"nsid": request.Nsid,
	}
	query := url.Values{}
	if request.GwGroup != nil {
		query.Set("gw_group", *request.GwGroup)
	}
	if request.Traddr != nil {
		query.Set("traddr", *request.Traddr)
	}
	var body any
	body = nil
	var response GetNvmeofSubsystemByNqnNamespaceByNsidIoStatsResponse
	err := c.doJSON(ctx, http.MethodGet, "/api/nvmeof/subsystem/{nqn}/namespace/{nsid}/io_stats", path, query, body, true, &response)
	return response, err
}

// PutNvmeofSubsystemByNqnNamespaceByNsidRefreshSize calls PUT /api/nvmeof/subsystem/{nqn}/namespace/{nsid}/refresh_size with typed request and response values.
func (c *Client) PutNvmeofSubsystemByNqnNamespaceByNsidRefreshSize(ctx context.Context, request PutNvmeofSubsystemByNqnNamespaceByNsidRefreshSizeRequest) (PutNvmeofSubsystemByNqnNamespaceByNsidRefreshSizeResponse, error) {
	path := map[string]string{
		"nqn":  request.Nqn,
		"nsid": request.Nsid,
	}
	query := url.Values{}
	var body any
	body = nil
	body = request.Body
	var response PutNvmeofSubsystemByNqnNamespaceByNsidRefreshSizeResponse
	err := c.doJSON(ctx, http.MethodPut, "/api/nvmeof/subsystem/{nqn}/namespace/{nsid}/refresh_size", path, query, body, true, &response)
	return response, err
}

// PutNvmeofSubsystemByNqnNamespaceByNsidResize calls PUT /api/nvmeof/subsystem/{nqn}/namespace/{nsid}/resize with typed request and response values.
func (c *Client) PutNvmeofSubsystemByNqnNamespaceByNsidResize(ctx context.Context, request PutNvmeofSubsystemByNqnNamespaceByNsidResizeRequest) (PutNvmeofSubsystemByNqnNamespaceByNsidResizeResponse, error) {
	path := map[string]string{
		"nqn":  request.Nqn,
		"nsid": request.Nsid,
	}
	query := url.Values{}
	var body any
	body = nil
	body = request.Body
	var response PutNvmeofSubsystemByNqnNamespaceByNsidResizeResponse
	err := c.doJSON(ctx, http.MethodPut, "/api/nvmeof/subsystem/{nqn}/namespace/{nsid}/resize", path, query, body, true, &response)
	return response, err
}

// PutNvmeofSubsystemByNqnNamespaceByNsidSetAutoResize calls PUT /api/nvmeof/subsystem/{nqn}/namespace/{nsid}/set_auto_resize with typed request and response values.
func (c *Client) PutNvmeofSubsystemByNqnNamespaceByNsidSetAutoResize(ctx context.Context, request PutNvmeofSubsystemByNqnNamespaceByNsidSetAutoResizeRequest) (PutNvmeofSubsystemByNqnNamespaceByNsidSetAutoResizeResponse, error) {
	path := map[string]string{
		"nqn":  request.Nqn,
		"nsid": request.Nsid,
	}
	query := url.Values{}
	var body any
	body = nil
	body = request.Body
	var response PutNvmeofSubsystemByNqnNamespaceByNsidSetAutoResizeResponse
	err := c.doJSON(ctx, http.MethodPut, "/api/nvmeof/subsystem/{nqn}/namespace/{nsid}/set_auto_resize", path, query, body, true, &response)
	return response, err
}

// PutNvmeofSubsystemByNqnNamespaceByNsidSetQos calls PUT /api/nvmeof/subsystem/{nqn}/namespace/{nsid}/set_qos with typed request and response values.
func (c *Client) PutNvmeofSubsystemByNqnNamespaceByNsidSetQos(ctx context.Context, request PutNvmeofSubsystemByNqnNamespaceByNsidSetQosRequest) (PutNvmeofSubsystemByNqnNamespaceByNsidSetQosResponse, error) {
	path := map[string]string{
		"nqn":  request.Nqn,
		"nsid": request.Nsid,
	}
	query := url.Values{}
	var body any
	body = nil
	body = request.Body
	var response PutNvmeofSubsystemByNqnNamespaceByNsidSetQosResponse
	err := c.doJSON(ctx, http.MethodPut, "/api/nvmeof/subsystem/{nqn}/namespace/{nsid}/set_qos", path, query, body, true, &response)
	return response, err
}

// PutNvmeofSubsystemByNqnNamespaceByNsidSetRbdTrashImage calls PUT /api/nvmeof/subsystem/{nqn}/namespace/{nsid}/set_rbd_trash_image with typed request and response values.
func (c *Client) PutNvmeofSubsystemByNqnNamespaceByNsidSetRbdTrashImage(ctx context.Context, request PutNvmeofSubsystemByNqnNamespaceByNsidSetRbdTrashImageRequest) (PutNvmeofSubsystemByNqnNamespaceByNsidSetRbdTrashImageResponse, error) {
	path := map[string]string{
		"nqn":  request.Nqn,
		"nsid": request.Nsid,
	}
	query := url.Values{}
	var body any
	body = nil
	body = request.Body
	var response PutNvmeofSubsystemByNqnNamespaceByNsidSetRbdTrashImageResponse
	err := c.doJSON(ctx, http.MethodPut, "/api/nvmeof/subsystem/{nqn}/namespace/{nsid}/set_rbd_trash_image", path, query, body, true, &response)
	return response, err
}
