// Code generated by tools/generate_ceph_dashboard_client.rb; DO NOT EDIT.

package typed

import (
	"context"
	"encoding/json"
	"net/http"
	"net/url"
	"strconv"
)

// rgw typed endpoints from docs/references/ceph/src/pybind/mgr/dashboard/openapi.yaml.

type GetRgwAccountsResponse map[string]json.RawMessage

type GetRgwAccountsRequest struct {
	DaemonName *string `query:"daemon_name"`
	Detailed   *bool   `query:"detailed"`
}

type PostRgwAccountsBody struct {
	AccountName   string `json:"account_name"`
	DaemonName    string `json:"daemon_name,omitempty"`
	Email         string `json:"email,omitempty"`
	MaxAccessKeys int    `json:"max_access_keys,omitempty"`
	MaxBuckets    int    `json:"max_buckets,omitempty"`
	MaxGroup      int    `json:"max_group,omitempty"`
	MaxRoles      int    `json:"max_roles,omitempty"`
	MaxUsers      int    `json:"max_users,omitempty"`
	Tenant        string `json:"tenant,omitempty"`
}

type PostRgwAccountsResponse map[string]json.RawMessage

type PostRgwAccountsRequest struct {
	Body PostRgwAccountsBody `json:"-"`
}

type DeleteRgwAccountsByAccountIdResponse map[string]json.RawMessage

type DeleteRgwAccountsByAccountIdRequest struct {
	AccountId  string  `path:"account_id"`
	DaemonName *string `query:"daemon_name"`
}

type GetRgwAccountsByAccountIdResponse map[string]json.RawMessage

type GetRgwAccountsByAccountIdRequest struct {
	AccountId  string  `path:"account_id"`
	DaemonName *string `query:"daemon_name"`
}

type PutRgwAccountsByAccountIdBody struct {
	AccountName   string `json:"account_name"`
	DaemonName    string `json:"daemon_name,omitempty"`
	Email         string `json:"email,omitempty"`
	MaxAccessKeys int    `json:"max_access_keys,omitempty"`
	MaxBuckets    int    `json:"max_buckets,omitempty"`
	MaxGroup      int    `json:"max_group,omitempty"`
	MaxRoles      int    `json:"max_roles,omitempty"`
	MaxUsers      int    `json:"max_users,omitempty"`
	Tenant        string `json:"tenant,omitempty"`
}

type PutRgwAccountsByAccountIdResponse map[string]json.RawMessage

type PutRgwAccountsByAccountIdRequest struct {
	AccountId string                        `path:"account_id"`
	Body      PutRgwAccountsByAccountIdBody `json:"-"`
}

type PutRgwAccountsByAccountIdQuotaBody struct {
	Enabled    string `json:"enabled"`
	MaxObjects string `json:"max_objects"`
	MaxSize    string `json:"max_size"`
	QuotaType  string `json:"quota_type"`
}

type PutRgwAccountsByAccountIdQuotaResponse map[string]json.RawMessage

type PutRgwAccountsByAccountIdQuotaRequest struct {
	AccountId string                             `path:"account_id"`
	Body      PutRgwAccountsByAccountIdQuotaBody `json:"-"`
}

type PutRgwAccountsByAccountIdQuotaStatusBody struct {
	QuotaStatus string `json:"quota_status"`
	QuotaType   string `json:"quota_type"`
}

type PutRgwAccountsByAccountIdQuotaStatusResponse map[string]json.RawMessage

type PutRgwAccountsByAccountIdQuotaStatusRequest struct {
	AccountId string                                   `path:"account_id"`
	Body      PutRgwAccountsByAccountIdQuotaStatusBody `json:"-"`
}

type GetRgwBucketResponse map[string]json.RawMessage

type GetRgwBucketRequest struct {
	Stats      *bool   `query:"stats"`
	DaemonName *string `query:"daemon_name"`
	Uid        *string `query:"uid"`
}

type PostRgwBucketBody struct {
	Bucket                   string `json:"bucket"`
	BucketPolicy             string `json:"bucket_policy,omitempty"`
	CannedAcl                string `json:"canned_acl,omitempty"`
	DaemonName               string `json:"daemon_name,omitempty"`
	EncryptionState          string `json:"encryption_state,omitempty"`
	EncryptionType           string `json:"encryption_type,omitempty"`
	KeyId                    string `json:"key_id,omitempty"`
	LockEnabled              string `json:"lock_enabled,omitempty"`
	LockMode                 string `json:"lock_mode,omitempty"`
	LockRetentionPeriodDays  string `json:"lock_retention_period_days,omitempty"`
	LockRetentionPeriodYears string `json:"lock_retention_period_years,omitempty"`
	PlacementTarget          string `json:"placement_target,omitempty"`
	Replication              string `json:"replication,omitempty"`
	Tags                     string `json:"tags,omitempty"`
	Uid                      string `json:"uid"`
	Zonegroup                string `json:"zonegroup,omitempty"`
}

type PostRgwBucketResponse map[string]json.RawMessage

type PostRgwBucketRequest struct {
	Body PostRgwBucketBody `json:"-"`
}

type DeleteRgwBucketDeleteEncryptionResponse map[string]json.RawMessage

type DeleteRgwBucketDeleteEncryptionRequest struct {
	BucketName string  `query:"bucket_name"`
	DaemonName *string `query:"daemon_name"`
	Owner      *string `query:"owner"`
}

type GetRgwBucketGetEncryptionResponse map[string]json.RawMessage

type GetRgwBucketGetEncryptionRequest struct {
	BucketName string  `query:"bucket_name"`
	DaemonName *string `query:"daemon_name"`
	Owner      *string `query:"owner"`
}

type GetRgwBucketGetEncryptionConfigResponse map[string]json.RawMessage

type GetRgwBucketGetEncryptionConfigRequest struct {
	DaemonName *string `query:"daemon_name"`
	Owner      *string `query:"owner"`
}

type GetRgwBucketLifecycleResponse map[string]json.RawMessage

type GetRgwBucketLifecycleRequest struct {
	BucketName *string `query:"bucket_name"`
	DaemonName *string `query:"daemon_name"`
	Owner      *string `query:"owner"`
	Tenant     *string `query:"tenant"`
}

type PutRgwBucketLifecycleBody struct {
	BucketName string `json:"bucket_name,omitempty"`
	DaemonName string `json:"daemon_name,omitempty"`
	Lifecycle  string `json:"lifecycle,omitempty"`
	Owner      string `json:"owner,omitempty"`
	Tenant     string `json:"tenant,omitempty"`
}

type PutRgwBucketLifecycleResponse map[string]json.RawMessage

type PutRgwBucketLifecycleRequest struct {
	Body PutRgwBucketLifecycleBody `json:"-"`
}

type DeleteRgwBucketNotificationResponse map[string]json.RawMessage

type DeleteRgwBucketNotificationRequest struct {
	BucketName     string  `query:"bucket_name"`
	NotificationId string  `query:"notification_id"`
	DaemonName     *string `query:"daemon_name"`
	Owner          *string `query:"owner"`
}

type GetRgwBucketNotificationResponse map[string]json.RawMessage

type GetRgwBucketNotificationRequest struct {
	BucketName string  `query:"bucket_name"`
	DaemonName *string `query:"daemon_name"`
	Owner      *string `query:"owner"`
}

type PutRgwBucketNotificationBody struct {
	BucketName   string `json:"bucket_name"`
	DaemonName   string `json:"daemon_name,omitempty"`
	Notification string `json:"notification,omitempty"`
	Owner        string `json:"owner,omitempty"`
}

type PutRgwBucketNotificationResponse map[string]json.RawMessage

type PutRgwBucketNotificationRequest struct {
	Body PutRgwBucketNotificationBody `json:"-"`
}

type GetRgwBucketRatelimitResponse map[string]json.RawMessage

type GetRgwBucketRatelimitRequest struct{}

type PutRgwBucketSetEncryptionConfigBody struct {
	Config         string `json:"config,omitempty"`
	DaemonName     string `json:"daemon_name,omitempty"`
	EncryptionType string `json:"encryption_type,omitempty"`
	KmsProvider    string `json:"kms_provider,omitempty"`
}

type PutRgwBucketSetEncryptionConfigResponse map[string]json.RawMessage

type PutRgwBucketSetEncryptionConfigRequest struct {
	Body PutRgwBucketSetEncryptionConfigBody `json:"-"`
}

type DeleteRgwBucketByBucketResponse map[string]json.RawMessage

type DeleteRgwBucketByBucketRequest struct {
	Bucket     string  `path:"bucket"`
	DaemonName *string `query:"daemon_name"`
}

type GetRgwBucketByBucketResponse map[string]json.RawMessage

type GetRgwBucketByBucketRequest struct {
	Bucket     string  `path:"bucket"`
	DaemonName *string `query:"daemon_name"`
}

type PutRgwBucketByBucketBody struct {
	BucketId                 string `json:"bucket_id"`
	BucketPolicy             string `json:"bucket_policy,omitempty"`
	CannedAcl                string `json:"canned_acl,omitempty"`
	DaemonName               string `json:"daemon_name,omitempty"`
	EncryptionState          string `json:"encryption_state,omitempty"`
	EncryptionType           string `json:"encryption_type,omitempty"`
	KeyId                    string `json:"key_id,omitempty"`
	Lifecycle                string `json:"lifecycle,omitempty"`
	LockMode                 string `json:"lock_mode,omitempty"`
	LockRetentionPeriodDays  string `json:"lock_retention_period_days,omitempty"`
	LockRetentionPeriodYears string `json:"lock_retention_period_years,omitempty"`
	MfaDelete                string `json:"mfa_delete,omitempty"`
	MfaTokenPin              string `json:"mfa_token_pin,omitempty"`
	MfaTokenSerial           string `json:"mfa_token_serial,omitempty"`
	Replication              string `json:"replication,omitempty"`
	Tags                     string `json:"tags,omitempty"`
	Uid                      string `json:"uid,omitempty"`
	VersioningState          string `json:"versioning_state,omitempty"`
}

type PutRgwBucketByBucketResponse map[string]json.RawMessage

type PutRgwBucketByBucketRequest struct {
	Bucket string                   `path:"bucket"`
	Body   PutRgwBucketByBucketBody `json:"-"`
}

type GetRgwBucketByUidRatelimitResponse map[string]json.RawMessage

type GetRgwBucketByUidRatelimitRequest struct {
	Uid string `path:"uid"`
}

type PutRgwBucketByUidRatelimitBody struct {
	Enabled       string `json:"enabled"`
	MaxReadBytes  string `json:"max_read_bytes"`
	MaxReadOps    string `json:"max_read_ops"`
	MaxWriteBytes string `json:"max_write_bytes"`
	MaxWriteOps   string `json:"max_write_ops"`
}

type PutRgwBucketByUidRatelimitResponse map[string]json.RawMessage

type PutRgwBucketByUidRatelimitRequest struct {
	Uid  string                         `path:"uid"`
	Body PutRgwBucketByUidRatelimitBody `json:"-"`
}

type GetRgwDaemonResponseItem struct {
	Id             string `json:"id,omitempty"`
	Port           int    `json:"port,omitempty"`
	ServerHostname string `json:"server_hostname,omitempty"`
	Version        string `json:"version,omitempty"`
	ZoneName       string `json:"zone_name,omitempty"`
	ZonegroupName  string `json:"zonegroup_name,omitempty"`
}

type GetRgwDaemonResponse []GetRgwDaemonResponseItem

type GetRgwDaemonRequest struct{}

type PutRgwDaemonSetMultisiteConfigBody struct {
	DaemonName    string `json:"daemon_name,omitempty"`
	RealmName     string `json:"realm_name,omitempty"`
	ZoneName      string `json:"zone_name,omitempty"`
	ZonegroupName string `json:"zonegroup_name,omitempty"`
}

type PutRgwDaemonSetMultisiteConfigResponse map[string]json.RawMessage

type PutRgwDaemonSetMultisiteConfigRequest struct {
	Body PutRgwDaemonSetMultisiteConfigBody `json:"-"`
}

type GetRgwDaemonBySvcIdResponse map[string]json.RawMessage

type GetRgwDaemonBySvcIdRequest struct {
	SvcId string `path:"svc_id"`
}

type PutRgwMultisiteSyncFlowBody struct {
	BucketName      string `json:"bucket_name,omitempty"`
	DestinationZone string `json:"destination_zone,omitempty"`
	FlowId          string `json:"flow_id"`
	FlowType        string `json:"flow_type"`
	GroupId         string `json:"group_id"`
	SourceZone      string `json:"source_zone,omitempty"`
	Zones           string `json:"zones,omitempty"`
}

type PutRgwMultisiteSyncFlowResponse map[string]json.RawMessage

type PutRgwMultisiteSyncFlowRequest struct {
	Body PutRgwMultisiteSyncFlowBody `json:"-"`
}

type DeleteRgwMultisiteSyncFlowByFlowIdByFlowTypeByGroupIdResponse map[string]json.RawMessage

type DeleteRgwMultisiteSyncFlowByFlowIdByFlowTypeByGroupIdRequest struct {
	FlowId          string  `path:"flow_id"`
	FlowType        string  `path:"flow_type"`
	GroupId         string  `path:"group_id"`
	SourceZone      *string `query:"source_zone"`
	DestinationZone *string `query:"destination_zone"`
	Zones           *string `query:"zones"`
	BucketName      *string `query:"bucket_name"`
}

type PutRgwMultisiteSyncPipeBody struct {
	BucketName        string `json:"bucket_name,omitempty"`
	DestinationBucket string `json:"destination_bucket,omitempty"`
	DestinationZones  string `json:"destination_zones"`
	GroupId           string `json:"group_id"`
	Mode              string `json:"mode,omitempty"`
	PipeId            string `json:"pipe_id"`
	SourceBucket      string `json:"source_bucket,omitempty"`
	SourceZones       string `json:"source_zones"`
	User              string `json:"user,omitempty"`
}

type PutRgwMultisiteSyncPipeResponse map[string]json.RawMessage

type PutRgwMultisiteSyncPipeRequest struct {
	Body PutRgwMultisiteSyncPipeBody `json:"-"`
}

type DeleteRgwMultisiteSyncPipeByGroupIdByPipeIdResponse map[string]json.RawMessage

type DeleteRgwMultisiteSyncPipeByGroupIdByPipeIdRequest struct {
	GroupId          string  `path:"group_id"`
	PipeId           string  `path:"pipe_id"`
	SourceZones      *string `query:"source_zones"`
	DestinationZones *string `query:"destination_zones"`
	BucketName       *string `query:"bucket_name"`
}

type GetRgwMultisiteSyncPolicyResponse map[string]json.RawMessage

type GetRgwMultisiteSyncPolicyRequest struct {
	BucketName    *string `query:"bucket_name"`
	ZonegroupName *string `query:"zonegroup_name"`
	AllPolicy     *string `query:"all_policy"`
}

type PostRgwMultisiteSyncPolicyGroupBody struct {
	BucketName string `json:"bucket_name,omitempty"`
	GroupId    string `json:"group_id"`
	Status     string `json:"status"`
}

type PostRgwMultisiteSyncPolicyGroupResponse map[string]json.RawMessage

type PostRgwMultisiteSyncPolicyGroupRequest struct {
	Body PostRgwMultisiteSyncPolicyGroupBody `json:"-"`
}

type PutRgwMultisiteSyncPolicyGroupBody struct {
	BucketName string `json:"bucket_name,omitempty"`
	GroupId    string `json:"group_id"`
	Status     string `json:"status"`
}

type PutRgwMultisiteSyncPolicyGroupResponse map[string]json.RawMessage

type PutRgwMultisiteSyncPolicyGroupRequest struct {
	Body PutRgwMultisiteSyncPolicyGroupBody `json:"-"`
}

type DeleteRgwMultisiteSyncPolicyGroupByGroupIdResponse map[string]json.RawMessage

type DeleteRgwMultisiteSyncPolicyGroupByGroupIdRequest struct {
	GroupId    string  `path:"group_id"`
	BucketName *string `query:"bucket_name"`
}

type GetRgwMultisiteSyncPolicyGroupByGroupIdResponse map[string]json.RawMessage

type GetRgwMultisiteSyncPolicyGroupByGroupIdRequest struct {
	GroupId    string  `path:"group_id"`
	BucketName *string `query:"bucket_name"`
}

type GetRgwMultisiteSyncStatusResponse map[string]json.RawMessage

type GetRgwMultisiteSyncStatusRequest struct {
	DaemonName *string `query:"daemon_name"`
}

type GetRgwRealmResponse map[string]json.RawMessage

type GetRgwRealmRequest struct {
	Replicable *string `query:"replicable"`
}

type PostRgwRealmBody struct {
	DefaultValue string `json:"default"`
	RealmName    string `json:"realm_name"`
}

type PostRgwRealmResponse map[string]json.RawMessage

type PostRgwRealmRequest struct {
	Body PostRgwRealmBody `json:"-"`
}

type GetRgwRealmGetAllRealmsInfoResponse map[string]json.RawMessage

type GetRgwRealmGetAllRealmsInfoRequest struct{}

type GetRgwRealmGetRealmTokensResponse map[string]json.RawMessage

type GetRgwRealmGetRealmTokensRequest struct{}

type PostRgwRealmImportRealmTokenBody struct {
	PlacementSpec string `json:"placement_spec,omitempty"`
	Port          string `json:"port"`
	RealmToken    string `json:"realm_token"`
	TierType      string `json:"tier_type,omitempty"`
	ZoneName      string `json:"zone_name"`
}

type PostRgwRealmImportRealmTokenResponse map[string]json.RawMessage

type PostRgwRealmImportRealmTokenRequest struct {
	Body PostRgwRealmImportRealmTokenBody `json:"-"`
}

type DeleteRgwRealmByRealmNameResponse map[string]json.RawMessage

type DeleteRgwRealmByRealmNameRequest struct {
	RealmName string `path:"realm_name"`
}

type GetRgwRealmByRealmNameResponse map[string]json.RawMessage

type GetRgwRealmByRealmNameRequest struct {
	RealmName string `path:"realm_name"`
}

type PutRgwRealmByRealmNameBody struct {
	DefaultValue string `json:"default,omitempty"`
	NewRealmName string `json:"new_realm_name"`
}

type PutRgwRealmByRealmNameResponse map[string]json.RawMessage

type PutRgwRealmByRealmNameRequest struct {
	RealmName string                     `path:"realm_name"`
	Body      PutRgwRealmByRealmNameBody `json:"-"`
}

type GetRgwRolesResponse map[string]json.RawMessage

type GetRgwRolesRequest struct{}

type PostRgwRolesBody struct {
	RoleAssumePolicyDoc string `json:"role_assume_policy_doc,omitempty"`
	RoleName            string `json:"role_name,omitempty"`
	RolePath            string `json:"role_path,omitempty"`
}

type PostRgwRolesResponse map[string]json.RawMessage

type PostRgwRolesRequest struct {
	Body PostRgwRolesBody `json:"-"`
}

type PutRgwRolesBody struct {
	MaxSessionDuration string `json:"max_session_duration"`
	RoleName           string `json:"role_name"`
}

type PutRgwRolesResponse map[string]json.RawMessage

type PutRgwRolesRequest struct {
	Body PutRgwRolesBody `json:"-"`
}

type DeleteRgwRolesByRoleNameResponse map[string]json.RawMessage

type DeleteRgwRolesByRoleNameRequest struct {
	RoleName string `path:"role_name"`
}

type GetRgwSiteResponse map[string]json.RawMessage

type GetRgwSiteRequest struct {
	Query      *string `query:"query"`
	DaemonName *string `query:"daemon_name"`
}

type GetRgwTopicResponse map[string]json.RawMessage

type GetRgwTopicRequest struct{}

type PostRgwTopicBody struct {
	AckLevel           string `json:"ack_level,omitempty"`
	AmqpExchange       string `json:"amqp_exchange,omitempty"`
	CaLocation         string `json:"ca_location,omitempty"`
	CloudEvents        string `json:"cloud_events,omitempty"`
	DaemonName         string `json:"daemon_name,omitempty"`
	KafkaBrokers       string `json:"kafka_brokers,omitempty"`
	MaxRetries         string `json:"max_retries,omitempty"`
	Mechanism          string `json:"mechanism,omitempty"`
	Name               string `json:"name"`
	OpaqueData         string `json:"opaque_data,omitempty"`
	Owner              string `json:"owner,omitempty"`
	Persistent         bool   `json:"persistent,omitempty"`
	Policy             string `json:"policy,omitempty"`
	PushEndpoint       string `json:"push_endpoint,omitempty"`
	RetrySleepDuration string `json:"retry_sleep_duration,omitempty"`
	TimeToLive         string `json:"time_to_live,omitempty"`
	UseSsl             bool   `json:"use_ssl,omitempty"`
	VerifySsl          bool   `json:"verify_ssl,omitempty"`
}

type PostRgwTopicResponse map[string]json.RawMessage

type PostRgwTopicRequest struct {
	Body PostRgwTopicBody `json:"-"`
}

type DeleteRgwTopicByKeyResponse map[string]json.RawMessage

type DeleteRgwTopicByKeyRequest struct {
	Key string `path:"key"`
}

type GetRgwTopicByKeyResponse map[string]json.RawMessage

type GetRgwTopicByKeyRequest struct {
	Key string `path:"key"`
}

type GetRgwUserResponse struct {
	ListOfUsers []string `json:"list_of_users"`
}

type GetRgwUserRequest struct {
	DaemonName *string `query:"daemon_name"`
	Detailed   *bool   `query:"detailed"`
}

type PostRgwUserBody struct {
	AccessKey       string `json:"access_key,omitempty"`
	AccountId       int    `json:"account_id,omitempty"`
	AccountPolicies int    `json:"account_policies,omitempty"`
	AccountRootUser int    `json:"account_root_user,omitempty"`
	DaemonName      string `json:"daemon_name,omitempty"`
	DisplayName     string `json:"display_name"`
	Email           string `json:"email,omitempty"`
	GenerateKey     string `json:"generate_key,omitempty"`
	MaxBuckets      string `json:"max_buckets,omitempty"`
	SecretKey       string `json:"secret_key,omitempty"`
	Suspended       string `json:"suspended,omitempty"`
	System          string `json:"system,omitempty"`
	Uid             string `json:"uid"`
}

type PostRgwUserResponse map[string]json.RawMessage

type PostRgwUserRequest struct {
	Body PostRgwUserBody `json:"-"`
}

type GetRgwUserGetEmailsResponse map[string]json.RawMessage

type GetRgwUserGetEmailsRequest struct {
	DaemonName *string `query:"daemon_name"`
}

type GetRgwUserRatelimitResponse map[string]json.RawMessage

type GetRgwUserRatelimitRequest struct{}

type DeleteRgwUserByUidResponse map[string]json.RawMessage

type DeleteRgwUserByUidRequest struct {
	Uid        string  `path:"uid"`
	DaemonName *string `query:"daemon_name"`
}

type GetRgwUserByUidResponse map[string]json.RawMessage

type GetRgwUserByUidRequest struct {
	Uid        string  `path:"uid"`
	DaemonName *string `query:"daemon_name"`
	Stats      *bool   `query:"stats"`
}

type PutRgwUserByUidBody struct {
	AccountId       int    `json:"account_id,omitempty"`
	AccountPolicies int    `json:"account_policies,omitempty"`
	AccountRootUser int    `json:"account_root_user,omitempty"`
	DaemonName      string `json:"daemon_name,omitempty"`
	DisplayName     string `json:"display_name,omitempty"`
	Email           string `json:"email,omitempty"`
	MaxBuckets      string `json:"max_buckets,omitempty"`
	Suspended       string `json:"suspended,omitempty"`
	System          string `json:"system,omitempty"`
}

type PutRgwUserByUidResponse map[string]json.RawMessage

type PutRgwUserByUidRequest struct {
	Uid  string              `path:"uid"`
	Body PutRgwUserByUidBody `json:"-"`
}

type DeleteRgwUserByUidCapabilityResponse map[string]json.RawMessage

type DeleteRgwUserByUidCapabilityRequest struct {
	Uid        string  `path:"uid"`
	TypeValue  string  `query:"type"`
	Perm       string  `query:"perm"`
	DaemonName *string `query:"daemon_name"`
}

type PostRgwUserByUidCapabilityBody struct {
	DaemonName string `json:"daemon_name,omitempty"`
	Perm       string `json:"perm"`
	TypeValue  string `json:"type"`
}

type PostRgwUserByUidCapabilityResponse map[string]json.RawMessage

type PostRgwUserByUidCapabilityRequest struct {
	Uid  string                         `path:"uid"`
	Body PostRgwUserByUidCapabilityBody `json:"-"`
}

type DeleteRgwUserByUidKeyResponse map[string]json.RawMessage

type DeleteRgwUserByUidKeyRequest struct {
	Uid        string  `path:"uid"`
	KeyType    *string `query:"key_type"`
	Subuser    *string `query:"subuser"`
	AccessKey  *string `query:"access_key"`
	DaemonName *string `query:"daemon_name"`
}

type PostRgwUserByUidKeyBody struct {
	AccessKey   string `json:"access_key,omitempty"`
	DaemonName  string `json:"daemon_name,omitempty"`
	GenerateKey string `json:"generate_key,omitempty"`
	KeyType     string `json:"key_type,omitempty"`
	SecretKey   string `json:"secret_key,omitempty"`
	Subuser     string `json:"subuser,omitempty"`
}

type PostRgwUserByUidKeyResponse map[string]json.RawMessage

type PostRgwUserByUidKeyRequest struct {
	Uid  string                  `path:"uid"`
	Body PostRgwUserByUidKeyBody `json:"-"`
}

type GetRgwUserByUidQuotaResponse map[string]json.RawMessage

type GetRgwUserByUidQuotaRequest struct {
	Uid        string  `path:"uid"`
	DaemonName *string `query:"daemon_name"`
}

type PutRgwUserByUidQuotaBody struct {
	DaemonName string `json:"daemon_name,omitempty"`
	Enabled    string `json:"enabled"`
	MaxObjects string `json:"max_objects"`
	MaxSizeKb  int    `json:"max_size_kb"`
	QuotaType  string `json:"quota_type"`
}

type PutRgwUserByUidQuotaResponse map[string]json.RawMessage

type PutRgwUserByUidQuotaRequest struct {
	Uid  string                   `path:"uid"`
	Body PutRgwUserByUidQuotaBody `json:"-"`
}

type GetRgwUserByUidRatelimitResponse map[string]json.RawMessage

type GetRgwUserByUidRatelimitRequest struct {
	Uid string `path:"uid"`
}

type PutRgwUserByUidRatelimitBody struct {
	Enabled       bool `json:"enabled,omitempty"`
	MaxReadBytes  int  `json:"max_read_bytes,omitempty"`
	MaxReadOps    int  `json:"max_read_ops,omitempty"`
	MaxWriteBytes int  `json:"max_write_bytes,omitempty"`
	MaxWriteOps   int  `json:"max_write_ops,omitempty"`
}

type PutRgwUserByUidRatelimitResponse map[string]json.RawMessage

type PutRgwUserByUidRatelimitRequest struct {
	Uid  string                       `path:"uid"`
	Body PutRgwUserByUidRatelimitBody `json:"-"`
}

type PostRgwUserByUidSubuserBody struct {
	Access         string `json:"access"`
	AccessKey      string `json:"access_key,omitempty"`
	DaemonName     string `json:"daemon_name,omitempty"`
	GenerateSecret string `json:"generate_secret,omitempty"`
	KeyType        string `json:"key_type,omitempty"`
	SecretKey      string `json:"secret_key,omitempty"`
	Subuser        string `json:"subuser"`
}

type PostRgwUserByUidSubuserResponse map[string]json.RawMessage

type PostRgwUserByUidSubuserRequest struct {
	Uid  string                      `path:"uid"`
	Body PostRgwUserByUidSubuserBody `json:"-"`
}

type DeleteRgwUserByUidSubuserBySubuserResponse map[string]json.RawMessage

type DeleteRgwUserByUidSubuserBySubuserRequest struct {
	Uid        string  `path:"uid"`
	Subuser    string  `path:"subuser"`
	PurgeKeys  *string `query:"purge_keys"`
	DaemonName *string `query:"daemon_name"`
}

type GetRgwZoneResponse map[string]json.RawMessage

type GetRgwZoneRequest struct{}

type PostRgwZoneBody struct {
	AccessKey     string `json:"access_key,omitempty"`
	DefaultValue  bool   `json:"default,omitempty"`
	Master        bool   `json:"master,omitempty"`
	SecretKey     string `json:"secret_key,omitempty"`
	SyncFrom      string `json:"sync_from,omitempty"`
	SyncFromAll   string `json:"sync_from_all,omitempty"`
	TierType      string `json:"tier_type,omitempty"`
	ZoneEndpoints string `json:"zone_endpoints,omitempty"`
	ZoneName      string `json:"zone_name"`
	ZonegroupName string `json:"zonegroup_name,omitempty"`
}

type PostRgwZoneResponse map[string]json.RawMessage

type PostRgwZoneRequest struct {
	Body PostRgwZoneBody `json:"-"`
}

type PutRgwZoneCreateSystemUserBody struct {
	UserName string `json:"userName"`
	ZoneName string `json:"zoneName"`
}

type PutRgwZoneCreateSystemUserResponse map[string]json.RawMessage

type PutRgwZoneCreateSystemUserRequest struct {
	Body PutRgwZoneCreateSystemUserBody `json:"-"`
}

type GetRgwZoneGetAllZonesInfoResponse map[string]json.RawMessage

type GetRgwZoneGetAllZonesInfoRequest struct{}

type GetRgwZoneGetPoolNamesResponse map[string]json.RawMessage

type GetRgwZoneGetPoolNamesRequest struct{}

type GetRgwZoneGetUserListResponse map[string]json.RawMessage

type GetRgwZoneGetUserListRequest struct {
	ZoneName  *string `query:"zoneName"`
	RealmName *string `query:"realmName"`
}

type PostRgwZoneStorageClassBody struct {
	Compression     string `json:"compression,omitempty"`
	DataPool        string `json:"data_pool"`
	PlacementTarget string `json:"placement_target"`
	StorageClass    string `json:"storage_class"`
	ZoneName        string `json:"zone_name"`
}

type PostRgwZoneStorageClassResponse map[string]json.RawMessage

type PostRgwZoneStorageClassRequest struct {
	Body PostRgwZoneStorageClassBody `json:"-"`
}

type PutRgwZoneStorageClassBody struct {
	Compression     string `json:"compression,omitempty"`
	DataPool        string `json:"data_pool"`
	PlacementTarget string `json:"placement_target"`
	StorageClass    string `json:"storage_class"`
	ZoneName        string `json:"zone_name"`
}

type PutRgwZoneStorageClassResponse map[string]json.RawMessage

type PutRgwZoneStorageClassRequest struct {
	Body PutRgwZoneStorageClassBody `json:"-"`
}

type DeleteRgwZoneByZoneNameResponse map[string]json.RawMessage

type DeleteRgwZoneByZoneNameRequest struct {
	ZoneName      string  `path:"zone_name"`
	DeletePools   string  `query:"delete_pools"`
	Pools         *string `query:"pools"`
	ZonegroupName *string `query:"zonegroup_name"`
	RealmName     *string `query:"realm_name"`
}

type GetRgwZoneByZoneNameResponse map[string]json.RawMessage

type GetRgwZoneByZoneNameRequest struct {
	ZoneName string `path:"zone_name"`
}

type PutRgwZoneByZoneNameBody struct {
	AccessKey       string `json:"access_key,omitempty"`
	Compression     string `json:"compression,omitempty"`
	DataExtraPool   string `json:"data_extra_pool,omitempty"`
	DataPool        string `json:"data_pool,omitempty"`
	DataPoolClass   string `json:"data_pool_class,omitempty"`
	DefaultValue    string `json:"default,omitempty"`
	IndexPool       string `json:"index_pool,omitempty"`
	Master          string `json:"master,omitempty"`
	NewZoneName     string `json:"new_zone_name"`
	PlacementTarget string `json:"placement_target,omitempty"`
	SecretKey       string `json:"secret_key,omitempty"`
	StorageClass    string `json:"storage_class,omitempty"`
	SyncFrom        string `json:"sync_from,omitempty"`
	SyncFromAll     string `json:"sync_from_all,omitempty"`
	TierType        string `json:"tier_type,omitempty"`
	ZoneEndpoints   string `json:"zone_endpoints,omitempty"`
	ZonegroupName   string `json:"zonegroup_name"`
}

type PutRgwZoneByZoneNameResponse map[string]json.RawMessage

type PutRgwZoneByZoneNameRequest struct {
	ZoneName string                   `path:"zone_name"`
	Body     PutRgwZoneByZoneNameBody `json:"-"`
}

type GetRgwZonegroupResponse map[string]json.RawMessage

type GetRgwZonegroupRequest struct{}

type PostRgwZonegroupBody struct {
	DefaultValue       string `json:"default,omitempty"`
	Master             string `json:"master,omitempty"`
	RealmName          string `json:"realm_name"`
	ZonegroupEndpoints string `json:"zonegroup_endpoints,omitempty"`
	ZonegroupName      string `json:"zonegroup_name"`
}

type PostRgwZonegroupResponse map[string]json.RawMessage

type PostRgwZonegroupRequest struct {
	Body PostRgwZonegroupBody `json:"-"`
}

type GetRgwZonegroupGetAllZonegroupsInfoResponse map[string]json.RawMessage

type GetRgwZonegroupGetAllZonegroupsInfoRequest struct{}

type GetRgwZonegroupGetPlacementTargetByPlacementIdByPlacementIdResponse map[string]json.RawMessage

type GetRgwZonegroupGetPlacementTargetByPlacementIdByPlacementIdRequest struct {
	PlacementId string `path:"placement_id"`
}

type PostRgwZonegroupStorageClassBody struct {
	PlacementTargets string `json:"placement_targets,omitempty"`
	ZoneGroup        string `json:"zone_group"`
}

type PostRgwZonegroupStorageClassResponse map[string]json.RawMessage

type PostRgwZonegroupStorageClassRequest struct {
	Body PostRgwZonegroupStorageClassBody `json:"-"`
}

type PutRgwZonegroupStorageClassBody struct {
	PlacementTargets string `json:"placement_targets,omitempty"`
	ZoneGroup        string `json:"zone_group"`
}

type PutRgwZonegroupStorageClassResponse map[string]json.RawMessage

type PutRgwZonegroupStorageClassRequest struct {
	Body PutRgwZonegroupStorageClassBody `json:"-"`
}

type DeleteRgwZonegroupStorageClassByPlacementIdByStorageClassResponse map[string]json.RawMessage

type DeleteRgwZonegroupStorageClassByPlacementIdByStorageClassRequest struct {
	PlacementId  string  `path:"placement_id"`
	StorageClass string  `path:"storage_class"`
	ZoneName     *string `query:"zone_name"`
}

type DeleteRgwZonegroupByZonegroupNameResponse map[string]json.RawMessage

type DeleteRgwZonegroupByZonegroupNameRequest struct {
	ZonegroupName string  `path:"zonegroup_name"`
	DeletePools   string  `query:"delete_pools"`
	Pools         *string `query:"pools"`
	RealmName     *string `query:"realm_name"`
}

type GetRgwZonegroupByZonegroupNameResponse map[string]json.RawMessage

type GetRgwZonegroupByZonegroupNameRequest struct {
	ZonegroupName string `path:"zonegroup_name"`
}

type PutRgwZonegroupByZonegroupNameBody struct {
	AddZones           string `json:"add_zones,omitempty"`
	DefaultValue       string `json:"default,omitempty"`
	Master             string `json:"master,omitempty"`
	NewZonegroupName   string `json:"new_zonegroup_name"`
	PlacementTargets   string `json:"placement_targets,omitempty"`
	RealmName          string `json:"realm_name"`
	RemoveZones        string `json:"remove_zones,omitempty"`
	ZonegroupEndpoints string `json:"zonegroup_endpoints,omitempty"`
}

type PutRgwZonegroupByZonegroupNameResponse map[string]json.RawMessage

type PutRgwZonegroupByZonegroupNameRequest struct {
	ZonegroupName string                             `path:"zonegroup_name"`
	Body          PutRgwZonegroupByZonegroupNameBody `json:"-"`
}

// GetRgwAccounts calls GET /api/rgw/accounts with typed request and response values.
func (c *Client) GetRgwAccounts(ctx context.Context, request GetRgwAccountsRequest) (GetRgwAccountsResponse, error) {
	path := map[string]string{}
	query := url.Values{}
	if request.DaemonName != nil {
		query.Set("daemon_name", *request.DaemonName)
	}
	if request.Detailed != nil {
		query.Set("detailed", strconv.FormatBool(*request.Detailed))
	}
	var body any
	body = nil
	var response GetRgwAccountsResponse
	err := c.doJSON(ctx, http.MethodGet, "/api/rgw/accounts", path, query, body, true, &response)
	return response, err
}

// PostRgwAccounts calls POST /api/rgw/accounts with typed request and response values.
func (c *Client) PostRgwAccounts(ctx context.Context, request PostRgwAccountsRequest) (PostRgwAccountsResponse, error) {
	path := map[string]string{}
	query := url.Values{}
	var body any
	body = nil
	body = request.Body
	var response PostRgwAccountsResponse
	err := c.doJSON(ctx, http.MethodPost, "/api/rgw/accounts", path, query, body, true, &response)
	return response, err
}

// DeleteRgwAccountsByAccountId calls DELETE /api/rgw/accounts/{account_id} with typed request and response values.
func (c *Client) DeleteRgwAccountsByAccountId(ctx context.Context, request DeleteRgwAccountsByAccountIdRequest) (DeleteRgwAccountsByAccountIdResponse, error) {
	path := map[string]string{
		"account_id": request.AccountId,
	}
	query := url.Values{}
	if request.DaemonName != nil {
		query.Set("daemon_name", *request.DaemonName)
	}
	var body any
	body = nil
	var response DeleteRgwAccountsByAccountIdResponse
	err := c.doJSON(ctx, http.MethodDelete, "/api/rgw/accounts/{account_id}", path, query, body, true, &response)
	return response, err
}

// GetRgwAccountsByAccountId calls GET /api/rgw/accounts/{account_id} with typed request and response values.
func (c *Client) GetRgwAccountsByAccountId(ctx context.Context, request GetRgwAccountsByAccountIdRequest) (GetRgwAccountsByAccountIdResponse, error) {
	path := map[string]string{
		"account_id": request.AccountId,
	}
	query := url.Values{}
	if request.DaemonName != nil {
		query.Set("daemon_name", *request.DaemonName)
	}
	var body any
	body = nil
	var response GetRgwAccountsByAccountIdResponse
	err := c.doJSON(ctx, http.MethodGet, "/api/rgw/accounts/{account_id}", path, query, body, true, &response)
	return response, err
}

// PutRgwAccountsByAccountId calls PUT /api/rgw/accounts/{account_id} with typed request and response values.
func (c *Client) PutRgwAccountsByAccountId(ctx context.Context, request PutRgwAccountsByAccountIdRequest) (PutRgwAccountsByAccountIdResponse, error) {
	path := map[string]string{
		"account_id": request.AccountId,
	}
	query := url.Values{}
	var body any
	body = nil
	body = request.Body
	var response PutRgwAccountsByAccountIdResponse
	err := c.doJSON(ctx, http.MethodPut, "/api/rgw/accounts/{account_id}", path, query, body, true, &response)
	return response, err
}

// PutRgwAccountsByAccountIdQuota calls PUT /api/rgw/accounts/{account_id}/quota with typed request and response values.
func (c *Client) PutRgwAccountsByAccountIdQuota(ctx context.Context, request PutRgwAccountsByAccountIdQuotaRequest) (PutRgwAccountsByAccountIdQuotaResponse, error) {
	path := map[string]string{
		"account_id": request.AccountId,
	}
	query := url.Values{}
	var body any
	body = nil
	body = request.Body
	var response PutRgwAccountsByAccountIdQuotaResponse
	err := c.doJSON(ctx, http.MethodPut, "/api/rgw/accounts/{account_id}/quota", path, query, body, true, &response)
	return response, err
}

// PutRgwAccountsByAccountIdQuotaStatus calls PUT /api/rgw/accounts/{account_id}/quota/status with typed request and response values.
func (c *Client) PutRgwAccountsByAccountIdQuotaStatus(ctx context.Context, request PutRgwAccountsByAccountIdQuotaStatusRequest) (PutRgwAccountsByAccountIdQuotaStatusResponse, error) {
	path := map[string]string{
		"account_id": request.AccountId,
	}
	query := url.Values{}
	var body any
	body = nil
	body = request.Body
	var response PutRgwAccountsByAccountIdQuotaStatusResponse
	err := c.doJSON(ctx, http.MethodPut, "/api/rgw/accounts/{account_id}/quota/status", path, query, body, true, &response)
	return response, err
}

// GetRgwBucket calls GET /api/rgw/bucket with typed request and response values.
func (c *Client) GetRgwBucket(ctx context.Context, request GetRgwBucketRequest) (GetRgwBucketResponse, error) {
	path := map[string]string{}
	query := url.Values{}
	if request.Stats != nil {
		query.Set("stats", strconv.FormatBool(*request.Stats))
	}
	if request.DaemonName != nil {
		query.Set("daemon_name", *request.DaemonName)
	}
	if request.Uid != nil {
		query.Set("uid", *request.Uid)
	}
	var body any
	body = nil
	var response GetRgwBucketResponse
	err := c.doJSON(ctx, http.MethodGet, "/api/rgw/bucket", path, query, body, true, &response)
	return response, err
}

// PostRgwBucket calls POST /api/rgw/bucket with typed request and response values.
func (c *Client) PostRgwBucket(ctx context.Context, request PostRgwBucketRequest) (PostRgwBucketResponse, error) {
	path := map[string]string{}
	query := url.Values{}
	var body any
	body = nil
	body = request.Body
	var response PostRgwBucketResponse
	err := c.doJSON(ctx, http.MethodPost, "/api/rgw/bucket", path, query, body, true, &response)
	return response, err
}

// DeleteRgwBucketDeleteEncryption calls DELETE /api/rgw/bucket/deleteEncryption with typed request and response values.
func (c *Client) DeleteRgwBucketDeleteEncryption(ctx context.Context, request DeleteRgwBucketDeleteEncryptionRequest) (DeleteRgwBucketDeleteEncryptionResponse, error) {
	path := map[string]string{}
	query := url.Values{}
	query.Set("bucket_name", request.BucketName)
	if request.DaemonName != nil {
		query.Set("daemon_name", *request.DaemonName)
	}
	if request.Owner != nil {
		query.Set("owner", *request.Owner)
	}
	var body any
	body = nil
	var response DeleteRgwBucketDeleteEncryptionResponse
	err := c.doJSON(ctx, http.MethodDelete, "/api/rgw/bucket/deleteEncryption", path, query, body, true, &response)
	return response, err
}

// GetRgwBucketGetEncryption calls GET /api/rgw/bucket/getEncryption with typed request and response values.
func (c *Client) GetRgwBucketGetEncryption(ctx context.Context, request GetRgwBucketGetEncryptionRequest) (GetRgwBucketGetEncryptionResponse, error) {
	path := map[string]string{}
	query := url.Values{}
	query.Set("bucket_name", request.BucketName)
	if request.DaemonName != nil {
		query.Set("daemon_name", *request.DaemonName)
	}
	if request.Owner != nil {
		query.Set("owner", *request.Owner)
	}
	var body any
	body = nil
	var response GetRgwBucketGetEncryptionResponse
	err := c.doJSON(ctx, http.MethodGet, "/api/rgw/bucket/getEncryption", path, query, body, true, &response)
	return response, err
}

// GetRgwBucketGetEncryptionConfig calls GET /api/rgw/bucket/getEncryptionConfig with typed request and response values.
func (c *Client) GetRgwBucketGetEncryptionConfig(ctx context.Context, request GetRgwBucketGetEncryptionConfigRequest) (GetRgwBucketGetEncryptionConfigResponse, error) {
	path := map[string]string{}
	query := url.Values{}
	if request.DaemonName != nil {
		query.Set("daemon_name", *request.DaemonName)
	}
	if request.Owner != nil {
		query.Set("owner", *request.Owner)
	}
	var body any
	body = nil
	var response GetRgwBucketGetEncryptionConfigResponse
	err := c.doJSON(ctx, http.MethodGet, "/api/rgw/bucket/getEncryptionConfig", path, query, body, true, &response)
	return response, err
}

// GetRgwBucketLifecycle calls GET /api/rgw/bucket/lifecycle with typed request and response values.
func (c *Client) GetRgwBucketLifecycle(ctx context.Context, request GetRgwBucketLifecycleRequest) (GetRgwBucketLifecycleResponse, error) {
	path := map[string]string{}
	query := url.Values{}
	if request.BucketName != nil {
		query.Set("bucket_name", *request.BucketName)
	}
	if request.DaemonName != nil {
		query.Set("daemon_name", *request.DaemonName)
	}
	if request.Owner != nil {
		query.Set("owner", *request.Owner)
	}
	if request.Tenant != nil {
		query.Set("tenant", *request.Tenant)
	}
	var body any
	body = nil
	var response GetRgwBucketLifecycleResponse
	err := c.doJSON(ctx, http.MethodGet, "/api/rgw/bucket/lifecycle", path, query, body, true, &response)
	return response, err
}

// PutRgwBucketLifecycle calls PUT /api/rgw/bucket/lifecycle with typed request and response values.
func (c *Client) PutRgwBucketLifecycle(ctx context.Context, request PutRgwBucketLifecycleRequest) (PutRgwBucketLifecycleResponse, error) {
	path := map[string]string{}
	query := url.Values{}
	var body any
	body = nil
	body = request.Body
	var response PutRgwBucketLifecycleResponse
	err := c.doJSON(ctx, http.MethodPut, "/api/rgw/bucket/lifecycle", path, query, body, true, &response)
	return response, err
}

// DeleteRgwBucketNotification calls DELETE /api/rgw/bucket/notification with typed request and response values.
func (c *Client) DeleteRgwBucketNotification(ctx context.Context, request DeleteRgwBucketNotificationRequest) (DeleteRgwBucketNotificationResponse, error) {
	path := map[string]string{}
	query := url.Values{}
	query.Set("bucket_name", request.BucketName)
	query.Set("notification_id", request.NotificationId)
	if request.DaemonName != nil {
		query.Set("daemon_name", *request.DaemonName)
	}
	if request.Owner != nil {
		query.Set("owner", *request.Owner)
	}
	var body any
	body = nil
	var response DeleteRgwBucketNotificationResponse
	err := c.doJSON(ctx, http.MethodDelete, "/api/rgw/bucket/notification", path, query, body, true, &response)
	return response, err
}

// GetRgwBucketNotification calls GET /api/rgw/bucket/notification with typed request and response values.
func (c *Client) GetRgwBucketNotification(ctx context.Context, request GetRgwBucketNotificationRequest) (GetRgwBucketNotificationResponse, error) {
	path := map[string]string{}
	query := url.Values{}
	query.Set("bucket_name", request.BucketName)
	if request.DaemonName != nil {
		query.Set("daemon_name", *request.DaemonName)
	}
	if request.Owner != nil {
		query.Set("owner", *request.Owner)
	}
	var body any
	body = nil
	var response GetRgwBucketNotificationResponse
	err := c.doJSON(ctx, http.MethodGet, "/api/rgw/bucket/notification", path, query, body, true, &response)
	return response, err
}

// PutRgwBucketNotification calls PUT /api/rgw/bucket/notification with typed request and response values.
func (c *Client) PutRgwBucketNotification(ctx context.Context, request PutRgwBucketNotificationRequest) (PutRgwBucketNotificationResponse, error) {
	path := map[string]string{}
	query := url.Values{}
	var body any
	body = nil
	body = request.Body
	var response PutRgwBucketNotificationResponse
	err := c.doJSON(ctx, http.MethodPut, "/api/rgw/bucket/notification", path, query, body, true, &response)
	return response, err
}

// GetRgwBucketRatelimit calls GET /api/rgw/bucket/ratelimit with typed request and response values.
func (c *Client) GetRgwBucketRatelimit(ctx context.Context, request GetRgwBucketRatelimitRequest) (GetRgwBucketRatelimitResponse, error) {
	path := map[string]string{}
	query := url.Values{}
	var body any
	body = nil
	var response GetRgwBucketRatelimitResponse
	err := c.doJSON(ctx, http.MethodGet, "/api/rgw/bucket/ratelimit", path, query, body, true, &response)
	return response, err
}

// PutRgwBucketSetEncryptionConfig calls PUT /api/rgw/bucket/setEncryptionConfig with typed request and response values.
func (c *Client) PutRgwBucketSetEncryptionConfig(ctx context.Context, request PutRgwBucketSetEncryptionConfigRequest) (PutRgwBucketSetEncryptionConfigResponse, error) {
	path := map[string]string{}
	query := url.Values{}
	var body any
	body = nil
	body = request.Body
	var response PutRgwBucketSetEncryptionConfigResponse
	err := c.doJSON(ctx, http.MethodPut, "/api/rgw/bucket/setEncryptionConfig", path, query, body, true, &response)
	return response, err
}

// DeleteRgwBucketByBucket calls DELETE /api/rgw/bucket/{bucket} with typed request and response values.
func (c *Client) DeleteRgwBucketByBucket(ctx context.Context, request DeleteRgwBucketByBucketRequest) (DeleteRgwBucketByBucketResponse, error) {
	path := map[string]string{
		"bucket": request.Bucket,
	}
	query := url.Values{}
	if request.DaemonName != nil {
		query.Set("daemon_name", *request.DaemonName)
	}
	var body any
	body = nil
	var response DeleteRgwBucketByBucketResponse
	err := c.doJSON(ctx, http.MethodDelete, "/api/rgw/bucket/{bucket}", path, query, body, true, &response)
	return response, err
}

// GetRgwBucketByBucket calls GET /api/rgw/bucket/{bucket} with typed request and response values.
func (c *Client) GetRgwBucketByBucket(ctx context.Context, request GetRgwBucketByBucketRequest) (GetRgwBucketByBucketResponse, error) {
	path := map[string]string{
		"bucket": request.Bucket,
	}
	query := url.Values{}
	if request.DaemonName != nil {
		query.Set("daemon_name", *request.DaemonName)
	}
	var body any
	body = nil
	var response GetRgwBucketByBucketResponse
	err := c.doJSON(ctx, http.MethodGet, "/api/rgw/bucket/{bucket}", path, query, body, true, &response)
	return response, err
}

// PutRgwBucketByBucket calls PUT /api/rgw/bucket/{bucket} with typed request and response values.
func (c *Client) PutRgwBucketByBucket(ctx context.Context, request PutRgwBucketByBucketRequest) (PutRgwBucketByBucketResponse, error) {
	path := map[string]string{
		"bucket": request.Bucket,
	}
	query := url.Values{}
	var body any
	body = nil
	body = request.Body
	var response PutRgwBucketByBucketResponse
	err := c.doJSON(ctx, http.MethodPut, "/api/rgw/bucket/{bucket}", path, query, body, true, &response)
	return response, err
}

// GetRgwBucketByUidRatelimit calls GET /api/rgw/bucket/{uid}/ratelimit with typed request and response values.
func (c *Client) GetRgwBucketByUidRatelimit(ctx context.Context, request GetRgwBucketByUidRatelimitRequest) (GetRgwBucketByUidRatelimitResponse, error) {
	path := map[string]string{
		"uid": request.Uid,
	}
	query := url.Values{}
	var body any
	body = nil
	var response GetRgwBucketByUidRatelimitResponse
	err := c.doJSON(ctx, http.MethodGet, "/api/rgw/bucket/{uid}/ratelimit", path, query, body, true, &response)
	return response, err
}

// PutRgwBucketByUidRatelimit calls PUT /api/rgw/bucket/{uid}/ratelimit with typed request and response values.
func (c *Client) PutRgwBucketByUidRatelimit(ctx context.Context, request PutRgwBucketByUidRatelimitRequest) (PutRgwBucketByUidRatelimitResponse, error) {
	path := map[string]string{
		"uid": request.Uid,
	}
	query := url.Values{}
	var body any
	body = nil
	body = request.Body
	var response PutRgwBucketByUidRatelimitResponse
	err := c.doJSON(ctx, http.MethodPut, "/api/rgw/bucket/{uid}/ratelimit", path, query, body, true, &response)
	return response, err
}

// GetRgwDaemon calls GET /api/rgw/daemon with typed request and response values.
func (c *Client) GetRgwDaemon(ctx context.Context, request GetRgwDaemonRequest) (GetRgwDaemonResponse, error) {
	path := map[string]string{}
	query := url.Values{}
	var body any
	body = nil
	var response GetRgwDaemonResponse
	err := c.doJSON(ctx, http.MethodGet, "/api/rgw/daemon", path, query, body, true, &response)
	return response, err
}

// PutRgwDaemonSetMultisiteConfig calls PUT /api/rgw/daemon/set_multisite_config with typed request and response values.
func (c *Client) PutRgwDaemonSetMultisiteConfig(ctx context.Context, request PutRgwDaemonSetMultisiteConfigRequest) (PutRgwDaemonSetMultisiteConfigResponse, error) {
	path := map[string]string{}
	query := url.Values{}
	var body any
	body = nil
	body = request.Body
	var response PutRgwDaemonSetMultisiteConfigResponse
	err := c.doJSON(ctx, http.MethodPut, "/api/rgw/daemon/set_multisite_config", path, query, body, true, &response)
	return response, err
}

// GetRgwDaemonBySvcId calls GET /api/rgw/daemon/{svc_id} with typed request and response values.
func (c *Client) GetRgwDaemonBySvcId(ctx context.Context, request GetRgwDaemonBySvcIdRequest) (GetRgwDaemonBySvcIdResponse, error) {
	path := map[string]string{
		"svc_id": request.SvcId,
	}
	query := url.Values{}
	var body any
	body = nil
	var response GetRgwDaemonBySvcIdResponse
	err := c.doJSON(ctx, http.MethodGet, "/api/rgw/daemon/{svc_id}", path, query, body, true, &response)
	return response, err
}

// PutRgwMultisiteSyncFlow calls PUT /api/rgw/multisite/sync-flow with typed request and response values.
func (c *Client) PutRgwMultisiteSyncFlow(ctx context.Context, request PutRgwMultisiteSyncFlowRequest) (PutRgwMultisiteSyncFlowResponse, error) {
	path := map[string]string{}
	query := url.Values{}
	var body any
	body = nil
	body = request.Body
	var response PutRgwMultisiteSyncFlowResponse
	err := c.doJSON(ctx, http.MethodPut, "/api/rgw/multisite/sync-flow", path, query, body, true, &response)
	return response, err
}

// DeleteRgwMultisiteSyncFlowByFlowIdByFlowTypeByGroupId calls DELETE /api/rgw/multisite/sync-flow/{flow_id}/{flow_type}/{group_id} with typed request and response values.
func (c *Client) DeleteRgwMultisiteSyncFlowByFlowIdByFlowTypeByGroupId(ctx context.Context, request DeleteRgwMultisiteSyncFlowByFlowIdByFlowTypeByGroupIdRequest) (DeleteRgwMultisiteSyncFlowByFlowIdByFlowTypeByGroupIdResponse, error) {
	path := map[string]string{
		"flow_id":   request.FlowId,
		"flow_type": request.FlowType,
		"group_id":  request.GroupId,
	}
	query := url.Values{}
	if request.SourceZone != nil {
		query.Set("source_zone", *request.SourceZone)
	}
	if request.DestinationZone != nil {
		query.Set("destination_zone", *request.DestinationZone)
	}
	if request.Zones != nil {
		query.Set("zones", *request.Zones)
	}
	if request.BucketName != nil {
		query.Set("bucket_name", *request.BucketName)
	}
	var body any
	body = nil
	var response DeleteRgwMultisiteSyncFlowByFlowIdByFlowTypeByGroupIdResponse
	err := c.doJSON(ctx, http.MethodDelete, "/api/rgw/multisite/sync-flow/{flow_id}/{flow_type}/{group_id}", path, query, body, true, &response)
	return response, err
}

// PutRgwMultisiteSyncPipe calls PUT /api/rgw/multisite/sync-pipe with typed request and response values.
func (c *Client) PutRgwMultisiteSyncPipe(ctx context.Context, request PutRgwMultisiteSyncPipeRequest) (PutRgwMultisiteSyncPipeResponse, error) {
	path := map[string]string{}
	query := url.Values{}
	var body any
	body = nil
	body = request.Body
	var response PutRgwMultisiteSyncPipeResponse
	err := c.doJSON(ctx, http.MethodPut, "/api/rgw/multisite/sync-pipe", path, query, body, true, &response)
	return response, err
}

// DeleteRgwMultisiteSyncPipeByGroupIdByPipeId calls DELETE /api/rgw/multisite/sync-pipe/{group_id}/{pipe_id} with typed request and response values.
func (c *Client) DeleteRgwMultisiteSyncPipeByGroupIdByPipeId(ctx context.Context, request DeleteRgwMultisiteSyncPipeByGroupIdByPipeIdRequest) (DeleteRgwMultisiteSyncPipeByGroupIdByPipeIdResponse, error) {
	path := map[string]string{
		"group_id": request.GroupId,
		"pipe_id":  request.PipeId,
	}
	query := url.Values{}
	if request.SourceZones != nil {
		query.Set("source_zones", *request.SourceZones)
	}
	if request.DestinationZones != nil {
		query.Set("destination_zones", *request.DestinationZones)
	}
	if request.BucketName != nil {
		query.Set("bucket_name", *request.BucketName)
	}
	var body any
	body = nil
	var response DeleteRgwMultisiteSyncPipeByGroupIdByPipeIdResponse
	err := c.doJSON(ctx, http.MethodDelete, "/api/rgw/multisite/sync-pipe/{group_id}/{pipe_id}", path, query, body, true, &response)
	return response, err
}

// GetRgwMultisiteSyncPolicy calls GET /api/rgw/multisite/sync-policy with typed request and response values.
func (c *Client) GetRgwMultisiteSyncPolicy(ctx context.Context, request GetRgwMultisiteSyncPolicyRequest) (GetRgwMultisiteSyncPolicyResponse, error) {
	path := map[string]string{}
	query := url.Values{}
	if request.BucketName != nil {
		query.Set("bucket_name", *request.BucketName)
	}
	if request.ZonegroupName != nil {
		query.Set("zonegroup_name", *request.ZonegroupName)
	}
	if request.AllPolicy != nil {
		query.Set("all_policy", *request.AllPolicy)
	}
	var body any
	body = nil
	var response GetRgwMultisiteSyncPolicyResponse
	err := c.doJSON(ctx, http.MethodGet, "/api/rgw/multisite/sync-policy", path, query, body, true, &response)
	return response, err
}

// PostRgwMultisiteSyncPolicyGroup calls POST /api/rgw/multisite/sync-policy-group with typed request and response values.
func (c *Client) PostRgwMultisiteSyncPolicyGroup(ctx context.Context, request PostRgwMultisiteSyncPolicyGroupRequest) (PostRgwMultisiteSyncPolicyGroupResponse, error) {
	path := map[string]string{}
	query := url.Values{}
	var body any
	body = nil
	body = request.Body
	var response PostRgwMultisiteSyncPolicyGroupResponse
	err := c.doJSON(ctx, http.MethodPost, "/api/rgw/multisite/sync-policy-group", path, query, body, true, &response)
	return response, err
}

// PutRgwMultisiteSyncPolicyGroup calls PUT /api/rgw/multisite/sync-policy-group with typed request and response values.
func (c *Client) PutRgwMultisiteSyncPolicyGroup(ctx context.Context, request PutRgwMultisiteSyncPolicyGroupRequest) (PutRgwMultisiteSyncPolicyGroupResponse, error) {
	path := map[string]string{}
	query := url.Values{}
	var body any
	body = nil
	body = request.Body
	var response PutRgwMultisiteSyncPolicyGroupResponse
	err := c.doJSON(ctx, http.MethodPut, "/api/rgw/multisite/sync-policy-group", path, query, body, true, &response)
	return response, err
}

// DeleteRgwMultisiteSyncPolicyGroupByGroupId calls DELETE /api/rgw/multisite/sync-policy-group/{group_id} with typed request and response values.
func (c *Client) DeleteRgwMultisiteSyncPolicyGroupByGroupId(ctx context.Context, request DeleteRgwMultisiteSyncPolicyGroupByGroupIdRequest) (DeleteRgwMultisiteSyncPolicyGroupByGroupIdResponse, error) {
	path := map[string]string{
		"group_id": request.GroupId,
	}
	query := url.Values{}
	if request.BucketName != nil {
		query.Set("bucket_name", *request.BucketName)
	}
	var body any
	body = nil
	var response DeleteRgwMultisiteSyncPolicyGroupByGroupIdResponse
	err := c.doJSON(ctx, http.MethodDelete, "/api/rgw/multisite/sync-policy-group/{group_id}", path, query, body, true, &response)
	return response, err
}

// GetRgwMultisiteSyncPolicyGroupByGroupId calls GET /api/rgw/multisite/sync-policy-group/{group_id} with typed request and response values.
func (c *Client) GetRgwMultisiteSyncPolicyGroupByGroupId(ctx context.Context, request GetRgwMultisiteSyncPolicyGroupByGroupIdRequest) (GetRgwMultisiteSyncPolicyGroupByGroupIdResponse, error) {
	path := map[string]string{
		"group_id": request.GroupId,
	}
	query := url.Values{}
	if request.BucketName != nil {
		query.Set("bucket_name", *request.BucketName)
	}
	var body any
	body = nil
	var response GetRgwMultisiteSyncPolicyGroupByGroupIdResponse
	err := c.doJSON(ctx, http.MethodGet, "/api/rgw/multisite/sync-policy-group/{group_id}", path, query, body, true, &response)
	return response, err
}

// GetRgwMultisiteSyncStatus calls GET /api/rgw/multisite/sync_status with typed request and response values.
func (c *Client) GetRgwMultisiteSyncStatus(ctx context.Context, request GetRgwMultisiteSyncStatusRequest) (GetRgwMultisiteSyncStatusResponse, error) {
	path := map[string]string{}
	query := url.Values{}
	if request.DaemonName != nil {
		query.Set("daemon_name", *request.DaemonName)
	}
	var body any
	body = nil
	var response GetRgwMultisiteSyncStatusResponse
	err := c.doJSON(ctx, http.MethodGet, "/api/rgw/multisite/sync_status", path, query, body, true, &response)
	return response, err
}

// GetRgwRealm calls GET /api/rgw/realm with typed request and response values.
func (c *Client) GetRgwRealm(ctx context.Context, request GetRgwRealmRequest) (GetRgwRealmResponse, error) {
	path := map[string]string{}
	query := url.Values{}
	if request.Replicable != nil {
		query.Set("replicable", *request.Replicable)
	}
	var body any
	body = nil
	var response GetRgwRealmResponse
	err := c.doJSON(ctx, http.MethodGet, "/api/rgw/realm", path, query, body, true, &response)
	return response, err
}

// PostRgwRealm calls POST /api/rgw/realm with typed request and response values.
func (c *Client) PostRgwRealm(ctx context.Context, request PostRgwRealmRequest) (PostRgwRealmResponse, error) {
	path := map[string]string{}
	query := url.Values{}
	var body any
	body = nil
	body = request.Body
	var response PostRgwRealmResponse
	err := c.doJSON(ctx, http.MethodPost, "/api/rgw/realm", path, query, body, true, &response)
	return response, err
}

// GetRgwRealmGetAllRealmsInfo calls GET /api/rgw/realm/get_all_realms_info with typed request and response values.
func (c *Client) GetRgwRealmGetAllRealmsInfo(ctx context.Context, request GetRgwRealmGetAllRealmsInfoRequest) (GetRgwRealmGetAllRealmsInfoResponse, error) {
	path := map[string]string{}
	query := url.Values{}
	var body any
	body = nil
	var response GetRgwRealmGetAllRealmsInfoResponse
	err := c.doJSON(ctx, http.MethodGet, "/api/rgw/realm/get_all_realms_info", path, query, body, true, &response)
	return response, err
}

// GetRgwRealmGetRealmTokens calls GET /api/rgw/realm/get_realm_tokens with typed request and response values.
func (c *Client) GetRgwRealmGetRealmTokens(ctx context.Context, request GetRgwRealmGetRealmTokensRequest) (GetRgwRealmGetRealmTokensResponse, error) {
	path := map[string]string{}
	query := url.Values{}
	var body any
	body = nil
	var response GetRgwRealmGetRealmTokensResponse
	err := c.doJSON(ctx, http.MethodGet, "/api/rgw/realm/get_realm_tokens", path, query, body, true, &response)
	return response, err
}

// PostRgwRealmImportRealmToken calls POST /api/rgw/realm/import_realm_token with typed request and response values.
func (c *Client) PostRgwRealmImportRealmToken(ctx context.Context, request PostRgwRealmImportRealmTokenRequest) (PostRgwRealmImportRealmTokenResponse, error) {
	path := map[string]string{}
	query := url.Values{}
	var body any
	body = nil
	body = request.Body
	var response PostRgwRealmImportRealmTokenResponse
	err := c.doJSON(ctx, http.MethodPost, "/api/rgw/realm/import_realm_token", path, query, body, true, &response)
	return response, err
}

// DeleteRgwRealmByRealmName calls DELETE /api/rgw/realm/{realm_name} with typed request and response values.
func (c *Client) DeleteRgwRealmByRealmName(ctx context.Context, request DeleteRgwRealmByRealmNameRequest) (DeleteRgwRealmByRealmNameResponse, error) {
	path := map[string]string{
		"realm_name": request.RealmName,
	}
	query := url.Values{}
	var body any
	body = nil
	var response DeleteRgwRealmByRealmNameResponse
	err := c.doJSON(ctx, http.MethodDelete, "/api/rgw/realm/{realm_name}", path, query, body, true, &response)
	return response, err
}

// GetRgwRealmByRealmName calls GET /api/rgw/realm/{realm_name} with typed request and response values.
func (c *Client) GetRgwRealmByRealmName(ctx context.Context, request GetRgwRealmByRealmNameRequest) (GetRgwRealmByRealmNameResponse, error) {
	path := map[string]string{
		"realm_name": request.RealmName,
	}
	query := url.Values{}
	var body any
	body = nil
	var response GetRgwRealmByRealmNameResponse
	err := c.doJSON(ctx, http.MethodGet, "/api/rgw/realm/{realm_name}", path, query, body, true, &response)
	return response, err
}

// PutRgwRealmByRealmName calls PUT /api/rgw/realm/{realm_name} with typed request and response values.
func (c *Client) PutRgwRealmByRealmName(ctx context.Context, request PutRgwRealmByRealmNameRequest) (PutRgwRealmByRealmNameResponse, error) {
	path := map[string]string{
		"realm_name": request.RealmName,
	}
	query := url.Values{}
	var body any
	body = nil
	body = request.Body
	var response PutRgwRealmByRealmNameResponse
	err := c.doJSON(ctx, http.MethodPut, "/api/rgw/realm/{realm_name}", path, query, body, true, &response)
	return response, err
}

// GetRgwRoles calls GET /api/rgw/roles with typed request and response values.
func (c *Client) GetRgwRoles(ctx context.Context, request GetRgwRolesRequest) (GetRgwRolesResponse, error) {
	path := map[string]string{}
	query := url.Values{}
	var body any
	body = nil
	var response GetRgwRolesResponse
	err := c.doJSON(ctx, http.MethodGet, "/api/rgw/roles", path, query, body, true, &response)
	return response, err
}

// PostRgwRoles calls POST /api/rgw/roles with typed request and response values.
func (c *Client) PostRgwRoles(ctx context.Context, request PostRgwRolesRequest) (PostRgwRolesResponse, error) {
	path := map[string]string{}
	query := url.Values{}
	var body any
	body = nil
	body = request.Body
	var response PostRgwRolesResponse
	err := c.doJSON(ctx, http.MethodPost, "/api/rgw/roles", path, query, body, true, &response)
	return response, err
}

// PutRgwRoles calls PUT /api/rgw/roles with typed request and response values.
func (c *Client) PutRgwRoles(ctx context.Context, request PutRgwRolesRequest) (PutRgwRolesResponse, error) {
	path := map[string]string{}
	query := url.Values{}
	var body any
	body = nil
	body = request.Body
	var response PutRgwRolesResponse
	err := c.doJSON(ctx, http.MethodPut, "/api/rgw/roles", path, query, body, true, &response)
	return response, err
}

// DeleteRgwRolesByRoleName calls DELETE /api/rgw/roles/{role_name} with typed request and response values.
func (c *Client) DeleteRgwRolesByRoleName(ctx context.Context, request DeleteRgwRolesByRoleNameRequest) (DeleteRgwRolesByRoleNameResponse, error) {
	path := map[string]string{
		"role_name": request.RoleName,
	}
	query := url.Values{}
	var body any
	body = nil
	var response DeleteRgwRolesByRoleNameResponse
	err := c.doJSON(ctx, http.MethodDelete, "/api/rgw/roles/{role_name}", path, query, body, true, &response)
	return response, err
}

// GetRgwSite calls GET /api/rgw/site with typed request and response values.
func (c *Client) GetRgwSite(ctx context.Context, request GetRgwSiteRequest) (GetRgwSiteResponse, error) {
	path := map[string]string{}
	query := url.Values{}
	if request.Query != nil {
		query.Set("query", *request.Query)
	}
	if request.DaemonName != nil {
		query.Set("daemon_name", *request.DaemonName)
	}
	var body any
	body = nil
	var response GetRgwSiteResponse
	err := c.doJSON(ctx, http.MethodGet, "/api/rgw/site", path, query, body, true, &response)
	return response, err
}

// GetRgwTopic calls GET /api/rgw/topic with typed request and response values.
func (c *Client) GetRgwTopic(ctx context.Context, request GetRgwTopicRequest) (GetRgwTopicResponse, error) {
	path := map[string]string{}
	query := url.Values{}
	var body any
	body = nil
	var response GetRgwTopicResponse
	err := c.doJSON(ctx, http.MethodGet, "/api/rgw/topic", path, query, body, true, &response)
	return response, err
}

// PostRgwTopic calls POST /api/rgw/topic with typed request and response values.
func (c *Client) PostRgwTopic(ctx context.Context, request PostRgwTopicRequest) (PostRgwTopicResponse, error) {
	path := map[string]string{}
	query := url.Values{}
	var body any
	body = nil
	body = request.Body
	var response PostRgwTopicResponse
	err := c.doJSON(ctx, http.MethodPost, "/api/rgw/topic", path, query, body, true, &response)
	return response, err
}

// DeleteRgwTopicByKey calls DELETE /api/rgw/topic/{key} with typed request and response values.
func (c *Client) DeleteRgwTopicByKey(ctx context.Context, request DeleteRgwTopicByKeyRequest) (DeleteRgwTopicByKeyResponse, error) {
	path := map[string]string{
		"key": request.Key,
	}
	query := url.Values{}
	var body any
	body = nil
	var response DeleteRgwTopicByKeyResponse
	err := c.doJSON(ctx, http.MethodDelete, "/api/rgw/topic/{key}", path, query, body, true, &response)
	return response, err
}

// GetRgwTopicByKey calls GET /api/rgw/topic/{key} with typed request and response values.
func (c *Client) GetRgwTopicByKey(ctx context.Context, request GetRgwTopicByKeyRequest) (GetRgwTopicByKeyResponse, error) {
	path := map[string]string{
		"key": request.Key,
	}
	query := url.Values{}
	var body any
	body = nil
	var response GetRgwTopicByKeyResponse
	err := c.doJSON(ctx, http.MethodGet, "/api/rgw/topic/{key}", path, query, body, true, &response)
	return response, err
}

// GetRgwUser calls GET /api/rgw/user with typed request and response values.
func (c *Client) GetRgwUser(ctx context.Context, request GetRgwUserRequest) (GetRgwUserResponse, error) {
	path := map[string]string{}
	query := url.Values{}
	if request.DaemonName != nil {
		query.Set("daemon_name", *request.DaemonName)
	}
	if request.Detailed != nil {
		query.Set("detailed", strconv.FormatBool(*request.Detailed))
	}
	var body any
	body = nil
	var response GetRgwUserResponse
	err := c.doJSON(ctx, http.MethodGet, "/api/rgw/user", path, query, body, true, &response)
	return response, err
}

// PostRgwUser calls POST /api/rgw/user with typed request and response values.
func (c *Client) PostRgwUser(ctx context.Context, request PostRgwUserRequest) (PostRgwUserResponse, error) {
	path := map[string]string{}
	query := url.Values{}
	var body any
	body = nil
	body = request.Body
	var response PostRgwUserResponse
	err := c.doJSON(ctx, http.MethodPost, "/api/rgw/user", path, query, body, true, &response)
	return response, err
}

// GetRgwUserGetEmails calls GET /api/rgw/user/get_emails with typed request and response values.
func (c *Client) GetRgwUserGetEmails(ctx context.Context, request GetRgwUserGetEmailsRequest) (GetRgwUserGetEmailsResponse, error) {
	path := map[string]string{}
	query := url.Values{}
	if request.DaemonName != nil {
		query.Set("daemon_name", *request.DaemonName)
	}
	var body any
	body = nil
	var response GetRgwUserGetEmailsResponse
	err := c.doJSON(ctx, http.MethodGet, "/api/rgw/user/get_emails", path, query, body, true, &response)
	return response, err
}

// GetRgwUserRatelimit calls GET /api/rgw/user/ratelimit with typed request and response values.
func (c *Client) GetRgwUserRatelimit(ctx context.Context, request GetRgwUserRatelimitRequest) (GetRgwUserRatelimitResponse, error) {
	path := map[string]string{}
	query := url.Values{}
	var body any
	body = nil
	var response GetRgwUserRatelimitResponse
	err := c.doJSON(ctx, http.MethodGet, "/api/rgw/user/ratelimit", path, query, body, true, &response)
	return response, err
}

// DeleteRgwUserByUid calls DELETE /api/rgw/user/{uid} with typed request and response values.
func (c *Client) DeleteRgwUserByUid(ctx context.Context, request DeleteRgwUserByUidRequest) (DeleteRgwUserByUidResponse, error) {
	path := map[string]string{
		"uid": request.Uid,
	}
	query := url.Values{}
	if request.DaemonName != nil {
		query.Set("daemon_name", *request.DaemonName)
	}
	var body any
	body = nil
	var response DeleteRgwUserByUidResponse
	err := c.doJSON(ctx, http.MethodDelete, "/api/rgw/user/{uid}", path, query, body, true, &response)
	return response, err
}

// GetRgwUserByUid calls GET /api/rgw/user/{uid} with typed request and response values.
func (c *Client) GetRgwUserByUid(ctx context.Context, request GetRgwUserByUidRequest) (GetRgwUserByUidResponse, error) {
	path := map[string]string{
		"uid": request.Uid,
	}
	query := url.Values{}
	if request.DaemonName != nil {
		query.Set("daemon_name", *request.DaemonName)
	}
	if request.Stats != nil {
		query.Set("stats", strconv.FormatBool(*request.Stats))
	}
	var body any
	body = nil
	var response GetRgwUserByUidResponse
	err := c.doJSON(ctx, http.MethodGet, "/api/rgw/user/{uid}", path, query, body, true, &response)
	return response, err
}

// PutRgwUserByUid calls PUT /api/rgw/user/{uid} with typed request and response values.
func (c *Client) PutRgwUserByUid(ctx context.Context, request PutRgwUserByUidRequest) (PutRgwUserByUidResponse, error) {
	path := map[string]string{
		"uid": request.Uid,
	}
	query := url.Values{}
	var body any
	body = nil
	body = request.Body
	var response PutRgwUserByUidResponse
	err := c.doJSON(ctx, http.MethodPut, "/api/rgw/user/{uid}", path, query, body, true, &response)
	return response, err
}

// DeleteRgwUserByUidCapability calls DELETE /api/rgw/user/{uid}/capability with typed request and response values.
func (c *Client) DeleteRgwUserByUidCapability(ctx context.Context, request DeleteRgwUserByUidCapabilityRequest) (DeleteRgwUserByUidCapabilityResponse, error) {
	path := map[string]string{
		"uid": request.Uid,
	}
	query := url.Values{}
	query.Set("type", request.TypeValue)
	query.Set("perm", request.Perm)
	if request.DaemonName != nil {
		query.Set("daemon_name", *request.DaemonName)
	}
	var body any
	body = nil
	var response DeleteRgwUserByUidCapabilityResponse
	err := c.doJSON(ctx, http.MethodDelete, "/api/rgw/user/{uid}/capability", path, query, body, true, &response)
	return response, err
}

// PostRgwUserByUidCapability calls POST /api/rgw/user/{uid}/capability with typed request and response values.
func (c *Client) PostRgwUserByUidCapability(ctx context.Context, request PostRgwUserByUidCapabilityRequest) (PostRgwUserByUidCapabilityResponse, error) {
	path := map[string]string{
		"uid": request.Uid,
	}
	query := url.Values{}
	var body any
	body = nil
	body = request.Body
	var response PostRgwUserByUidCapabilityResponse
	err := c.doJSON(ctx, http.MethodPost, "/api/rgw/user/{uid}/capability", path, query, body, true, &response)
	return response, err
}

// DeleteRgwUserByUidKey calls DELETE /api/rgw/user/{uid}/key with typed request and response values.
func (c *Client) DeleteRgwUserByUidKey(ctx context.Context, request DeleteRgwUserByUidKeyRequest) (DeleteRgwUserByUidKeyResponse, error) {
	path := map[string]string{
		"uid": request.Uid,
	}
	query := url.Values{}
	if request.KeyType != nil {
		query.Set("key_type", *request.KeyType)
	}
	if request.Subuser != nil {
		query.Set("subuser", *request.Subuser)
	}
	if request.AccessKey != nil {
		query.Set("access_key", *request.AccessKey)
	}
	if request.DaemonName != nil {
		query.Set("daemon_name", *request.DaemonName)
	}
	var body any
	body = nil
	var response DeleteRgwUserByUidKeyResponse
	err := c.doJSON(ctx, http.MethodDelete, "/api/rgw/user/{uid}/key", path, query, body, true, &response)
	return response, err
}

// PostRgwUserByUidKey calls POST /api/rgw/user/{uid}/key with typed request and response values.
func (c *Client) PostRgwUserByUidKey(ctx context.Context, request PostRgwUserByUidKeyRequest) (PostRgwUserByUidKeyResponse, error) {
	path := map[string]string{
		"uid": request.Uid,
	}
	query := url.Values{}
	var body any
	body = nil
	body = request.Body
	var response PostRgwUserByUidKeyResponse
	err := c.doJSON(ctx, http.MethodPost, "/api/rgw/user/{uid}/key", path, query, body, true, &response)
	return response, err
}

// GetRgwUserByUidQuota calls GET /api/rgw/user/{uid}/quota with typed request and response values.
func (c *Client) GetRgwUserByUidQuota(ctx context.Context, request GetRgwUserByUidQuotaRequest) (GetRgwUserByUidQuotaResponse, error) {
	path := map[string]string{
		"uid": request.Uid,
	}
	query := url.Values{}
	if request.DaemonName != nil {
		query.Set("daemon_name", *request.DaemonName)
	}
	var body any
	body = nil
	var response GetRgwUserByUidQuotaResponse
	err := c.doJSON(ctx, http.MethodGet, "/api/rgw/user/{uid}/quota", path, query, body, true, &response)
	return response, err
}

// PutRgwUserByUidQuota calls PUT /api/rgw/user/{uid}/quota with typed request and response values.
func (c *Client) PutRgwUserByUidQuota(ctx context.Context, request PutRgwUserByUidQuotaRequest) (PutRgwUserByUidQuotaResponse, error) {
	path := map[string]string{
		"uid": request.Uid,
	}
	query := url.Values{}
	var body any
	body = nil
	body = request.Body
	var response PutRgwUserByUidQuotaResponse
	err := c.doJSON(ctx, http.MethodPut, "/api/rgw/user/{uid}/quota", path, query, body, true, &response)
	return response, err
}

// GetRgwUserByUidRatelimit calls GET /api/rgw/user/{uid}/ratelimit with typed request and response values.
func (c *Client) GetRgwUserByUidRatelimit(ctx context.Context, request GetRgwUserByUidRatelimitRequest) (GetRgwUserByUidRatelimitResponse, error) {
	path := map[string]string{
		"uid": request.Uid,
	}
	query := url.Values{}
	var body any
	body = nil
	var response GetRgwUserByUidRatelimitResponse
	err := c.doJSON(ctx, http.MethodGet, "/api/rgw/user/{uid}/ratelimit", path, query, body, true, &response)
	return response, err
}

// PutRgwUserByUidRatelimit calls PUT /api/rgw/user/{uid}/ratelimit with typed request and response values.
func (c *Client) PutRgwUserByUidRatelimit(ctx context.Context, request PutRgwUserByUidRatelimitRequest) (PutRgwUserByUidRatelimitResponse, error) {
	path := map[string]string{
		"uid": request.Uid,
	}
	query := url.Values{}
	var body any
	body = nil
	body = request.Body
	var response PutRgwUserByUidRatelimitResponse
	err := c.doJSON(ctx, http.MethodPut, "/api/rgw/user/{uid}/ratelimit", path, query, body, true, &response)
	return response, err
}

// PostRgwUserByUidSubuser calls POST /api/rgw/user/{uid}/subuser with typed request and response values.
func (c *Client) PostRgwUserByUidSubuser(ctx context.Context, request PostRgwUserByUidSubuserRequest) (PostRgwUserByUidSubuserResponse, error) {
	path := map[string]string{
		"uid": request.Uid,
	}
	query := url.Values{}
	var body any
	body = nil
	body = request.Body
	var response PostRgwUserByUidSubuserResponse
	err := c.doJSON(ctx, http.MethodPost, "/api/rgw/user/{uid}/subuser", path, query, body, true, &response)
	return response, err
}

// DeleteRgwUserByUidSubuserBySubuser calls DELETE /api/rgw/user/{uid}/subuser/{subuser} with typed request and response values.
func (c *Client) DeleteRgwUserByUidSubuserBySubuser(ctx context.Context, request DeleteRgwUserByUidSubuserBySubuserRequest) (DeleteRgwUserByUidSubuserBySubuserResponse, error) {
	path := map[string]string{
		"uid":     request.Uid,
		"subuser": request.Subuser,
	}
	query := url.Values{}
	if request.PurgeKeys != nil {
		query.Set("purge_keys", *request.PurgeKeys)
	}
	if request.DaemonName != nil {
		query.Set("daemon_name", *request.DaemonName)
	}
	var body any
	body = nil
	var response DeleteRgwUserByUidSubuserBySubuserResponse
	err := c.doJSON(ctx, http.MethodDelete, "/api/rgw/user/{uid}/subuser/{subuser}", path, query, body, true, &response)
	return response, err
}

// GetRgwZone calls GET /api/rgw/zone with typed request and response values.
func (c *Client) GetRgwZone(ctx context.Context, request GetRgwZoneRequest) (GetRgwZoneResponse, error) {
	path := map[string]string{}
	query := url.Values{}
	var body any
	body = nil
	var response GetRgwZoneResponse
	err := c.doJSON(ctx, http.MethodGet, "/api/rgw/zone", path, query, body, true, &response)
	return response, err
}

// PostRgwZone calls POST /api/rgw/zone with typed request and response values.
func (c *Client) PostRgwZone(ctx context.Context, request PostRgwZoneRequest) (PostRgwZoneResponse, error) {
	path := map[string]string{}
	query := url.Values{}
	var body any
	body = nil
	body = request.Body
	var response PostRgwZoneResponse
	err := c.doJSON(ctx, http.MethodPost, "/api/rgw/zone", path, query, body, true, &response)
	return response, err
}

// PutRgwZoneCreateSystemUser calls PUT /api/rgw/zone/create_system_user with typed request and response values.
func (c *Client) PutRgwZoneCreateSystemUser(ctx context.Context, request PutRgwZoneCreateSystemUserRequest) (PutRgwZoneCreateSystemUserResponse, error) {
	path := map[string]string{}
	query := url.Values{}
	var body any
	body = nil
	body = request.Body
	var response PutRgwZoneCreateSystemUserResponse
	err := c.doJSON(ctx, http.MethodPut, "/api/rgw/zone/create_system_user", path, query, body, true, &response)
	return response, err
}

// GetRgwZoneGetAllZonesInfo calls GET /api/rgw/zone/get_all_zones_info with typed request and response values.
func (c *Client) GetRgwZoneGetAllZonesInfo(ctx context.Context, request GetRgwZoneGetAllZonesInfoRequest) (GetRgwZoneGetAllZonesInfoResponse, error) {
	path := map[string]string{}
	query := url.Values{}
	var body any
	body = nil
	var response GetRgwZoneGetAllZonesInfoResponse
	err := c.doJSON(ctx, http.MethodGet, "/api/rgw/zone/get_all_zones_info", path, query, body, true, &response)
	return response, err
}

// GetRgwZoneGetPoolNames calls GET /api/rgw/zone/get_pool_names with typed request and response values.
func (c *Client) GetRgwZoneGetPoolNames(ctx context.Context, request GetRgwZoneGetPoolNamesRequest) (GetRgwZoneGetPoolNamesResponse, error) {
	path := map[string]string{}
	query := url.Values{}
	var body any
	body = nil
	var response GetRgwZoneGetPoolNamesResponse
	err := c.doJSON(ctx, http.MethodGet, "/api/rgw/zone/get_pool_names", path, query, body, true, &response)
	return response, err
}

// GetRgwZoneGetUserList calls GET /api/rgw/zone/get_user_list with typed request and response values.
func (c *Client) GetRgwZoneGetUserList(ctx context.Context, request GetRgwZoneGetUserListRequest) (GetRgwZoneGetUserListResponse, error) {
	path := map[string]string{}
	query := url.Values{}
	if request.ZoneName != nil {
		query.Set("zoneName", *request.ZoneName)
	}
	if request.RealmName != nil {
		query.Set("realmName", *request.RealmName)
	}
	var body any
	body = nil
	var response GetRgwZoneGetUserListResponse
	err := c.doJSON(ctx, http.MethodGet, "/api/rgw/zone/get_user_list", path, query, body, true, &response)
	return response, err
}

// PostRgwZoneStorageClass calls POST /api/rgw/zone/storage-class with typed request and response values.
func (c *Client) PostRgwZoneStorageClass(ctx context.Context, request PostRgwZoneStorageClassRequest) (PostRgwZoneStorageClassResponse, error) {
	path := map[string]string{}
	query := url.Values{}
	var body any
	body = nil
	body = request.Body
	var response PostRgwZoneStorageClassResponse
	err := c.doJSON(ctx, http.MethodPost, "/api/rgw/zone/storage-class", path, query, body, true, &response)
	return response, err
}

// PutRgwZoneStorageClass calls PUT /api/rgw/zone/storage-class with typed request and response values.
func (c *Client) PutRgwZoneStorageClass(ctx context.Context, request PutRgwZoneStorageClassRequest) (PutRgwZoneStorageClassResponse, error) {
	path := map[string]string{}
	query := url.Values{}
	var body any
	body = nil
	body = request.Body
	var response PutRgwZoneStorageClassResponse
	err := c.doJSON(ctx, http.MethodPut, "/api/rgw/zone/storage-class", path, query, body, true, &response)
	return response, err
}

// DeleteRgwZoneByZoneName calls DELETE /api/rgw/zone/{zone_name} with typed request and response values.
func (c *Client) DeleteRgwZoneByZoneName(ctx context.Context, request DeleteRgwZoneByZoneNameRequest) (DeleteRgwZoneByZoneNameResponse, error) {
	path := map[string]string{
		"zone_name": request.ZoneName,
	}
	query := url.Values{}
	query.Set("delete_pools", request.DeletePools)
	if request.Pools != nil {
		query.Set("pools", *request.Pools)
	}
	if request.ZonegroupName != nil {
		query.Set("zonegroup_name", *request.ZonegroupName)
	}
	if request.RealmName != nil {
		query.Set("realm_name", *request.RealmName)
	}
	var body any
	body = nil
	var response DeleteRgwZoneByZoneNameResponse
	err := c.doJSON(ctx, http.MethodDelete, "/api/rgw/zone/{zone_name}", path, query, body, true, &response)
	return response, err
}

// GetRgwZoneByZoneName calls GET /api/rgw/zone/{zone_name} with typed request and response values.
func (c *Client) GetRgwZoneByZoneName(ctx context.Context, request GetRgwZoneByZoneNameRequest) (GetRgwZoneByZoneNameResponse, error) {
	path := map[string]string{
		"zone_name": request.ZoneName,
	}
	query := url.Values{}
	var body any
	body = nil
	var response GetRgwZoneByZoneNameResponse
	err := c.doJSON(ctx, http.MethodGet, "/api/rgw/zone/{zone_name}", path, query, body, true, &response)
	return response, err
}

// PutRgwZoneByZoneName calls PUT /api/rgw/zone/{zone_name} with typed request and response values.
func (c *Client) PutRgwZoneByZoneName(ctx context.Context, request PutRgwZoneByZoneNameRequest) (PutRgwZoneByZoneNameResponse, error) {
	path := map[string]string{
		"zone_name": request.ZoneName,
	}
	query := url.Values{}
	var body any
	body = nil
	body = request.Body
	var response PutRgwZoneByZoneNameResponse
	err := c.doJSON(ctx, http.MethodPut, "/api/rgw/zone/{zone_name}", path, query, body, true, &response)
	return response, err
}

// GetRgwZonegroup calls GET /api/rgw/zonegroup with typed request and response values.
func (c *Client) GetRgwZonegroup(ctx context.Context, request GetRgwZonegroupRequest) (GetRgwZonegroupResponse, error) {
	path := map[string]string{}
	query := url.Values{}
	var body any
	body = nil
	var response GetRgwZonegroupResponse
	err := c.doJSON(ctx, http.MethodGet, "/api/rgw/zonegroup", path, query, body, true, &response)
	return response, err
}

// PostRgwZonegroup calls POST /api/rgw/zonegroup with typed request and response values.
func (c *Client) PostRgwZonegroup(ctx context.Context, request PostRgwZonegroupRequest) (PostRgwZonegroupResponse, error) {
	path := map[string]string{}
	query := url.Values{}
	var body any
	body = nil
	body = request.Body
	var response PostRgwZonegroupResponse
	err := c.doJSON(ctx, http.MethodPost, "/api/rgw/zonegroup", path, query, body, true, &response)
	return response, err
}

// GetRgwZonegroupGetAllZonegroupsInfo calls GET /api/rgw/zonegroup/get_all_zonegroups_info with typed request and response values.
func (c *Client) GetRgwZonegroupGetAllZonegroupsInfo(ctx context.Context, request GetRgwZonegroupGetAllZonegroupsInfoRequest) (GetRgwZonegroupGetAllZonegroupsInfoResponse, error) {
	path := map[string]string{}
	query := url.Values{}
	var body any
	body = nil
	var response GetRgwZonegroupGetAllZonegroupsInfoResponse
	err := c.doJSON(ctx, http.MethodGet, "/api/rgw/zonegroup/get_all_zonegroups_info", path, query, body, true, &response)
	return response, err
}

// GetRgwZonegroupGetPlacementTargetByPlacementIdByPlacementId calls GET /api/rgw/zonegroup/get_placement_target_by_placement_id/{placement_id} with typed request and response values.
func (c *Client) GetRgwZonegroupGetPlacementTargetByPlacementIdByPlacementId(ctx context.Context, request GetRgwZonegroupGetPlacementTargetByPlacementIdByPlacementIdRequest) (GetRgwZonegroupGetPlacementTargetByPlacementIdByPlacementIdResponse, error) {
	path := map[string]string{
		"placement_id": request.PlacementId,
	}
	query := url.Values{}
	var body any
	body = nil
	var response GetRgwZonegroupGetPlacementTargetByPlacementIdByPlacementIdResponse
	err := c.doJSON(ctx, http.MethodGet, "/api/rgw/zonegroup/get_placement_target_by_placement_id/{placement_id}", path, query, body, true, &response)
	return response, err
}

// PostRgwZonegroupStorageClass calls POST /api/rgw/zonegroup/storage-class with typed request and response values.
func (c *Client) PostRgwZonegroupStorageClass(ctx context.Context, request PostRgwZonegroupStorageClassRequest) (PostRgwZonegroupStorageClassResponse, error) {
	path := map[string]string{}
	query := url.Values{}
	var body any
	body = nil
	body = request.Body
	var response PostRgwZonegroupStorageClassResponse
	err := c.doJSON(ctx, http.MethodPost, "/api/rgw/zonegroup/storage-class", path, query, body, true, &response)
	return response, err
}

// PutRgwZonegroupStorageClass calls PUT /api/rgw/zonegroup/storage-class with typed request and response values.
func (c *Client) PutRgwZonegroupStorageClass(ctx context.Context, request PutRgwZonegroupStorageClassRequest) (PutRgwZonegroupStorageClassResponse, error) {
	path := map[string]string{}
	query := url.Values{}
	var body any
	body = nil
	body = request.Body
	var response PutRgwZonegroupStorageClassResponse
	err := c.doJSON(ctx, http.MethodPut, "/api/rgw/zonegroup/storage-class", path, query, body, true, &response)
	return response, err
}

// DeleteRgwZonegroupStorageClassByPlacementIdByStorageClass calls DELETE /api/rgw/zonegroup/storage-class/{placement_id}/{storage_class} with typed request and response values.
func (c *Client) DeleteRgwZonegroupStorageClassByPlacementIdByStorageClass(ctx context.Context, request DeleteRgwZonegroupStorageClassByPlacementIdByStorageClassRequest) (DeleteRgwZonegroupStorageClassByPlacementIdByStorageClassResponse, error) {
	path := map[string]string{
		"placement_id":  request.PlacementId,
		"storage_class": request.StorageClass,
	}
	query := url.Values{}
	if request.ZoneName != nil {
		query.Set("zone_name", *request.ZoneName)
	}
	var body any
	body = nil
	var response DeleteRgwZonegroupStorageClassByPlacementIdByStorageClassResponse
	err := c.doJSON(ctx, http.MethodDelete, "/api/rgw/zonegroup/storage-class/{placement_id}/{storage_class}", path, query, body, true, &response)
	return response, err
}

// DeleteRgwZonegroupByZonegroupName calls DELETE /api/rgw/zonegroup/{zonegroup_name} with typed request and response values.
func (c *Client) DeleteRgwZonegroupByZonegroupName(ctx context.Context, request DeleteRgwZonegroupByZonegroupNameRequest) (DeleteRgwZonegroupByZonegroupNameResponse, error) {
	path := map[string]string{
		"zonegroup_name": request.ZonegroupName,
	}
	query := url.Values{}
	query.Set("delete_pools", request.DeletePools)
	if request.Pools != nil {
		query.Set("pools", *request.Pools)
	}
	if request.RealmName != nil {
		query.Set("realm_name", *request.RealmName)
	}
	var body any
	body = nil
	var response DeleteRgwZonegroupByZonegroupNameResponse
	err := c.doJSON(ctx, http.MethodDelete, "/api/rgw/zonegroup/{zonegroup_name}", path, query, body, true, &response)
	return response, err
}

// GetRgwZonegroupByZonegroupName calls GET /api/rgw/zonegroup/{zonegroup_name} with typed request and response values.
func (c *Client) GetRgwZonegroupByZonegroupName(ctx context.Context, request GetRgwZonegroupByZonegroupNameRequest) (GetRgwZonegroupByZonegroupNameResponse, error) {
	path := map[string]string{
		"zonegroup_name": request.ZonegroupName,
	}
	query := url.Values{}
	var body any
	body = nil
	var response GetRgwZonegroupByZonegroupNameResponse
	err := c.doJSON(ctx, http.MethodGet, "/api/rgw/zonegroup/{zonegroup_name}", path, query, body, true, &response)
	return response, err
}

// PutRgwZonegroupByZonegroupName calls PUT /api/rgw/zonegroup/{zonegroup_name} with typed request and response values.
func (c *Client) PutRgwZonegroupByZonegroupName(ctx context.Context, request PutRgwZonegroupByZonegroupNameRequest) (PutRgwZonegroupByZonegroupNameResponse, error) {
	path := map[string]string{
		"zonegroup_name": request.ZonegroupName,
	}
	query := url.Values{}
	var body any
	body = nil
	body = request.Body
	var response PutRgwZonegroupByZonegroupNameResponse
	err := c.doJSON(ctx, http.MethodPut, "/api/rgw/zonegroup/{zonegroup_name}", path, query, body, true, &response)
	return response, err
}
