// Code generated by tools/generate_ceph_dashboard_client.rb; DO NOT EDIT.

package typed

import (
	"context"
	"encoding/json"
	"net/http"
	"net/url"
	"strconv"
)

// service typed endpoints from docs/references/ceph/src/pybind/mgr/dashboard/openapi.yaml.

type GetServiceResponse map[string]json.RawMessage

type GetServiceRequest struct {
	ServiceName *string `query:"service_name"`
	Offset      *int    `query:"offset"`
	Limit       *int    `query:"limit"`
	Search      *string `query:"search"`
	Sort        *string `query:"sort"`
}

type PostServiceBody struct {
	ServiceName string `json:"service_name"`
	ServiceSpec string `json:"service_spec"`
}

type PostServiceResponse map[string]json.RawMessage

type PostServiceRequest struct {
	Body PostServiceBody `json:"-"`
}

type GetServiceKnownTypesResponse map[string]json.RawMessage

type GetServiceKnownTypesRequest struct{}

type DeleteServiceByServiceNameResponse map[string]json.RawMessage

type DeleteServiceByServiceNameRequest struct {
	ServiceName string `path:"service_name"`
}

type GetServiceByServiceNameResponse map[string]json.RawMessage

type GetServiceByServiceNameRequest struct {
	ServiceName string `path:"service_name"`
}

type PutServiceByServiceNameBody struct {
	ServiceSpec string `json:"service_spec"`
}

type PutServiceByServiceNameResponse map[string]json.RawMessage

type PutServiceByServiceNameRequest struct {
	ServiceName string                      `path:"service_name"`
	Body        PutServiceByServiceNameBody `json:"-"`
}

type GetServiceByServiceNameDaemonsResponse map[string]json.RawMessage

type GetServiceByServiceNameDaemonsRequest struct {
	ServiceName string `path:"service_name"`
}

// GetService calls GET /api/service with typed request and response values.
func (c *Client) GetService(ctx context.Context, request GetServiceRequest) (GetServiceResponse, error) {
	path := map[string]string{}
	query := url.Values{}
	if request.ServiceName != nil {
		query.Set("service_name", *request.ServiceName)
	}
	if request.Offset != nil {
		query.Set("offset", strconv.Itoa(*request.Offset))
	}
	if request.Limit != nil {
		query.Set("limit", strconv.Itoa(*request.Limit))
	}
	if request.Search != nil {
		query.Set("search", *request.Search)
	}
	if request.Sort != nil {
		query.Set("sort", *request.Sort)
	}
	var body any
	body = nil
	var response GetServiceResponse
	err := c.doJSON(ctx, http.MethodGet, "/api/service", path, query, body, true, &response)
	return response, err
}

// PostService calls POST /api/service with typed request and response values.
func (c *Client) PostService(ctx context.Context, request PostServiceRequest) (PostServiceResponse, error) {
	path := map[string]string{}
	query := url.Values{}
	var body any
	body = nil
	body = request.Body
	var response PostServiceResponse
	err := c.doJSON(ctx, http.MethodPost, "/api/service", path, query, body, true, &response)
	return response, err
}

// GetServiceKnownTypes calls GET /api/service/known_types with typed request and response values.
func (c *Client) GetServiceKnownTypes(ctx context.Context, request GetServiceKnownTypesRequest) (GetServiceKnownTypesResponse, error) {
	path := map[string]string{}
	query := url.Values{}
	var body any
	body = nil
	var response GetServiceKnownTypesResponse
	err := c.doJSON(ctx, http.MethodGet, "/api/service/known_types", path, query, body, true, &response)
	return response, err
}

// DeleteServiceByServiceName calls DELETE /api/service/{service_name} with typed request and response values.
func (c *Client) DeleteServiceByServiceName(ctx context.Context, request DeleteServiceByServiceNameRequest) (DeleteServiceByServiceNameResponse, error) {
	path := map[string]string{
		"service_name": request.ServiceName,
	}
	query := url.Values{}
	var body any
	body = nil
	var response DeleteServiceByServiceNameResponse
	err := c.doJSON(ctx, http.MethodDelete, "/api/service/{service_name}", path, query, body, true, &response)
	return response, err
}

// GetServiceByServiceName calls GET /api/service/{service_name} with typed request and response values.
func (c *Client) GetServiceByServiceName(ctx context.Context, request GetServiceByServiceNameRequest) (GetServiceByServiceNameResponse, error) {
	path := map[string]string{
		"service_name": request.ServiceName,
	}
	query := url.Values{}
	var body any
	body = nil
	var response GetServiceByServiceNameResponse
	err := c.doJSON(ctx, http.MethodGet, "/api/service/{service_name}", path, query, body, true, &response)
	return response, err
}

// PutServiceByServiceName calls PUT /api/service/{service_name} with typed request and response values.
func (c *Client) PutServiceByServiceName(ctx context.Context, request PutServiceByServiceNameRequest) (PutServiceByServiceNameResponse, error) {
	path := map[string]string{
		"service_name": request.ServiceName,
	}
	query := url.Values{}
	var body any
	body = nil
	body = request.Body
	var response PutServiceByServiceNameResponse
	err := c.doJSON(ctx, http.MethodPut, "/api/service/{service_name}", path, query, body, true, &response)
	return response, err
}

// GetServiceByServiceNameDaemons calls GET /api/service/{service_name}/daemons with typed request and response values.
func (c *Client) GetServiceByServiceNameDaemons(ctx context.Context, request GetServiceByServiceNameDaemonsRequest) (GetServiceByServiceNameDaemonsResponse, error) {
	path := map[string]string{
		"service_name": request.ServiceName,
	}
	query := url.Values{}
	var body any
	body = nil
	var response GetServiceByServiceNameDaemonsResponse
	err := c.doJSON(ctx, http.MethodGet, "/api/service/{service_name}/daemons", path, query, body, true, &response)
	return response, err
}
