// Code generated by tools/generate_ceph_dashboard_client.rb; DO NOT EDIT.

package typed

import (
	"context"
	"encoding/json"
	"net/http"
	"net/url"
)

// cluster_conf typed endpoints from docs/references/ceph/src/pybind/mgr/dashboard/openapi.yaml.

type GetClusterConfResponse map[string]json.RawMessage

type GetClusterConfRequest struct{}

type PostClusterConfBodyValueItem struct {
	Section string `json:"section"`
	Value   string `json:"value"`
}

type PostClusterConfBody struct {
	ForceUpdate bool                           `json:"force_update,omitempty"`
	Name        string                         `json:"name"`
	Value       []PostClusterConfBodyValueItem `json:"value"`
}

type PostClusterConfResponse map[string]json.RawMessage

type PostClusterConfRequest struct {
	Body PostClusterConfBody `json:"-"`
}

type PutClusterConfBody struct {
	Options string `json:"options"`
}

type PutClusterConfResponse map[string]json.RawMessage

type PutClusterConfRequest struct {
	Body PutClusterConfBody `json:"-"`
}

type GetClusterConfFilterResponseItem struct {
	CanUpdateAtRuntime bool     `json:"can_update_at_runtime,omitempty"`
	DaemonDefault      string   `json:"daemon_default,omitempty"`
	DefaultValue       string   `json:"default,omitempty"`
	Desc               string   `json:"desc,omitempty"`
	EnumValues         []string `json:"enum_values,omitempty"`
	Flags              []string `json:"flags,omitempty"`
	Level              string   `json:"level,omitempty"`
	LongDesc           string   `json:"long_desc,omitempty"`
	Max                string   `json:"max,omitempty"`
	Min                string   `json:"min,omitempty"`
	Name               string   `json:"name,omitempty"`
	SeeAlso            []string `json:"see_also,omitempty"`
	Services           []string `json:"services,omitempty"`
	Tags               []string `json:"tags,omitempty"`
	TypeValue          string   `json:"type,omitempty"`
}

type GetClusterConfFilterResponse []GetClusterConfFilterResponseItem

type GetClusterConfFilterRequest struct {
	Names *string `query:"names"`
}

type DeleteClusterConfByNameResponse map[string]json.RawMessage

type DeleteClusterConfByNameRequest struct {
	Name    string `path:"name"`
	Section string `query:"section"`
}

type GetClusterConfByNameResponse map[string]json.RawMessage

type GetClusterConfByNameRequest struct {
	Name string `path:"name"`
}

// GetClusterConf calls GET /api/cluster_conf with typed request and response values.
func (c *Client) GetClusterConf(ctx context.Context, request GetClusterConfRequest) (GetClusterConfResponse, error) {
	path := map[string]string{}
	query := url.Values{}
	var body any
	body = nil
	var response GetClusterConfResponse
	err := c.doJSON(ctx, http.MethodGet, "/api/cluster_conf", path, query, body, true, &response)
	return response, err
}

// PostClusterConf calls POST /api/cluster_conf with typed request and response values.
func (c *Client) PostClusterConf(ctx context.Context, request PostClusterConfRequest) (PostClusterConfResponse, error) {
	path := map[string]string{}
	query := url.Values{}
	var body any
	body = nil
	body = request.Body
	var response PostClusterConfResponse
	err := c.doJSON(ctx, http.MethodPost, "/api/cluster_conf", path, query, body, true, &response)
	return response, err
}

// PutClusterConf calls PUT /api/cluster_conf with typed request and response values.
func (c *Client) PutClusterConf(ctx context.Context, request PutClusterConfRequest) (PutClusterConfResponse, error) {
	path := map[string]string{}
	query := url.Values{}
	var body any
	body = nil
	body = request.Body
	var response PutClusterConfResponse
	err := c.doJSON(ctx, http.MethodPut, "/api/cluster_conf", path, query, body, true, &response)
	return response, err
}

// GetClusterConfFilter calls GET /api/cluster_conf/filter with typed request and response values.
func (c *Client) GetClusterConfFilter(ctx context.Context, request GetClusterConfFilterRequest) (GetClusterConfFilterResponse, error) {
	path := map[string]string{}
	query := url.Values{}
	if request.Names != nil {
		query.Set("names", *request.Names)
	}
	var body any
	body = nil
	var response GetClusterConfFilterResponse
	err := c.doJSON(ctx, http.MethodGet, "/api/cluster_conf/filter", path, query, body, true, &response)
	return response, err
}

// DeleteClusterConfByName calls DELETE /api/cluster_conf/{name} with typed request and response values.
func (c *Client) DeleteClusterConfByName(ctx context.Context, request DeleteClusterConfByNameRequest) (DeleteClusterConfByNameResponse, error) {
	path := map[string]string{
		"name": request.Name,
	}
	query := url.Values{}
	query.Set("section", request.Section)
	var body any
	body = nil
	var response DeleteClusterConfByNameResponse
	err := c.doJSON(ctx, http.MethodDelete, "/api/cluster_conf/{name}", path, query, body, true, &response)
	return response, err
}

// GetClusterConfByName calls GET /api/cluster_conf/{name} with typed request and response values.
func (c *Client) GetClusterConfByName(ctx context.Context, request GetClusterConfByNameRequest) (GetClusterConfByNameResponse, error) {
	path := map[string]string{
		"name": request.Name,
	}
	query := url.Values{}
	var body any
	body = nil
	var response GetClusterConfByNameResponse
	err := c.doJSON(ctx, http.MethodGet, "/api/cluster_conf/{name}", path, query, body, true, &response)
	return response, err
}
