// Code generated by tools/generate_ceph_dashboard_client.rb; DO NOT EDIT.

package typed

import (
	"context"
	"net/http"
	"net/url"
)

// feature_toggles typed endpoints from docs/references/ceph/src/pybind/mgr/dashboard/openapi.yaml.

type GetFeatureTogglesResponse struct {
	Cephfs    bool `json:"cephfs"`
	Dashboard bool `json:"dashboard"`
	Iscsi     bool `json:"iscsi"`
	Mirroring bool `json:"mirroring"`
	Nfs       bool `json:"nfs"`
	Rbd       bool `json:"rbd"`
	Rgw       bool `json:"rgw"`
}

type GetFeatureTogglesRequest struct{}

// GetFeatureToggles calls GET /api/feature_toggles with typed request and response values.
func (c *Client) GetFeatureToggles(ctx context.Context, request GetFeatureTogglesRequest) (GetFeatureTogglesResponse, error) {
	path := map[string]string{}
	query := url.Values{}
	var body any
	body = nil
	var response GetFeatureTogglesResponse
	err := c.doJSON(ctx, http.MethodGet, "/api/feature_toggles", path, query, body, true, &response)
	return response, err
}
