// Code generated by tools/generate_ceph_dashboard_client.rb; DO NOT EDIT.

package typed

import (
	"context"
	"net/http"
	"net/url"
)

// logs typed endpoints from docs/references/ceph/src/pybind/mgr/dashboard/openapi.yaml.

type GetLogsAllResponseAuditLogItemAddrsAddrvecItem struct {
	Addr      string `json:"addr"`
	Nonce     int    `json:"nonce"`
	TypeValue string `json:"type"`
}

type GetLogsAllResponseAuditLogItemAddrs struct {
	Addrvec []GetLogsAllResponseAuditLogItemAddrsAddrvecItem `json:"addrvec"`
}

type GetLogsAllResponseAuditLogItem struct {
	Addrs    GetLogsAllResponseAuditLogItemAddrs `json:"addrs"`
	Channel  string                              `json:"channel"`
	Message  string                              `json:"message"`
	Name     string                              `json:"name"`
	Priority string                              `json:"priority"`
	Rank     string                              `json:"rank"`
	Seq      int                                 `json:"seq"`
	Stamp    string                              `json:"stamp"`
}

type GetLogsAllResponse struct {
	AuditLog []GetLogsAllResponseAuditLogItem `json:"audit_log"`
	Clog     []string                         `json:"clog"`
}

type GetLogsAllRequest struct{}

// GetLogsAll calls GET /api/logs/all with typed request and response values.
func (c *Client) GetLogsAll(ctx context.Context, request GetLogsAllRequest) (GetLogsAllResponse, error) {
	path := map[string]string{}
	query := url.Values{}
	var body any
	body = nil
	var response GetLogsAllResponse
	err := c.doJSON(ctx, http.MethodGet, "/api/logs/all", path, query, body, true, &response)
	return response, err
}
