// Code generated by tools/generate_ceph_dashboard_client.rb; DO NOT EDIT.

package typed

import (
	"context"
	"encoding/json"
	"net/http"
	"net/url"
)

// motd typed endpoints from docs/references/ceph/src/pybind/mgr/dashboard/openapi.yaml.

type PostMotdBody struct {
	Expires  string `json:"expires"`
	Message  string `json:"message"`
	Severity string `json:"severity"`
}

type PostMotdResponse map[string]json.RawMessage

type PostMotdRequest struct {
	Body PostMotdBody `json:"-"`
}

type DeleteMotdClearResponse map[string]json.RawMessage

type DeleteMotdClearRequest struct{}

// PostMotd calls POST /api/motd with typed request and response values.
func (c *Client) PostMotd(ctx context.Context, request PostMotdRequest) (PostMotdResponse, error) {
	path := map[string]string{}
	query := url.Values{}
	var body any
	body = nil
	body = request.Body
	var response PostMotdResponse
	err := c.doJSON(ctx, http.MethodPost, "/api/motd", path, query, body, true, &response)
	return response, err
}

// DeleteMotdClear calls DELETE /api/motd/clear with typed request and response values.
func (c *Client) DeleteMotdClear(ctx context.Context, request DeleteMotdClearRequest) (DeleteMotdClearResponse, error) {
	path := map[string]string{}
	query := url.Values{}
	var body any
	body = nil
	var response DeleteMotdClearResponse
	err := c.doJSON(ctx, http.MethodDelete, "/api/motd/clear", path, query, body, true, &response)
	return response, err
}
