// Code generated by tools/generate_ceph_dashboard_client.rb; DO NOT EDIT.

package typed

import (
	"context"
	"encoding/json"
	"net/http"
	"net/url"
	"strconv"
)

// nfs_ganesha typed endpoints from docs/references/ceph/src/pybind/mgr/dashboard/openapi.yaml.

type GetNfsGaneshaClusterResponse map[string]json.RawMessage

type GetNfsGaneshaClusterRequest struct {
	Info *bool `query:"info"`
}

type GetNfsGaneshaExportResponseItemClientsItem struct {
	AccessType string   `json:"access_type"`
	Addresses  []string `json:"addresses"`
	Squash     string   `json:"squash"`
}

type GetNfsGaneshaExportResponseItemFsal struct {
	FsName        string `json:"fs_name,omitempty"`
	Name          string `json:"name"`
	SecLabelXattr string `json:"sec_label_xattr,omitempty"`
	UserId        string `json:"user_id,omitempty"`
}

type GetNfsGaneshaExportResponseItem struct {
	AccessType    string                                       `json:"access_type,omitempty"`
	Clients       []GetNfsGaneshaExportResponseItemClientsItem `json:"clients,omitempty"`
	ClusterId     string                                       `json:"cluster_id,omitempty"`
	ExportId      int                                          `json:"export_id,omitempty"`
	Fsal          GetNfsGaneshaExportResponseItemFsal          `json:"fsal,omitempty"`
	Path          string                                       `json:"path,omitempty"`
	Protocols     []int                                        `json:"protocols,omitempty"`
	Pseudo        string                                       `json:"pseudo,omitempty"`
	SecurityLabel string                                       `json:"security_label,omitempty"`
	Squash        string                                       `json:"squash,omitempty"`
	Transports    []string                                     `json:"transports,omitempty"`
}

type GetNfsGaneshaExportResponse []GetNfsGaneshaExportResponseItem

type GetNfsGaneshaExportRequest struct {
	ClusterId *string `query:"cluster_id"`
}

type PostNfsGaneshaExportBodyClientsItem struct {
	AccessType string   `json:"access_type"`
	Addresses  []string `json:"addresses"`
	Squash     string   `json:"squash"`
}

type PostNfsGaneshaExportBodyFsal struct {
	FsName        string `json:"fs_name,omitempty"`
	Name          string `json:"name"`
	SecLabelXattr string `json:"sec_label_xattr,omitempty"`
}

type PostNfsGaneshaExportBody struct {
	AccessType    string                                `json:"access_type"`
	Clients       []PostNfsGaneshaExportBodyClientsItem `json:"clients"`
	ClusterId     string                                `json:"cluster_id"`
	Fsal          PostNfsGaneshaExportBodyFsal          `json:"fsal"`
	Path          string                                `json:"path"`
	Protocols     []int                                 `json:"protocols"`
	Pseudo        string                                `json:"pseudo"`
	SecurityLabel string                                `json:"security_label"`
	Squash        string                                `json:"squash"`
	Transports    []string                              `json:"transports"`
}

type PostNfsGaneshaExportResponseClientsItem struct {
	AccessType string   `json:"access_type"`
	Addresses  []string `json:"addresses"`
	Squash     string   `json:"squash"`
}

type PostNfsGaneshaExportResponseFsal struct {
	FsName        string `json:"fs_name,omitempty"`
	Name          string `json:"name"`
	SecLabelXattr string `json:"sec_label_xattr,omitempty"`
	UserId        string `json:"user_id,omitempty"`
}

type PostNfsGaneshaExportResponse struct {
	AccessType    string                                    `json:"access_type"`
	Clients       []PostNfsGaneshaExportResponseClientsItem `json:"clients"`
	ClusterId     string                                    `json:"cluster_id"`
	ExportId      int                                       `json:"export_id"`
	Fsal          PostNfsGaneshaExportResponseFsal          `json:"fsal"`
	Path          string                                    `json:"path"`
	Protocols     []int                                     `json:"protocols"`
	Pseudo        string                                    `json:"pseudo"`
	SecurityLabel string                                    `json:"security_label"`
	Squash        string                                    `json:"squash"`
	Transports    []string                                  `json:"transports"`
}

type PostNfsGaneshaExportRequest struct {
	Body PostNfsGaneshaExportBody `json:"-"`
}

type DeleteNfsGaneshaExportByClusterIdByExportIdResponse map[string]json.RawMessage

type DeleteNfsGaneshaExportByClusterIdByExportIdRequest struct {
	ClusterId string `path:"cluster_id"`
	ExportId  string `path:"export_id"`
}

type GetNfsGaneshaExportByClusterIdByExportIdResponseClientsItem struct {
	AccessType string   `json:"access_type"`
	Addresses  []string `json:"addresses"`
	Squash     string   `json:"squash"`
}

type GetNfsGaneshaExportByClusterIdByExportIdResponseFsal struct {
	FsName        string `json:"fs_name,omitempty"`
	Name          string `json:"name"`
	SecLabelXattr string `json:"sec_label_xattr,omitempty"`
	UserId        string `json:"user_id,omitempty"`
}

type GetNfsGaneshaExportByClusterIdByExportIdResponse struct {
	AccessType    string                                                        `json:"access_type"`
	Clients       []GetNfsGaneshaExportByClusterIdByExportIdResponseClientsItem `json:"clients"`
	ClusterId     string                                                        `json:"cluster_id"`
	ExportId      int                                                           `json:"export_id"`
	Fsal          GetNfsGaneshaExportByClusterIdByExportIdResponseFsal          `json:"fsal"`
	Path          string                                                        `json:"path"`
	Protocols     []int                                                         `json:"protocols"`
	Pseudo        string                                                        `json:"pseudo"`
	SecurityLabel string                                                        `json:"security_label"`
	Squash        string                                                        `json:"squash"`
	Transports    []string                                                      `json:"transports"`
}

type GetNfsGaneshaExportByClusterIdByExportIdRequest struct {
	ClusterId string `path:"cluster_id"`
	ExportId  string `path:"export_id"`
}

type PutNfsGaneshaExportByClusterIdByExportIdBodyClientsItem struct {
	AccessType string   `json:"access_type"`
	Addresses  []string `json:"addresses"`
	Squash     string   `json:"squash"`
}

type PutNfsGaneshaExportByClusterIdByExportIdBodyFsal struct {
	FsName        string `json:"fs_name,omitempty"`
	Name          string `json:"name"`
	SecLabelXattr string `json:"sec_label_xattr,omitempty"`
}

type PutNfsGaneshaExportByClusterIdByExportIdBody struct {
	AccessType    string                                                    `json:"access_type"`
	Clients       []PutNfsGaneshaExportByClusterIdByExportIdBodyClientsItem `json:"clients"`
	Fsal          PutNfsGaneshaExportByClusterIdByExportIdBodyFsal          `json:"fsal"`
	Path          string                                                    `json:"path"`
	Protocols     []int                                                     `json:"protocols"`
	Pseudo        string                                                    `json:"pseudo"`
	SecurityLabel string                                                    `json:"security_label"`
	Squash        string                                                    `json:"squash"`
	Transports    []string                                                  `json:"transports"`
}

type PutNfsGaneshaExportByClusterIdByExportIdResponseClientsItem struct {
	AccessType string   `json:"access_type"`
	Addresses  []string `json:"addresses"`
	Squash     string   `json:"squash"`
}

type PutNfsGaneshaExportByClusterIdByExportIdResponseFsal struct {
	FsName        string `json:"fs_name,omitempty"`
	Name          string `json:"name"`
	SecLabelXattr string `json:"sec_label_xattr,omitempty"`
	UserId        string `json:"user_id,omitempty"`
}

type PutNfsGaneshaExportByClusterIdByExportIdResponse struct {
	AccessType    string                                                        `json:"access_type"`
	Clients       []PutNfsGaneshaExportByClusterIdByExportIdResponseClientsItem `json:"clients"`
	ClusterId     string                                                        `json:"cluster_id"`
	ExportId      int                                                           `json:"export_id"`
	Fsal          PutNfsGaneshaExportByClusterIdByExportIdResponseFsal          `json:"fsal"`
	Path          string                                                        `json:"path"`
	Protocols     []int                                                         `json:"protocols"`
	Pseudo        string                                                        `json:"pseudo"`
	SecurityLabel string                                                        `json:"security_label"`
	Squash        string                                                        `json:"squash"`
	Transports    []string                                                      `json:"transports"`
}

type PutNfsGaneshaExportByClusterIdByExportIdRequest struct {
	ClusterId string                                       `path:"cluster_id"`
	ExportId  string                                       `path:"export_id"`
	Body      PutNfsGaneshaExportByClusterIdByExportIdBody `json:"-"`
}

// GetNfsGaneshaCluster calls GET /api/nfs-ganesha/cluster with typed request and response values.
func (c *Client) GetNfsGaneshaCluster(ctx context.Context, request GetNfsGaneshaClusterRequest) (GetNfsGaneshaClusterResponse, error) {
	path := map[string]string{}
	query := url.Values{}
	if request.Info != nil {
		query.Set("info", strconv.FormatBool(*request.Info))
	}
	var body any
	body = nil
	var response GetNfsGaneshaClusterResponse
	err := c.doJSON(ctx, http.MethodGet, "/api/nfs-ganesha/cluster", path, query, body, true, &response)
	return response, err
}

// GetNfsGaneshaExport calls GET /api/nfs-ganesha/export with typed request and response values.
func (c *Client) GetNfsGaneshaExport(ctx context.Context, request GetNfsGaneshaExportRequest) (GetNfsGaneshaExportResponse, error) {
	path := map[string]string{}
	query := url.Values{}
	if request.ClusterId != nil {
		query.Set("cluster_id", *request.ClusterId)
	}
	var body any
	body = nil
	var response GetNfsGaneshaExportResponse
	err := c.doJSON(ctx, http.MethodGet, "/api/nfs-ganesha/export", path, query, body, true, &response)
	return response, err
}

// PostNfsGaneshaExport calls POST /api/nfs-ganesha/export with typed request and response values.
func (c *Client) PostNfsGaneshaExport(ctx context.Context, request PostNfsGaneshaExportRequest) (PostNfsGaneshaExportResponse, error) {
	path := map[string]string{}
	query := url.Values{}
	var body any
	body = nil
	body = request.Body
	var response PostNfsGaneshaExportResponse
	err := c.doJSON(ctx, http.MethodPost, "/api/nfs-ganesha/export", path, query, body, true, &response)
	return response, err
}

// DeleteNfsGaneshaExportByClusterIdByExportId calls DELETE /api/nfs-ganesha/export/{cluster_id}/{export_id} with typed request and response values.
func (c *Client) DeleteNfsGaneshaExportByClusterIdByExportId(ctx context.Context, request DeleteNfsGaneshaExportByClusterIdByExportIdRequest) (DeleteNfsGaneshaExportByClusterIdByExportIdResponse, error) {
	path := map[string]string{
		"cluster_id": request.ClusterId,
		"export_id":  request.ExportId,
	}
	query := url.Values{}
	var body any
	body = nil
	var response DeleteNfsGaneshaExportByClusterIdByExportIdResponse
	err := c.doJSON(ctx, http.MethodDelete, "/api/nfs-ganesha/export/{cluster_id}/{export_id}", path, query, body, true, &response)
	return response, err
}

// GetNfsGaneshaExportByClusterIdByExportId calls GET /api/nfs-ganesha/export/{cluster_id}/{export_id} with typed request and response values.
func (c *Client) GetNfsGaneshaExportByClusterIdByExportId(ctx context.Context, request GetNfsGaneshaExportByClusterIdByExportIdRequest) (GetNfsGaneshaExportByClusterIdByExportIdResponse, error) {
	path := map[string]string{
		"cluster_id": request.ClusterId,
		"export_id":  request.ExportId,
	}
	query := url.Values{}
	var body any
	body = nil
	var response GetNfsGaneshaExportByClusterIdByExportIdResponse
	err := c.doJSON(ctx, http.MethodGet, "/api/nfs-ganesha/export/{cluster_id}/{export_id}", path, query, body, true, &response)
	return response, err
}

// PutNfsGaneshaExportByClusterIdByExportId calls PUT /api/nfs-ganesha/export/{cluster_id}/{export_id} with typed request and response values.
func (c *Client) PutNfsGaneshaExportByClusterIdByExportId(ctx context.Context, request PutNfsGaneshaExportByClusterIdByExportIdRequest) (PutNfsGaneshaExportByClusterIdByExportIdResponse, error) {
	path := map[string]string{
		"cluster_id": request.ClusterId,
		"export_id":  request.ExportId,
	}
	query := url.Values{}
	var body any
	body = nil
	body = request.Body
	var response PutNfsGaneshaExportByClusterIdByExportIdResponse
	err := c.doJSON(ctx, http.MethodPut, "/api/nfs-ganesha/export/{cluster_id}/{export_id}", path, query, body, true, &response)
	return response, err
}
