// Code generated by tools/generate_ceph_dashboard_client.rb; DO NOT EDIT.

package typed

import (
	"context"
	"encoding/json"
	"net/http"
	"net/url"
)

// perf_counters typed endpoints from docs/references/ceph/src/pybind/mgr/dashboard/openapi.yaml.

type GetPerfCountersResponseMonACacheBytes struct {
	Description string `json:"description"`
	Nick        string `json:"nick"`
	Priority    int    `json:"priority"`
	TypeValue   int    `json:"type"`
	Units       int    `json:"units"`
	Value       int    `json:"value"`
}

type GetPerfCountersResponseMonA struct {
	CacheBytes GetPerfCountersResponseMonACacheBytes `json:".cache_bytes"`
}

type GetPerfCountersResponse struct {
	MonA GetPerfCountersResponseMonA `json:"mon.a"`
}

type GetPerfCountersRequest struct{}

type GetPerfCountersMdsByServiceIdResponse map[string]json.RawMessage

type GetPerfCountersMdsByServiceIdRequest struct {
	ServiceId string `path:"service_id"`
}

type GetPerfCountersMgrByServiceIdResponse map[string]json.RawMessage

type GetPerfCountersMgrByServiceIdRequest struct {
	ServiceId string `path:"service_id"`
}

type GetPerfCountersMonByServiceIdResponse map[string]json.RawMessage

type GetPerfCountersMonByServiceIdRequest struct {
	ServiceId string `path:"service_id"`
}

type GetPerfCountersOsdByServiceIdResponse map[string]json.RawMessage

type GetPerfCountersOsdByServiceIdRequest struct {
	ServiceId string `path:"service_id"`
}

type GetPerfCountersRbdMirrorByServiceIdResponse map[string]json.RawMessage

type GetPerfCountersRbdMirrorByServiceIdRequest struct {
	ServiceId string `path:"service_id"`
}

type GetPerfCountersRgwByServiceIdResponse map[string]json.RawMessage

type GetPerfCountersRgwByServiceIdRequest struct {
	ServiceId string `path:"service_id"`
}

type GetPerfCountersTcmuRunnerByServiceIdResponse map[string]json.RawMessage

type GetPerfCountersTcmuRunnerByServiceIdRequest struct {
	ServiceId string `path:"service_id"`
}

// GetPerfCounters calls GET /api/perf_counters with typed request and response values.
func (c *Client) GetPerfCounters(ctx context.Context, request GetPerfCountersRequest) (GetPerfCountersResponse, error) {
	path := map[string]string{}
	query := url.Values{}
	var body any
	body = nil
	var response GetPerfCountersResponse
	err := c.doJSON(ctx, http.MethodGet, "/api/perf_counters", path, query, body, true, &response)
	return response, err
}

// GetPerfCountersMdsByServiceId calls GET /api/perf_counters/mds/{service_id} with typed request and response values.
func (c *Client) GetPerfCountersMdsByServiceId(ctx context.Context, request GetPerfCountersMdsByServiceIdRequest) (GetPerfCountersMdsByServiceIdResponse, error) {
	path := map[string]string{
		"service_id": request.ServiceId,
	}
	query := url.Values{}
	var body any
	body = nil
	var response GetPerfCountersMdsByServiceIdResponse
	err := c.doJSON(ctx, http.MethodGet, "/api/perf_counters/mds/{service_id}", path, query, body, true, &response)
	return response, err
}

// GetPerfCountersMgrByServiceId calls GET /api/perf_counters/mgr/{service_id} with typed request and response values.
func (c *Client) GetPerfCountersMgrByServiceId(ctx context.Context, request GetPerfCountersMgrByServiceIdRequest) (GetPerfCountersMgrByServiceIdResponse, error) {
	path := map[string]string{
		"service_id": request.ServiceId,
	}
	query := url.Values{}
	var body any
	body = nil
	var response GetPerfCountersMgrByServiceIdResponse
	err := c.doJSON(ctx, http.MethodGet, "/api/perf_counters/mgr/{service_id}", path, query, body, true, &response)
	return response, err
}

// GetPerfCountersMonByServiceId calls GET /api/perf_counters/mon/{service_id} with typed request and response values.
func (c *Client) GetPerfCountersMonByServiceId(ctx context.Context, request GetPerfCountersMonByServiceIdRequest) (GetPerfCountersMonByServiceIdResponse, error) {
	path := map[string]string{
		"service_id": request.ServiceId,
	}
	query := url.Values{}
	var body any
	body = nil
	var response GetPerfCountersMonByServiceIdResponse
	err := c.doJSON(ctx, http.MethodGet, "/api/perf_counters/mon/{service_id}", path, query, body, true, &response)
	return response, err
}

// GetPerfCountersOsdByServiceId calls GET /api/perf_counters/osd/{service_id} with typed request and response values.
func (c *Client) GetPerfCountersOsdByServiceId(ctx context.Context, request GetPerfCountersOsdByServiceIdRequest) (GetPerfCountersOsdByServiceIdResponse, error) {
	path := map[string]string{
		"service_id": request.ServiceId,
	}
	query := url.Values{}
	var body any
	body = nil
	var response GetPerfCountersOsdByServiceIdResponse
	err := c.doJSON(ctx, http.MethodGet, "/api/perf_counters/osd/{service_id}", path, query, body, true, &response)
	return response, err
}

// GetPerfCountersRbdMirrorByServiceId calls GET /api/perf_counters/rbd-mirror/{service_id} with typed request and response values.
func (c *Client) GetPerfCountersRbdMirrorByServiceId(ctx context.Context, request GetPerfCountersRbdMirrorByServiceIdRequest) (GetPerfCountersRbdMirrorByServiceIdResponse, error) {
	path := map[string]string{
		"service_id": request.ServiceId,
	}
	query := url.Values{}
	var body any
	body = nil
	var response GetPerfCountersRbdMirrorByServiceIdResponse
	err := c.doJSON(ctx, http.MethodGet, "/api/perf_counters/rbd-mirror/{service_id}", path, query, body, true, &response)
	return response, err
}

// GetPerfCountersRgwByServiceId calls GET /api/perf_counters/rgw/{service_id} with typed request and response values.
func (c *Client) GetPerfCountersRgwByServiceId(ctx context.Context, request GetPerfCountersRgwByServiceIdRequest) (GetPerfCountersRgwByServiceIdResponse, error) {
	path := map[string]string{
		"service_id": request.ServiceId,
	}
	query := url.Values{}
	var body any
	body = nil
	var response GetPerfCountersRgwByServiceIdResponse
	err := c.doJSON(ctx, http.MethodGet, "/api/perf_counters/rgw/{service_id}", path, query, body, true, &response)
	return response, err
}

// GetPerfCountersTcmuRunnerByServiceId calls GET /api/perf_counters/tcmu-runner/{service_id} with typed request and response values.
func (c *Client) GetPerfCountersTcmuRunnerByServiceId(ctx context.Context, request GetPerfCountersTcmuRunnerByServiceIdRequest) (GetPerfCountersTcmuRunnerByServiceIdResponse, error) {
	path := map[string]string{
		"service_id": request.ServiceId,
	}
	query := url.Values{}
	var body any
	body = nil
	var response GetPerfCountersTcmuRunnerByServiceIdResponse
	err := c.doJSON(ctx, http.MethodGet, "/api/perf_counters/tcmu-runner/{service_id}", path, query, body, true, &response)
	return response, err
}
