// Code generated by tools/generate_ceph_dashboard_client.rb; DO NOT EDIT.

package typed

import (
	"context"
	"net/http"
	"net/url"
)

// summary typed endpoints from docs/references/ceph/src/pybind/mgr/dashboard/openapi.yaml.

type GetSummaryResponseFinishedTasksItemMetadata struct {
	Pool int `json:"pool"`
}

type GetSummaryResponseFinishedTasksItem struct {
	BeginTime string                                      `json:"begin_time"`
	Duration  int                                         `json:"duration"`
	EndTime   string                                      `json:"end_time"`
	Exception string                                      `json:"exception"`
	Metadata  GetSummaryResponseFinishedTasksItemMetadata `json:"metadata"`
	Name      string                                      `json:"name"`
	Progress  int                                         `json:"progress"`
	RetValue  string                                      `json:"ret_value"`
	Success   bool                                        `json:"success"`
}

type GetSummaryResponseRbdMirroring struct {
	Errors   int `json:"errors"`
	Warnings int `json:"warnings"`
}

type GetSummaryResponse struct {
	ExecutingTasks    []string                              `json:"executing_tasks"`
	FinishedTasks     []GetSummaryResponseFinishedTasksItem `json:"finished_tasks"`
	HaveMonConnection string                                `json:"have_mon_connection"`
	HealthStatus      string                                `json:"health_status"`
	MgrHost           string                                `json:"mgr_host"`
	MgrId             string                                `json:"mgr_id"`
	RbdMirroring      GetSummaryResponseRbdMirroring        `json:"rbd_mirroring"`
	Version           string                                `json:"version"`
}

type GetSummaryRequest struct{}

// GetSummary calls GET /api/summary with typed request and response values.
func (c *Client) GetSummary(ctx context.Context, request GetSummaryRequest) (GetSummaryResponse, error) {
	path := map[string]string{}
	query := url.Values{}
	var body any
	body = nil
	var response GetSummaryResponse
	err := c.doJSON(ctx, http.MethodGet, "/api/summary", path, query, body, true, &response)
	return response, err
}
