// Code generated by tools/generate_ceph_dashboard_client.rb; DO NOT EDIT.

package typed

import (
	"context"
	"net/http"
	"net/url"
)

// task typed endpoints from docs/references/ceph/src/pybind/mgr/dashboard/openapi.yaml.

type GetTaskResponseFinishedTasksItemMetadata struct {
	Pool int `json:"pool"`
}

type GetTaskResponseFinishedTasksItem struct {
	BeginTime string                                   `json:"begin_time"`
	Duration  int                                      `json:"duration"`
	EndTime   string                                   `json:"end_time"`
	Exception bool                                     `json:"exception"`
	Metadata  GetTaskResponseFinishedTasksItemMetadata `json:"metadata"`
	Name      string                                   `json:"name"`
	Progress  int                                      `json:"progress"`
	RetValue  bool                                     `json:"ret_value"`
	Success   bool                                     `json:"success"`
}

type GetTaskResponse struct {
	ExecutingTasks string                             `json:"executing_tasks"`
	FinishedTasks  []GetTaskResponseFinishedTasksItem `json:"finished_tasks"`
}

type GetTaskRequest struct {
	Name *string `query:"name"`
}

// GetTask calls GET /api/task with typed request and response values.
func (c *Client) GetTask(ctx context.Context, request GetTaskRequest) (GetTaskResponse, error) {
	path := map[string]string{}
	query := url.Values{}
	if request.Name != nil {
		query.Set("name", *request.Name)
	}
	var body any
	body = nil
	var response GetTaskResponse
	err := c.doJSON(ctx, http.MethodGet, "/api/task", path, query, body, true, &response)
	return response, err
}
