// Code generated by tools/generate_ceph_dashboard_client.rb; DO NOT EDIT.

package typed

import (
	"context"
	"encoding/json"
	"net/http"
	"net/url"
)

// user typed endpoints from docs/references/ceph/src/pybind/mgr/dashboard/openapi.yaml.

type GetUserResponse struct {
	Email             string   `json:"email"`
	Enabled           bool     `json:"enabled"`
	LastUpdate        int      `json:"lastUpdate"`
	Name              string   `json:"name"`
	PwdExpirationDate string   `json:"pwdExpirationDate"`
	PwdUpdateRequired bool     `json:"pwdUpdateRequired"`
	Roles             []string `json:"roles"`
	Username          string   `json:"username"`
}

type GetUserRequest struct{}

type PostUserBody struct {
	Email             string `json:"email,omitempty"`
	Enabled           bool   `json:"enabled,omitempty"`
	Name              string `json:"name,omitempty"`
	Password          string `json:"password,omitempty"`
	PwdExpirationDate string `json:"pwdExpirationDate,omitempty"`
	PwdUpdateRequired bool   `json:"pwdUpdateRequired,omitempty"`
	Roles             string `json:"roles,omitempty"`
	Username          string `json:"username,omitempty"`
}

type PostUserResponse map[string]json.RawMessage

type PostUserRequest struct {
	Body PostUserBody `json:"-"`
}

type PostUserValidatePasswordBody struct {
	OldPassword string `json:"old_password,omitempty"`
	Password    string `json:"password"`
	Username    string `json:"username,omitempty"`
}

type PostUserValidatePasswordResponse map[string]json.RawMessage

type PostUserValidatePasswordRequest struct {
	Body PostUserValidatePasswordBody `json:"-"`
}

type DeleteUserByUsernameResponse map[string]json.RawMessage

type DeleteUserByUsernameRequest struct {
	Username string `path:"username"`
}

type GetUserByUsernameResponse map[string]json.RawMessage

type GetUserByUsernameRequest struct {
	Username string `path:"username"`
}

type PutUserByUsernameBody struct {
	Email             string `json:"email,omitempty"`
	Enabled           string `json:"enabled,omitempty"`
	Name              string `json:"name,omitempty"`
	Password          string `json:"password,omitempty"`
	PwdExpirationDate string `json:"pwdExpirationDate,omitempty"`
	PwdUpdateRequired bool   `json:"pwdUpdateRequired,omitempty"`
	Roles             string `json:"roles,omitempty"`
}

type PutUserByUsernameResponse map[string]json.RawMessage

type PutUserByUsernameRequest struct {
	Username string                `path:"username"`
	Body     PutUserByUsernameBody `json:"-"`
}

type PostUserByUsernameChangePasswordBody struct {
	NewPassword string `json:"new_password"`
	OldPassword string `json:"old_password"`
}

type PostUserByUsernameChangePasswordResponse map[string]json.RawMessage

type PostUserByUsernameChangePasswordRequest struct {
	Username string                               `path:"username"`
	Body     PostUserByUsernameChangePasswordBody `json:"-"`
}

// GetUser calls GET /api/user with typed request and response values.
func (c *Client) GetUser(ctx context.Context, request GetUserRequest) (GetUserResponse, error) {
	path := map[string]string{}
	query := url.Values{}
	var body any
	body = nil
	var response GetUserResponse
	err := c.doJSON(ctx, http.MethodGet, "/api/user", path, query, body, true, &response)
	return response, err
}

// PostUser calls POST /api/user with typed request and response values.
func (c *Client) PostUser(ctx context.Context, request PostUserRequest) (PostUserResponse, error) {
	path := map[string]string{}
	query := url.Values{}
	var body any
	body = nil
	body = request.Body
	var response PostUserResponse
	err := c.doJSON(ctx, http.MethodPost, "/api/user", path, query, body, true, &response)
	return response, err
}

// PostUserValidatePassword calls POST /api/user/validate_password with typed request and response values.
func (c *Client) PostUserValidatePassword(ctx context.Context, request PostUserValidatePasswordRequest) (PostUserValidatePasswordResponse, error) {
	path := map[string]string{}
	query := url.Values{}
	var body any
	body = nil
	body = request.Body
	var response PostUserValidatePasswordResponse
	err := c.doJSON(ctx, http.MethodPost, "/api/user/validate_password", path, query, body, true, &response)
	return response, err
}

// DeleteUserByUsername calls DELETE /api/user/{username} with typed request and response values.
func (c *Client) DeleteUserByUsername(ctx context.Context, request DeleteUserByUsernameRequest) (DeleteUserByUsernameResponse, error) {
	path := map[string]string{
		"username": request.Username,
	}
	query := url.Values{}
	var body any
	body = nil
	var response DeleteUserByUsernameResponse
	err := c.doJSON(ctx, http.MethodDelete, "/api/user/{username}", path, query, body, true, &response)
	return response, err
}

// GetUserByUsername calls GET /api/user/{username} with typed request and response values.
func (c *Client) GetUserByUsername(ctx context.Context, request GetUserByUsernameRequest) (GetUserByUsernameResponse, error) {
	path := map[string]string{
		"username": request.Username,
	}
	query := url.Values{}
	var body any
	body = nil
	var response GetUserByUsernameResponse
	err := c.doJSON(ctx, http.MethodGet, "/api/user/{username}", path, query, body, true, &response)
	return response, err
}

// PutUserByUsername calls PUT /api/user/{username} with typed request and response values.
func (c *Client) PutUserByUsername(ctx context.Context, request PutUserByUsernameRequest) (PutUserByUsernameResponse, error) {
	path := map[string]string{
		"username": request.Username,
	}
	query := url.Values{}
	var body any
	body = nil
	body = request.Body
	var response PutUserByUsernameResponse
	err := c.doJSON(ctx, http.MethodPut, "/api/user/{username}", path, query, body, true, &response)
	return response, err
}

// PostUserByUsernameChangePassword calls POST /api/user/{username}/change_password with typed request and response values.
func (c *Client) PostUserByUsernameChangePassword(ctx context.Context, request PostUserByUsernameChangePasswordRequest) (PostUserByUsernameChangePasswordResponse, error) {
	path := map[string]string{
		"username": request.Username,
	}
	query := url.Values{}
	var body any
	body = nil
	body = request.Body
	var response PostUserByUsernameChangePasswordResponse
	err := c.doJSON(ctx, http.MethodPost, "/api/user/{username}/change_password", path, query, body, true, &response)
	return response, err
}
