// Code generated by tools/generate_ceph_dashboard_client.rb; DO NOT EDIT.

package typed

import (
	"context"
	"encoding/json"
	"net/http"
	"net/url"
	"strconv"
)

// cluster typed endpoints from docs/references/ceph/src/pybind/mgr/dashboard/openapi.yaml.

type GetClusterResponse map[string]json.RawMessage

type GetClusterRequest struct{}

type PutClusterBody struct {
	Status string `json:"status"`
}

type PutClusterResponse map[string]json.RawMessage

type PutClusterRequest struct {
	Body PutClusterBody `json:"-"`
}

type GetClusterUpgradeResponse map[string]json.RawMessage

type GetClusterUpgradeRequest struct {
	Tags            *bool   `query:"tags"`
	Image           *string `query:"image"`
	ShowAllVersions *bool   `query:"show_all_versions"`
}

type PutClusterUpgradePauseResponse map[string]json.RawMessage

type PutClusterUpgradePauseRequest struct{}

type PutClusterUpgradeResumeResponse map[string]json.RawMessage

type PutClusterUpgradeResumeRequest struct{}

type PostClusterUpgradeStartBody struct {
	DaemonTypes   string `json:"daemon_types,omitempty"`
	HostPlacement string `json:"host_placement,omitempty"`
	Image         string `json:"image,omitempty"`
	Limit         string `json:"limit,omitempty"`
	Services      string `json:"services,omitempty"`
	Version       string `json:"version,omitempty"`
}

type PostClusterUpgradeStartResponse map[string]json.RawMessage

type PostClusterUpgradeStartRequest struct {
	Body PostClusterUpgradeStartBody `json:"-"`
}

type GetClusterUpgradeStatusResponse map[string]json.RawMessage

type GetClusterUpgradeStatusRequest struct{}

type PutClusterUpgradeStopResponse map[string]json.RawMessage

type PutClusterUpgradeStopRequest struct{}

type GetClusterUserResponse map[string]json.RawMessage

type GetClusterUserRequest struct{}

type PostClusterUserBodyCapabilitiesItem struct {
	Cap    string `json:"cap"`
	Entity string `json:"entity"`
}

type PostClusterUserBody struct {
	Capabilities []PostClusterUserBodyCapabilitiesItem `json:"capabilities,omitempty"`
	ImportData   string                                `json:"import_data,omitempty"`
	UserEntity   string                                `json:"user_entity,omitempty"`
}

type PostClusterUserResponse map[string]json.RawMessage

type PostClusterUserRequest struct {
	Body PostClusterUserBody `json:"-"`
}

type PutClusterUserBodyCapabilitiesItem struct {
	Cap    string `json:"cap"`
	Entity string `json:"entity"`
}

type PutClusterUserBody struct {
	Capabilities []PutClusterUserBodyCapabilitiesItem `json:"capabilities,omitempty"`
	UserEntity   string                               `json:"user_entity,omitempty"`
}

type PutClusterUserResponse map[string]json.RawMessage

type PutClusterUserRequest struct {
	Body PutClusterUserBody `json:"-"`
}

type PostClusterUserExportBody struct {
	Entities []string `json:"entities"`
}

type PostClusterUserExportResponse map[string]json.RawMessage

type PostClusterUserExportRequest struct {
	Body PostClusterUserExportBody `json:"-"`
}

type DeleteClusterUserByUserEntitiesResponse map[string]json.RawMessage

type DeleteClusterUserByUserEntitiesRequest struct {
	UserEntities string `path:"user_entities"`
}

// GetCluster calls GET /api/cluster with typed request and response values.
func (c *Client) GetCluster(ctx context.Context, request GetClusterRequest) (GetClusterResponse, error) {
	path := map[string]string{}
	query := url.Values{}
	var body any
	body = nil
	var response GetClusterResponse
	err := c.doJSON(ctx, http.MethodGet, "/api/cluster", path, query, body, true, &response)
	return response, err
}

// PutCluster calls PUT /api/cluster with typed request and response values.
func (c *Client) PutCluster(ctx context.Context, request PutClusterRequest) (PutClusterResponse, error) {
	path := map[string]string{}
	query := url.Values{}
	var body any
	body = nil
	body = request.Body
	var response PutClusterResponse
	err := c.doJSON(ctx, http.MethodPut, "/api/cluster", path, query, body, true, &response)
	return response, err
}

// GetClusterUpgrade calls GET /api/cluster/upgrade with typed request and response values.
func (c *Client) GetClusterUpgrade(ctx context.Context, request GetClusterUpgradeRequest) (GetClusterUpgradeResponse, error) {
	path := map[string]string{}
	query := url.Values{}
	if request.Tags != nil {
		query.Set("tags", strconv.FormatBool(*request.Tags))
	}
	if request.Image != nil {
		query.Set("image", *request.Image)
	}
	if request.ShowAllVersions != nil {
		query.Set("show_all_versions", strconv.FormatBool(*request.ShowAllVersions))
	}
	var body any
	body = nil
	var response GetClusterUpgradeResponse
	err := c.doJSON(ctx, http.MethodGet, "/api/cluster/upgrade", path, query, body, true, &response)
	return response, err
}

// PutClusterUpgradePause calls PUT /api/cluster/upgrade/pause with typed request and response values.
func (c *Client) PutClusterUpgradePause(ctx context.Context, request PutClusterUpgradePauseRequest) (PutClusterUpgradePauseResponse, error) {
	path := map[string]string{}
	query := url.Values{}
	var body any
	body = nil
	var response PutClusterUpgradePauseResponse
	err := c.doJSON(ctx, http.MethodPut, "/api/cluster/upgrade/pause", path, query, body, true, &response)
	return response, err
}

// PutClusterUpgradeResume calls PUT /api/cluster/upgrade/resume with typed request and response values.
func (c *Client) PutClusterUpgradeResume(ctx context.Context, request PutClusterUpgradeResumeRequest) (PutClusterUpgradeResumeResponse, error) {
	path := map[string]string{}
	query := url.Values{}
	var body any
	body = nil
	var response PutClusterUpgradeResumeResponse
	err := c.doJSON(ctx, http.MethodPut, "/api/cluster/upgrade/resume", path, query, body, true, &response)
	return response, err
}

// PostClusterUpgradeStart calls POST /api/cluster/upgrade/start with typed request and response values.
func (c *Client) PostClusterUpgradeStart(ctx context.Context, request PostClusterUpgradeStartRequest) (PostClusterUpgradeStartResponse, error) {
	path := map[string]string{}
	query := url.Values{}
	var body any
	body = nil
	body = request.Body
	var response PostClusterUpgradeStartResponse
	err := c.doJSON(ctx, http.MethodPost, "/api/cluster/upgrade/start", path, query, body, true, &response)
	return response, err
}

// GetClusterUpgradeStatus calls GET /api/cluster/upgrade/status with typed request and response values.
func (c *Client) GetClusterUpgradeStatus(ctx context.Context, request GetClusterUpgradeStatusRequest) (GetClusterUpgradeStatusResponse, error) {
	path := map[string]string{}
	query := url.Values{}
	var body any
	body = nil
	var response GetClusterUpgradeStatusResponse
	err := c.doJSON(ctx, http.MethodGet, "/api/cluster/upgrade/status", path, query, body, true, &response)
	return response, err
}

// PutClusterUpgradeStop calls PUT /api/cluster/upgrade/stop with typed request and response values.
func (c *Client) PutClusterUpgradeStop(ctx context.Context, request PutClusterUpgradeStopRequest) (PutClusterUpgradeStopResponse, error) {
	path := map[string]string{}
	query := url.Values{}
	var body any
	body = nil
	var response PutClusterUpgradeStopResponse
	err := c.doJSON(ctx, http.MethodPut, "/api/cluster/upgrade/stop", path, query, body, true, &response)
	return response, err
}

// GetClusterUser calls GET /api/cluster/user with typed request and response values.
func (c *Client) GetClusterUser(ctx context.Context, request GetClusterUserRequest) (GetClusterUserResponse, error) {
	path := map[string]string{}
	query := url.Values{}
	var body any
	body = nil
	var response GetClusterUserResponse
	err := c.doJSON(ctx, http.MethodGet, "/api/cluster/user", path, query, body, true, &response)
	return response, err
}

// PostClusterUser calls POST /api/cluster/user with typed request and response values.
func (c *Client) PostClusterUser(ctx context.Context, request PostClusterUserRequest) (PostClusterUserResponse, error) {
	path := map[string]string{}
	query := url.Values{}
	var body any
	body = nil
	body = request.Body
	var response PostClusterUserResponse
	err := c.doJSON(ctx, http.MethodPost, "/api/cluster/user", path, query, body, true, &response)
	return response, err
}

// PutClusterUser calls PUT /api/cluster/user with typed request and response values.
func (c *Client) PutClusterUser(ctx context.Context, request PutClusterUserRequest) (PutClusterUserResponse, error) {
	path := map[string]string{}
	query := url.Values{}
	var body any
	body = nil
	body = request.Body
	var response PutClusterUserResponse
	err := c.doJSON(ctx, http.MethodPut, "/api/cluster/user", path, query, body, true, &response)
	return response, err
}

// PostClusterUserExport calls POST /api/cluster/user/export with typed request and response values.
func (c *Client) PostClusterUserExport(ctx context.Context, request PostClusterUserExportRequest) (PostClusterUserExportResponse, error) {
	path := map[string]string{}
	query := url.Values{}
	var body any
	body = nil
	body = request.Body
	var response PostClusterUserExportResponse
	err := c.doJSON(ctx, http.MethodPost, "/api/cluster/user/export", path, query, body, true, &response)
	return response, err
}

// DeleteClusterUserByUserEntities calls DELETE /api/cluster/user/{user_entities} with typed request and response values.
func (c *Client) DeleteClusterUserByUserEntities(ctx context.Context, request DeleteClusterUserByUserEntitiesRequest) (DeleteClusterUserByUserEntitiesResponse, error) {
	path := map[string]string{
		"user_entities": request.UserEntities,
	}
	query := url.Values{}
	var body any
	body = nil
	var response DeleteClusterUserByUserEntitiesResponse
	err := c.doJSON(ctx, http.MethodDelete, "/api/cluster/user/{user_entities}", path, query, body, true, &response)
	return response, err
}
