// Code generated by tools/generate_ceph_dashboard_client.rb; DO NOT EDIT.

package typed

import (
	"context"
	"encoding/json"
	"net/http"
	"net/url"
)

// daemon typed endpoints from docs/references/ceph/src/pybind/mgr/dashboard/openapi.yaml.

type GetDaemonResponse map[string]json.RawMessage

type GetDaemonRequest struct {
	DaemonTypes *string `query:"daemon_types"`
}

type PutDaemonByDaemonNameBody struct {
	Action         string `json:"action,omitempty"`
	ContainerImage string `json:"container_image,omitempty"`
	Force          bool   `json:"force,omitempty"`
}

type PutDaemonByDaemonNameResponse map[string]json.RawMessage

type PutDaemonByDaemonNameRequest struct {
	DaemonName string                    `path:"daemon_name"`
	Body       PutDaemonByDaemonNameBody `json:"-"`
}

// GetDaemon calls GET /api/daemon with typed request and response values.
func (c *Client) GetDaemon(ctx context.Context, request GetDaemonRequest) (GetDaemonResponse, error) {
	path := map[string]string{}
	query := url.Values{}
	if request.DaemonTypes != nil {
		query.Set("daemon_types", *request.DaemonTypes)
	}
	var body any
	body = nil
	var response GetDaemonResponse
	err := c.doJSON(ctx, http.MethodGet, "/api/daemon", path, query, body, true, &response)
	return response, err
}

// PutDaemonByDaemonName calls PUT /api/daemon/{daemon_name} with typed request and response values.
func (c *Client) PutDaemonByDaemonName(ctx context.Context, request PutDaemonByDaemonNameRequest) (PutDaemonByDaemonNameResponse, error) {
	path := map[string]string{
		"daemon_name": request.DaemonName,
	}
	query := url.Values{}
	var body any
	body = nil
	body = request.Body
	var response PutDaemonByDaemonNameResponse
	err := c.doJSON(ctx, http.MethodPut, "/api/daemon/{daemon_name}", path, query, body, true, &response)
	return response, err
}
