// Code generated by tools/generate_ceph_dashboard_client.rb; DO NOT EDIT.

package typed

import (
	"context"
	"encoding/json"
	"net/http"
	"net/url"
)

// grafana typed endpoints from docs/references/ceph/src/pybind/mgr/dashboard/openapi.yaml.

type PostGrafanaDashboardsResponse map[string]json.RawMessage

type PostGrafanaDashboardsRequest struct{}

type GetGrafanaUrlResponse struct {
	Instance string `json:"instance"`
}

type GetGrafanaUrlRequest struct{}

type GetGrafanaValidationByParamsResponse map[string]json.RawMessage

type GetGrafanaValidationByParamsRequest struct {
	Params string `path:"params"`
}

// PostGrafanaDashboards calls POST /api/grafana/dashboards with typed request and response values.
func (c *Client) PostGrafanaDashboards(ctx context.Context, request PostGrafanaDashboardsRequest) (PostGrafanaDashboardsResponse, error) {
	path := map[string]string{}
	query := url.Values{}
	var body any
	body = nil
	var response PostGrafanaDashboardsResponse
	err := c.doJSON(ctx, http.MethodPost, "/api/grafana/dashboards", path, query, body, true, &response)
	return response, err
}

// GetGrafanaUrl calls GET /api/grafana/url with typed request and response values.
func (c *Client) GetGrafanaUrl(ctx context.Context, request GetGrafanaUrlRequest) (GetGrafanaUrlResponse, error) {
	path := map[string]string{}
	query := url.Values{}
	var body any
	body = nil
	var response GetGrafanaUrlResponse
	err := c.doJSON(ctx, http.MethodGet, "/api/grafana/url", path, query, body, true, &response)
	return response, err
}

// GetGrafanaValidationByParams calls GET /api/grafana/validation/{params} with typed request and response values.
func (c *Client) GetGrafanaValidationByParams(ctx context.Context, request GetGrafanaValidationByParamsRequest) (GetGrafanaValidationByParamsResponse, error) {
	path := map[string]string{
		"params": request.Params,
	}
	query := url.Values{}
	var body any
	body = nil
	var response GetGrafanaValidationByParamsResponse
	err := c.doJSON(ctx, http.MethodGet, "/api/grafana/validation/{params}", path, query, body, true, &response)
	return response, err
}
