// Code generated by tools/generate_ceph_dashboard_client.rb; DO NOT EDIT.

package typed

import (
	"context"
	"encoding/json"
	"net/http"
	"net/url"
	"strconv"
)

// host typed endpoints from docs/references/ceph/src/pybind/mgr/dashboard/openapi.yaml.

type GetHostResponseServiceInstancesItem struct {
	Count     int    `json:"count"`
	TypeValue string `json:"type"`
}

type GetHostResponseServicesItem struct {
	Id        string `json:"id"`
	TypeValue string `json:"type"`
}

type GetHostResponseSources struct {
	Ceph         bool `json:"ceph"`
	Orchestrator bool `json:"orchestrator"`
}

type GetHostResponse struct {
	Addr             string                                `json:"addr"`
	CephVersion      string                                `json:"ceph_version"`
	Hostname         string                                `json:"hostname"`
	Labels           []string                              `json:"labels"`
	ServiceInstances []GetHostResponseServiceInstancesItem `json:"service_instances"`
	ServiceType      string                                `json:"service_type"`
	Services         []GetHostResponseServicesItem         `json:"services"`
	Sources          GetHostResponseSources                `json:"sources"`
	Status           string                                `json:"status"`
}

type GetHostRequest struct {
	Sources                 *string `query:"sources"`
	Facts                   *bool   `query:"facts"`
	Offset                  *int    `query:"offset"`
	Limit                   *int    `query:"limit"`
	Search                  *string `query:"search"`
	Sort                    *string `query:"sort"`
	IncludeServiceInstances *bool   `query:"include_service_instances"`
}

type PostHostBody struct {
	Addr     string   `json:"addr,omitempty"`
	Hostname string   `json:"hostname"`
	Labels   []string `json:"labels,omitempty"`
	Status   string   `json:"status,omitempty"`
}

type PostHostResponse map[string]json.RawMessage

type PostHostRequest struct {
	Body PostHostBody `json:"-"`
}

type DeleteHostByHostnameResponse map[string]json.RawMessage

type DeleteHostByHostnameRequest struct {
	Hostname string `path:"hostname"`
}

type GetHostByHostnameResponse map[string]json.RawMessage

type GetHostByHostnameRequest struct {
	Hostname string `path:"hostname"`
}

type PutHostByHostnameBody struct {
	Drain        bool     `json:"drain,omitempty"`
	Force        bool     `json:"force,omitempty"`
	Labels       []string `json:"labels,omitempty"`
	Maintenance  bool     `json:"maintenance,omitempty"`
	UpdateLabels bool     `json:"update_labels,omitempty"`
}

type PutHostByHostnameResponse map[string]json.RawMessage

type PutHostByHostnameRequest struct {
	Hostname string                `path:"hostname"`
	Body     PutHostByHostnameBody `json:"-"`
}

type GetHostByHostnameDaemonsResponse map[string]json.RawMessage

type GetHostByHostnameDaemonsRequest struct {
	Hostname string `path:"hostname"`
}

type GetHostByHostnameDevicesResponse map[string]json.RawMessage

type GetHostByHostnameDevicesRequest struct {
	Hostname string `path:"hostname"`
}

type PostHostByHostnameIdentifyDeviceBody struct {
	Device   string `json:"device"`
	Duration string `json:"duration"`
}

type PostHostByHostnameIdentifyDeviceResponse map[string]json.RawMessage

type PostHostByHostnameIdentifyDeviceRequest struct {
	Hostname string                               `path:"hostname"`
	Body     PostHostByHostnameIdentifyDeviceBody `json:"-"`
}

type GetHostByHostnameInventoryResponseDevicesItemLsmDataLedSupport struct {
	FAILstatus   string `json:"FAILstatus"`
	FAILsupport  string `json:"FAILsupport"`
	IDENTstatus  string `json:"IDENTstatus"`
	IDENTsupport string `json:"IDENTsupport"`
}

type GetHostByHostnameInventoryResponseDevicesItemLsmData struct {
	Errors     []string                                                       `json:"errors"`
	Health     string                                                         `json:"health"`
	LedSupport GetHostByHostnameInventoryResponseDevicesItemLsmDataLedSupport `json:"ledSupport"`
	LinkSpeed  string                                                         `json:"linkSpeed"`
	MediaType  string                                                         `json:"mediaType"`
	Rpm        string                                                         `json:"rpm"`
	SerialNum  string                                                         `json:"serialNum"`
	Transport  string                                                         `json:"transport"`
}

type GetHostByHostnameInventoryResponseDevicesItemLvsItem struct {
	BlockUuid       string `json:"block_uuid"`
	ClusterFsid     string `json:"cluster_fsid"`
	ClusterName     string `json:"cluster_name"`
	Name            string `json:"name"`
	OsdFsid         string `json:"osd_fsid"`
	OsdId           string `json:"osd_id"`
	OsdspecAffinity string `json:"osdspec_affinity"`
	TypeValue       string `json:"type"`
}

type GetHostByHostnameInventoryResponseDevicesItemSysApiPartitionsPartitionName struct {
	Holders           []string `json:"holders"`
	HumanReadableSize string   `json:"human_readable_size"`
	Sectors           string   `json:"sectors"`
	Sectorsize        int      `json:"sectorsize"`
	Size              int      `json:"size"`
	Start             string   `json:"start"`
}

type GetHostByHostnameInventoryResponseDevicesItemSysApiPartitions struct {
	PartitionName GetHostByHostnameInventoryResponseDevicesItemSysApiPartitionsPartitionName `json:"partition_name"`
}

type GetHostByHostnameInventoryResponseDevicesItemSysApi struct {
	HumanReadableSize string                                                        `json:"human_readable_size"`
	Locked            int                                                           `json:"locked"`
	Model             string                                                        `json:"model"`
	NrRequests        string                                                        `json:"nr_requests"`
	Partitions        GetHostByHostnameInventoryResponseDevicesItemSysApiPartitions `json:"partitions"`
	Path              string                                                        `json:"path"`
	Removable         string                                                        `json:"removable"`
	Rev               string                                                        `json:"rev"`
	Ro                string                                                        `json:"ro"`
	Rotational        string                                                        `json:"rotational"`
	SasAddress        string                                                        `json:"sas_address"`
	SasDeviceHandle   string                                                        `json:"sas_device_handle"`
	SchedulerMode     string                                                        `json:"scheduler_mode"`
	Sectors           int                                                           `json:"sectors"`
	Sectorsize        string                                                        `json:"sectorsize"`
	Size              int                                                           `json:"size"`
	SupportDiscard    string                                                        `json:"support_discard"`
	Vendor            string                                                        `json:"vendor"`
}

type GetHostByHostnameInventoryResponseDevicesItem struct {
	Available         bool                                                   `json:"available"`
	DeviceId          string                                                 `json:"device_id"`
	HumanReadableType string                                                 `json:"human_readable_type"`
	LsmData           GetHostByHostnameInventoryResponseDevicesItemLsmData   `json:"lsm_data"`
	Lvs               []GetHostByHostnameInventoryResponseDevicesItemLvsItem `json:"lvs"`
	OsdIds            []int                                                  `json:"osd_ids"`
	Path              string                                                 `json:"path"`
	RejectedReasons   []string                                               `json:"rejected_reasons"`
	SysApi            GetHostByHostnameInventoryResponseDevicesItemSysApi    `json:"sys_api"`
}

type GetHostByHostnameInventoryResponse struct {
	Addr    string                                          `json:"addr"`
	Devices []GetHostByHostnameInventoryResponseDevicesItem `json:"devices"`
	Labels  []string                                        `json:"labels"`
	Name    string                                          `json:"name"`
}

type GetHostByHostnameInventoryRequest struct {
	Hostname string  `path:"hostname"`
	Refresh  *string `query:"refresh"`
}

type GetHostByHostnameSmartResponse map[string]json.RawMessage

type GetHostByHostnameSmartRequest struct {
	Hostname string `path:"hostname"`
}

// GetHost calls GET /api/host with typed request and response values.
func (c *Client) GetHost(ctx context.Context, request GetHostRequest) (GetHostResponse, error) {
	path := map[string]string{}
	query := url.Values{}
	if request.Sources != nil {
		query.Set("sources", *request.Sources)
	}
	if request.Facts != nil {
		query.Set("facts", strconv.FormatBool(*request.Facts))
	}
	if request.Offset != nil {
		query.Set("offset", strconv.Itoa(*request.Offset))
	}
	if request.Limit != nil {
		query.Set("limit", strconv.Itoa(*request.Limit))
	}
	if request.Search != nil {
		query.Set("search", *request.Search)
	}
	if request.Sort != nil {
		query.Set("sort", *request.Sort)
	}
	if request.IncludeServiceInstances != nil {
		query.Set("include_service_instances", strconv.FormatBool(*request.IncludeServiceInstances))
	}
	var body any
	body = nil
	var response GetHostResponse
	err := c.doJSON(ctx, http.MethodGet, "/api/host", path, query, body, true, &response)
	return response, err
}

// PostHost calls POST /api/host with typed request and response values.
func (c *Client) PostHost(ctx context.Context, request PostHostRequest) (PostHostResponse, error) {
	path := map[string]string{}
	query := url.Values{}
	var body any
	body = nil
	body = request.Body
	var response PostHostResponse
	err := c.doJSON(ctx, http.MethodPost, "/api/host", path, query, body, true, &response)
	return response, err
}

// DeleteHostByHostname calls DELETE /api/host/{hostname} with typed request and response values.
func (c *Client) DeleteHostByHostname(ctx context.Context, request DeleteHostByHostnameRequest) (DeleteHostByHostnameResponse, error) {
	path := map[string]string{
		"hostname": request.Hostname,
	}
	query := url.Values{}
	var body any
	body = nil
	var response DeleteHostByHostnameResponse
	err := c.doJSON(ctx, http.MethodDelete, "/api/host/{hostname}", path, query, body, true, &response)
	return response, err
}

// GetHostByHostname calls GET /api/host/{hostname} with typed request and response values.
func (c *Client) GetHostByHostname(ctx context.Context, request GetHostByHostnameRequest) (GetHostByHostnameResponse, error) {
	path := map[string]string{
		"hostname": request.Hostname,
	}
	query := url.Values{}
	var body any
	body = nil
	var response GetHostByHostnameResponse
	err := c.doJSON(ctx, http.MethodGet, "/api/host/{hostname}", path, query, body, true, &response)
	return response, err
}

// PutHostByHostname calls PUT /api/host/{hostname} with typed request and response values.
func (c *Client) PutHostByHostname(ctx context.Context, request PutHostByHostnameRequest) (PutHostByHostnameResponse, error) {
	path := map[string]string{
		"hostname": request.Hostname,
	}
	query := url.Values{}
	var body any
	body = nil
	body = request.Body
	var response PutHostByHostnameResponse
	err := c.doJSON(ctx, http.MethodPut, "/api/host/{hostname}", path, query, body, true, &response)
	return response, err
}

// GetHostByHostnameDaemons calls GET /api/host/{hostname}/daemons with typed request and response values.
func (c *Client) GetHostByHostnameDaemons(ctx context.Context, request GetHostByHostnameDaemonsRequest) (GetHostByHostnameDaemonsResponse, error) {
	path := map[string]string{
		"hostname": request.Hostname,
	}
	query := url.Values{}
	var body any
	body = nil
	var response GetHostByHostnameDaemonsResponse
	err := c.doJSON(ctx, http.MethodGet, "/api/host/{hostname}/daemons", path, query, body, true, &response)
	return response, err
}

// GetHostByHostnameDevices calls GET /api/host/{hostname}/devices with typed request and response values.
func (c *Client) GetHostByHostnameDevices(ctx context.Context, request GetHostByHostnameDevicesRequest) (GetHostByHostnameDevicesResponse, error) {
	path := map[string]string{
		"hostname": request.Hostname,
	}
	query := url.Values{}
	var body any
	body = nil
	var response GetHostByHostnameDevicesResponse
	err := c.doJSON(ctx, http.MethodGet, "/api/host/{hostname}/devices", path, query, body, true, &response)
	return response, err
}

// PostHostByHostnameIdentifyDevice calls POST /api/host/{hostname}/identify_device with typed request and response values.
func (c *Client) PostHostByHostnameIdentifyDevice(ctx context.Context, request PostHostByHostnameIdentifyDeviceRequest) (PostHostByHostnameIdentifyDeviceResponse, error) {
	path := map[string]string{
		"hostname": request.Hostname,
	}
	query := url.Values{}
	var body any
	body = nil
	body = request.Body
	var response PostHostByHostnameIdentifyDeviceResponse
	err := c.doJSON(ctx, http.MethodPost, "/api/host/{hostname}/identify_device", path, query, body, true, &response)
	return response, err
}

// GetHostByHostnameInventory calls GET /api/host/{hostname}/inventory with typed request and response values.
func (c *Client) GetHostByHostnameInventory(ctx context.Context, request GetHostByHostnameInventoryRequest) (GetHostByHostnameInventoryResponse, error) {
	path := map[string]string{
		"hostname": request.Hostname,
	}
	query := url.Values{}
	if request.Refresh != nil {
		query.Set("refresh", *request.Refresh)
	}
	var body any
	body = nil
	var response GetHostByHostnameInventoryResponse
	err := c.doJSON(ctx, http.MethodGet, "/api/host/{hostname}/inventory", path, query, body, true, &response)
	return response, err
}

// GetHostByHostnameSmart calls GET /api/host/{hostname}/smart with typed request and response values.
func (c *Client) GetHostByHostnameSmart(ctx context.Context, request GetHostByHostnameSmartRequest) (GetHostByHostnameSmartResponse, error) {
	path := map[string]string{
		"hostname": request.Hostname,
	}
	query := url.Values{}
	var body any
	body = nil
	var response GetHostByHostnameSmartResponse
	err := c.doJSON(ctx, http.MethodGet, "/api/host/{hostname}/smart", path, query, body, true, &response)
	return response, err
}
