// Code generated by tools/generate_ceph_dashboard_client.rb; DO NOT EDIT.

package typed

import (
	"context"
	"encoding/json"
	"net/http"
	"net/url"
)

// iscsi typed endpoints from docs/references/ceph/src/pybind/mgr/dashboard/openapi.yaml.

type GetIscsiDiscoveryauthResponseItem struct {
	MutualPassword string `json:"mutual_password,omitempty"`
	MutualUser     string `json:"mutual_user,omitempty"`
	Password       string `json:"password,omitempty"`
	User           string `json:"user,omitempty"`
}

type GetIscsiDiscoveryauthResponse []GetIscsiDiscoveryauthResponseItem

type GetIscsiDiscoveryauthRequest struct{}

type PutIscsiDiscoveryauthBody struct {
	MutualPassword string `json:"mutual_password"`
	MutualUser     string `json:"mutual_user"`
	Password       string `json:"password"`
	User           string `json:"user"`
}

type PutIscsiDiscoveryauthResponse map[string]json.RawMessage

type PutIscsiDiscoveryauthRequest struct {
	User           string                    `query:"user"`
	Password       string                    `query:"password"`
	MutualUser     string                    `query:"mutual_user"`
	MutualPassword string                    `query:"mutual_password"`
	Body           PutIscsiDiscoveryauthBody `json:"-"`
}

type GetIscsiTargetResponse map[string]json.RawMessage

type GetIscsiTargetRequest struct{}

type PostIscsiTargetBody struct {
	AclEnabled     string `json:"acl_enabled,omitempty"`
	Auth           string `json:"auth,omitempty"`
	Clients        string `json:"clients,omitempty"`
	Disks          string `json:"disks,omitempty"`
	Groups         string `json:"groups,omitempty"`
	Portals        string `json:"portals,omitempty"`
	TargetControls string `json:"target_controls,omitempty"`
	TargetIqn      string `json:"target_iqn,omitempty"`
}

type PostIscsiTargetResponse map[string]json.RawMessage

type PostIscsiTargetRequest struct {
	Body PostIscsiTargetBody `json:"-"`
}

type DeleteIscsiTargetByTargetIqnResponse map[string]json.RawMessage

type DeleteIscsiTargetByTargetIqnRequest struct {
	TargetIqn string `path:"target_iqn"`
}

type GetIscsiTargetByTargetIqnResponse map[string]json.RawMessage

type GetIscsiTargetByTargetIqnRequest struct {
	TargetIqn string `path:"target_iqn"`
}

type PutIscsiTargetByTargetIqnBody struct {
	AclEnabled     string `json:"acl_enabled,omitempty"`
	Auth           string `json:"auth,omitempty"`
	Clients        string `json:"clients,omitempty"`
	Disks          string `json:"disks,omitempty"`
	Groups         string `json:"groups,omitempty"`
	NewTargetIqn   string `json:"new_target_iqn,omitempty"`
	Portals        string `json:"portals,omitempty"`
	TargetControls string `json:"target_controls,omitempty"`
}

type PutIscsiTargetByTargetIqnResponse map[string]json.RawMessage

type PutIscsiTargetByTargetIqnRequest struct {
	TargetIqn string                        `path:"target_iqn"`
	Body      PutIscsiTargetByTargetIqnBody `json:"-"`
}

// GetIscsiDiscoveryauth calls GET /api/iscsi/discoveryauth with typed request and response values.
func (c *Client) GetIscsiDiscoveryauth(ctx context.Context, request GetIscsiDiscoveryauthRequest) (GetIscsiDiscoveryauthResponse, error) {
	path := map[string]string{}
	query := url.Values{}
	var body any
	body = nil
	var response GetIscsiDiscoveryauthResponse
	err := c.doJSON(ctx, http.MethodGet, "/api/iscsi/discoveryauth", path, query, body, true, &response)
	return response, err
}

// PutIscsiDiscoveryauth calls PUT /api/iscsi/discoveryauth with typed request and response values.
func (c *Client) PutIscsiDiscoveryauth(ctx context.Context, request PutIscsiDiscoveryauthRequest) (PutIscsiDiscoveryauthResponse, error) {
	path := map[string]string{}
	query := url.Values{}
	query.Set("user", request.User)
	query.Set("password", request.Password)
	query.Set("mutual_user", request.MutualUser)
	query.Set("mutual_password", request.MutualPassword)
	var body any
	body = nil
	body = request.Body
	var response PutIscsiDiscoveryauthResponse
	err := c.doJSON(ctx, http.MethodPut, "/api/iscsi/discoveryauth", path, query, body, true, &response)
	return response, err
}

// GetIscsiTarget calls GET /api/iscsi/target with typed request and response values.
func (c *Client) GetIscsiTarget(ctx context.Context, request GetIscsiTargetRequest) (GetIscsiTargetResponse, error) {
	path := map[string]string{}
	query := url.Values{}
	var body any
	body = nil
	var response GetIscsiTargetResponse
	err := c.doJSON(ctx, http.MethodGet, "/api/iscsi/target", path, query, body, true, &response)
	return response, err
}

// PostIscsiTarget calls POST /api/iscsi/target with typed request and response values.
func (c *Client) PostIscsiTarget(ctx context.Context, request PostIscsiTargetRequest) (PostIscsiTargetResponse, error) {
	path := map[string]string{}
	query := url.Values{}
	var body any
	body = nil
	body = request.Body
	var response PostIscsiTargetResponse
	err := c.doJSON(ctx, http.MethodPost, "/api/iscsi/target", path, query, body, true, &response)
	return response, err
}

// DeleteIscsiTargetByTargetIqn calls DELETE /api/iscsi/target/{target_iqn} with typed request and response values.
func (c *Client) DeleteIscsiTargetByTargetIqn(ctx context.Context, request DeleteIscsiTargetByTargetIqnRequest) (DeleteIscsiTargetByTargetIqnResponse, error) {
	path := map[string]string{
		"target_iqn": request.TargetIqn,
	}
	query := url.Values{}
	var body any
	body = nil
	var response DeleteIscsiTargetByTargetIqnResponse
	err := c.doJSON(ctx, http.MethodDelete, "/api/iscsi/target/{target_iqn}", path, query, body, true, &response)
	return response, err
}

// GetIscsiTargetByTargetIqn calls GET /api/iscsi/target/{target_iqn} with typed request and response values.
func (c *Client) GetIscsiTargetByTargetIqn(ctx context.Context, request GetIscsiTargetByTargetIqnRequest) (GetIscsiTargetByTargetIqnResponse, error) {
	path := map[string]string{
		"target_iqn": request.TargetIqn,
	}
	query := url.Values{}
	var body any
	body = nil
	var response GetIscsiTargetByTargetIqnResponse
	err := c.doJSON(ctx, http.MethodGet, "/api/iscsi/target/{target_iqn}", path, query, body, true, &response)
	return response, err
}

// PutIscsiTargetByTargetIqn calls PUT /api/iscsi/target/{target_iqn} with typed request and response values.
func (c *Client) PutIscsiTargetByTargetIqn(ctx context.Context, request PutIscsiTargetByTargetIqnRequest) (PutIscsiTargetByTargetIqnResponse, error) {
	path := map[string]string{
		"target_iqn": request.TargetIqn,
	}
	query := url.Values{}
	var body any
	body = nil
	body = request.Body
	var response PutIscsiTargetByTargetIqnResponse
	err := c.doJSON(ctx, http.MethodPut, "/api/iscsi/target/{target_iqn}", path, query, body, true, &response)
	return response, err
}
