// Code generated by tools/generate_ceph_dashboard_client.rb; DO NOT EDIT.

package typed

import (
	"context"
	"encoding/json"
	"net/http"
	"net/url"
	"strconv"
)

// osd typed endpoints from docs/references/ceph/src/pybind/mgr/dashboard/openapi.yaml.

type GetOsdResponse map[string]json.RawMessage

type GetOsdRequest struct {
	Offset *int    `query:"offset"`
	Limit  *int    `query:"limit"`
	Search *string `query:"search"`
	Sort   *string `query:"sort"`
}

type PostOsdBody struct {
	Data       string `json:"data"`
	Method     string `json:"method"`
	TrackingId string `json:"tracking_id"`
}

type PostOsdResponse map[string]json.RawMessage

type PostOsdRequest struct {
	Body PostOsdBody `json:"-"`
}

type GetOsdFlagsResponse struct {
	ListOfFlags []string `json:"list_of_flags"`
}

type GetOsdFlagsRequest struct{}

type PutOsdFlagsBody struct {
	Flags []string `json:"flags"`
}

type PutOsdFlagsResponse struct {
	ListOfFlags []string `json:"list_of_flags"`
}

type PutOsdFlagsRequest struct {
	Body PutOsdFlagsBody `json:"-"`
}

type GetOsdFlagsIndividualResponse struct {
	Flags []string `json:"flags"`
	Osd   int      `json:"osd"`
}

type GetOsdFlagsIndividualRequest struct{}

type PutOsdFlagsIndividualBodyFlags struct {
	Nodown bool `json:"nodown,omitempty"`
	Noin   bool `json:"noin,omitempty"`
	Noout  bool `json:"noout,omitempty"`
	Noup   bool `json:"noup,omitempty"`
}

type PutOsdFlagsIndividualBody struct {
	Flags PutOsdFlagsIndividualBodyFlags `json:"flags"`
	Ids   []int                          `json:"ids"`
}

type PutOsdFlagsIndividualResponse struct {
	Added   []string `json:"added"`
	Ids     []int    `json:"ids"`
	Removed []string `json:"removed"`
}

type PutOsdFlagsIndividualRequest struct {
	Body PutOsdFlagsIndividualBody `json:"-"`
}

type GetOsdSafeToDeleteResponse map[string]json.RawMessage

type GetOsdSafeToDeleteRequest struct {
	SvcIds string `query:"svc_ids"`
}

type GetOsdSafeToDestroyResponse struct {
	Active          []int    `json:"active"`
	IsSafeToDestroy bool     `json:"is_safe_to_destroy"`
	MissingStats    []string `json:"missing_stats"`
	SafeToDestroy   []string `json:"safe_to_destroy"`
	StoredPgs       []string `json:"stored_pgs"`
}

type GetOsdSafeToDestroyRequest struct {
	Ids string `query:"ids"`
}

type GetOsdSettingsResponse map[string]json.RawMessage

type GetOsdSettingsRequest struct{}

type DeleteOsdBySvcIdResponse map[string]json.RawMessage

type DeleteOsdBySvcIdRequest struct {
	SvcId      string  `path:"svc_id"`
	PreserveId *string `query:"preserve_id"`
	Force      *string `query:"force"`
}

type GetOsdBySvcIdResponse map[string]json.RawMessage

type GetOsdBySvcIdRequest struct {
	SvcId string `path:"svc_id"`
}

type PutOsdBySvcIdBody struct {
	DeviceClass string `json:"device_class"`
}

type PutOsdBySvcIdResponse map[string]json.RawMessage

type PutOsdBySvcIdRequest struct {
	SvcId string            `path:"svc_id"`
	Body  PutOsdBySvcIdBody `json:"-"`
}

type PostOsdBySvcIdDestroyResponse map[string]json.RawMessage

type PostOsdBySvcIdDestroyRequest struct {
	SvcId string `path:"svc_id"`
}

type GetOsdBySvcIdDevicesResponse map[string]json.RawMessage

type GetOsdBySvcIdDevicesRequest struct {
	SvcId string `path:"svc_id"`
}

type GetOsdBySvcIdHistogramResponse map[string]json.RawMessage

type GetOsdBySvcIdHistogramRequest struct {
	SvcId string `path:"svc_id"`
}

type PutOsdBySvcIdMarkBody struct {
	Action string `json:"action"`
}

type PutOsdBySvcIdMarkResponse map[string]json.RawMessage

type PutOsdBySvcIdMarkRequest struct {
	SvcId string                `path:"svc_id"`
	Body  PutOsdBySvcIdMarkBody `json:"-"`
}

type PostOsdBySvcIdPurgeResponse map[string]json.RawMessage

type PostOsdBySvcIdPurgeRequest struct {
	SvcId string `path:"svc_id"`
}

type PostOsdBySvcIdReweightBody struct {
	Weight string `json:"weight"`
}

type PostOsdBySvcIdReweightResponse map[string]json.RawMessage

type PostOsdBySvcIdReweightRequest struct {
	SvcId string                     `path:"svc_id"`
	Body  PostOsdBySvcIdReweightBody `json:"-"`
}

type PostOsdBySvcIdScrubBody struct {
	Deep bool `json:"deep,omitempty"`
}

type PostOsdBySvcIdScrubResponse map[string]json.RawMessage

type PostOsdBySvcIdScrubRequest struct {
	SvcId string                  `path:"svc_id"`
	Deep  *bool                   `query:"deep"`
	Body  PostOsdBySvcIdScrubBody `json:"-"`
}

type GetOsdBySvcIdSmartResponse map[string]json.RawMessage

type GetOsdBySvcIdSmartRequest struct {
	SvcId string `path:"svc_id"`
}

// GetOsd calls GET /api/osd with typed request and response values.
func (c *Client) GetOsd(ctx context.Context, request GetOsdRequest) (GetOsdResponse, error) {
	path := map[string]string{}
	query := url.Values{}
	if request.Offset != nil {
		query.Set("offset", strconv.Itoa(*request.Offset))
	}
	if request.Limit != nil {
		query.Set("limit", strconv.Itoa(*request.Limit))
	}
	if request.Search != nil {
		query.Set("search", *request.Search)
	}
	if request.Sort != nil {
		query.Set("sort", *request.Sort)
	}
	var body any
	body = nil
	var response GetOsdResponse
	err := c.doJSON(ctx, http.MethodGet, "/api/osd", path, query, body, true, &response)
	return response, err
}

// PostOsd calls POST /api/osd with typed request and response values.
func (c *Client) PostOsd(ctx context.Context, request PostOsdRequest) (PostOsdResponse, error) {
	path := map[string]string{}
	query := url.Values{}
	var body any
	body = nil
	body = request.Body
	var response PostOsdResponse
	err := c.doJSON(ctx, http.MethodPost, "/api/osd", path, query, body, true, &response)
	return response, err
}

// GetOsdFlags calls GET /api/osd/flags with typed request and response values.
func (c *Client) GetOsdFlags(ctx context.Context, request GetOsdFlagsRequest) (GetOsdFlagsResponse, error) {
	path := map[string]string{}
	query := url.Values{}
	var body any
	body = nil
	var response GetOsdFlagsResponse
	err := c.doJSON(ctx, http.MethodGet, "/api/osd/flags", path, query, body, true, &response)
	return response, err
}

// PutOsdFlags calls PUT /api/osd/flags with typed request and response values.
func (c *Client) PutOsdFlags(ctx context.Context, request PutOsdFlagsRequest) (PutOsdFlagsResponse, error) {
	path := map[string]string{}
	query := url.Values{}
	var body any
	body = nil
	body = request.Body
	var response PutOsdFlagsResponse
	err := c.doJSON(ctx, http.MethodPut, "/api/osd/flags", path, query, body, true, &response)
	return response, err
}

// GetOsdFlagsIndividual calls GET /api/osd/flags/individual with typed request and response values.
func (c *Client) GetOsdFlagsIndividual(ctx context.Context, request GetOsdFlagsIndividualRequest) (GetOsdFlagsIndividualResponse, error) {
	path := map[string]string{}
	query := url.Values{}
	var body any
	body = nil
	var response GetOsdFlagsIndividualResponse
	err := c.doJSON(ctx, http.MethodGet, "/api/osd/flags/individual", path, query, body, true, &response)
	return response, err
}

// PutOsdFlagsIndividual calls PUT /api/osd/flags/individual with typed request and response values.
func (c *Client) PutOsdFlagsIndividual(ctx context.Context, request PutOsdFlagsIndividualRequest) (PutOsdFlagsIndividualResponse, error) {
	path := map[string]string{}
	query := url.Values{}
	var body any
	body = nil
	body = request.Body
	var response PutOsdFlagsIndividualResponse
	err := c.doJSON(ctx, http.MethodPut, "/api/osd/flags/individual", path, query, body, true, &response)
	return response, err
}

// GetOsdSafeToDelete calls GET /api/osd/safe_to_delete with typed request and response values.
func (c *Client) GetOsdSafeToDelete(ctx context.Context, request GetOsdSafeToDeleteRequest) (GetOsdSafeToDeleteResponse, error) {
	path := map[string]string{}
	query := url.Values{}
	query.Set("svc_ids", request.SvcIds)
	var body any
	body = nil
	var response GetOsdSafeToDeleteResponse
	err := c.doJSON(ctx, http.MethodGet, "/api/osd/safe_to_delete", path, query, body, true, &response)
	return response, err
}

// GetOsdSafeToDestroy calls GET /api/osd/safe_to_destroy with typed request and response values.
func (c *Client) GetOsdSafeToDestroy(ctx context.Context, request GetOsdSafeToDestroyRequest) (GetOsdSafeToDestroyResponse, error) {
	path := map[string]string{}
	query := url.Values{}
	query.Set("ids", request.Ids)
	var body any
	body = nil
	var response GetOsdSafeToDestroyResponse
	err := c.doJSON(ctx, http.MethodGet, "/api/osd/safe_to_destroy", path, query, body, true, &response)
	return response, err
}

// GetOsdSettings calls GET /api/osd/settings with typed request and response values.
func (c *Client) GetOsdSettings(ctx context.Context, request GetOsdSettingsRequest) (GetOsdSettingsResponse, error) {
	path := map[string]string{}
	query := url.Values{}
	var body any
	body = nil
	var response GetOsdSettingsResponse
	err := c.doJSON(ctx, http.MethodGet, "/api/osd/settings", path, query, body, true, &response)
	return response, err
}

// DeleteOsdBySvcId calls DELETE /api/osd/{svc_id} with typed request and response values.
func (c *Client) DeleteOsdBySvcId(ctx context.Context, request DeleteOsdBySvcIdRequest) (DeleteOsdBySvcIdResponse, error) {
	path := map[string]string{
		"svc_id": request.SvcId,
	}
	query := url.Values{}
	if request.PreserveId != nil {
		query.Set("preserve_id", *request.PreserveId)
	}
	if request.Force != nil {
		query.Set("force", *request.Force)
	}
	var body any
	body = nil
	var response DeleteOsdBySvcIdResponse
	err := c.doJSON(ctx, http.MethodDelete, "/api/osd/{svc_id}", path, query, body, true, &response)
	return response, err
}

// GetOsdBySvcId calls GET /api/osd/{svc_id} with typed request and response values.
func (c *Client) GetOsdBySvcId(ctx context.Context, request GetOsdBySvcIdRequest) (GetOsdBySvcIdResponse, error) {
	path := map[string]string{
		"svc_id": request.SvcId,
	}
	query := url.Values{}
	var body any
	body = nil
	var response GetOsdBySvcIdResponse
	err := c.doJSON(ctx, http.MethodGet, "/api/osd/{svc_id}", path, query, body, true, &response)
	return response, err
}

// PutOsdBySvcId calls PUT /api/osd/{svc_id} with typed request and response values.
func (c *Client) PutOsdBySvcId(ctx context.Context, request PutOsdBySvcIdRequest) (PutOsdBySvcIdResponse, error) {
	path := map[string]string{
		"svc_id": request.SvcId,
	}
	query := url.Values{}
	var body any
	body = nil
	body = request.Body
	var response PutOsdBySvcIdResponse
	err := c.doJSON(ctx, http.MethodPut, "/api/osd/{svc_id}", path, query, body, true, &response)
	return response, err
}

// PostOsdBySvcIdDestroy calls POST /api/osd/{svc_id}/destroy with typed request and response values.
func (c *Client) PostOsdBySvcIdDestroy(ctx context.Context, request PostOsdBySvcIdDestroyRequest) (PostOsdBySvcIdDestroyResponse, error) {
	path := map[string]string{
		"svc_id": request.SvcId,
	}
	query := url.Values{}
	var body any
	body = nil
	var response PostOsdBySvcIdDestroyResponse
	err := c.doJSON(ctx, http.MethodPost, "/api/osd/{svc_id}/destroy", path, query, body, true, &response)
	return response, err
}

// GetOsdBySvcIdDevices calls GET /api/osd/{svc_id}/devices with typed request and response values.
func (c *Client) GetOsdBySvcIdDevices(ctx context.Context, request GetOsdBySvcIdDevicesRequest) (GetOsdBySvcIdDevicesResponse, error) {
	path := map[string]string{
		"svc_id": request.SvcId,
	}
	query := url.Values{}
	var body any
	body = nil
	var response GetOsdBySvcIdDevicesResponse
	err := c.doJSON(ctx, http.MethodGet, "/api/osd/{svc_id}/devices", path, query, body, true, &response)
	return response, err
}

// GetOsdBySvcIdHistogram calls GET /api/osd/{svc_id}/histogram with typed request and response values.
func (c *Client) GetOsdBySvcIdHistogram(ctx context.Context, request GetOsdBySvcIdHistogramRequest) (GetOsdBySvcIdHistogramResponse, error) {
	path := map[string]string{
		"svc_id": request.SvcId,
	}
	query := url.Values{}
	var body any
	body = nil
	var response GetOsdBySvcIdHistogramResponse
	err := c.doJSON(ctx, http.MethodGet, "/api/osd/{svc_id}/histogram", path, query, body, true, &response)
	return response, err
}

// PutOsdBySvcIdMark calls PUT /api/osd/{svc_id}/mark with typed request and response values.
func (c *Client) PutOsdBySvcIdMark(ctx context.Context, request PutOsdBySvcIdMarkRequest) (PutOsdBySvcIdMarkResponse, error) {
	path := map[string]string{
		"svc_id": request.SvcId,
	}
	query := url.Values{}
	var body any
	body = nil
	body = request.Body
	var response PutOsdBySvcIdMarkResponse
	err := c.doJSON(ctx, http.MethodPut, "/api/osd/{svc_id}/mark", path, query, body, true, &response)
	return response, err
}

// PostOsdBySvcIdPurge calls POST /api/osd/{svc_id}/purge with typed request and response values.
func (c *Client) PostOsdBySvcIdPurge(ctx context.Context, request PostOsdBySvcIdPurgeRequest) (PostOsdBySvcIdPurgeResponse, error) {
	path := map[string]string{
		"svc_id": request.SvcId,
	}
	query := url.Values{}
	var body any
	body = nil
	var response PostOsdBySvcIdPurgeResponse
	err := c.doJSON(ctx, http.MethodPost, "/api/osd/{svc_id}/purge", path, query, body, true, &response)
	return response, err
}

// PostOsdBySvcIdReweight calls POST /api/osd/{svc_id}/reweight with typed request and response values.
func (c *Client) PostOsdBySvcIdReweight(ctx context.Context, request PostOsdBySvcIdReweightRequest) (PostOsdBySvcIdReweightResponse, error) {
	path := map[string]string{
		"svc_id": request.SvcId,
	}
	query := url.Values{}
	var body any
	body = nil
	body = request.Body
	var response PostOsdBySvcIdReweightResponse
	err := c.doJSON(ctx, http.MethodPost, "/api/osd/{svc_id}/reweight", path, query, body, true, &response)
	return response, err
}

// PostOsdBySvcIdScrub calls POST /api/osd/{svc_id}/scrub with typed request and response values.
func (c *Client) PostOsdBySvcIdScrub(ctx context.Context, request PostOsdBySvcIdScrubRequest) (PostOsdBySvcIdScrubResponse, error) {
	path := map[string]string{
		"svc_id": request.SvcId,
	}
	query := url.Values{}
	if request.Deep != nil {
		query.Set("deep", strconv.FormatBool(*request.Deep))
	}
	var body any
	body = nil
	body = request.Body
	var response PostOsdBySvcIdScrubResponse
	err := c.doJSON(ctx, http.MethodPost, "/api/osd/{svc_id}/scrub", path, query, body, true, &response)
	return response, err
}

// GetOsdBySvcIdSmart calls GET /api/osd/{svc_id}/smart with typed request and response values.
func (c *Client) GetOsdBySvcIdSmart(ctx context.Context, request GetOsdBySvcIdSmartRequest) (GetOsdBySvcIdSmartResponse, error) {
	path := map[string]string{
		"svc_id": request.SvcId,
	}
	query := url.Values{}
	var body any
	body = nil
	var response GetOsdBySvcIdSmartResponse
	err := c.doJSON(ctx, http.MethodGet, "/api/osd/{svc_id}/smart", path, query, body, true, &response)
	return response, err
}
