// Code generated by tools/generate_ceph_dashboard_client.rb; DO NOT EDIT.

package typed

import (
	"context"
	"encoding/json"
	"net/http"
	"net/url"
	"strconv"
)

// pool typed endpoints from docs/references/ceph/src/pybind/mgr/dashboard/openapi.yaml.

type GetPoolResponseItemHitSetParams struct {
	TypeValue string `json:"type"`
}

type GetPoolResponseItemLastPgMergeMeta struct {
	LastEpochClean   int    `json:"last_epoch_clean"`
	LastEpochStarted int    `json:"last_epoch_started"`
	ReadyEpoch       int    `json:"ready_epoch"`
	SourcePgid       string `json:"source_pgid"`
	SourceVersion    string `json:"source_version"`
	TargetVersion    string `json:"target_version"`
}

type GetPoolResponseItemOptions struct {
	PgNumMax int `json:"pg_num_max"`
	PgNumMin int `json:"pg_num_min"`
}

type GetPoolResponseItem struct {
	ApplicationMetadata            []string                           `json:"application_metadata,omitempty"`
	Auid                           int                                `json:"auid,omitempty"`
	CacheMinEvictAge               int                                `json:"cache_min_evict_age,omitempty"`
	CacheMinFlushAge               int                                `json:"cache_min_flush_age,omitempty"`
	CacheMode                      string                             `json:"cache_mode,omitempty"`
	CacheTargetDirtyHighRatioMicro int                                `json:"cache_target_dirty_high_ratio_micro,omitempty"`
	CacheTargetDirtyRatioMicro     int                                `json:"cache_target_dirty_ratio_micro,omitempty"`
	CacheTargetFullRatioMicro      int                                `json:"cache_target_full_ratio_micro,omitempty"`
	CreateTime                     string                             `json:"create_time,omitempty"`
	CrushRule                      string                             `json:"crush_rule,omitempty"`
	ErasureCodeProfile             string                             `json:"erasure_code_profile,omitempty"`
	ExpectedNumObjects             int                                `json:"expected_num_objects,omitempty"`
	FastRead                       bool                               `json:"fast_read,omitempty"`
	Flags                          int                                `json:"flags,omitempty"`
	FlagsNames                     string                             `json:"flags_names,omitempty"`
	GradeTable                     []string                           `json:"grade_table,omitempty"`
	HitSetCount                    int                                `json:"hit_set_count,omitempty"`
	HitSetGradeDecayRate           int                                `json:"hit_set_grade_decay_rate,omitempty"`
	HitSetParams                   GetPoolResponseItemHitSetParams    `json:"hit_set_params,omitempty"`
	HitSetPeriod                   int                                `json:"hit_set_period,omitempty"`
	HitSetSearchLastN              int                                `json:"hit_set_search_last_n,omitempty"`
	LastChange                     string                             `json:"last_change,omitempty"`
	LastForceOpResend              string                             `json:"last_force_op_resend,omitempty"`
	LastForceOpResendPreluminous   string                             `json:"last_force_op_resend_preluminous,omitempty"`
	LastForceOpResendPrenautilus   string                             `json:"last_force_op_resend_prenautilus,omitempty"`
	LastPgMergeMeta                GetPoolResponseItemLastPgMergeMeta `json:"last_pg_merge_meta,omitempty"`
	MinReadRecencyForPromote       int                                `json:"min_read_recency_for_promote,omitempty"`
	MinSize                        int                                `json:"min_size,omitempty"`
	MinWriteRecencyForPromote      int                                `json:"min_write_recency_for_promote,omitempty"`
	ObjectHash                     int                                `json:"object_hash,omitempty"`
	Options                        GetPoolResponseItemOptions         `json:"options,omitempty"`
	PgAutoscaleMode                string                             `json:"pg_autoscale_mode,omitempty"`
	PgNum                          int                                `json:"pg_num,omitempty"`
	PgNumPending                   int                                `json:"pg_num_pending,omitempty"`
	PgNumTarget                    int                                `json:"pg_num_target,omitempty"`
	PgPlacementNum                 int                                `json:"pg_placement_num,omitempty"`
	PgPlacementNumTarget           int                                `json:"pg_placement_num_target,omitempty"`
	Pool                           int                                `json:"pool,omitempty"`
	PoolName                       string                             `json:"pool_name,omitempty"`
	PoolSnaps                      []string                           `json:"pool_snaps,omitempty"`
	QuotaMaxBytes                  int                                `json:"quota_max_bytes,omitempty"`
	QuotaMaxObjects                int                                `json:"quota_max_objects,omitempty"`
	ReadTier                       int                                `json:"read_tier,omitempty"`
	RemovedSnaps                   []string                           `json:"removed_snaps,omitempty"`
	Size                           int                                `json:"size,omitempty"`
	SnapEpoch                      int                                `json:"snap_epoch,omitempty"`
	SnapMode                       string                             `json:"snap_mode,omitempty"`
	SnapSeq                        int                                `json:"snap_seq,omitempty"`
	StripeWidth                    int                                `json:"stripe_width,omitempty"`
	TargetMaxBytes                 int                                `json:"target_max_bytes,omitempty"`
	TargetMaxObjects               int                                `json:"target_max_objects,omitempty"`
	TierOf                         int                                `json:"tier_of,omitempty"`
	Tiers                          []string                           `json:"tiers,omitempty"`
	TypeValue                      string                             `json:"type,omitempty"`
	UseGmtHitset                   bool                               `json:"use_gmt_hitset,omitempty"`
	WriteTier                      int                                `json:"write_tier,omitempty"`
}

type GetPoolResponse []GetPoolResponseItem

type GetPoolRequest struct {
	Attrs *string `query:"attrs"`
	Stats *bool   `query:"stats"`
}

type PostPoolBody struct {
	Pool string `json:"pool,omitempty"`
}

type PostPoolResponse map[string]json.RawMessage

type PostPoolRequest struct {
	Body PostPoolBody `json:"-"`
}

type DeletePoolByPoolNameResponse map[string]json.RawMessage

type DeletePoolByPoolNameRequest struct {
	PoolName string `path:"pool_name"`
}

type GetPoolByPoolNameResponse map[string]json.RawMessage

type GetPoolByPoolNameRequest struct {
	PoolName string  `path:"pool_name"`
	Attrs    *string `query:"attrs"`
	Stats    *bool   `query:"stats"`
}

type PutPoolByPoolNameBody struct {
	ApplicationMetadata string `json:"application_metadata,omitempty"`
	Configuration       string `json:"configuration,omitempty"`
	Flags               string `json:"flags,omitempty"`
	RbdMirroring        string `json:"rbd_mirroring,omitempty"`
}

type PutPoolByPoolNameResponse map[string]json.RawMessage

type PutPoolByPoolNameRequest struct {
	PoolName string                `path:"pool_name"`
	Body     PutPoolByPoolNameBody `json:"-"`
}

type GetPoolByPoolNameConfigurationResponse map[string]json.RawMessage

type GetPoolByPoolNameConfigurationRequest struct {
	PoolName string `path:"pool_name"`
}

// GetPool calls GET /api/pool with typed request and response values.
func (c *Client) GetPool(ctx context.Context, request GetPoolRequest) (GetPoolResponse, error) {
	path := map[string]string{}
	query := url.Values{}
	if request.Attrs != nil {
		query.Set("attrs", *request.Attrs)
	}
	if request.Stats != nil {
		query.Set("stats", strconv.FormatBool(*request.Stats))
	}
	var body any
	body = nil
	var response GetPoolResponse
	err := c.doJSON(ctx, http.MethodGet, "/api/pool", path, query, body, true, &response)
	return response, err
}

// PostPool calls POST /api/pool with typed request and response values.
func (c *Client) PostPool(ctx context.Context, request PostPoolRequest) (PostPoolResponse, error) {
	path := map[string]string{}
	query := url.Values{}
	var body any
	body = nil
	body = request.Body
	var response PostPoolResponse
	err := c.doJSON(ctx, http.MethodPost, "/api/pool", path, query, body, true, &response)
	return response, err
}

// DeletePoolByPoolName calls DELETE /api/pool/{pool_name} with typed request and response values.
func (c *Client) DeletePoolByPoolName(ctx context.Context, request DeletePoolByPoolNameRequest) (DeletePoolByPoolNameResponse, error) {
	path := map[string]string{
		"pool_name": request.PoolName,
	}
	query := url.Values{}
	var body any
	body = nil
	var response DeletePoolByPoolNameResponse
	err := c.doJSON(ctx, http.MethodDelete, "/api/pool/{pool_name}", path, query, body, true, &response)
	return response, err
}

// GetPoolByPoolName calls GET /api/pool/{pool_name} with typed request and response values.
func (c *Client) GetPoolByPoolName(ctx context.Context, request GetPoolByPoolNameRequest) (GetPoolByPoolNameResponse, error) {
	path := map[string]string{
		"pool_name": request.PoolName,
	}
	query := url.Values{}
	if request.Attrs != nil {
		query.Set("attrs", *request.Attrs)
	}
	if request.Stats != nil {
		query.Set("stats", strconv.FormatBool(*request.Stats))
	}
	var body any
	body = nil
	var response GetPoolByPoolNameResponse
	err := c.doJSON(ctx, http.MethodGet, "/api/pool/{pool_name}", path, query, body, true, &response)
	return response, err
}

// PutPoolByPoolName calls PUT /api/pool/{pool_name} with typed request and response values.
func (c *Client) PutPoolByPoolName(ctx context.Context, request PutPoolByPoolNameRequest) (PutPoolByPoolNameResponse, error) {
	path := map[string]string{
		"pool_name": request.PoolName,
	}
	query := url.Values{}
	var body any
	body = nil
	body = request.Body
	var response PutPoolByPoolNameResponse
	err := c.doJSON(ctx, http.MethodPut, "/api/pool/{pool_name}", path, query, body, true, &response)
	return response, err
}

// GetPoolByPoolNameConfiguration calls GET /api/pool/{pool_name}/configuration with typed request and response values.
func (c *Client) GetPoolByPoolNameConfiguration(ctx context.Context, request GetPoolByPoolNameConfigurationRequest) (GetPoolByPoolNameConfigurationResponse, error) {
	path := map[string]string{
		"pool_name": request.PoolName,
	}
	query := url.Values{}
	var body any
	body = nil
	var response GetPoolByPoolNameConfigurationResponse
	err := c.doJSON(ctx, http.MethodGet, "/api/pool/{pool_name}/configuration", path, query, body, true, &response)
	return response, err
}
