// Code generated by tools/generate_ceph_dashboard_client.rb; DO NOT EDIT.

package typed

import (
	"context"
	"encoding/json"
	"net/http"
	"net/url"
	"strconv"
)

// prometheus typed endpoints from docs/references/ceph/src/pybind/mgr/dashboard/openapi.yaml.

type GetPrometheusResponse map[string]json.RawMessage

type GetPrometheusRequest struct {
	ClusterFilter *bool `query:"cluster_filter"`
}

type GetPrometheusAlertgroupResponse map[string]json.RawMessage

type GetPrometheusAlertgroupRequest struct {
	ClusterFilter *bool `query:"cluster_filter"`
}

type GetPrometheusDataResponse map[string]json.RawMessage

type GetPrometheusDataRequest struct{}

type GetPrometheusNotificationsResponse map[string]json.RawMessage

type GetPrometheusNotificationsRequest struct{}

type GetPrometheusPrometheusQueryDataResponse map[string]json.RawMessage

type GetPrometheusPrometheusQueryDataRequest struct{}

type GetPrometheusRulesResponse map[string]json.RawMessage

type GetPrometheusRulesRequest struct{}

type PostPrometheusSilenceResponse map[string]json.RawMessage

type PostPrometheusSilenceRequest struct{}

type DeletePrometheusSilenceBySIdResponse map[string]json.RawMessage

type DeletePrometheusSilenceBySIdRequest struct {
	SId string `path:"s_id"`
}

type GetPrometheusSilencesResponse map[string]json.RawMessage

type GetPrometheusSilencesRequest struct{}

// GetPrometheus calls GET /api/prometheus with typed request and response values.
func (c *Client) GetPrometheus(ctx context.Context, request GetPrometheusRequest) (GetPrometheusResponse, error) {
	path := map[string]string{}
	query := url.Values{}
	if request.ClusterFilter != nil {
		query.Set("cluster_filter", strconv.FormatBool(*request.ClusterFilter))
	}
	var body any
	body = nil
	var response GetPrometheusResponse
	err := c.doJSON(ctx, http.MethodGet, "/api/prometheus", path, query, body, true, &response)
	return response, err
}

// GetPrometheusAlertgroup calls GET /api/prometheus/alertgroup with typed request and response values.
func (c *Client) GetPrometheusAlertgroup(ctx context.Context, request GetPrometheusAlertgroupRequest) (GetPrometheusAlertgroupResponse, error) {
	path := map[string]string{}
	query := url.Values{}
	if request.ClusterFilter != nil {
		query.Set("cluster_filter", strconv.FormatBool(*request.ClusterFilter))
	}
	var body any
	body = nil
	var response GetPrometheusAlertgroupResponse
	err := c.doJSON(ctx, http.MethodGet, "/api/prometheus/alertgroup", path, query, body, true, &response)
	return response, err
}

// GetPrometheusData calls GET /api/prometheus/data with typed request and response values.
func (c *Client) GetPrometheusData(ctx context.Context, request GetPrometheusDataRequest) (GetPrometheusDataResponse, error) {
	path := map[string]string{}
	query := url.Values{}
	var body any
	body = nil
	var response GetPrometheusDataResponse
	err := c.doJSON(ctx, http.MethodGet, "/api/prometheus/data", path, query, body, true, &response)
	return response, err
}

// GetPrometheusNotifications calls GET /api/prometheus/notifications with typed request and response values.
func (c *Client) GetPrometheusNotifications(ctx context.Context, request GetPrometheusNotificationsRequest) (GetPrometheusNotificationsResponse, error) {
	path := map[string]string{}
	query := url.Values{}
	var body any
	body = nil
	var response GetPrometheusNotificationsResponse
	err := c.doJSON(ctx, http.MethodGet, "/api/prometheus/notifications", path, query, body, true, &response)
	return response, err
}

// GetPrometheusPrometheusQueryData calls GET /api/prometheus/prometheus_query_data with typed request and response values.
func (c *Client) GetPrometheusPrometheusQueryData(ctx context.Context, request GetPrometheusPrometheusQueryDataRequest) (GetPrometheusPrometheusQueryDataResponse, error) {
	path := map[string]string{}
	query := url.Values{}
	var body any
	body = nil
	var response GetPrometheusPrometheusQueryDataResponse
	err := c.doJSON(ctx, http.MethodGet, "/api/prometheus/prometheus_query_data", path, query, body, true, &response)
	return response, err
}

// GetPrometheusRules calls GET /api/prometheus/rules with typed request and response values.
func (c *Client) GetPrometheusRules(ctx context.Context, request GetPrometheusRulesRequest) (GetPrometheusRulesResponse, error) {
	path := map[string]string{}
	query := url.Values{}
	var body any
	body = nil
	var response GetPrometheusRulesResponse
	err := c.doJSON(ctx, http.MethodGet, "/api/prometheus/rules", path, query, body, true, &response)
	return response, err
}

// PostPrometheusSilence calls POST /api/prometheus/silence with typed request and response values.
func (c *Client) PostPrometheusSilence(ctx context.Context, request PostPrometheusSilenceRequest) (PostPrometheusSilenceResponse, error) {
	path := map[string]string{}
	query := url.Values{}
	var body any
	body = nil
	var response PostPrometheusSilenceResponse
	err := c.doJSON(ctx, http.MethodPost, "/api/prometheus/silence", path, query, body, true, &response)
	return response, err
}

// DeletePrometheusSilenceBySId calls DELETE /api/prometheus/silence/{s_id} with typed request and response values.
func (c *Client) DeletePrometheusSilenceBySId(ctx context.Context, request DeletePrometheusSilenceBySIdRequest) (DeletePrometheusSilenceBySIdResponse, error) {
	path := map[string]string{
		"s_id": request.SId,
	}
	query := url.Values{}
	var body any
	body = nil
	var response DeletePrometheusSilenceBySIdResponse
	err := c.doJSON(ctx, http.MethodDelete, "/api/prometheus/silence/{s_id}", path, query, body, true, &response)
	return response, err
}

// GetPrometheusSilences calls GET /api/prometheus/silences with typed request and response values.
func (c *Client) GetPrometheusSilences(ctx context.Context, request GetPrometheusSilencesRequest) (GetPrometheusSilencesResponse, error) {
	path := map[string]string{}
	query := url.Values{}
	var body any
	body = nil
	var response GetPrometheusSilencesResponse
	err := c.doJSON(ctx, http.MethodGet, "/api/prometheus/silences", path, query, body, true, &response)
	return response, err
}
