// Code generated by tools/generate_ceph_dashboard_client.rb; DO NOT EDIT.

package typed

import (
	"context"
	"encoding/json"
	"net/http"
	"net/url"
)

// role typed endpoints from docs/references/ceph/src/pybind/mgr/dashboard/openapi.yaml.

type GetRoleResponseItemScopesPermissions struct {
	Cephfs []string `json:"cephfs"`
}

type GetRoleResponseItem struct {
	Description       string                               `json:"description,omitempty"`
	Name              string                               `json:"name,omitempty"`
	ScopesPermissions GetRoleResponseItemScopesPermissions `json:"scopes_permissions,omitempty"`
	System            bool                                 `json:"system,omitempty"`
}

type GetRoleResponse []GetRoleResponseItem

type GetRoleRequest struct{}

type PostRoleBody struct {
	Description       string `json:"description,omitempty"`
	Name              string `json:"name,omitempty"`
	ScopesPermissions string `json:"scopes_permissions,omitempty"`
}

type PostRoleResponse map[string]json.RawMessage

type PostRoleRequest struct {
	Body PostRoleBody `json:"-"`
}

type DeleteRoleByNameResponse map[string]json.RawMessage

type DeleteRoleByNameRequest struct {
	Name string `path:"name"`
}

type GetRoleByNameResponse map[string]json.RawMessage

type GetRoleByNameRequest struct {
	Name string `path:"name"`
}

type PutRoleByNameBody struct {
	Description       string `json:"description,omitempty"`
	ScopesPermissions string `json:"scopes_permissions,omitempty"`
}

type PutRoleByNameResponse map[string]json.RawMessage

type PutRoleByNameRequest struct {
	Name string            `path:"name"`
	Body PutRoleByNameBody `json:"-"`
}

type PostRoleByNameCloneBody struct {
	NewName string `json:"new_name"`
}

type PostRoleByNameCloneResponse map[string]json.RawMessage

type PostRoleByNameCloneRequest struct {
	Name string                  `path:"name"`
	Body PostRoleByNameCloneBody `json:"-"`
}

// GetRole calls GET /api/role with typed request and response values.
func (c *Client) GetRole(ctx context.Context, request GetRoleRequest) (GetRoleResponse, error) {
	path := map[string]string{}
	query := url.Values{}
	var body any
	body = nil
	var response GetRoleResponse
	err := c.doJSON(ctx, http.MethodGet, "/api/role", path, query, body, true, &response)
	return response, err
}

// PostRole calls POST /api/role with typed request and response values.
func (c *Client) PostRole(ctx context.Context, request PostRoleRequest) (PostRoleResponse, error) {
	path := map[string]string{}
	query := url.Values{}
	var body any
	body = nil
	body = request.Body
	var response PostRoleResponse
	err := c.doJSON(ctx, http.MethodPost, "/api/role", path, query, body, true, &response)
	return response, err
}

// DeleteRoleByName calls DELETE /api/role/{name} with typed request and response values.
func (c *Client) DeleteRoleByName(ctx context.Context, request DeleteRoleByNameRequest) (DeleteRoleByNameResponse, error) {
	path := map[string]string{
		"name": request.Name,
	}
	query := url.Values{}
	var body any
	body = nil
	var response DeleteRoleByNameResponse
	err := c.doJSON(ctx, http.MethodDelete, "/api/role/{name}", path, query, body, true, &response)
	return response, err
}

// GetRoleByName calls GET /api/role/{name} with typed request and response values.
func (c *Client) GetRoleByName(ctx context.Context, request GetRoleByNameRequest) (GetRoleByNameResponse, error) {
	path := map[string]string{
		"name": request.Name,
	}
	query := url.Values{}
	var body any
	body = nil
	var response GetRoleByNameResponse
	err := c.doJSON(ctx, http.MethodGet, "/api/role/{name}", path, query, body, true, &response)
	return response, err
}

// PutRoleByName calls PUT /api/role/{name} with typed request and response values.
func (c *Client) PutRoleByName(ctx context.Context, request PutRoleByNameRequest) (PutRoleByNameResponse, error) {
	path := map[string]string{
		"name": request.Name,
	}
	query := url.Values{}
	var body any
	body = nil
	body = request.Body
	var response PutRoleByNameResponse
	err := c.doJSON(ctx, http.MethodPut, "/api/role/{name}", path, query, body, true, &response)
	return response, err
}

// PostRoleByNameClone calls POST /api/role/{name}/clone with typed request and response values.
func (c *Client) PostRoleByNameClone(ctx context.Context, request PostRoleByNameCloneRequest) (PostRoleByNameCloneResponse, error) {
	path := map[string]string{
		"name": request.Name,
	}
	query := url.Values{}
	var body any
	body = nil
	body = request.Body
	var response PostRoleByNameCloneResponse
	err := c.doJSON(ctx, http.MethodPost, "/api/role/{name}/clone", path, query, body, true, &response)
	return response, err
}
