// Code generated by tools/generate_ceph_dashboard_client.rb; DO NOT EDIT.

package typed

import (
	"context"
	"encoding/json"
	"net/http"
	"net/url"
)

// settings typed endpoints from docs/references/ceph/src/pybind/mgr/dashboard/openapi.yaml.

type GetSettingsResponseItem struct {
	DefaultValue bool   `json:"default,omitempty"`
	Name         string `json:"name,omitempty"`
	TypeValue    string `json:"type,omitempty"`
	Value        bool   `json:"value,omitempty"`
}

type GetSettingsResponse []GetSettingsResponseItem

type GetSettingsRequest struct {
	Names *string `query:"names"`
}

type PutSettingsResponse map[string]json.RawMessage

type PutSettingsRequest struct{}

type DeleteSettingsByNameResponse map[string]json.RawMessage

type DeleteSettingsByNameRequest struct {
	Name string `path:"name"`
}

type GetSettingsByNameResponse map[string]json.RawMessage

type GetSettingsByNameRequest struct {
	Name string `path:"name"`
}

type PutSettingsByNameBody struct {
	Value string `json:"value"`
}

type PutSettingsByNameResponse map[string]json.RawMessage

type PutSettingsByNameRequest struct {
	Name string                `path:"name"`
	Body PutSettingsByNameBody `json:"-"`
}

// GetSettings calls GET /api/settings with typed request and response values.
func (c *Client) GetSettings(ctx context.Context, request GetSettingsRequest) (GetSettingsResponse, error) {
	path := map[string]string{}
	query := url.Values{}
	if request.Names != nil {
		query.Set("names", *request.Names)
	}
	var body any
	body = nil
	var response GetSettingsResponse
	err := c.doJSON(ctx, http.MethodGet, "/api/settings", path, query, body, true, &response)
	return response, err
}

// PutSettings calls PUT /api/settings with typed request and response values.
func (c *Client) PutSettings(ctx context.Context, request PutSettingsRequest) (PutSettingsResponse, error) {
	path := map[string]string{}
	query := url.Values{}
	var body any
	body = nil
	var response PutSettingsResponse
	err := c.doJSON(ctx, http.MethodPut, "/api/settings", path, query, body, true, &response)
	return response, err
}

// DeleteSettingsByName calls DELETE /api/settings/{name} with typed request and response values.
func (c *Client) DeleteSettingsByName(ctx context.Context, request DeleteSettingsByNameRequest) (DeleteSettingsByNameResponse, error) {
	path := map[string]string{
		"name": request.Name,
	}
	query := url.Values{}
	var body any
	body = nil
	var response DeleteSettingsByNameResponse
	err := c.doJSON(ctx, http.MethodDelete, "/api/settings/{name}", path, query, body, true, &response)
	return response, err
}

// GetSettingsByName calls GET /api/settings/{name} with typed request and response values.
func (c *Client) GetSettingsByName(ctx context.Context, request GetSettingsByNameRequest) (GetSettingsByNameResponse, error) {
	path := map[string]string{
		"name": request.Name,
	}
	query := url.Values{}
	var body any
	body = nil
	var response GetSettingsByNameResponse
	err := c.doJSON(ctx, http.MethodGet, "/api/settings/{name}", path, query, body, true, &response)
	return response, err
}

// PutSettingsByName calls PUT /api/settings/{name} with typed request and response values.
func (c *Client) PutSettingsByName(ctx context.Context, request PutSettingsByNameRequest) (PutSettingsByNameResponse, error) {
	path := map[string]string{
		"name": request.Name,
	}
	query := url.Values{}
	var body any
	body = nil
	body = request.Body
	var response PutSettingsByNameResponse
	err := c.doJSON(ctx, http.MethodPut, "/api/settings/{name}", path, query, body, true, &response)
	return response, err
}
