// Code generated by tools/generate_ceph_dashboard_client.rb; DO NOT EDIT.

package endpoints

import (
	"context"
	"encoding/json"
	"net/http"
)

// grafana endpoints from docs/references/ceph/src/pybind/mgr/dashboard/openapi.yaml.

// PostGrafanaDashboards calls POST /api/grafana/dashboards.
// POST /api/grafana/dashboards
func (c *Client) PostGrafanaDashboards(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodPost, "/api/grafana/dashboards", request, true)
}

// GetGrafanaUrl calls GET /api/grafana/url.
// List Grafana URL Instance
func (c *Client) GetGrafanaUrl(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodGet, "/api/grafana/url", request, true)
}

// GetGrafanaValidationByParams calls GET /api/grafana/validation/{params}.
// GET /api/grafana/validation/{params}
func (c *Client) GetGrafanaValidationByParams(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodGet, "/api/grafana/validation/{params}", request, true)
}
