// Code generated by tools/generate_ceph_dashboard_client.rb; DO NOT EDIT.

package endpoints

import (
	"context"
	"encoding/json"
	"net/http"
)

// hardware endpoints from docs/references/ceph/src/pybind/mgr/dashboard/openapi.yaml.

// GetHardwareSummary calls GET /api/hardware/summary.
// Retrieve a summary of the hardware health status
func (c *Client) GetHardwareSummary(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodGet, "/api/hardware/summary", request, true)
}
