// Code generated by tools/generate_ceph_dashboard_client.rb; DO NOT EDIT.

package endpoints

import (
	"context"
	"encoding/json"
	"net/http"
)

// rgw endpoints from docs/references/ceph/src/pybind/mgr/dashboard/openapi.yaml.

// GetRgwAccounts calls GET /api/rgw/accounts.
// GET /api/rgw/accounts
func (c *Client) GetRgwAccounts(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodGet, "/api/rgw/accounts", request, true)
}

// PostRgwAccounts calls POST /api/rgw/accounts.
// Update RGW account info
func (c *Client) PostRgwAccounts(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodPost, "/api/rgw/accounts", request, true)
}

// DeleteRgwAccountsByAccountId calls DELETE /api/rgw/accounts/{account_id}.
// Delete RGW Account
func (c *Client) DeleteRgwAccountsByAccountId(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodDelete, "/api/rgw/accounts/{account_id}", request, true)
}

// GetRgwAccountsByAccountId calls GET /api/rgw/accounts/{account_id}.
// Get RGW Account by id
func (c *Client) GetRgwAccountsByAccountId(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodGet, "/api/rgw/accounts/{account_id}", request, true)
}

// PutRgwAccountsByAccountId calls PUT /api/rgw/accounts/{account_id}.
// Update RGW account info
func (c *Client) PutRgwAccountsByAccountId(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodPut, "/api/rgw/accounts/{account_id}", request, true)
}

// PutRgwAccountsByAccountIdQuota calls PUT /api/rgw/accounts/{account_id}/quota.
// Set RGW Account/Bucket quota
func (c *Client) PutRgwAccountsByAccountIdQuota(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodPut, "/api/rgw/accounts/{account_id}/quota", request, true)
}

// PutRgwAccountsByAccountIdQuotaStatus calls PUT /api/rgw/accounts/{account_id}/quota/status.
// Enable/Disable RGW Account/Bucket quota
func (c *Client) PutRgwAccountsByAccountIdQuotaStatus(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodPut, "/api/rgw/accounts/{account_id}/quota/status", request, true)
}

// GetRgwBucket calls GET /api/rgw/bucket.
// GET /api/rgw/bucket
func (c *Client) GetRgwBucket(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodGet, "/api/rgw/bucket", request, true)
}

// PostRgwBucket calls POST /api/rgw/bucket.
// POST /api/rgw/bucket
func (c *Client) PostRgwBucket(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodPost, "/api/rgw/bucket", request, true)
}

// DeleteRgwBucketDeleteEncryption calls DELETE /api/rgw/bucket/deleteEncryption.
// DELETE /api/rgw/bucket/deleteEncryption
func (c *Client) DeleteRgwBucketDeleteEncryption(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodDelete, "/api/rgw/bucket/deleteEncryption", request, true)
}

// GetRgwBucketGetEncryption calls GET /api/rgw/bucket/getEncryption.
// GET /api/rgw/bucket/getEncryption
func (c *Client) GetRgwBucketGetEncryption(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodGet, "/api/rgw/bucket/getEncryption", request, true)
}

// GetRgwBucketGetEncryptionConfig calls GET /api/rgw/bucket/getEncryptionConfig.
// GET /api/rgw/bucket/getEncryptionConfig
func (c *Client) GetRgwBucketGetEncryptionConfig(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodGet, "/api/rgw/bucket/getEncryptionConfig", request, true)
}

// GetRgwBucketLifecycle calls GET /api/rgw/bucket/lifecycle.
// GET /api/rgw/bucket/lifecycle
func (c *Client) GetRgwBucketLifecycle(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodGet, "/api/rgw/bucket/lifecycle", request, true)
}

// PutRgwBucketLifecycle calls PUT /api/rgw/bucket/lifecycle.
// PUT /api/rgw/bucket/lifecycle
func (c *Client) PutRgwBucketLifecycle(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodPut, "/api/rgw/bucket/lifecycle", request, true)
}

// DeleteRgwBucketNotification calls DELETE /api/rgw/bucket/notification.
// Delete the bucket notification
func (c *Client) DeleteRgwBucketNotification(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodDelete, "/api/rgw/bucket/notification", request, true)
}

// GetRgwBucketNotification calls GET /api/rgw/bucket/notification.
// Get the bucket notification
func (c *Client) GetRgwBucketNotification(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodGet, "/api/rgw/bucket/notification", request, true)
}

// PutRgwBucketNotification calls PUT /api/rgw/bucket/notification.
// Create or update the bucket notification
func (c *Client) PutRgwBucketNotification(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodPut, "/api/rgw/bucket/notification", request, true)
}

// GetRgwBucketRatelimit calls GET /api/rgw/bucket/ratelimit.
// Get the bucket global rate limit
func (c *Client) GetRgwBucketRatelimit(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodGet, "/api/rgw/bucket/ratelimit", request, true)
}

// PutRgwBucketSetEncryptionConfig calls PUT /api/rgw/bucket/setEncryptionConfig.
// PUT /api/rgw/bucket/setEncryptionConfig
func (c *Client) PutRgwBucketSetEncryptionConfig(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodPut, "/api/rgw/bucket/setEncryptionConfig", request, true)
}

// DeleteRgwBucketByBucket calls DELETE /api/rgw/bucket/{bucket}.
// DELETE /api/rgw/bucket/{bucket}
func (c *Client) DeleteRgwBucketByBucket(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodDelete, "/api/rgw/bucket/{bucket}", request, true)
}

// GetRgwBucketByBucket calls GET /api/rgw/bucket/{bucket}.
// GET /api/rgw/bucket/{bucket}
func (c *Client) GetRgwBucketByBucket(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodGet, "/api/rgw/bucket/{bucket}", request, true)
}

// PutRgwBucketByBucket calls PUT /api/rgw/bucket/{bucket}.
// PUT /api/rgw/bucket/{bucket}
func (c *Client) PutRgwBucketByBucket(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodPut, "/api/rgw/bucket/{bucket}", request, true)
}

// GetRgwBucketByUidRatelimit calls GET /api/rgw/bucket/{uid}/ratelimit.
// Get the bucket rate limit
func (c *Client) GetRgwBucketByUidRatelimit(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodGet, "/api/rgw/bucket/{uid}/ratelimit", request, true)
}

// PutRgwBucketByUidRatelimit calls PUT /api/rgw/bucket/{uid}/ratelimit.
// Update the bucket rate limit
func (c *Client) PutRgwBucketByUidRatelimit(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodPut, "/api/rgw/bucket/{uid}/ratelimit", request, true)
}

// GetRgwDaemon calls GET /api/rgw/daemon.
// Display RGW Daemons
func (c *Client) GetRgwDaemon(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodGet, "/api/rgw/daemon", request, true)
}

// PutRgwDaemonSetMultisiteConfig calls PUT /api/rgw/daemon/set_multisite_config.
// PUT /api/rgw/daemon/set_multisite_config
func (c *Client) PutRgwDaemonSetMultisiteConfig(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodPut, "/api/rgw/daemon/set_multisite_config", request, true)
}

// GetRgwDaemonBySvcId calls GET /api/rgw/daemon/{svc_id}.
// GET /api/rgw/daemon/{svc_id}
func (c *Client) GetRgwDaemonBySvcId(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodGet, "/api/rgw/daemon/{svc_id}", request, true)
}

// PutRgwMultisiteSyncFlow calls PUT /api/rgw/multisite/sync-flow.
// Create or update the sync flow
func (c *Client) PutRgwMultisiteSyncFlow(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodPut, "/api/rgw/multisite/sync-flow", request, true)
}

// DeleteRgwMultisiteSyncFlowByFlowIdByFlowTypeByGroupId calls DELETE /api/rgw/multisite/sync-flow/{flow_id}/{flow_type}/{group_id}.
// Remove the sync flow
func (c *Client) DeleteRgwMultisiteSyncFlowByFlowIdByFlowTypeByGroupId(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodDelete, "/api/rgw/multisite/sync-flow/{flow_id}/{flow_type}/{group_id}", request, true)
}

// PutRgwMultisiteSyncPipe calls PUT /api/rgw/multisite/sync-pipe.
// Create or update the sync pipe
func (c *Client) PutRgwMultisiteSyncPipe(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodPut, "/api/rgw/multisite/sync-pipe", request, true)
}

// DeleteRgwMultisiteSyncPipeByGroupIdByPipeId calls DELETE /api/rgw/multisite/sync-pipe/{group_id}/{pipe_id}.
// Remove the sync pipe
func (c *Client) DeleteRgwMultisiteSyncPipeByGroupIdByPipeId(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodDelete, "/api/rgw/multisite/sync-pipe/{group_id}/{pipe_id}", request, true)
}

// GetRgwMultisiteSyncPolicy calls GET /api/rgw/multisite/sync-policy.
// Get the sync policy
func (c *Client) GetRgwMultisiteSyncPolicy(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodGet, "/api/rgw/multisite/sync-policy", request, true)
}

// PostRgwMultisiteSyncPolicyGroup calls POST /api/rgw/multisite/sync-policy-group.
// Create the sync policy group
func (c *Client) PostRgwMultisiteSyncPolicyGroup(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodPost, "/api/rgw/multisite/sync-policy-group", request, true)
}

// PutRgwMultisiteSyncPolicyGroup calls PUT /api/rgw/multisite/sync-policy-group.
// Update the sync policy group
func (c *Client) PutRgwMultisiteSyncPolicyGroup(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodPut, "/api/rgw/multisite/sync-policy-group", request, true)
}

// DeleteRgwMultisiteSyncPolicyGroupByGroupId calls DELETE /api/rgw/multisite/sync-policy-group/{group_id}.
// Remove the sync policy group
func (c *Client) DeleteRgwMultisiteSyncPolicyGroupByGroupId(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodDelete, "/api/rgw/multisite/sync-policy-group/{group_id}", request, true)
}

// GetRgwMultisiteSyncPolicyGroupByGroupId calls GET /api/rgw/multisite/sync-policy-group/{group_id}.
// Get the sync policy group
func (c *Client) GetRgwMultisiteSyncPolicyGroupByGroupId(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodGet, "/api/rgw/multisite/sync-policy-group/{group_id}", request, true)
}

// GetRgwMultisiteSyncStatus calls GET /api/rgw/multisite/sync_status.
// Get the sync status
func (c *Client) GetRgwMultisiteSyncStatus(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodGet, "/api/rgw/multisite/sync_status", request, true)
}

// GetRgwRealm calls GET /api/rgw/realm.
// GET /api/rgw/realm
func (c *Client) GetRgwRealm(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodGet, "/api/rgw/realm", request, true)
}

// PostRgwRealm calls POST /api/rgw/realm.
// POST /api/rgw/realm
func (c *Client) PostRgwRealm(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodPost, "/api/rgw/realm", request, true)
}

// GetRgwRealmGetAllRealmsInfo calls GET /api/rgw/realm/get_all_realms_info.
// GET /api/rgw/realm/get_all_realms_info
func (c *Client) GetRgwRealmGetAllRealmsInfo(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodGet, "/api/rgw/realm/get_all_realms_info", request, true)
}

// GetRgwRealmGetRealmTokens calls GET /api/rgw/realm/get_realm_tokens.
// GET /api/rgw/realm/get_realm_tokens
func (c *Client) GetRgwRealmGetRealmTokens(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodGet, "/api/rgw/realm/get_realm_tokens", request, true)
}

// PostRgwRealmImportRealmToken calls POST /api/rgw/realm/import_realm_token.
// POST /api/rgw/realm/import_realm_token
func (c *Client) PostRgwRealmImportRealmToken(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodPost, "/api/rgw/realm/import_realm_token", request, true)
}

// DeleteRgwRealmByRealmName calls DELETE /api/rgw/realm/{realm_name}.
// DELETE /api/rgw/realm/{realm_name}
func (c *Client) DeleteRgwRealmByRealmName(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodDelete, "/api/rgw/realm/{realm_name}", request, true)
}

// GetRgwRealmByRealmName calls GET /api/rgw/realm/{realm_name}.
// GET /api/rgw/realm/{realm_name}
func (c *Client) GetRgwRealmByRealmName(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodGet, "/api/rgw/realm/{realm_name}", request, true)
}

// PutRgwRealmByRealmName calls PUT /api/rgw/realm/{realm_name}.
// PUT /api/rgw/realm/{realm_name}
func (c *Client) PutRgwRealmByRealmName(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodPut, "/api/rgw/realm/{realm_name}", request, true)
}

// GetRgwRoles calls GET /api/rgw/roles.
// List RGW roles
func (c *Client) GetRgwRoles(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodGet, "/api/rgw/roles", request, true)
}

// PostRgwRoles calls POST /api/rgw/roles.
// Create RGW role
func (c *Client) PostRgwRoles(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodPost, "/api/rgw/roles", request, true)
}

// PutRgwRoles calls PUT /api/rgw/roles.
// Edit RGW role
func (c *Client) PutRgwRoles(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodPut, "/api/rgw/roles", request, true)
}

// DeleteRgwRolesByRoleName calls DELETE /api/rgw/roles/{role_name}.
// Delete RGW role
func (c *Client) DeleteRgwRolesByRoleName(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodDelete, "/api/rgw/roles/{role_name}", request, true)
}

// GetRgwSite calls GET /api/rgw/site.
// GET /api/rgw/site
func (c *Client) GetRgwSite(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodGet, "/api/rgw/site", request, true)
}

// GetRgwTopic calls GET /api/rgw/topic.
// Get RGW Topic List
func (c *Client) GetRgwTopic(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodGet, "/api/rgw/topic", request, true)
}

// PostRgwTopic calls POST /api/rgw/topic.
// Create a new RGW Topic
func (c *Client) PostRgwTopic(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodPost, "/api/rgw/topic", request, true)
}

// DeleteRgwTopicByKey calls DELETE /api/rgw/topic/{key}.
// Delete RGW Topic
func (c *Client) DeleteRgwTopicByKey(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodDelete, "/api/rgw/topic/{key}", request, true)
}

// GetRgwTopicByKey calls GET /api/rgw/topic/{key}.
// Get RGW Topic
func (c *Client) GetRgwTopicByKey(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodGet, "/api/rgw/topic/{key}", request, true)
}

// GetRgwUser calls GET /api/rgw/user.
// Display RGW Users
func (c *Client) GetRgwUser(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodGet, "/api/rgw/user", request, true)
}

// PostRgwUser calls POST /api/rgw/user.
// POST /api/rgw/user
func (c *Client) PostRgwUser(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodPost, "/api/rgw/user", request, true)
}

// GetRgwUserGetEmails calls GET /api/rgw/user/get_emails.
// GET /api/rgw/user/get_emails
func (c *Client) GetRgwUserGetEmails(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodGet, "/api/rgw/user/get_emails", request, true)
}

// GetRgwUserRatelimit calls GET /api/rgw/user/ratelimit.
// Get the user global rate limit
func (c *Client) GetRgwUserRatelimit(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodGet, "/api/rgw/user/ratelimit", request, true)
}

// DeleteRgwUserByUid calls DELETE /api/rgw/user/{uid}.
// DELETE /api/rgw/user/{uid}
func (c *Client) DeleteRgwUserByUid(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodDelete, "/api/rgw/user/{uid}", request, true)
}

// GetRgwUserByUid calls GET /api/rgw/user/{uid}.
// GET /api/rgw/user/{uid}
func (c *Client) GetRgwUserByUid(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodGet, "/api/rgw/user/{uid}", request, true)
}

// PutRgwUserByUid calls PUT /api/rgw/user/{uid}.
// PUT /api/rgw/user/{uid}
func (c *Client) PutRgwUserByUid(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodPut, "/api/rgw/user/{uid}", request, true)
}

// DeleteRgwUserByUidCapability calls DELETE /api/rgw/user/{uid}/capability.
// DELETE /api/rgw/user/{uid}/capability
func (c *Client) DeleteRgwUserByUidCapability(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodDelete, "/api/rgw/user/{uid}/capability", request, true)
}

// PostRgwUserByUidCapability calls POST /api/rgw/user/{uid}/capability.
// POST /api/rgw/user/{uid}/capability
func (c *Client) PostRgwUserByUidCapability(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodPost, "/api/rgw/user/{uid}/capability", request, true)
}

// DeleteRgwUserByUidKey calls DELETE /api/rgw/user/{uid}/key.
// DELETE /api/rgw/user/{uid}/key
func (c *Client) DeleteRgwUserByUidKey(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodDelete, "/api/rgw/user/{uid}/key", request, true)
}

// PostRgwUserByUidKey calls POST /api/rgw/user/{uid}/key.
// POST /api/rgw/user/{uid}/key
func (c *Client) PostRgwUserByUidKey(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodPost, "/api/rgw/user/{uid}/key", request, true)
}

// GetRgwUserByUidQuota calls GET /api/rgw/user/{uid}/quota.
// GET /api/rgw/user/{uid}/quota
func (c *Client) GetRgwUserByUidQuota(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodGet, "/api/rgw/user/{uid}/quota", request, true)
}

// PutRgwUserByUidQuota calls PUT /api/rgw/user/{uid}/quota.
// PUT /api/rgw/user/{uid}/quota
func (c *Client) PutRgwUserByUidQuota(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodPut, "/api/rgw/user/{uid}/quota", request, true)
}

// GetRgwUserByUidRatelimit calls GET /api/rgw/user/{uid}/ratelimit.
// Get the user rate limit
func (c *Client) GetRgwUserByUidRatelimit(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodGet, "/api/rgw/user/{uid}/ratelimit", request, true)
}

// PutRgwUserByUidRatelimit calls PUT /api/rgw/user/{uid}/ratelimit.
// Update the user rate limit
func (c *Client) PutRgwUserByUidRatelimit(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodPut, "/api/rgw/user/{uid}/ratelimit", request, true)
}

// PostRgwUserByUidSubuser calls POST /api/rgw/user/{uid}/subuser.
// POST /api/rgw/user/{uid}/subuser
func (c *Client) PostRgwUserByUidSubuser(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodPost, "/api/rgw/user/{uid}/subuser", request, true)
}

// DeleteRgwUserByUidSubuserBySubuser calls DELETE /api/rgw/user/{uid}/subuser/{subuser}.
// DELETE /api/rgw/user/{uid}/subuser/{subuser}
func (c *Client) DeleteRgwUserByUidSubuserBySubuser(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodDelete, "/api/rgw/user/{uid}/subuser/{subuser}", request, true)
}

// GetRgwZone calls GET /api/rgw/zone.
// GET /api/rgw/zone
func (c *Client) GetRgwZone(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodGet, "/api/rgw/zone", request, true)
}

// PostRgwZone calls POST /api/rgw/zone.
// POST /api/rgw/zone
func (c *Client) PostRgwZone(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodPost, "/api/rgw/zone", request, true)
}

// PutRgwZoneCreateSystemUser calls PUT /api/rgw/zone/create_system_user.
// PUT /api/rgw/zone/create_system_user
func (c *Client) PutRgwZoneCreateSystemUser(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodPut, "/api/rgw/zone/create_system_user", request, true)
}

// GetRgwZoneGetAllZonesInfo calls GET /api/rgw/zone/get_all_zones_info.
// GET /api/rgw/zone/get_all_zones_info
func (c *Client) GetRgwZoneGetAllZonesInfo(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodGet, "/api/rgw/zone/get_all_zones_info", request, true)
}

// GetRgwZoneGetPoolNames calls GET /api/rgw/zone/get_pool_names.
// GET /api/rgw/zone/get_pool_names
func (c *Client) GetRgwZoneGetPoolNames(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodGet, "/api/rgw/zone/get_pool_names", request, true)
}

// GetRgwZoneGetUserList calls GET /api/rgw/zone/get_user_list.
// GET /api/rgw/zone/get_user_list
func (c *Client) GetRgwZoneGetUserList(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodGet, "/api/rgw/zone/get_user_list", request, true)
}

// PostRgwZoneStorageClass calls POST /api/rgw/zone/storage-class.
// POST /api/rgw/zone/storage-class
func (c *Client) PostRgwZoneStorageClass(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodPost, "/api/rgw/zone/storage-class", request, true)
}

// PutRgwZoneStorageClass calls PUT /api/rgw/zone/storage-class.
// PUT /api/rgw/zone/storage-class
func (c *Client) PutRgwZoneStorageClass(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodPut, "/api/rgw/zone/storage-class", request, true)
}

// DeleteRgwZoneByZoneName calls DELETE /api/rgw/zone/{zone_name}.
// DELETE /api/rgw/zone/{zone_name}
func (c *Client) DeleteRgwZoneByZoneName(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodDelete, "/api/rgw/zone/{zone_name}", request, true)
}

// GetRgwZoneByZoneName calls GET /api/rgw/zone/{zone_name}.
// GET /api/rgw/zone/{zone_name}
func (c *Client) GetRgwZoneByZoneName(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodGet, "/api/rgw/zone/{zone_name}", request, true)
}

// PutRgwZoneByZoneName calls PUT /api/rgw/zone/{zone_name}.
// PUT /api/rgw/zone/{zone_name}
func (c *Client) PutRgwZoneByZoneName(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodPut, "/api/rgw/zone/{zone_name}", request, true)
}

// GetRgwZonegroup calls GET /api/rgw/zonegroup.
// GET /api/rgw/zonegroup
func (c *Client) GetRgwZonegroup(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodGet, "/api/rgw/zonegroup", request, true)
}

// PostRgwZonegroup calls POST /api/rgw/zonegroup.
// POST /api/rgw/zonegroup
func (c *Client) PostRgwZonegroup(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodPost, "/api/rgw/zonegroup", request, true)
}

// GetRgwZonegroupGetAllZonegroupsInfo calls GET /api/rgw/zonegroup/get_all_zonegroups_info.
// GET /api/rgw/zonegroup/get_all_zonegroups_info
func (c *Client) GetRgwZonegroupGetAllZonegroupsInfo(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodGet, "/api/rgw/zonegroup/get_all_zonegroups_info", request, true)
}

// GetRgwZonegroupGetPlacementTargetByPlacementIdByPlacementId calls GET /api/rgw/zonegroup/get_placement_target_by_placement_id/{placement_id}.
// GET /api/rgw/zonegroup/get_placement_target_by_placement_id/{placement_id}
func (c *Client) GetRgwZonegroupGetPlacementTargetByPlacementIdByPlacementId(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodGet, "/api/rgw/zonegroup/get_placement_target_by_placement_id/{placement_id}", request, true)
}

// PostRgwZonegroupStorageClass calls POST /api/rgw/zonegroup/storage-class.
// POST /api/rgw/zonegroup/storage-class
func (c *Client) PostRgwZonegroupStorageClass(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodPost, "/api/rgw/zonegroup/storage-class", request, true)
}

// PutRgwZonegroupStorageClass calls PUT /api/rgw/zonegroup/storage-class.
// PUT /api/rgw/zonegroup/storage-class
func (c *Client) PutRgwZonegroupStorageClass(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodPut, "/api/rgw/zonegroup/storage-class", request, true)
}

// DeleteRgwZonegroupStorageClassByPlacementIdByStorageClass calls DELETE /api/rgw/zonegroup/storage-class/{placement_id}/{storage_class}.
// DELETE /api/rgw/zonegroup/storage-class/{placement_id}/{storage_class}
func (c *Client) DeleteRgwZonegroupStorageClassByPlacementIdByStorageClass(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodDelete, "/api/rgw/zonegroup/storage-class/{placement_id}/{storage_class}", request, true)
}

// DeleteRgwZonegroupByZonegroupName calls DELETE /api/rgw/zonegroup/{zonegroup_name}.
// DELETE /api/rgw/zonegroup/{zonegroup_name}
func (c *Client) DeleteRgwZonegroupByZonegroupName(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodDelete, "/api/rgw/zonegroup/{zonegroup_name}", request, true)
}

// GetRgwZonegroupByZonegroupName calls GET /api/rgw/zonegroup/{zonegroup_name}.
// GET /api/rgw/zonegroup/{zonegroup_name}
func (c *Client) GetRgwZonegroupByZonegroupName(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodGet, "/api/rgw/zonegroup/{zonegroup_name}", request, true)
}

// PutRgwZonegroupByZonegroupName calls PUT /api/rgw/zonegroup/{zonegroup_name}.
// PUT /api/rgw/zonegroup/{zonegroup_name}
func (c *Client) PutRgwZonegroupByZonegroupName(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodPut, "/api/rgw/zonegroup/{zonegroup_name}", request, true)
}
