// Code generated by tools/generate_ceph_dashboard_client.rb; DO NOT EDIT.

package endpoints

import (
	"context"
	"encoding/json"
	"net/http"
)

// summary endpoints from docs/references/ceph/src/pybind/mgr/dashboard/openapi.yaml.

// GetSummary calls GET /api/summary.
// Display Summary
func (c *Client) GetSummary(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodGet, "/api/summary", request, true)
}
