// Code generated by tools/generate_ceph_dashboard_client.rb; DO NOT EDIT.

package endpoints

import (
	"context"
	"encoding/json"
	"net/http"
)

// task endpoints from docs/references/ceph/src/pybind/mgr/dashboard/openapi.yaml.

// GetTask calls GET /api/task.
// Display Tasks
func (c *Client) GetTask(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodGet, "/api/task", request, true)
}
