http_addr: :36900
logging:
    level: info
    format: txt
database:
    engine: sqlite
    sqlite:
        path: app/data/cephtower.db
    mysql:
        host: 127.0.0.1
        port: 3306
        username: ""
        password: ""
        database: ""
        params: charset=utf8mb4&parseTime=True&loc=Local
smtp:
    host: ""
    port: 587
    username: ""
    password: ""
    from: ""
