package main

import (
	"bytes"
	"flag"
	"fmt"
	"os"
	"sort"
	"strings"

	"cephtower/backend/internal/api/v1/handler"
	"cephtower/backend/internal/api/v1/router"
)

func main() {
	output := flag.String("output", "api/openapi-v1.yaml", "output path")
	check := flag.Bool("check", false, "verify output is current")
	flag.Parse()
	document := generate()
	if *check {
		current, err := os.ReadFile(*output)
		if err != nil || !bytes.Equal(current, document) {
			fmt.Fprintln(os.Stderr, "OpenAPI contract is not current; run go run ./tools/openapi-gen")
			os.Exit(1)
		}
		return
	}
	if err := os.MkdirAll(filepathDir(*output), 0o755); err != nil {
		panic(err)
	}
	if err := os.WriteFile(*output, document, 0o644); err != nil {
		panic(err)
	}
}
func generate() []byte {
	routes := router.ReadRoutesForContract(handler.New(handler.Dependencies{}))
	grouped := map[string][]router.Route{}
	var paths []string
	for _, route := range routes {
		if _, ok := grouped[route.Path]; !ok {
			paths = append(paths, route.Path)
		}
		grouped[route.Path] = append(grouped[route.Path], route)
	}
	sort.Strings(paths)
	var b strings.Builder
	b.WriteString("# Code generated by tools/openapi-gen; DO NOT EDIT.\nopenapi: 3.1.0\ninfo:\n  title: CephTower API\n  version: 1.0.0\nservers:\n  - url: /api/v1\npaths:\n")
	for _, path := range paths {
		b.WriteString("  " + path + ":\n")
		routes := grouped[path]
		sort.Slice(routes, func(i, j int) bool { return routes[i].Method < routes[j].Method })
		for _, route := range routes {
			method := strings.ToLower(route.Method)
			operationID := operationID(route)
			b.WriteString("    " + method + ":\n      operationId: " + operationID + "\n")
			if !isPublicRoute(route) {
				b.WriteString("      security:\n        - bearerAuth: []\n")
			}
			parameters := routeParameters(route)
			if len(parameters) > 0 {
				b.WriteString("      parameters:\n")
				for _, parameter := range parameters {
					b.WriteString("        - name: " + parameter.Name + "\n          in: " + parameter.In + "\n          required: " + fmt.Sprint(parameter.Required) + "\n          schema:\n            type: " + parameter.Type + "\n")
					if parameter.Minimum != "" {
						b.WriteString("            minimum: " + parameter.Minimum + "\n")
					}
					if parameter.Format != "" {
						b.WriteString("            format: " + parameter.Format + "\n")
					}
					if len(parameter.Enum) > 0 {
						b.WriteString("            enum: [" + strings.Join(parameter.Enum, ", ") + "]\n")
					}
				}
			}
			if schema, ok := requestSchema(route); ok {
				b.WriteString("      requestBody:\n        required: " + fmt.Sprint(schema.Required) + "\n        content:\n          application/json:\n            schema:\n")
				writeRequestSchema(&b, schema, 14)
			}
			status := "200"
			if explicit := explicitSuccessStatus(route); explicit != "" {
				status = explicit
			}
			mediaType := "application/json"
			if isStreamRoute(route) {
				mediaType = "text/event-stream"
			}
			b.WriteString("      responses:\n        '" + status + "':\n          description: success\n          content:\n            " + mediaType + ":\n              schema:\n                $ref: '#/components/schemas/" + successResponseSchema(route) + "'\n        default:\n          description: error\n          content:\n            application/json:\n              schema:\n                $ref: '#/components/schemas/ErrorResponse'\n")
		}
	}
	b.WriteString(components)
	writeResponseSchemas(&b)
	return []byte(b.String())
}

func successResponseSchema(route router.Route) string {
	key := route.Method + " " + route.Path
	switch key {
	case "GET /healthz", "GET /readyz":
		return "HealthResponse"
	case "GET /bootstrap":
		return "BootstrapResponse"
	case "POST /bootstrap/run", "POST /user":
		return "UserResponse"
	case "POST /auth/login":
		return "LoginResponse"
	case "GET /user":
		return "UserListResponse"
	case "GET /role":
		return "RoleListResponse"
	case "POST /role":
		return "RoleResponse"
	case "GET /role/bindings":
		return "RoleBindingListResponse"
	case "POST /role/binding":
		return "RoleBindingResponse"
	case "DELETE /role/binding":
		return "NullResponse"
	case "GET /clusters":
		return "ClusterListResponse"
	case "GET /cluster":
		return "ClusterResponse"
	case "POST /cluster":
		return "ClusterMutationResponse"
	case "GET /cluster/capabilities":
		return "CapabilityListResponse"
	case "GET /credentials":
		return "CredentialListResponse"
	case "PUT /credential":
		return "CredentialResponse"
	case "DELETE /credential", "DELETE /endpoint":
		return "NullResponse"
	case "GET /endpoints":
		return "EndpointListResponse"
	case "POST /endpoint", "PATCH /endpoint":
		return "EndpointResponse"
	case "GET /audit/events":
		return "AuditEventListResponse"
	case "POST /resource/refresh":
		return "ActionResponse"
	case "GET /rgw/bucket/policy":
		return "BucketConfigurationResponse"
	}
	if isStreamRoute(route) {
		return "EventStream"
	}
	if route.Method != "GET" {
		return "ActionResponse"
	}
	switch {
	case strings.HasPrefix(route.Path, "/metric/"):
		return "MetricResponse"
	case route.Path == "/alert/alerts" ||
		route.Path == "/alert/rules" ||
		route.Path == "/alert/silences" ||
		route.Path == "/grafana":
		return "ExternalListResponse"
	case route.Path == "/iscsi/gateway":
		return "ISCSIGatewayResponse"
	case strings.HasPrefix(route.Path, "/iscsi/target"):
		if route.Path == "/iscsi/target" {
			return "ISCSITargetResponse"
		}
		return "ISCSITargetListResponse"
	case strings.HasPrefix(route.Path, "/nvmeof/"):
		return "ExternalResultResponse"
	}
	if isItemResourceRoute(route) {
		return "ResourceResponse"
	}
	return "ResourceListResponse"
}

func writeResponseSchemas(b *strings.Builder) {
	responses := []struct{ name, data string }{
		{"HealthResponse", "HealthData"}, {"BootstrapResponse", "BootstrapData"},
		{"UserResponse", "User"}, {"LoginResponse", "LoginData"}, {"UserListResponse", "UserListData"},
		{"RoleResponse", "Role"}, {"RoleListResponse", "RoleListData"},
		{"RoleBindingResponse", "RoleBinding"}, {"RoleBindingListResponse", "RoleBindingListData"},
		{"ClusterResponse", "Cluster"}, {"ClusterListResponse", "ClusterListData"},
		{"CapabilityListResponse", "CapabilityListData"}, {"CredentialResponse", "Credential"},
		{"CredentialListResponse", "CredentialListData"}, {"EndpointResponse", "Endpoint"},
		{"EndpointListResponse", "EndpointListData"}, {"ClusterMutationResponse", "ClusterMutationData"},
		{"ActionResponse", "ActionResult"}, {"AuditEventListResponse", "AuditEventListData"},
		{"ResourceResponse", "Resource"}, {"ResourceListResponse", "ResourceListData"},
		{"MetricResponse", "MetricData"}, {"ExternalListResponse", "ExternalListData"},
		{"ExternalResultResponse", "ExternalResultData"}, {"ISCSIGatewayResponse", "ISCSIGateway"},
		{"ISCSITargetResponse", "ISCSITarget"}, {"ISCSITargetListResponse", "ISCSITargetListData"},
		{"BucketConfigurationResponse", "BucketConfiguration"},
	}
	for _, response := range responses {
		b.WriteString("    " + response.name + ":\n      allOf:\n        - $ref: '#/components/schemas/APIResponse'\n        - type: object\n          unevaluatedProperties: false\n          required: [data]\n          properties:\n            data:\n              $ref: '#/components/schemas/" + response.data + "'\n")
	}
	b.WriteString("    NullResponse:\n      allOf:\n        - $ref: '#/components/schemas/APIResponse'\n        - type: object\n          unevaluatedProperties: false\n          required: [data]\n          properties:\n            data:\n              type: 'null'\n")
}

type parameterSpec struct {
	Name, In, Type, Format, Minimum string
	Required                        bool
	Enum                            []string
}

func routeParameters(route router.Route) []parameterSpec {
	var result []parameterSpec
	if isStreamRoute(route) {
		result = append(result, parameterSpec{Name: "Last-Event-ID", In: "header", Type: "integer", Minimum: "0"})
	}
	switch route.Path {
	case "/audit/events":
		result = append(result,
			parameterSpec{Name: "username", In: "query", Type: "string"},
			parameterSpec{Name: "action", In: "query", Type: "string"},
			parameterSpec{Name: "resource_kind", In: "query", Type: "string"},
			parameterSpec{Name: "resource_key", In: "query", Type: "string"},
			parameterSpec{Name: "user_id", In: "query", Type: "integer", Minimum: "1"},
			parameterSpec{Name: "limit", In: "query", Type: "integer", Minimum: "1"})
	case "/clusters":
		result = append(result,
			parameterSpec{Name: "filter.name", In: "query", Type: "string"},
			parameterSpec{Name: "filter.client_username", In: "query", Type: "string"},
			parameterSpec{Name: "filter_options", In: "query", Type: "integer", Enum: []string{"1"}},
			parameterSpec{Name: "fields", In: "query", Type: "string"})
	case "/metric/query":
		result = append(result, parameterSpec{Name: "metric_id", In: "query", Type: "string", Required: true}, parameterSpec{Name: "time", In: "query", Type: "string", Format: "date-time"})
	case "/metric/range":
		result = append(result, parameterSpec{Name: "metric_id", In: "query", Type: "string", Required: true}, parameterSpec{Name: "start", In: "query", Type: "string", Format: "date-time", Required: true}, parameterSpec{Name: "end", In: "query", Type: "string", Format: "date-time", Required: true}, parameterSpec{Name: "step", In: "query", Type: "string", Required: true})
	case "/rgw/bucket/policy":
		if route.Method == "GET" {
			result = append(result, parameterSpec{Name: "kind", In: "query", Type: "string", Enum: []string{"policy", "cors", "lifecycle", "encryption", "versioning"}})
		}
	}
	return result
}

func requestSchema(route router.Route) (handler.RequestContract, bool) {
	stringField := func(required bool) handler.JSONField { return handler.JSONField{Type: "string", Required: required} }
	boolField := func(required bool) handler.JSONField { return handler.JSONField{Type: "boolean", Required: required} }
	integerField := func(required bool) handler.JSONField { return handler.JSONField{Type: "integer", Required: required} }
	stringArrayField := func(required bool) handler.JSONField {
		return handler.JSONField{Type: "array", Required: required, Items: &handler.JSONField{Type: "string"}}
	}
	object := func(required bool, fields map[string]handler.JSONField) handler.JSONField {
		return handler.JSONField{Type: "object", Required: required, Properties: fields}
	}
	identifierFields := func() map[string]handler.JSONField {
		return map[string]handler.JSONField{
			"account_id":    stringField(false),
			"binding_id":    integerField(false),
			"bucket_id":     stringField(false),
			"client_id":     stringField(false),
			"code":          stringField(false),
			"device_id":     stringField(false),
			"endpoint_id":   integerField(false),
			"export_id":     stringField(false),
			"fs":            stringField(false),
			"group":         stringField(false),
			"host":          stringField(false),
			"host_nqn":      stringField(false),
			"id":            stringField(false),
			"image_id":      stringField(false),
			"image_spec":    stringField(false),
			"iqn":           stringField(false),
			"listener_id":   stringField(false),
			"metric_id":     stringField(false),
			"name":          stringField(false),
			"namespace":     stringField(false),
			"nqn":           stringField(false),
			"nsid":          stringField(false),
			"operation_id":  stringField(false),
			"osd_id":        stringField(false),
			"pool":          stringField(false),
			"service_id":    stringField(false),
			"share_id":      stringField(false),
			"silence_id":    stringField(false),
			"snap":          stringField(false),
			"subvolume":     stringField(false),
			"subsystem_nqn": stringField(false),
			"uid":           stringField(false),
			"who":           stringField(false),
		}
	}
	key := route.Method + " " + route.Path
	var fields map[string]handler.JSONField
	required := true
	switch key {
	case "POST /bootstrap/run":
		database := object(true, map[string]handler.JSONField{
			"engine": stringField(true),
			"sqlite": object(true, map[string]handler.JSONField{
				"name": stringField(true),
			}),
			"mysql": object(true, map[string]handler.JSONField{
				"host":     stringField(true),
				"port":     integerField(true),
				"username": stringField(true),
				"password": {Type: "string", Required: false, WriteOnly: true},
				"database": stringField(true),
				"params":   stringField(true),
				"tls":      stringField(true),
			}),
		})
		user := object(true, map[string]handler.JSONField{"username": stringField(true), "display_name": stringField(true), "email": stringField(false), "password": {Type: "string", Required: true, WriteOnly: true}, "role": stringField(false)})
		fields = map[string]handler.JSONField{"database": database, "user": user}
	case "POST /bootstrap/dbtest":
		fields = map[string]handler.JSONField{
			"engine": stringField(true),
			"sqlite": object(true, map[string]handler.JSONField{
				"name": stringField(true),
			}),
			"mysql": object(true, map[string]handler.JSONField{
				"host":     stringField(true),
				"port":     integerField(true),
				"username": stringField(true),
				"password": {Type: "string", Required: false, WriteOnly: true},
				"database": stringField(true),
				"params":   stringField(true),
				"tls":      stringField(true),
			}),
		}
	case "POST /user":
		fields = map[string]handler.JSONField{"username": stringField(true), "display_name": stringField(true), "email": stringField(false), "password": {Type: "string", Required: true, WriteOnly: true}, "role": stringField(route.Path == "/user")}
	case "POST /auth/login":
		fields = map[string]handler.JSONField{"username": stringField(true), "password": {Type: "string", Required: true, WriteOnly: true}}
	case "POST /role":
		fields = map[string]handler.JSONField{"name": stringField(true), "description": stringField(false)}
	case "POST /role/binding":
		fields = map[string]handler.JSONField{"cluster_id": integerField(true), "user_id": integerField(true), "role": stringField(true)}
	case "DELETE /role/binding":
		fields = map[string]handler.JSONField{"cluster_id": integerField(true), "binding_id": integerField(true)}
	case "POST /cluster":
		fields = map[string]handler.JSONField{"name": stringField(true), "monitor_addresses": stringField(true), "client_username": stringField(true), "client_key": {Type: "string", Required: true, WriteOnly: true}}
	case "PATCH /cluster":
		fields = map[string]handler.JSONField{"cluster_id": integerField(true), "name": stringField(false), "monitor_addresses": stringField(false), "client_username": stringField(false), "client_key": {Type: "string", WriteOnly: true}}
	case "DELETE /cluster":
		fields = map[string]handler.JSONField{"cluster_id": integerField(true), "delete_cached_data": boolField(true)}
	case "POST /cluster/probe":
		fields = map[string]handler.JSONField{"cluster_id": integerField(true)}
	case "POST /resource/refresh":
		fields = map[string]handler.JSONField{"cluster_id": integerField(true), "scope": stringField(false), "module": stringField(false), "modules": stringArrayField(false), "kind": stringField(false), "kinds": stringArrayField(false)}
	case "GET /cluster", "GET /cluster/capabilities", "GET /credentials", "GET /endpoints", "GET /role/bindings", "GET /logs/stream":
		fields = map[string]handler.JSONField{"cluster_id": integerField(true)}
	case "PUT /credential":
		credentialFields := map[string]handler.JSONField{"token": {Type: "string", WriteOnly: true}, "username": stringField(false), "password": {Type: "string", WriteOnly: true}, "ca_certificate": {Type: "string", WriteOnly: true}, "client_certificate": {Type: "string", WriteOnly: true}, "client_key": {Type: "string", WriteOnly: true}, "access_key": {Type: "string", WriteOnly: true}, "secret_key": {Type: "string", WriteOnly: true}, "session_token": {Type: "string", WriteOnly: true}, "region": stringField(false)}
		fields = map[string]handler.JSONField{"cluster_id": integerField(true), "kind": stringField(true), "credential": object(true, credentialFields)}
	case "DELETE /credential":
		fields = map[string]handler.JSONField{"cluster_id": integerField(true), "kind": stringField(true)}
	case "POST /endpoint", "PATCH /endpoint":
		fields = map[string]handler.JSONField{"cluster_id": integerField(true), "endpoint_id": integerField(route.Method == "PATCH"), "kind": stringField(true), "name": stringField(false), "url": stringField(true), "tls_mode": stringField(false), "ca_credential_id": integerField(false), "timeout_seconds": integerField(false), "enabled": boolField(false)}
	case "DELETE /endpoint":
		fields = map[string]handler.JSONField{"cluster_id": integerField(true), "endpoint_id": integerField(true)}
	default:
		if route.Method == "GET" && isClusterScopedRoute(route) {
			fields := identifierFields()
			fields["cluster_id"] = integerField(true)
			return handler.RequestContract{Required: true, Fields: fields}, true
		}
		if route.Method != "GET" && isClusterScopedRoute(route) {
			fields := mutationFieldUnion()
			fields["cluster_id"] = integerField(true)
			return handler.RequestContract{Required: true, Fields: fields}, true
		}
		return handler.RequestContract{}, false
	}
	return handler.RequestContract{Required: required, Fields: fields}, true
}

func mutationFieldUnion() map[string]handler.JSONField {
	fields := map[string]handler.JSONField{}
	for _, action := range handler.MutationContractActions() {
		contract, _ := handler.MutationRequestContract(action)
		for name, field := range contract.Fields {
			field.Required = false
			if existing, ok := fields[name]; ok && existing.Type != field.Type {
				field = handler.JSONField{}
			}
			fields[name] = field
		}
	}
	return fields
}

func writeRequestSchema(b *strings.Builder, schema handler.RequestContract, indent int) {
	writeObjectSchema(b, schema.Fields, indent)
}

func writeObjectSchema(b *strings.Builder, fields map[string]handler.JSONField, indent int) {
	pad := strings.Repeat(" ", indent)
	b.WriteString(pad + "type: object\n" + pad + "additionalProperties: false\n")
	var required []string
	var names []string
	for name, field := range fields {
		names = append(names, name)
		if field.Required {
			required = append(required, name)
		}
	}
	sort.Strings(names)
	sort.Strings(required)
	if len(required) > 0 {
		b.WriteString(pad + "required: [" + strings.Join(required, ", ") + "]\n")
	}
	b.WriteString(pad + "properties:\n")
	for _, name := range names {
		b.WriteString(pad + "  " + name + ":\n")
		writeFieldSchema(b, fields[name], indent+4)
	}
}

func writeFieldSchema(b *strings.Builder, field handler.JSONField, indent int) {
	pad := strings.Repeat(" ", indent)
	if field.Type == "" {
		b.WriteString(pad + "description: action-specific JSON value\n")
		return
	}
	if field.Type == "object" {
		writeObjectSchema(b, field.Properties, indent)
	} else {
		b.WriteString(pad + "type: " + field.Type + "\n")
		if field.Type == "array" && field.Items != nil {
			b.WriteString(pad + "items:\n")
			writeFieldSchema(b, *field.Items, indent+2)
		}
	}
	if field.WriteOnly {
		b.WriteString(pad + "writeOnly: true\n")
	}
	if len(field.Enum) > 0 {
		values := append([]string(nil), field.Enum...)
		sort.Strings(values)
		b.WriteString(pad + "enum: [" + strings.Join(values, ", ") + "]\n")
	}
}
func explicitSuccessStatus(route router.Route) string {
	key := route.Method + " " + route.Path
	switch key {
	case "POST /bootstrap/run", "POST /user", "POST /role", "POST /role/binding", "POST /endpoint":
		return "201"
	case "POST /auth/login", "PUT /credential", "DELETE /credential", "PATCH /endpoint", "DELETE /endpoint", "DELETE /role/binding":
		return "200"
	default:
		return ""
	}
}
func operationID(route router.Route) string {
	value := strings.ToLower(route.Method) + "_" + strings.Trim(route.Path, "/")
	replacer := strings.NewReplacer("/", "_", "-", "_", "{", "", "}", "")
	return replacer.Replace(value)
}

func isPublicRoute(route router.Route) bool {
	key := route.Method + " " + route.Path
	return key == "GET /healthz" ||
		key == "GET /readyz" ||
		key == "GET /bootstrap" ||
		key == "POST /bootstrap/dbtest" ||
		key == "POST /bootstrap/run" ||
		key == "POST /auth/login"
}

func isClusterScopedRoute(route router.Route) bool {
	key := route.Method + " " + route.Path
	if isPublicRoute(route) {
		return false
	}
	switch key {
	case "GET /clusters",
		"POST /cluster",
		"GET /user",
		"POST /user",
		"GET /role",
		"POST /role":
		return false
	default:
		return true
	}
}

func isStreamRoute(route router.Route) bool {
	return strings.HasSuffix(route.Path, "/stream")
}

func isItemResourceRoute(route router.Route) bool {
	if route.Method != "GET" {
		return false
	}
	switch route.Path {
	case "/cluster",
		"/cluster/capabilities",
		"/credentials",
		"/endpoints",
		"/audit/events",
		"/health",
		"/devices",
		"/filesystem/clients",
		"/filesystem/subvolume/groups",
		"/filesystem/subvolumes",
		"/filesystem/subvolume/snapshots",
		"/filesystem/snapshot/schedules",
		"/filesystem/authorizations",
		"/filesystem/entries",
		"/rbd/trash":
		return false
	}
	if strings.HasSuffix(route.Path, "s") {
		return false
	}
	return true
}
func filepathDir(path string) string {
	index := strings.LastIndex(path, string(os.PathSeparator))
	if index < 0 {
		return "."
	}
	return path[:index]
}

const components = `components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
  schemas:
    APIResponse:
      type: object
      additionalProperties: false
      required: [code, message, data]
      properties:
        code:
          type: integer
          const: 0
        message:
          type: string
        data:
          $ref: '#/components/schemas/JSONValue'
    JSONValue:
      oneOf:
        - type: object
          additionalProperties:
            $ref: '#/components/schemas/JSONValue'
        - type: array
          items:
            $ref: '#/components/schemas/JSONValue'
        - type: string
        - type: number
        - type: boolean
        - type: 'null'
    ErrorData:
      type: object
      additionalProperties: false
      required: [error_code, retryable, request_id]
      properties:
        error_code:
          type: string
        retryable:
          type: boolean
        details:
          type: object
          additionalProperties:
            $ref: '#/components/schemas/JSONValue'
        request_id:
          type: string
    ErrorResponse:
      type: object
      additionalProperties: false
      required: [code, message, data]
      properties:
        code:
          type: integer
          minimum: 400
        message:
          type: string
        data:
          $ref: '#/components/schemas/ErrorData'
    ClusterCreateRequest:
      type: object
      additionalProperties: false
      required: [name, monitor_addresses, client_username, client_key]
      properties:
        name: {type: string, minLength: 1, maxLength: 128}
        monitor_addresses: {type: string, minLength: 1, maxLength: 4096}
        client_username: {type: string, pattern: '^client\\.'}
        client_key: {type: string, writeOnly: true, minLength: 1}
    ActionResult:
      type: object
      additionalProperties: false
      properties:
        resource_url: {type: string}
        details: {$ref: '#/components/schemas/JSONValue'}
    Pagination:
      type: object
      additionalProperties: false
      required: [next_cursor]
      properties:
        next_cursor: {type: [string, 'null']}
    Meta:
      type: object
      additionalProperties: false
      properties:
        request_id: {type: string}
        observed_at: {type: [string, 'null'], format: date-time}
        stale: {type: boolean}
        stale_reason: {type: [string, 'null']}
    HealthData:
      type: object
      additionalProperties: false
      required: [status]
      properties:
        status: {type: string, enum: [ok, ready]}
    BootstrapData:
      type: object
      additionalProperties: false
      required: [required]
      properties:
        required: {type: boolean}
    User:
      type: object
      additionalProperties: false
      required: [id, username, display_name, email, status, last_login_at, created_at, updated_at]
      properties:
        id: {type: integer, minimum: 1}
        username: {type: string}
        display_name: {type: string}
        email: {type: [string, 'null']}
        status: {type: string}
        last_login_at: {type: [string, 'null'], format: date-time}
        created_at: {type: string, format: date-time}
        updated_at: {type: string, format: date-time}
    LoginData:
      type: object
      additionalProperties: false
      required: [token, expires_at, user]
      properties:
        token: {type: string, readOnly: true}
        expires_at: {type: string, format: date-time}
        user: {$ref: '#/components/schemas/User'}
    Role:
      type: object
      additionalProperties: false
      required: [id, name, created_at, updated_at]
      properties:
        id: {type: integer, minimum: 1}
        name: {type: string}
        description: {type: [string, 'null']}
        created_at: {type: string, format: date-time}
        updated_at: {type: string, format: date-time}
    RoleBinding:
      type: object
      additionalProperties: false
      required: [role_binding_id, user_id, username, role, cluster_id, created_at]
      properties:
        role_binding_id: {type: integer, minimum: 1}
        user_id: {type: integer, minimum: 1}
        username: {type: string}
        role: {type: string}
        cluster_id: {type: integer, minimum: 1}
        created_at: {type: string, format: date-time}
    Cluster:
      type: object
      additionalProperties: false
      required: [cluster_id, name, monitor_addresses, client_username, created_at, updated_at]
      properties:
        cluster_id: {type: integer, minimum: 1}
        name: {type: string}
        monitor_addresses: {type: string}
        client_username: {type: string}
        created_at: {type: string, format: date-time}
        updated_at: {type: string, format: date-time}
    Capability:
      type: object
      additionalProperties: false
      required: [name, supported, reason, version, details, observed_at]
      properties:
        name: {type: string}
        supported: {type: boolean}
        reason: {type: [string, 'null']}
        version: {type: [string, 'null']}
        details: {$ref: '#/components/schemas/JSONValue'}
        observed_at: {type: string, format: date-time}
    Credential:
      type: object
      additionalProperties: false
      required: [kind, fingerprint, created_at, updated_at]
      properties:
        kind: {type: string}
        fingerprint: {type: string}
        created_at: {type: string, format: date-time}
        updated_at: {type: string, format: date-time}
    Endpoint:
      type: object
      additionalProperties: false
      required: [endpoint_id, kind, name, url, tls_mode, ca_credential_id, enabled, created_at, updated_at]
      properties:
        endpoint_id: {type: integer, minimum: 1}
        kind: {type: string}
        name: {type: string}
        url: {type: string, format: uri}
        tls_mode: {type: string}
        ca_credential_id: {type: [integer, 'null']}
        enabled: {type: boolean}
        created_at: {type: string, format: date-time}
        updated_at: {type: string, format: date-time}
    AuditEvent:
      type: object
      additionalProperties: false
      required: [audit_event_id, occurred_at, event_type, request_id, actor_username, action, outcome, event_hash]
      properties:
        audit_event_id: {type: integer, minimum: 1}
        occurred_at: {type: string, format: date-time}
        event_type: {type: string}
        request_id: {type: string}
        actor_username: {type: string}
        cluster_id: {type: [integer, 'null']}
        cluster_name: {type: [string, 'null']}
        action: {type: string}
        resource_kind: {type: [string, 'null']}
        resource_key: {type: [string, 'null']}
        risk: {type: [string, 'null']}
        outcome: {type: string}
        http_status: {type: [integer, 'null']}
        error_code: {type: [string, 'null']}
        before_generation: {type: [integer, 'null']}
        after_generation: {type: [integer, 'null']}
        parameters: {$ref: '#/components/schemas/JSONValue'}
        details: {$ref: '#/components/schemas/JSONValue'}
        event_hash: {type: string, pattern: '^[0-9a-f]{64}$'}
    Resource:
      type: object
      additionalProperties: false
      required: [kind, natural_key, name, status, resource_version, source, observed_at, stale, data]
      properties:
        kind: {type: string}
        natural_key: {type: string}
        name: {type: [string, 'null']}
        status: {type: [string, 'null']}
        resource_version: {type: integer, minimum: 1}
        source: {type: string, enum: [ceph_cli, rbd_cli, rgw_admin, cephfs_cli]}
        observed_at: {type: string, format: date-time}
        stale: {type: boolean}
        data:
          $ref: '#/components/schemas/JSONValue'
    BucketConfiguration:
      type: object
      additionalProperties: false
      required: [bucket_id, kind, document, content_type]
      properties:
        bucket_id: {type: string}
        kind: {type: string, enum: [policy, cors, lifecycle, encryption, versioning]}
        document: {type: string}
        content_type: {type: string}
    MetricData:
      type: object
      additionalProperties: false
      required: [result_type, series, meta]
      properties:
        result_type: {type: string}
        series: {type: array, items: {$ref: '#/components/schemas/JSONValue'}}
        meta: {$ref: '#/components/schemas/Meta'}
    ExternalResultData:
      type: object
      additionalProperties: false
      required: [result, meta]
      properties:
        result: {$ref: '#/components/schemas/JSONValue'}
        meta: {$ref: '#/components/schemas/Meta'}
    ISCSIGateway:
      type: object
      additionalProperties: false
      required: [status]
      properties:
        status: {type: string}
        message: {type: string}
    ISCSIPortal:
      type: object
      additionalProperties: false
      required: [host, ip]
      properties:
        host: {type: string}
        ip: {type: string}
    ISCSIDisk:
      type: object
      additionalProperties: false
      required: [pool, image, backstore]
      properties:
        pool: {type: string}
        image: {type: string}
        backstore: {type: string}
    ISCSIInitiator:
      type: object
      additionalProperties: false
      required: [iqn, luns]
      properties:
        iqn: {type: string}
        luns: {type: array, items: {type: string}}
    ISCSIGroup:
      type: object
      additionalProperties: false
      required: [name, members, disks]
      properties:
        name: {type: string}
        members: {type: array, items: {type: string}}
        disks: {type: array, items: {type: string}}
    ISCSITarget:
      type: object
      additionalProperties: false
      required: [iqn, portals, disks, clients, groups]
      properties:
        iqn: {type: string}
        portals: {type: array, items: {$ref: '#/components/schemas/ISCSIPortal'}}
        disks: {type: array, items: {$ref: '#/components/schemas/ISCSIDisk'}}
        clients: {type: array, items: {$ref: '#/components/schemas/ISCSIInitiator'}}
        groups: {type: array, items: {$ref: '#/components/schemas/ISCSIGroup'}}
    EventStream:
      type: string
      description: stream of data lines containing APIResponse JSON objects
    UserListData:
      allOf:
        - $ref: '#/components/schemas/ListData'
        - type: object
          properties:
            items: {type: array, items: {$ref: '#/components/schemas/User'}}
    RoleListData:
      allOf:
        - $ref: '#/components/schemas/ListData'
        - type: object
          properties:
            items: {type: array, items: {$ref: '#/components/schemas/Role'}}
    RoleBindingListData:
      allOf:
        - $ref: '#/components/schemas/ListData'
        - type: object
          properties:
            items: {type: array, items: {$ref: '#/components/schemas/RoleBinding'}}
    ClusterListData:
      allOf:
        - $ref: '#/components/schemas/ListData'
        - type: object
          properties:
            items: {type: array, items: {$ref: '#/components/schemas/Cluster'}}
    ClusterMutationData:
      type: object
      additionalProperties: false
      required: [cluster, result]
      properties:
        cluster: {$ref: '#/components/schemas/Cluster'}
        result: {$ref: '#/components/schemas/ActionResult'}
    CapabilityListData:
      allOf:
        - $ref: '#/components/schemas/ListData'
        - type: object
          properties:
            items: {type: array, items: {$ref: '#/components/schemas/Capability'}}
    CredentialListData:
      allOf:
        - $ref: '#/components/schemas/ListData'
        - type: object
          properties:
            items: {type: array, items: {$ref: '#/components/schemas/Credential'}}
    EndpointListData:
      allOf:
        - $ref: '#/components/schemas/ListData'
        - type: object
          properties:
            items: {type: array, items: {$ref: '#/components/schemas/Endpoint'}}
    AuditEventListData:
      allOf:
        - $ref: '#/components/schemas/ListData'
        - type: object
          properties:
            items: {type: array, items: {$ref: '#/components/schemas/AuditEvent'}}
    ResourceListData:
      allOf:
        - $ref: '#/components/schemas/ListData'
        - type: object
          properties:
            items: {type: array, items: {$ref: '#/components/schemas/Resource'}}
    ExternalListData:
      allOf:
        - $ref: '#/components/schemas/ListData'
        - type: object
          properties:
            items: {type: array, items: {$ref: '#/components/schemas/JSONValue'}}
    ISCSITargetListData:
      allOf:
        - $ref: '#/components/schemas/ListData'
        - type: object
          properties:
            items: {type: array, items: {$ref: '#/components/schemas/ISCSITarget'}}
    ListData:
      type: object
      additionalProperties: false
      required: [items, pagination, meta]
      properties:
        items: {type: array}
        pagination: {$ref: '#/components/schemas/Pagination'}
        meta: {$ref: '#/components/schemas/Meta'}
`
