// Code generated by tools/generate_ceph_dashboard_client.rb; DO NOT EDIT.

package endpoints

import (
	"context"
	"encoding/json"
	"net/http"
)

// host endpoints from docs/references/ceph/src/pybind/mgr/dashboard/openapi.yaml.

// GetHost calls GET /api/host.
// List Host Specifications
func (c *Client) GetHost(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodGet, "/api/host", request, true)
}

// PostHost calls POST /api/host.
// POST /api/host
func (c *Client) PostHost(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodPost, "/api/host", request, true)
}

// DeleteHostByHostname calls DELETE /api/host/{hostname}.
// DELETE /api/host/{hostname}
func (c *Client) DeleteHostByHostname(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodDelete, "/api/host/{hostname}", request, true)
}

// GetHostByHostname calls GET /api/host/{hostname}.
// GET /api/host/{hostname}
func (c *Client) GetHostByHostname(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodGet, "/api/host/{hostname}", request, true)
}

// PutHostByHostname calls PUT /api/host/{hostname}.
// PUT /api/host/{hostname}
func (c *Client) PutHostByHostname(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodPut, "/api/host/{hostname}", request, true)
}

// GetHostByHostnameDaemons calls GET /api/host/{hostname}/daemons.
// GET /api/host/{hostname}/daemons
func (c *Client) GetHostByHostnameDaemons(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodGet, "/api/host/{hostname}/daemons", request, true)
}

// GetHostByHostnameDevices calls GET /api/host/{hostname}/devices.
// GET /api/host/{hostname}/devices
func (c *Client) GetHostByHostnameDevices(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodGet, "/api/host/{hostname}/devices", request, true)
}

// PostHostByHostnameIdentifyDevice calls POST /api/host/{hostname}/identify_device.
// POST /api/host/{hostname}/identify_device
func (c *Client) PostHostByHostnameIdentifyDevice(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodPost, "/api/host/{hostname}/identify_device", request, true)
}

// GetHostByHostnameInventory calls GET /api/host/{hostname}/inventory.
// Get inventory of a host
func (c *Client) GetHostByHostnameInventory(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodGet, "/api/host/{hostname}/inventory", request, true)
}

// GetHostByHostnameSmart calls GET /api/host/{hostname}/smart.
// GET /api/host/{hostname}/smart
func (c *Client) GetHostByHostnameSmart(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodGet, "/api/host/{hostname}/smart", request, true)
}
