// Code generated by tools/generate_ceph_dashboard_client.rb; DO NOT EDIT.

package endpoints

import (
	"context"
	"encoding/json"
	"net/http"
)

// monitor endpoints from docs/references/ceph/src/pybind/mgr/dashboard/openapi.yaml.

// GetMonitor calls GET /api/monitor.
// Get Monitor Details
func (c *Client) GetMonitor(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodGet, "/api/monitor", request, true)
}
