// Code generated by tools/generate_ceph_dashboard_client.rb; DO NOT EDIT.

package endpoints

import (
	"context"
	"encoding/json"
	"net/http"
)

// pool endpoints from docs/references/ceph/src/pybind/mgr/dashboard/openapi.yaml.

// GetPool calls GET /api/pool.
// Display Pool List
func (c *Client) GetPool(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodGet, "/api/pool", request, true)
}

// PostPool calls POST /api/pool.
// POST /api/pool
func (c *Client) PostPool(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodPost, "/api/pool", request, true)
}

// DeletePoolByPoolName calls DELETE /api/pool/{pool_name}.
// DELETE /api/pool/{pool_name}
func (c *Client) DeletePoolByPoolName(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodDelete, "/api/pool/{pool_name}", request, true)
}

// GetPoolByPoolName calls GET /api/pool/{pool_name}.
// GET /api/pool/{pool_name}
func (c *Client) GetPoolByPoolName(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodGet, "/api/pool/{pool_name}", request, true)
}

// PutPoolByPoolName calls PUT /api/pool/{pool_name}.
// PUT /api/pool/{pool_name}
func (c *Client) PutPoolByPoolName(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodPut, "/api/pool/{pool_name}", request, true)
}

// GetPoolByPoolNameConfiguration calls GET /api/pool/{pool_name}/configuration.
// GET /api/pool/{pool_name}/configuration
func (c *Client) GetPoolByPoolNameConfiguration(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodGet, "/api/pool/{pool_name}/configuration", request, true)
}
