// Code generated by tools/generate_ceph_dashboard_client.rb; DO NOT EDIT.

package endpoints

import (
	"context"
	"encoding/json"
	"net/http"
)

// service endpoints from docs/references/ceph/src/pybind/mgr/dashboard/openapi.yaml.

// GetService calls GET /api/service.
// GET /api/service
func (c *Client) GetService(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodGet, "/api/service", request, true)
}

// PostService calls POST /api/service.
// POST /api/service
func (c *Client) PostService(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodPost, "/api/service", request, true)
}

// GetServiceKnownTypes calls GET /api/service/known_types.
// GET /api/service/known_types
func (c *Client) GetServiceKnownTypes(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodGet, "/api/service/known_types", request, true)
}

// DeleteServiceByServiceName calls DELETE /api/service/{service_name}.
// DELETE /api/service/{service_name}
func (c *Client) DeleteServiceByServiceName(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodDelete, "/api/service/{service_name}", request, true)
}

// GetServiceByServiceName calls GET /api/service/{service_name}.
// GET /api/service/{service_name}
func (c *Client) GetServiceByServiceName(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodGet, "/api/service/{service_name}", request, true)
}

// PutServiceByServiceName calls PUT /api/service/{service_name}.
// PUT /api/service/{service_name}
func (c *Client) PutServiceByServiceName(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodPut, "/api/service/{service_name}", request, true)
}

// GetServiceByServiceNameDaemons calls GET /api/service/{service_name}/daemons.
// GET /api/service/{service_name}/daemons
func (c *Client) GetServiceByServiceNameDaemons(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodGet, "/api/service/{service_name}/daemons", request, true)
}
