// Code generated by tools/generate_ceph_dashboard_client.rb; DO NOT EDIT.

package endpoints

import (
	"context"
	"encoding/json"
	"net/http"
)

// erasure_code_profile endpoints from docs/references/ceph/src/pybind/mgr/dashboard/openapi.yaml.

// GetErasureCodeProfile calls GET /api/erasure_code_profile.
// List Erasure Code Profile Information
func (c *Client) GetErasureCodeProfile(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodGet, "/api/erasure_code_profile", request, true)
}

// PostErasureCodeProfile calls POST /api/erasure_code_profile.
// POST /api/erasure_code_profile
func (c *Client) PostErasureCodeProfile(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodPost, "/api/erasure_code_profile", request, true)
}

// DeleteErasureCodeProfileByName calls DELETE /api/erasure_code_profile/{name}.
// DELETE /api/erasure_code_profile/{name}
func (c *Client) DeleteErasureCodeProfileByName(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodDelete, "/api/erasure_code_profile/{name}", request, true)
}

// GetErasureCodeProfileByName calls GET /api/erasure_code_profile/{name}.
// GET /api/erasure_code_profile/{name}
func (c *Client) GetErasureCodeProfileByName(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodGet, "/api/erasure_code_profile/{name}", request, true)
}
