// Code generated by tools/generate_ceph_dashboard_client.rb; DO NOT EDIT.

package endpoints

import (
	"context"
	"encoding/json"
	"net/http"
)

// feature_toggles endpoints from docs/references/ceph/src/pybind/mgr/dashboard/openapi.yaml.

// GetFeatureToggles calls GET /api/feature_toggles.
// Get List Of Features
func (c *Client) GetFeatureToggles(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodGet, "/api/feature_toggles", request, true)
}
