// Code generated by tools/generate_ceph_dashboard_client.rb; DO NOT EDIT.

package endpoints

import (
	"context"
	"encoding/json"
	"net/http"
)

// feedback endpoints from docs/references/ceph/src/pybind/mgr/dashboard/openapi.yaml.

// GetFeedback calls GET /api/feedback.
// GET /api/feedback
func (c *Client) GetFeedback(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodGet, "/api/feedback", request, true)
}

// PostFeedback calls POST /api/feedback.
// POST /api/feedback
func (c *Client) PostFeedback(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodPost, "/api/feedback", request, true)
}

// DeleteFeedbackApiKey calls DELETE /api/feedback/api_key.
// DELETE /api/feedback/api_key
func (c *Client) DeleteFeedbackApiKey(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodDelete, "/api/feedback/api_key", request, true)
}

// GetFeedbackApiKey calls GET /api/feedback/api_key.
// GET /api/feedback/api_key
func (c *Client) GetFeedbackApiKey(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodGet, "/api/feedback/api_key", request, true)
}

// PostFeedbackApiKey calls POST /api/feedback/api_key.
// POST /api/feedback/api_key
func (c *Client) PostFeedbackApiKey(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodPost, "/api/feedback/api_key", request, true)
}
