// Code generated by tools/generate_ceph_dashboard_client.rb; DO NOT EDIT.

package endpoints

import (
	"context"
	"encoding/json"
	"net/http"
)

// motd endpoints from docs/references/ceph/src/pybind/mgr/dashboard/openapi.yaml.

// PostMotd calls POST /api/motd.
// POST /api/motd
func (c *Client) PostMotd(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodPost, "/api/motd", request, true)
}

// DeleteMotdClear calls DELETE /api/motd/clear.
// DELETE /api/motd/clear
func (c *Client) DeleteMotdClear(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodDelete, "/api/motd/clear", request, true)
}
