// Code generated by tools/generate_ceph_dashboard_client.rb; DO NOT EDIT.

package endpoints

import (
	"context"
	"encoding/json"
	"net/http"
)

// perf_counters endpoints from docs/references/ceph/src/pybind/mgr/dashboard/openapi.yaml.

// GetPerfCounters calls GET /api/perf_counters.
// Display Perf Counters
func (c *Client) GetPerfCounters(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodGet, "/api/perf_counters", request, true)
}

// GetPerfCountersMdsByServiceId calls GET /api/perf_counters/mds/{service_id}.
// GET /api/perf_counters/mds/{service_id}
func (c *Client) GetPerfCountersMdsByServiceId(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodGet, "/api/perf_counters/mds/{service_id}", request, true)
}

// GetPerfCountersMgrByServiceId calls GET /api/perf_counters/mgr/{service_id}.
// GET /api/perf_counters/mgr/{service_id}
func (c *Client) GetPerfCountersMgrByServiceId(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodGet, "/api/perf_counters/mgr/{service_id}", request, true)
}

// GetPerfCountersMonByServiceId calls GET /api/perf_counters/mon/{service_id}.
// GET /api/perf_counters/mon/{service_id}
func (c *Client) GetPerfCountersMonByServiceId(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodGet, "/api/perf_counters/mon/{service_id}", request, true)
}

// GetPerfCountersOsdByServiceId calls GET /api/perf_counters/osd/{service_id}.
// GET /api/perf_counters/osd/{service_id}
func (c *Client) GetPerfCountersOsdByServiceId(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodGet, "/api/perf_counters/osd/{service_id}", request, true)
}

// GetPerfCountersRbdMirrorByServiceId calls GET /api/perf_counters/rbd-mirror/{service_id}.
// GET /api/perf_counters/rbd-mirror/{service_id}
func (c *Client) GetPerfCountersRbdMirrorByServiceId(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodGet, "/api/perf_counters/rbd-mirror/{service_id}", request, true)
}

// GetPerfCountersRgwByServiceId calls GET /api/perf_counters/rgw/{service_id}.
// GET /api/perf_counters/rgw/{service_id}
func (c *Client) GetPerfCountersRgwByServiceId(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodGet, "/api/perf_counters/rgw/{service_id}", request, true)
}

// GetPerfCountersTcmuRunnerByServiceId calls GET /api/perf_counters/tcmu-runner/{service_id}.
// GET /api/perf_counters/tcmu-runner/{service_id}
func (c *Client) GetPerfCountersTcmuRunnerByServiceId(ctx context.Context, request OperationRequest) (json.RawMessage, error) {
	return c.do(ctx, http.MethodGet, "/api/perf_counters/tcmu-runner/{service_id}", request, true)
}
